#!/usr/bin/env python3
"""
Translate pharmacology quiz CSVs from Chinese to English for Chapters 13-18.
Reads pharma_cn_chXX.csv, writes pharma_en_chXX.csv.
"""

import csv
import re
import os

BASE_DIR = "/Users/weixu/Downloads/pnas"

# ============================================================
# SECTION 1: CATEGORY NAME TRANSLATIONS
# ============================================================
CATEGORY_TRANSLATIONS = {
    # Ch13: Sedative-Hypnotics and Wakefulness-Promoting Drugs
    "镇静催眠药概述": "Overview of Sedative-Hypnotics",
    "苯二氮䓬类": "Benzodiazepines",
    "苯二氮䓬类作用机制": "Mechanisms of Benzodiazepines",
    "巴比妥类": "Barbiturates",
    "巴比妥类作用机制": "Mechanisms of Barbiturates",
    "苯二氮䓬类与巴比妥类比较": "Benzodiazepines vs. Barbiturates",
    "其他镇静催眠药": "Other Sedative-Hypnotics",
    "非苯二氮䓬类": "Non-Benzodiazepines (Z-drugs)",
    "促觉醒药": "Wakefulness-Promoting Drugs",
    "抗组胺药": "Antihistamines",
    "镇静催眠药使用原则": "Principles of Sedative-Hypnotic Use",
    "各类镇静催眠药": "Classes of Sedative-Hypnotics",
    "褪黑素受体激动药": "Melatonin Receptor Agonists",
    "食欲素受体阻断药": "Orexin Receptor Antagonists",

    # Ch14: Antiepileptic and Anticonvulsant Drugs
    "抗癫痫药概述": "Overview of Antiepileptic Drugs",
    "抗癫痫药分类": "Classification of Antiepileptic Drugs",
    "抗癫痫药作用机制": "Mechanisms of Antiepileptic Drugs",
    "苯妥英钠": "Phenytoin",
    "卡马西平": "Carbamazepine",
    "奥卡西平": "Oxcarbazepine",
    "丙戊酸钠": "Valproate",
    "乙琥胺": "Ethosuximide",
    "左乙拉西坦": "Levetiracetam",
    "布瓦西坦": "Brivaracetam",
    "托吡酯": "Topiramate",
    "吡仑帕奈": "Perampanel",
    "卢非酰胺": "Rufinamide",
    "司替戊醇": "Stiripentol",
    "大麻二酚": "Cannabidiol",
    "抗惊厥药": "Anticonvulsant Drugs",

    # Ch15: Drugs for Neurodegenerative Diseases
    "帕金森病概述": "Overview of Parkinson Disease",
    "左旋多巴": "Levodopa",
    "拟多巴胺类药": "Dopaminergic Drugs",
    "卡比多巴": "Carbidopa",
    "苄丝肼": "Benserazide",
    "多巴胺受体激动药": "Dopamine Receptor Agonists",
    "MAO-B抑制药": "MAO-B Inhibitors",
    "COMT抑制药": "COMT Inhibitors",
    "中枢M受体阻断药": "Central Muscarinic Receptor Antagonists",
    "M受体激动药": "Muscarinic Receptor Agonists",
    "NMDA受体拮抗药": "NMDA Receptor Antagonists",
    "AD治疗药物": "Drugs for Alzheimer Disease",
    "胆碱酯酶抑制药": "Cholinesterase Inhibitors",
    "单克隆抗体": "Monoclonal Antibodies",
    "其他药物": "Other Drugs",

    # Ch16: Drugs for Mental Disorders
    "抗精神病药基本概念": "Basic Concepts of Antipsychotic Drugs",
    "抗精神病药-典型": "Typical Antipsychotics",
    "抗精神病药-非典型": "Atypical Antipsychotics",
    "抗抑郁症药": "Antidepressant Drugs",
    "抗抑郁症药基本概念": "Basic Concepts of Antidepressant Drugs",
    "抗躁狂症药": "Antimanic Drugs",
    "抗焦虑药": "Anxiolytic Drugs",

    # Ch17: Opioid Analgesics, Drug Dependence and Abuse
    "阿片受体基础": "Opioid Receptor Basics",
    "吗啡": "Morphine",
    "可待因": "Codeine",
    "哌替啶": "Meperidine (Pethidine)",
    "美沙酮": "Methadone",
    "芬太尼": "Fentanyl",
    "其他镇痛药": "Other Analgesics",
    "阿片受体部分激动药": "Opioid Receptor Partial Agonists",
    "阿片受体阻断药": "Opioid Receptor Antagonists",
    "药物依赖性": "Drug Dependence",
    "阿片受体激动药": "Opioid Receptor Agonists",

    # Ch18: Antipyretic, Analgesic and Anti-inflammatory Drugs (NSAIDs)
    "NSAIDs概述": "Overview of NSAIDs",
    "阿司匹林": "Aspirin",
    "水杨酸类": "Salicylates",
    "对乙酰氨基酚": "Acetaminophen (Paracetamol)",
    "乙酸类": "Acetic Acid Derivatives",
    "丙酸类": "Propionic Acid Derivatives",
    "烯醇酸类": "Enolic Acid Derivatives (Oxicams)",
    "吡唑酮类": "Pyrazolones",
    "灭酸酯类": "Fenamates",
    "选择性COX-2抑制药": "Selective COX-2 Inhibitors",
    "DMARDs": "DMARDs",
    "抗痛风药": "Antigout Drugs",
}

# ============================================================
# SECTION 2: DRUG NAME TRANSLATIONS (INN/Generic)
# ============================================================
DRUG_NAMES = {
    # Benzodiazepines
    "地西泮": "diazepam",
    "艾司唑仑": "estazolam",
    "阿普唑仑": "alprazolam",
    "劳拉西泮": "lorazepam",
    "奥沙西泮": "oxazepam",
    "氯硝西泮": "clonazepam",
    "三唑仑": "triazolam",
    "氟西泮": "flurazepam",
    "硝西泮": "nitrazepam",
    "替马西泮": "temazepam",
    "咪达唑仑": "midazolam",
    "氟马西尼": "flumazenil",
    "氯氮卓": "chlordiazepoxide",

    # Barbiturates
    "苯巴比妥": "phenobarbital",
    "硫喷妥钠": "thiopental sodium",
    "异戊巴比妥": "amobarbital",
    "司可巴比妥": "secobarbital",
    "戊巴比妥": "pentobarbital",

    # Z-drugs
    "唑吡坦": "zolpidem",
    "扎来普隆": "zaleplon",
    "佐匹克隆": "zopiclone",
    "右佐匹克隆": "eszopiclone",

    # Melatonin / Orexin
    "褪黑素": "melatonin",
    "雷美替胺": "ramelteon",
    "阿戈美拉汀": "agomelatine",
    "苏沃雷生": "suvorexant",
    "达利多雷生": "daridorexant",
    "苯海拉明": "diphenhydramine",

    # Other sedative/anxiolytic
    "丁螺环酮": "buspirone",
    "水合氯醛": "chloral hydrate",

    # Wakefulness-promoting
    "咖啡因": "caffeine",
    "哌甲酯": "methylphenidate",
    "莫达非尼": "modafinil",
    "阿莫达非尼": "armodafinil",
    "索利氨酯": "solriamfetol",
    "替洛利生": "pitolisant",

    # Antiepileptics
    "苯妥英": "phenytoin",
    "苯妥英钠": "phenytoin sodium",
    "卡马西平": "carbamazepine",
    "奥卡西平": "oxcarbazepine",
    "丙戊酸": "valproic acid",
    "丙戊酸钠": "sodium valproate",
    "乙琥胺": "ethosuximide",
    "左乙拉西坦": "levetiracetam",
    "布瓦西坦": "brivaracetam",
    "托吡酯": "topiramate",
    "吡仑帕奈": "perampanel",
    "卢非酰胺": "rufinamide",
    "司替戊醇": "stiripentol",
    "大麻二酚": "cannabidiol",
    "苯二氮卓类": "benzodiazepines",
    "苯二氮䓬类": "benzodiazepines",
    "苯二氮䓬": "benzodiazepine",
    "加巴喷丁": "gabapentin",
    "普瑞巴林": "pregabalin",
    "拉莫三嗪": "lamotrigine",
    "非尔氨酯": "felbamate",
    "氨己烯酸": "vigabatrin",
    "噻加宾": "tiagabine",
    "唑尼沙胺": "zonisamide",
    "拉考沙胺": "lacosamide",
    "艾司利卡西平": "eslicarbazepine",
    "醋酸艾司利卡西平": "eslicarbazepine acetate",
    "芬氟拉明": "fenfluramine",
    "氯巴占": "clobazam",

    # Antipsychotics
    "氯丙嗪": "chlorpromazine",
    "奋乃静": "perphenazine",
    "氟奋乃静": "fluphenazine",
    "三氟拉嗪": "trifluoperazine",
    "硫利达嗪": "thioridazine",
    "氟哌啶醇": "haloperidol",
    "氯普噻吨": "chlorprothixene",
    "氟哌噻吨": "flupentixol",
    "舒必利": "sulpiride",
    "氯氮平": "clozapine",
    "奥氮平": "olanzapine",
    "利培酮": "risperidone",
    "帕利哌酮": "paliperidone",
    "喹硫平": "quetiapine",
    "齐拉西酮": "ziprasidone",
    "阿立哌唑": "aripiprazole",
    "布南色林": "blonanserin",
    "鲁拉西酮": "lurasidone",
    "氨磺必利": "amisulpride",
    "卡利拉嗪": "cariprazine",
    "依匹哌唑": "brexpiprazole",

    # Antidepressants
    "丙米嗪": "imipramine",
    "阿米替林": "amitriptyline",
    "氯米帕明": "clomipramine",
    "多塞平": "doxepin",
    "地昔帕明": "desipramine",
    "去甲替林": "nortriptyline",
    "氟西汀": "fluoxetine",
    "帕罗西汀": "paroxetine",
    "舍曲林": "sertraline",
    "氟伏沙明": "fluvoxamine",
    "西酞普兰": "citalopram",
    "艾司西酞普兰": "escitalopram",
    "文拉法辛": "venlafaxine",
    "度洛西汀": "duloxetine",
    "米氮平": "mirtazapine",
    "曲唑酮": "trazodone",
    "安非他酮": "bupropion",
    "吗氯贝胺": "moclobemide",
    "苯乙肼": "phenelzine",
    "反苯环丙胺": "tranylcypromine",
    "沃替西汀": "vortioxetine",
    "阿戈美拉汀": "agomelatine",
    "艾司氯胺酮": "esketamine",

    # Mood stabilizers
    "碳酸锂": "lithium carbonate",
    "锂盐": "lithium salts",
    "锂": "lithium",

    # Ch15 - Parkinson's / AD
    "左旋多巴": "levodopa",
    "卡比多巴": "carbidopa",
    "苄丝肼": "benserazide",
    "司来吉兰": "selegiline",
    "雷沙吉兰": "rasagiline",
    "恩他卡朋": "entacapone",
    "托卡朋": "tolcapone",
    "溴隐亭": "bromocriptine",
    "培高利特": "pergolide",
    "普拉克索": "pramipexole",
    "罗匹尼罗": "ropinirole",
    "罗替高汀": "rotigotine",
    "阿扑吗啡": "apomorphine",
    "苯海索": "trihexyphenidyl",
    "苯扎托品": "benztropine",
    "金刚烷胺": "amantadine",
    "多奈哌齐": "donepezil",
    "卡巴拉汀": "rivastigmine",
    "加兰他敏": "galantamine",
    "美金刚": "memantine",
    "阿杜那单抗": "aducanumab",
    "仑卡奈单抗": "lecanemab",
    "多奈单抗": "donanemab",
    "甘露特钠": "sodium oligomannate",
    "维生素B6": "vitamin B6",

    # Ch17 - Opioids
    "吗啡": "morphine",
    "可待因": "codeine",
    "哌替啶": "meperidine (pethidine)",
    "美沙酮": "methadone",
    "芬太尼": "fentanyl",
    "舒芬太尼": "sufentanil",
    "阿芬太尼": "alfentanil",
    "瑞芬太尼": "remifentanil",
    "羟甲左吗喃": "levorphanol",
    "布桂嗪": "bucinnazine",
    "曲马多": "tramadol",
    "罗通定": "rotundine",
    "喷他佐辛": "pentazocine",
    "布托啡诺": "butorphanol",
    "丁丙诺啡": "buprenorphine",
    "纳布啡": "nalbuphine",
    "地佐辛": "dezocine",
    "纳洛酮": "naloxone",
    "纳曲酮": "naltrexone",
    "纳美芬": "nalmefene",
    "海洛因": "heroin",
    "洛非西定": "lofexidine",
    "可乐定": "clonidine",
    "α-乙酰美沙酮": "α-acetylmethadol",

    # Ch18 - NSAIDs / Antigout
    "阿司匹林": "aspirin",
    "布洛芬": "ibuprofen",
    "对乙酰氨基酚": "acetaminophen (paracetamol)",
    "塞来昔布": "celecoxib",
    "双氯芬酸": "diclofenac",
    "吲哚美辛": "indomethacin",
    "萘普生": "naproxen",
    "舒林酸": "sulindac",
    "酮咯酸": "ketorolac",
    "萘丁美酮": "nabumetone",
    "托美丁": "tolmetin",
    "依托度酸": "etodolac",
    "吡罗昔康": "piroxicam",
    "美洛昔康": "meloxicam",
    "氯诺昔康": "lornoxicam",
    "替诺昔康": "tenoxicam",
    "氟比洛芬": "flurbiprofen",
    "酮洛芬": "ketoprofen",
    "奥沙普秦": "oxaprozin",
    "非诺洛芬": "fenoprofen",
    "保泰松": "phenylbutazone",
    "甲芬那酸": "mefenamic acid",
    "甲氯芬那酸": "meclofenamic acid",
    "氟芬那酸": "flufenamic acid",
    "罗非昔布": "rofecoxib",
    "伐地昔布": "valdecoxib",
    "帕瑞昔布": "parecoxib",
    "艾瑞昔布": "imrecoxib",
    "依托考昔": "etoricoxib",
    "鲁米昔布": "lumiracoxib",
    "尼美舒利": "nimesulide",
    "美沙拉嗪": "mesalazine",
    "二氟尼柳": "diflunisal",
    "米索前列醇": "misoprostol",
    "吲哚美辛": "indomethacin",

    # DMARDs
    "甲氨蝶呤": "methotrexate",
    "来氟米特": "leflunomide",
    "柳氮磺吡啶": "sulfasalazine",
    "羟氯喹": "hydroxychloroquine",
    "硫唑嘌呤": "azathioprine",
    "环孢素": "cyclosporine",
    "艾拉莫德": "iguratimod",
    "依那西普": "etanercept",
    "阿达木单抗": "adalimumab",
    "英夫利西单抗": "infliximab",
    "托珠单抗": "tocilizumab",
    "利妥昔单抗": "rituximab",
    "阿巴西普": "abatacept",
    "阿那白滞素": "anakinra",
    "托法替尼": "tofacitinib",
    "巴瑞替尼": "baricitinib",
    "乌帕替尼": "upadacitinib",
    "非戈替尼": "filgotinib",

    # Antigout
    "秋水仙碱": "colchicine",
    "别嘌醇": "allopurinol",
    "奥昔嘌醇": "oxypurinol",
    "非布司他": "febuxostat",
    "丙磺舒": "probenecid",
    "苯溴马隆": "benzbromarone",
    "多替诺雷": "dotinurad",
    "拉布立酶": "rasburicase",
    "普瑞凯希": "pegloticase",

    # Other drug terms
    "青霉素": "penicillin",
    "华法林": "warfarin",
    "地高辛": "digoxin",
    "阿托品": "atropine",
    "肾上腺素": "epinephrine",
    "去甲肾上腺素": "norepinephrine",
    "碳酸氢钠": "sodium bicarbonate",
    "N-乙酰半胱氨酸": "N-acetylcysteine",
    "谷胱甘肽": "glutathione",
}

# ============================================================
# SECTION 3: COMPOUND KEYWORD-PHRASE TRANSLATIONS (higher priority, longer matches first)
# ============================================================
# Format: (Chinese_phrase, English_translation) - applied in order, longest first
MEDICAL_TERMS = [
    # ----- Question Type & Basic Terms -----
    ("是非题", "True/False"),
    ("单选题", "Single Choice"),
    ("简答题(多选)", "Multiple Choice"),
    ("【简答题】", "[Multiple Choice] "),
    ("（多选）", " (Select all that apply)"),
    ("正确", "True"),
    ("错误", "False"),
    ("（多选）", " (Select all that apply)"),

    # ----- Neurotransmitters & Receptors -----
    ("苯二氮䓬类", "benzodiazepines"),
    ("苯二氮䓬", "benzodiazepine"),
    ("巴比妥类", "barbiturates"),
    ("巴比妥", "barbiturate"),
    ("乙酰胆碱", "acetylcholine (ACh)"),
    ("去甲肾上腺素", "norepinephrine (NE/NA)"),
    ("5-羟色胺", "serotonin (5-HT)"),
    ("多巴胺", "dopamine (DA)"),
    ("γ-氨基丁酸", "GABA"),
    ("谷氨酸", "glutamate"),
    ("组胺", "histamine"),
    ("前列腺素", "prostaglandin (PG)"),
    ("白三烯", "leukotrienes"),
    ("缓激肽", "bradykinin"),
    ("P物质", "substance P"),
    ("脑啡肽", "enkephalin"),
    ("内啡肽", "endorphin"),
    ("强啡肽", "dynorphin"),
    ("内吗啡肽", "endomorphin"),
    ("孤啡肽", "nociceptin/orphanin FQ"),
    ("多巴胺能", "dopaminergic"),
    ("胆碱能", "cholinergic"),
    ("GABA能", "GABAergic"),
    ("谷氨酸能", "glutamatergic"),
    ("5-HT能", "serotonergic"),
    ("去甲肾上腺素能", "noradrenergic"),

    # ----- Receptor subtypes -----
    ("GABAA受体", "GABAA receptor"),
    ("GABAB受体", "GABAB receptor"),
    ("苯二氮䓬类结合位点", "benzodiazepine binding site"),
    ("苯二氮䓬结合位点", "benzodiazepine binding site"),
    ("D2样受体", "D2-like receptors"),
    ("D2受体", "D2 receptor"),
    ("D1受体", "D1 receptor"),
    ("5-HT2A受体", "5-HT2A receptor"),
    ("5-HT2C受体", "5-HT2C receptor"),
    ("5-HT1A受体", "5-HT1A receptor"),
    ("μ受体", "mu-opioid receptor (MOR)"),
    ("δ受体", "delta-opioid receptor (DOR)"),
    ("κ受体", "kappa-opioid receptor (KOR)"),
    ("NOP受体", "NOP receptor (nociceptin receptor)"),
    ("阿片受体", "opioid receptor"),
    ("MT1受体", "MT1 receptor"),
    ("MT2受体", "MT2 receptor"),
    ("H1受体", "H1 receptor"),
    ("NMDA受体", "NMDA receptor"),
    ("M受体", "muscarinic receptor"),
    ("M1受体", "M1 receptor"),
    ("M4受体", "M4 receptor"),
    ("M5受体", "M5 receptor"),
    ("α2受体", "alpha-2 receptor"),
    ("β受体", "beta receptor"),
    ("β1受体", "beta-1 receptor"),
    ("β2受体", "beta-2 receptor"),

    # ----- Ion channels -----
    ("钠通道", "sodium channel"),
    ("钙通道", "calcium channel"),
    ("钾通道", "potassium channel"),
    ("氯通道", "chloride channel"),
    ("氯离子通道", "chloride ion channel"),
    ("T型钙通道", "T-type calcium channel"),
    ("L型钙通道", "L-type calcium channel"),
    ("电压门控钠通道", "voltage-gated sodium channel"),
    ("电压门控钾通道", "voltage-gated potassium channel"),

    # ----- Enzymes & Proteins -----
    ("芳香族左旋氨基酸脱羧酶", "aromatic L-amino acid decarboxylase (AADC)"),
    ("AADC", "AADC"),
    ("单胺氧化酶", "monoamine oxidase (MAO)"),
    ("MAO-A", "MAO-A"),
    ("MAO-B", "MAO-B"),
    ("COMT", "COMT (catechol-O-methyltransferase)"),
    ("儿茶酚-O-甲基转移酶", "catechol-O-methyltransferase (COMT)"),
    ("乙酰胆碱酯酶", "acetylcholinesterase (AChE)"),
    ("丁酰胆碱酯酶", "butyrylcholinesterase (BuChE)"),
    ("胆碱酯酶", "cholinesterase"),
    ("环氧合酶", "cyclooxygenase (COX)"),
    ("COX-1", "COX-1"),
    ("COX-2", "COX-2"),
    ("COX", "COX"),
    ("腺苷酸环化酶", "adenylyl cyclase"),
    ("黄嘌呤氧化酶", "xanthine oxidase (XO)"),
    ("XO", "XO"),
    ("酪氨酸羟化酶", "tyrosine hydroxylase"),
    ("肝药酶", "hepatic drug-metabolizing enzymes"),
    ("细胞色素P450", "cytochrome P450"),
    ("CYP3A4", "CYP3A4"),
    ("CYP2D6", "CYP2D6"),
    ("CYP2C9", "CYP2C9"),
    ("CYP2C19", "CYP2C19"),

    # ----- Medical conditions -----
    ("帕金森病", "Parkinson disease (PD)"),
    ("PD", "PD"),
    ("阿尔茨海默病", "Alzheimer disease (AD)"),
    ("AD", "AD"),
    ("精神分裂症", "schizophrenia"),
    ("抑郁症", "depression"),
    ("双相情感障碍", "bipolar disorder"),
    ("躁狂症", "mania"),
    ("焦虑症", "anxiety disorder"),
    ("癫痫", "epilepsy"),
    ("癫痫持续状态", "status epilepticus"),
    ("失神发作", "absence seizure"),
    ("小发作", "absence seizure (petit mal)"),
    ("大发作", "generalized tonic-clonic seizure (grand mal)"),
    ("部分性发作", "focal (partial) seizure"),
    ("全身性发作", "generalized seizure"),
    ("肌阵挛发作", "myoclonic seizure"),
    ("失眠", "insomnia"),
    ("焦虑", "anxiety"),
    ("惊厥", "convulsion"),
    ("瑞氏综合征", "Reye syndrome"),
    ("支气管哮喘", "bronchial asthma"),
    ("哮喘", "asthma"),
    ("青光眼", "glaucoma"),
    ("重症肌无力", "myasthenia gravis"),
    ("颅脑损伤", "traumatic brain injury"),
    ("颅内压增高", "increased intracranial pressure"),
    ("肺心病", "cor pulmonale"),
    ("肝功能严重减退", "severe hepatic impairment"),
    ("肾功能减退", "renal impairment"),
    ("类风湿关节炎", "rheumatoid arthritis (RA)"),
    ("RA", "RA"),
    ("骨关节炎", "osteoarthritis"),
    ("痛风", "gout"),
    ("高尿酸血症", "hyperuricemia"),
    ("川崎病", "Kawasaki disease"),
    ("癌性疼痛", "cancer pain"),
    ("癌症晚期剧痛", "severe cancer-related pain"),
    ("心源性哮喘", "cardiac asthma"),
    ("克罗恩病", "Crohn disease"),
    ("溃疡性结肠炎", "ulcerative colitis"),
    ("高血压", "hypertension"),
    ("高血压危象", "hypertensive crisis"),
    ("心肌梗死", "myocardial infarction"),
    ("脑梗死", "cerebral infarction"),
    ("心绞痛", "angina pectoris"),

    # ----- Brain regions / pathways -----
    ("黑质-纹状体", "nigrostriatal"),
    ("黑质", "substantia nigra"),
    ("纹状体", "striatum"),
    ("中脑-边缘通路", "mesolimbic pathway"),
    ("中脑-皮质通路", "mesocortical pathway"),
    ("黑质-纹状体通路", "nigrostriatal pathway"),
    ("结节-漏斗通路", "tuberoinfundibular pathway"),
    ("中脑边缘多巴胺系统", "mesolimbic dopamine system"),
    ("奖赏通路", "reward pathway"),
    ("边缘系统", "limbic system"),
    ("蓝斑核", "locus coeruleus"),
    ("延髓孤束核", "nucleus tractus solitarius"),
    ("中脑盖前核", "pretectal nucleus"),
    ("丘脑内侧", "medial thalamus"),
    ("导水管周围灰质", "periaqueductal gray (PAG)"),
    ("脑桥呼吸调整中枢", "pontine respiratory center"),
    ("延髓", "medulla oblongata"),
    ("小脑", "cerebellum"),
    ("海马", "hippocampus"),
    ("前额叶皮质", "prefrontal cortex"),
    ("杏仁核", "amygdala"),

    # ----- Pharmacological concepts -----
    ("药动学", "pharmacokinetics"),
    ("药效学", "pharmacodynamics"),
    ("生物利用度", "bioavailability"),
    ("半衰期", "half-life"),
    ("表观分布容积", "apparent volume of distribution"),
    ("血浆蛋白结合率", "plasma protein binding rate"),
    ("稳态血药浓度", "steady-state plasma concentration"),
    ("血药浓度", "plasma concentration"),
    ("血脑屏障", "blood-brain barrier"),
    ("首过效应", "first-pass effect"),
    ("肝肠循环", "enterohepatic circulation"),
    ("肠肝循环", "enterohepatic circulation"),
    ("药物相互作用", "drug interaction"),
    ("不良反应", "adverse effects"),
    ("副作用", "side effects"),
    ("禁忌证", "contraindications"),
    ("适应症", "indications"),
    ("适应证", "indications"),
    ("耐受性", "tolerance"),
    ("依赖性", "dependence"),
    ("成瘾性", "addiction potential"),
    ("戒断症状", "withdrawal symptoms"),
    ("戒断综合征", "withdrawal syndrome"),
    ("药物依赖性", "drug dependence"),
    ("药物滥用", "drug abuse"),
    ("精神依赖性", "psychological dependence"),
    ("生理依赖性", "physical dependence"),
    ("欣快感", "euphoria"),
    ("正性强化作用", "positive reinforcement"),
    ("脱毒治疗", "detoxification treatment"),
    ("替代治疗", "substitution therapy"),
    ("防复吸", "relapse prevention"),
    ("维持治疗", "maintenance treatment"),
    ("效价强度", "potency"),
    ("效能", "efficacy"),
    ("竞争性拮抗", "competitive antagonism"),
    ("非竞争性拮抗", "noncompetitive antagonism"),
    ("激动药", "agonist"),
    ("拮抗药", "antagonist"),
    ("部分激动药", "partial agonist"),
    ("阻断药", "antagonist/blocker"),
    ("抑制药", "inhibitor"),
    ("诱导剂", "inducer"),
    ("前体药物", "prodrug"),
    ("前药", "prodrug"),
    ("代谢产物", "metabolite"),
    ("活性代谢物", "active metabolite"),
    ("原形", "unchanged form"),
    ("一级动力学", "first-order kinetics"),
    ("零级动力学", "zero-order kinetics"),
    ("G蛋白偶联受体", "G protein-coupled receptor (GPCR)"),
    ("血脂屏障", "blood-brain barrier"),

    # ----- Clinical terms -----
    ("锥体外系反应", "extrapyramidal symptoms (EPS)"),
    ("锥体外系", "extrapyramidal system"),
    ("体位性低血压", "orthostatic hypotension"),
    ("直立性低血压", "orthostatic hypotension"),
    ("胃肠道反应", "gastrointestinal adverse effects"),
    ("胃肠道不良反应", "gastrointestinal adverse effects"),
    ("胃肠道", "gastrointestinal tract"),
    ("呼吸抑制", "respiratory depression"),
    ("恶心", "nausea"),
    ("呕吐", "vomiting"),
    ("便秘", "constipation"),
    ("腹泻", "diarrhea"),
    ("镇静", "sedation"),
    ("催眠", "hypnosis"),
    ("嗜睡", "drowsiness"),
    ("眩晕", "dizziness"),
    ("头痛", "headache"),
    ("耳鸣", "tinnitus"),
    ("口干", "dry mouth"),
    ("尿潴留", "urinary retention"),
    ("瞳孔缩小", "miosis"),
    ("瞳孔散大", "mydriasis"),
    ("针尖样瞳孔", "pinpoint pupils"),
    ("高催乳素血症", "hyperprolactinemia"),
    ("溢乳", "galactorrhea"),
    ("迟发性运动障碍", "tardive dyskinesia"),
    ("静坐不能", "akathisia"),
    ("急性肌张力障碍", "acute dystonia"),
    ("帕金森综合征", "parkinsonism"),
    ("5-HT综合征", "serotonin syndrome"),
    ("恶性综合征", "neuroleptic malignant syndrome (NMS)"),
    ("心律失常", "arrhythmia"),
    ("QT间期延长", "QT interval prolongation"),
    ("肝毒性", "hepatotoxicity"),
    ("肝坏死", "hepatic necrosis"),
    ("肝损伤", "liver injury"),
    ("肾毒性", "nephrotoxicity"),
    ("耳毒性", "ototoxicity"),
    ("过敏反应", "hypersensitivity reaction"),
    ("皮疹", "rash"),
    ("荨麻疹", "urticaria"),
    ("阿司匹林哮喘", "aspirin-exacerbated respiratory disease (AERD)"),
    ("AERD", "AERD"),
    ("出血", "bleeding"),
    ("凝血功能障碍", "coagulation disorder"),
    ("血栓", "thrombosis"),
    ("胃肠道出血", "gastrointestinal bleeding"),
    ("胃溃疡", "gastric ulcer"),
    ("心血管事件", "cardiovascular events"),
    ("水钠潴留", "fluid and sodium retention"),
    ("高血钾", "hyperkalemia"),
    ("转氨酶", "transaminase"),
    ("粒细胞缺乏症", "agranulocytosis"),
    ("白细胞减少", "leukopenia"),
    ("肝药酶诱导", "enzyme induction"),
    ("肝药酶抑制", "enzyme inhibition"),

    # ----- Anatomical / physiological -----
    ("中枢神经系统", "central nervous system (CNS)"),
    ("中枢神经", "central nervous system"),
    ("中枢", "CNS"),
    ("外周", "peripheral"),
    ("突触前膜", "presynaptic membrane"),
    ("突触后膜", "postsynaptic membrane"),
    ("突触前", "presynaptic"),
    ("突触后", "postsynaptic"),
    ("突触间隙", "synaptic cleft"),
    ("神经末梢", "nerve terminal"),
    ("神经递质", "neurotransmitter"),
    ("神经调质", "neuromodulator"),
    ("再摄取", "reuptake"),
    ("重摄取", "reuptake"),
    ("胞吐", "exocytosis"),
    ("脱羧", "decarboxylation"),
    ("乙酰化", "acetylation"),
    ("甲基化", "methylation"),
    ("葡萄糖醛酸结合", "glucuronidation"),
    ("硫酸结合", "sulfation"),

    # ----- Disease concepts -----
    ("阳性症状", "positive symptoms"),
    ("阴性症状", "negative symptoms"),
    ("认知功能障碍", "cognitive impairment"),
    ("认知功能", "cognitive function"),
    ("神经元", "neuron"),
    ("神经元异常放电", "abnormal neuronal discharge"),
    ("神经退行性变", "neurodegeneration"),
    ("神经退行性疾病", "neurodegenerative disease"),
    ("神经保护", "neuroprotection"),
    ("神经可塑性", "neuroplasticity"),
    ("氧化应激", "oxidative stress"),
    ("炎症", "inflammation"),
    ("炎症介质", "inflammatory mediator"),
    ("免疫系统", "immune system"),
    ("淋巴细胞", "lymphocyte"),
    ("NK细胞", "NK cells"),
    ("细胞因子", "cytokine"),
    ("白细胞介素", "interleukin"),
    ("IL-1", "IL-1"),
    ("IL-6", "IL-6"),
    ("TNF-α", "TNF-alpha"),
    ("肿瘤坏死因子", "tumor necrosis factor (TNF)"),
    ("β-淀粉样蛋白", "beta-amyloid (Aβ)"),
    ("Aβ", "Aβ"),
    ("tau蛋白", "tau protein"),
    ("神经原纤维缠结", "neurofibrillary tangles"),
    ("老年斑", "senile plaques"),
    ("多巴胺", "dopamine"),
    ("5-HT", "5-HT"),
    ("NA", "NA (norepinephrine)"),

    # ----- Therapeutic approaches -----
    ("抗精神病药", "antipsychotic drug"),
    ("典型抗精神病药", "typical (first-generation) antipsychotic"),
    ("非典型抗精神病药", "atypical (second-generation) antipsychotic"),
    ("第一代抗精神病药", "first-generation antipsychotic"),
    ("第二代抗精神病药", "second-generation antipsychotic"),
    ("抗抑郁药", "antidepressant"),
    ("三环类抗抑郁药", "tricyclic antidepressant (TCA)"),
    ("TCA", "TCA"),
    ("SSRI", "SSRI"),
    ("SNRI", "SNRI"),
    ("MAOI", "MAOI"),
    ("NaSSA", "NaSSA"),
    ("选择性5-HT再摄取抑制药", "selective serotonin reuptake inhibitor (SSRI)"),
    ("5-HT和NA再摄取抑制药", "serotonin-norepinephrine reuptake inhibitor (SNRI)"),
    ("单胺氧化酶抑制药", "monoamine oxidase inhibitor (MAOI)"),
    ("抗癫痫药", "antiepileptic drug (AED)"),
    ("AED", "AED"),
    ("抗惊厥药", "anticonvulsant"),
    ("镇静催眠药", "sedative-hypnotic"),
    ("促觉醒药", "wakefulness-promoting drug"),
    ("阿片类镇痛药", "opioid analgesic"),
    ("解热镇痛抗炎药", "NSAID (nonsteroidal anti-inflammatory drug)"),
    ("NSAID", "NSAID"),
    ("非甾体抗炎药", "NSAID"),
    ("tNSAIDs", "tNSAIDs (traditional NSAIDs)"),
    ("选择性COX-2抑制药", "selective COX-2 inhibitor"),
    ("昔布类", "coxibs"),
    ("非选择性NSAIDs", "nonselective NSAIDs"),
    ("传统合成DMARDs", "conventional synthetic DMARDs (csDMARDs)"),
    ("DMARDs", "DMARDs"),
    ("生物制剂DMARDs", "biologic DMARDs (bDMARDs)"),
    ("靶向合成DMARDs", "targeted synthetic DMARDs (tsDMARDs)"),
    ("JAK抑制药", "JAK inhibitor"),
    ("NSAIDs", "NSAIDs"),

    # ----- Miscellaneous medical terms -----
    ("胃黏膜", "gastric mucosa"),
    ("胃肠黏膜", "gastrointestinal mucosa"),
    ("血小板", "platelet"),
    ("血小板聚集", "platelet aggregation"),
    ("血栓素", "thromboxane"),
    ("TxA2", "TxA2"),
    ("PGI2", "PGI2 (prostacyclin)"),
    ("PGE2", "PGE2"),
    ("NAPQI", "NAPQI (N-acetyl-p-benzoquinone imine)"),
    ("体温调定点", "thermoregulatory set point"),
    ("下丘脑", "hyPOthalamus"),
    ("体温调节中枢", "thermoregulatory center"),
    ("解热", "antipyresis"),
    ("镇痛", "analgesia"),
    ("抗炎", "anti-inflammatory"),
    ("抗风湿", "antirheumatic"),
    ("排尿", "urination"),
    ("排便", "defecation"),
    ("排便反射", "defecation reflex"),
    ("咳嗽反射", "cough reflex"),
    ("咳嗽中枢", "cough center"),
    ("呕吐中枢", "vomiting center"),
    ("催吐化学感受区", "chemoreceptor trigger zone (CTZ)"),
    ("CTZ", "CTZ"),
    ("麻醉药品", "controlled substance / narcotic"),
    ("麻醉", "anesthesia"),
    ("睡眠", "sleep"),
    ("觉醒", "wakefulness"),
    ("生物节律", "circadian rhythm"),
    ("昼夜节律", "circadian rhythm"),
    ("松果体", "pineal gland"),
    ("授时因子", "zeitgeber"),
    ("脱髓鞘", "demyelination"),
    ("髓鞘", "myelin sheath"),
    ("尿酸", "uric acid"),
    ("尿囊素", "allantoin"),
    ("肾小管", "renal tubule"),
    ("近曲小管", "proximal convoluted tubule"),
    ("URAT-1", "URAT1"),
    ("促尿酸排泄", "uricosuric"),
    ("微管蛋白", "tubulin"),
    ("中性粒细胞", "neutrophil"),
    ("滑膜腔", "synovial cavity"),
    ("关节", "joint"),
    ("肌肉", "muscle"),
    ("平滑肌", "smooth muscle"),
    ("括约肌", "sphincter"),
    ("奥狄括约肌", "sphincter of Oddi"),
    ("子宫平滑肌", "uterine smooth muscle"),
    ("催产素", "oxytocin"),
    ("支气管平滑肌", "bronchial smooth muscle"),
    ("血管平滑肌", "vascular smooth muscle"),
    ("胆道", "biliary tract"),
    ("胆囊", "gallbladder"),
    ("胆汁", "bile"),
    ("肥大细胞", "mast cell"),
    ("柱状细胞", "mast cell"),
    ("组胺释放", "histamine release"),
    ("抗组胺药", "antihistamine"),
    ("质子泵抑制药", "proton pump inhibitor (PPI)"),
    ("糖皮质激素", "glucocorticoid (GC)"),
    ("GC", "GC"),
    ("白三烯受体阻断药", "leukotriene receptor antagonist"),
    ("维生素D", "vitamin D"),
    ("叶酸", "folic acid"),
    ("饮酒", "alcohol consumption"),
    ("酒精", "alcohol"),
    ("乙醇", "ethanol"),

    # ----- Common pharmacological phrases -----
    ("治疗指数", "therapeutic index"),
    ("安全范围", "safety margin"),
    ("量效关系", "dose-response relationship"),
    ("最小有效剂量", "minimum effective dose"),
    ("常用量", "therapeutic dose"),
    ("中毒量", "toxic dose"),
    ("致死量", "lethal dose"),
    ("口服", "oral administration"),
    ("静脉注射", "intravenous injection"),
    ("肌肉注射", "intramuscular injection"),
    ("皮下注射", "subcutaneous injection"),
    ("舌下给药", "sublingual administration"),
    ("直肠给药", "rectal administration"),
    ("透皮", "transdermal"),
    ("贴剂", "patch"),
    ("滴眼液", "ophthalmic solution"),
    ("缓释制剂", "sustained-release preparation"),
    ("吸收", "absorption"),
    ("分布", "distribution"),
    ("代谢", "metabolism"),
    ("排泄", "excretion"),
    ("消除", "elimination"),
    ("蓄积", "accumulation"),

    # ----- Measurement units etc. -----
    ("mg", "mg"),
    ("g", "g"),
    ("μg", "mcg"),
    ("μg", "μg"),
    ("kg", "kg"),
    ("ml", "mL"),
    ("L", "L"),
    ("min", "min"),
    ("h", "h"),
    ("t1/2", "t1/2"),
    ("Css", "Css"),
    ("Cmax", "Cmax"),
    ("Tmax", "Tmax"),
    ("AUC", "AUC"),

    # ----- General Chinese characters/phrases -----
    ("增加", "increase"),
    ("减少", "decrease"),
    ("增强", "enhance"),
    ("减弱", "attenuate"),
    ("抑制", "inhibit"),
    ("激活", "activate"),
    ("阻断", "block"),
    ("促进", "promote"),
    ("加速", "accelerate"),
    ("延长", "prolong"),
    ("缩短", "shorten"),
    ("开放", "opening"),
    ("关闭", "closure"),
    ("频率", "frequency"),
    ("开放时间", "open time"),
    ("开放频率", "opening frequency"),
    ("导致", "leading to"),
    ("引起", "cause"),
    ("诱发", "induce"),
    ("产生", "produce"),
    ("发挥", "exert"),
    ("改善", "improve"),
    ("降低", "reduce"),
    ("升高", "elevate"),
    ("释放", "release"),
    ("合成", "synthesis"),
    ("分解", "degradation"),
    ("转运", "transport"),
    ("扩散", "spread"),
    ("传导", "conduction"),
    ("传递", "transmission"),
    ("整合", "integration"),
    ("调节", "regulate"),
    ("调控", "modulate"),
    ("维持", "maintain"),
    ("保护", "protect"),
    ("损伤", "damage"),
    ("修复", "repair"),
    ("再生", "regeneration"),
    ("变性", "degeneration"),
    ("坏死", "necrosis"),
    ("凋亡", "apoptosis"),
    ("内源性", "endogenous"),
    ("外源性", "exogenous"),
    ("选择性", "selective"),
    ("非选择性", "nonselective"),
    ("竞争性", "competitive"),
    ("非竞争性", "noncompetitive"),
    ("可逆性", "reversible"),
    ("不可逆性", "irreversible"),
    ("特异性", "specific"),
    ("高效", "high-potency"),
    ("低效", "low-potency"),
    ("长效", "long-acting"),
    ("短效", "short-acting"),
    ("中效", "intermediate-acting"),
    ("速效", "rapid-acting"),
    ("缓效", "slow-acting"),
    ("强效", "potent"),
    ("弱效", "weak"),
    ("立即", "immediately"),
    ("逐渐", "gradually"),
    ("持续", "continuous"),
    ("短暂", "transient"),
    ("长期", "long-term"),
    ("短期", "short-term"),
    ("急性", "acute"),
    ("慢性", "chronic"),
    ("亚急性", "subacute"),
    ("亚慢性", "subchronic"),

    # ----- Common verbs and connecting phrases -----
    ("表现为", "manifests as"),
    ("主要表现为", "is mainly characterized by"),
    ("可用于", "can be used for"),
    ("常用于", "is commonly used for"),
    ("主要用于", "is mainly used for"),
    ("适用于", "is indicated for"),
    ("禁用于", "is contraindicated in"),
    ("首选", "first-line / drug of choice"),
    ("一线", "first-line"),
    ("二线", "second-line"),
    ("与...相比", "compared with"),
    ("与...相似", "is similar to"),
    ("与...不同", "differs from"),
    ("与...合用", "used in combination with"),
    ("与...相同", "is identical to"),
    ("又称", "also known as"),
    ("即", "i.e.,"),
    ("例如", "for example"),
    ("如", "such as"),
    ("其中", "among which"),
    ("包括", "including"),
    ("不包括", "does not include / excluding"),
    ("属于", "belongs to"),
    ("机制", "mechanism"),
    ("通过", "via / through"),
    ("从而", "thereby"),
    ("防止", "prevent"),
    ("预防", "prevent"),
    ("治疗", "treat / treatment"),
    ("诊断", "diagnose / diagnosis"),
    ("预后", "prognosis"),
    ("发生", "occur"),
    ("发生率", "incidence"),
    ("死亡率", "mortality rate"),
    ("患病率", "prevalence"),
    ("恢复", "recovery"),

    # ===== SUPPLEMENTARY TERMS: Common Chinese medical/clinical vocabulary =====
    # Dosing & quantities
    ("小剂量", "low-dose"),
    ("大剂量", "high-dose"),
    ("较大剂量", "moderate-to-high dose"),
    ("中等剂量", "moderate dose"),
    ("常用量", "therapeutic dose"),
    ("用药量", "dosage"),
    ("给药剂量", "administered dose"),
    ("剂量依赖", "dose-dependent"),
    ("剂量依赖性", "dose-dependent"),
    ("用药", "medication"),
    ("服药", "administration"),
    ("给药", "administration"),
    ("用量", "dose"),
    ("用量过大", "excessive dosage"),
    ("口服给药", "oral administration"),
    ("静脉给药", "intravenous administration"),
    ("皮下给药", "subcutaneous administration"),
    ("用药期间", "during treatment"),
    ("给药后", "after administration"),
    ("服药后", "after administration"),
    ("用药次数", "dosing frequency"),
    ("给药间隔", "dosing interval"),
    ("每日给药一次", "once-daily dosing"),
    ("每日给药", "daily dosing"),
    ("每日一次", "once daily"),
    ("每日两次", "twice daily"),
    ("每日三次", "three times daily"),
    ("每次", "per dose"),
    ("过量", "overdose"),
    ("中毒", "poisoning"),
    ("中毒量", "toxic dose"),
    ("致死量", "lethal dose"),
    ("致死", "fatal"),
    ("致死性", "fatal"),
    ("严重", "severe"),
    ("轻度", "mild"),
    ("中度", "moderate"),
    ("重度", "severe"),
    ("危险", "risk / dangerous"),
    ("危及生命", "life-threatening"),
    ("最低有效浓度", "minimum effective concentration"),
    ("最低抑菌浓度", "minimum inhibitory concentration"),
    ("治疗浓度范围", "therapeutic range"),
    ("有效量", "effective dose"),
    ("维持量", "maintenance dose"),
    ("负荷量", "loading dose"),
    ("初始剂量", "initial dose"),
    ("起始剂量", "starting dose"),
    ("最大剂量", "maximum dose"),
    ("最小剂量", "minimum dose"),
    ("致死剂量", "lethal dose"),
    ("半数有效量", "ED50"),
    ("半数致死量", "LD50"),
    ("耐受", "tolerate"),

    # Time-related
    ("起效", "onset"),
    ("起效快", "rapid onset"),
    ("起效迅速", "rapid onset"),
    ("起效缓慢", "slow onset"),
    ("显效", "therapeutic effect"),
    ("达峰时间", "time to peak"),
    ("达峰值", "reaches peak concentration"),
    ("达峰浓度", "peak concentration"),
    ("持续时间", "duration"),
    ("作用时间", "duration of action"),
    ("作用持续时间", "duration of action"),
    ("消除半衰期", "elimination half-life"),
    ("终末半衰期", "terminal half-life"),
    ("分布半衰期", "distribution half-life"),
    ("达稳态时间", "time to steady state"),
    ("达稳态", "reach steady state"),
    ("长期用药", "long-term treatment"),
    ("短期用药", "short-term treatment"),
    ("长期使用", "long-term use"),
    ("长期服用", "long-term administration"),
    ("长期应用", "long-term use"),
    ("连续用药", "continuous administration"),
    ("长期大量", "prolonged high-dose"),
    ("立即起效", "immediate onset"),
    ("立即", "immediately"),
    ("逐渐", "gradually"),
    ("逐步", "stepwise"),
    ("缓慢", "slowly"),
    ("迅速", "rapidly"),
    ("快速", "rapidly"),
    ("很快", "quickly"),
    ("同时", "simultaneously"),
    ("预先", "in advance / prior"),
    ("之后", "after"),
    ("之前", "before"),
    ("之内", "within"),
    ("之后", "afterwards"),
    ("持续", "persistent"),
    ("间歇", "intermittent"),
    ("周期性", "periodic"),
    ("昼夜", "diurnal"),
    ("首次", "first / initial"),
    ("初", "initial / early"),
    ("末", "terminal / final"),
    ("晚期", "advanced / late-stage"),
    ("早期", "early-stage"),
    ("早期阶段", "early stage"),
    ("最后阶段", "final stage"),
    ("数小时", "several hours"),
    ("数天", "several days"),
    ("数周", "several weeks"),
    ("数月", "several months"),
    ("数年", "several years"),
    ("隔天", "every other day"),
    ("每晚", "every night"),
    ("临睡前", "before bedtime"),
    ("睡前", "before bedtime"),

    # Body systems and organs
    ("心血管系统", "cardiovascular system"),
    ("心血管", "cardiovascular"),
    ("肝脏", "liver"),
    ("肝脏代谢", "hepatic metabolism"),
    ("肝功能", "liver function"),
    ("肝功能不良", "hepatic impairment"),
    ("肝功能异常", "abnormal liver function"),
    ("肝功能不全", "hepatic insufficiency"),
    ("肝功能减退", "decreased liver function"),
    ("肝病", "liver disease"),
    ("肾脏", "kidney"),
    ("肾功能", "renal function"),
    ("肾功能不良", "renal impairment"),
    ("肾功能不全", "renal insufficiency"),
    ("肾衰竭", "renal failure"),
    ("肾功能衰竭", "renal failure"),
    ("肾毒性", "nephrotoxicity"),
    ("肾损伤", "renal injury"),
    ("肾脏损害", "renal damage"),
    ("胃肠道系统", "gastrointestinal system"),
    ("胃肠道黏膜", "gastrointestinal mucosa"),
    ("胃黏膜保护", "gastric mucosal protection"),
    ("消化道", "digestive tract"),
    ("消化道黏膜", "digestive tract mucosa"),
    ("肠黏膜", "intestinal mucosa"),
    ("肠道", "intestine"),
    ("小肠", "small intestine"),
    ("大肠", "large intestine"),
    ("结肠", "colon"),
    ("直肠", "rectum"),
    ("胃排空", "gastric emptying"),
    ("胃肠蠕动", "gastrointestinal motility"),
    ("胃肠运动", "gastrointestinal motility"),
    ("胃酸分泌", "gastric acid secretion"),
    ("胃液分泌", "gastric juice secretion"),
    ("胃蛋白酶", "pepsin"),
    ("幽门", "pylorus"),
    ("贲门", "cardia"),
    ("食管", "esophagus"),
    ("胰腺", "pancreas"),
    ("脾", "spleen"),
    ("肺", "lung"),
    ("肺泡", "alveoli"),
    ("支气管", "bronchi"),
    ("支气管收缩", "bronchoconstriction"),
    ("支气管扩张", "bronchodilation"),
    ("心脏", "heart"),
    ("心肌", "myocardium"),
    ("心率", "heart rate"),
    ("心律", "cardiac rhythm"),
    ("心输出量", "cardiac output"),
    ("血压", "blood pressure"),
    ("血压降低", "hypotension"),
    ("低血压", "hypotension"),
    ("高血压危象", "hypertensive crisis"),
    ("血管", "blood vessel"),
    ("血管扩张", "vasodilation"),
    ("血管收缩", "vasoconstriction"),
    ("阻力血管", "resistance vessels"),
    ("容量血管", "capacitance vessels"),
    ("动脉", "artery"),
    ("静脉", "vein"),
    ("毛细血管", "capillary"),
    ("冠状动脉", "coronary artery"),
    ("脑血管", "cerebral blood vessel"),
    ("脑血管扩张", "cerebral vasodilation"),
    ("脑血流", "cerebral blood flow"),
    ("脑血流量", "cerebral blood flow"),
    ("脑组织", "brain tissue"),
    ("脑内", "in the brain"),
    ("脑内分布", "brain distribution"),
    ("神经组织", "neural tissue"),
    ("神经元细胞", "neuronal cell"),
    ("神经细胞", "nerve cell"),
    ("神经末梢", "nerve terminal"),
    ("突触", "synapse"),
    ("突触间隙", "synaptic cleft"),
    ("突触小泡", "synaptic vesicle"),
    ("突触囊泡", "synaptic vesicle"),
    ("树突", "dendrite"),
    ("轴突", "axon"),
    ("胞体", "cell body"),
    ("髓鞘", "myelin sheath"),
    ("有髓纤维", "myelinated fiber"),
    ("无髓纤维", "unmyelinated fiber"),
    ("运动神经元", "motor neuron"),
    ("感觉神经元", "sensory neuron"),
    ("中间神经元", "interneuron"),
    ("交感神经", "sympathetic nerve"),
    ("副交感神经", "parasympathetic nerve"),
    ("自主神经", "autonomic nerve"),
    ("躯体运动神经", "somatic motor nerve"),

    # Common verbs in medical context
    ("表现为", "manifests as"),
    ("表现为", "presents as"),
    ("表明", "indicates"),
    ("提示", "suggests"),
    ("证实", "confirms"),
    ("显示", "shows / demonstrates"),
    ("研究表明", "studies show"),
    ("临床试验", "clinical trial"),
    ("临床研究", "clinical study"),
    ("临床观察", "clinical observation"),
    ("大样本", "large-scale"),
    ("随机对照", "randomized controlled"),
    ("安慰剂对照", "placebo-controlled"),
    ("前瞻性", "prospective"),
    ("回顾性", "retrospective"),
    ("双盲", "double-blind"),
    ("多中心", "multicenter"),
    ("临床数据", "clinical data"),
    ("临床证据", "clinical evidence"),
    ("循证医学", "evidence-based medicine"),
    ("产生", "produce"),
    ("生成", "generate / produce"),
    ("形成", "form"),
    ("合成", "synthesize"),
    ("分解", "decompose / degrade"),
    ("转化成", "convert to"),
    ("转变为", "transform into"),
    ("变为", "become"),
    ("造成", "cause / result in"),
    ("引起", "cause / induce"),
    ("导致", "lead to"),
    ("诱发", "induce / trigger"),
    ("促使", "promote"),
    ("诱发因素", "triggering factor"),
    ("危险因素", "risk factor"),
    ("危险因子", "risk factor"),
    ("保护因素", "protective factor"),
    ("发挥", "exert"),
    ("起作用", "act / function"),
    ("发挥效应", "exert effects"),
    ("产生影响", "exert influence"),
    ("具有活性", "is active / possesses activity"),
    ("有活性", "is active"),
    ("有作用", "has an effect"),
    ("无活性", "is inactive"),
    ("无作用", "has no effect"),
    ("无影响", "has no effect"),
    ("参与", "participate in / be involved in"),
    ("涉及", "involve"),
    ("关联", "be associated with"),
    ("相关", "related"),
    ("有关", "related / associated"),
    ("无关", "unrelated"),
    ("取决于", "depends on"),
    ("依赖于", "dependent on"),
    ("依赖", "depend on / rely on"),
    ("包括", "include"),
    ("含", "contain"),
    ("含有", "contain"),
    ("富含", "rich in"),
    ("缺乏", "lack / deficiency"),
    ("缺少", "lack"),
    ("不足", "insufficient / deficiency"),
    ("过量", "excessive / overdose"),
    ("过度", "excessive / over-"),
    ("过剩", "excess"),
    ("增多", "increased"),
    ("减少", "decreased"),
    ("增高", "elevated"),
    ("降低", "reduced"),
    ("升高", "elevated"),
    ("下降", "declined / decreased"),
    ("减退", "declined / reduced"),
    ("增强", "enhanced"),
    ("减弱", "attenuated"),
    ("加重", "exacerbate / worsen"),
    ("减轻", "alleviate / reduce"),
    ("缓解", "relieve / alleviate"),
    ("消除", "eliminate"),
    ("去除", "remove"),
    ("拮抗", "antagonize"),
    ("对抗", "counteract"),
    ("抵消", "offset / counteract"),
    ("中和", "neutralize"),
    ("干扰", "interfere with"),
    ("阻滞", "block"),
    ("阻碍", "impede / hinder"),
    ("防止", "prevent"),
    ("预防", "prevent / prophylaxis"),
    ("制止", "stop / arrest"),
    ("终止", "terminate"),
    ("停止", "stop / discontinue"),
    ("停药", "drug withdrawal / discontinuation"),
    ("暂停", "suspend / pause"),
    ("继续", "continue"),
    ("维持", "maintain"),
    ("保持", "keep / maintain"),
    ("恢复", "restore / recover"),
    ("修复", "repair"),
    ("再生", "regenerate"),
    ("重建", "rebuild / reconstruct"),
    ("逆转", "reverse"),
    ("转化", "convert / transform"),
    ("代谢转化", "metabolic conversion"),
    ("生物转化", "biotransformation"),
    ("吸收", "absorb"),
    ("分布", "distribute"),
    ("代谢", "metabolize"),
    ("排泄", "excrete"),
    ("消除", "eliminate"),
    ("蓄积", "accumulate"),
    ("蓄积中毒", "accumulation toxicity"),
    ("清除", "clear / eliminate"),
    ("清除率", "clearance"),
    ("廓清", "clear"),
    ("滤过", "filtration"),
    ("重吸收", "reabsorption"),
    ("分泌", "secrete"),
    ("排泄率", "excretion rate"),
    ("进入", "enter"),
    ("透过", "penetrate / cross"),
    ("不易透过", "does not readily cross"),
    ("易透过", "readily crosses"),
    ("可通过", "can cross"),
    ("不能通过", "cannot cross"),
    ("可通过胎盘", "crosses the placenta"),
    ("可透过胎盘", "can cross the placenta"),
    ("透过胎盘屏障", "cross the placental barrier"),
    ("随乳汁分泌", "excreted in breast milk"),
    ("乳汁", "breast milk"),
    ("乳汁分泌", "milk secretion"),
    ("哺乳", "breastfeeding / lactation"),
    ("新生儿", "neonate / newborn"),
    ("婴儿", "infant"),
    ("幼儿", "young child"),
    ("儿童", "child / children"),
    ("青少年", "adolescent"),
    ("成人", "adult"),
    ("老年人", "elderly"),
    ("育龄妇女", "woman of childbearing age"),
    ("孕妇", "pregnant woman"),
    ("妊娠期", "pregnancy"),
    ("产前", "antenatal / prenatal"),
    ("产后", "postpartum"),
    ("分娩", "childbirth / delivery / labor"),
    ("延长产程", "prolong labor"),
    ("围产期", "perinatal period"),
    ("哺乳期", "lactation period"),
    ("绝经后", "postmenopausal"),

    # Common adjectives & adverbs
    ("主要的", "main / primary"),
    ("主要", "mainly / primarily"),
    ("最重要的", "most important"),
    ("重要", "important"),
    ("基本", "basic / fundamental"),
    ("根本", "fundamental"),
    ("关键", "key / critical"),
    ("必要", "necessary / essential"),
    ("充分", "sufficient / adequate"),
    ("常见", "common"),
    ("常见的", "common"),
    ("常见的", "commonly seen"),
    ("偶见", "occasionally seen / rare"),
    ("少见", "rare"),
    ("罕见", "rare"),
    ("明显", "significant / marked"),
    ("显著", "significant"),
    ("显著性", "significance"),
    ("高效", "high-potency / highly effective"),
    ("强效", "potent"),
    ("中效", "intermediate-acting"),
    ("短效", "short-acting"),
    ("长效", "long-acting"),
    ("速效", "rapid-acting"),
    ("缓效", "slow-acting"),
    ("低效", "low-potency"),
    ("有效", "effective"),
    ("无效", "ineffective"),
    ("特效", "specific / specifically effective"),
    ("广谱", "broad-spectrum"),
    ("窄谱", "narrow-spectrum"),
    ("安全", "safe"),
    ("安全性", "safety"),
    ("不安全", "unsafe"),
    ("毒性", "toxicity"),
    ("毒", "toxic"),
    ("毒物", "toxic substance"),
    ("低毒", "low toxicity"),
    ("剧毒", "highly toxic"),
    ("无毒", "non-toxic"),
    ("相对安全", "relatively safe"),
    ("较为安全", "relatively safe"),
    ("方便", "convenient"),
    ("简便", "simple and convenient"),
    ("简单", "simple"),
    ("复杂", "complex"),
    ("困难", "difficult"),
    ("容易", "easy / readily"),
    ("难以", "difficult to"),
    ("易于", "prone to / easily"),
    ("适合", "suitable for"),
    ("适用", "applicable"),
    ("不适用", "not applicable"),
    ("合理", "rational / reasonable"),
    ("不合理", "irrational"),
    ("正确", "correct"),
    ("错误", "incorrect"),
    ("准确", "accurate"),
    ("精确", "precise"),
    ("正常", "normal"),
    ("异常", "abnormal"),
    ("阳性", "positive"),
    ("阴性", "negative"),
    ("假阳性", "false positive"),
    ("假阴性", "false negative"),
    ("真阳性", "true positive"),
    ("真阴性", "true negative"),
    ("纯", "pure"),
    ("混合型", "mixed-type"),
    ("杂合型", "hybrid type"),
    ("单纯型", "simple type"),
    ("典型", "typical"),
    ("非典型", "atypical"),
    ("经典型", "classical"),
    ("新型", "novel / new"),
    ("传统", "traditional / conventional"),
    ("经典", "classical"),
    ("常规", "routine / conventional"),
    ("非常规", "non-conventional"),
    ("特殊的", "specific / special"),
    ("特殊", "special"),
    ("一般", "general / generally"),
    ("普通", "common / ordinary"),
    ("广泛", "widely / extensively"),
    ("普遍", "generally / universally"),
    ("极少", "very rarely"),
    ("较多", "relatively many / more"),
    ("较少", "relatively few / less"),
    ("极少数", "very few"),
    ("绝大多数", "the vast majority"),
    ("多数", "most / majority"),
    ("少数", "a small number / minority"),
    ("部分", "part / some"),
    ("大部分", "most / the majority"),
    ("小部分", "a small portion"),
    ("某些", "certain / some"),
    ("全部", "all / entire"),
    ("整个", "the entire"),
    ("完全", "completely"),
    ("不完全", "incompletely"),
    ("彻底", "thoroughly"),
    ("充分地", "adequately"),
    ("适当地", "appropriately"),
    ("严格", "strictly"),
    ("慎重", "cautiously"),
    ("谨慎", "carefully / cautiously"),
    ("细心", "carefully"),
    ("仅", "only"),
    ("只", "only"),
    ("不仅", "not only"),
    ("除了", "besides / in addition to"),
    ("除...外", "except for / apart from"),
    ("不过", "however"),
    ("但是", "but / however"),
    ("而且", "moreover / furthermore"),
    ("并且", "and / also"),
    ("或", "or"),
    ("及", "and"),
    ("与", "and / with"),
    ("以及", "as well as"),
    ("及其", "and its"),
    ("其", "its / their"),
    ("该", "the / this"),
    ("此", "this"),
    ("这些", "these"),
    ("那些", "those"),
    ("这些药物", "these drugs"),
    ("这类药物", "this class of drugs"),
    ("此类药物", "this class of drugs"),
    ("该类药物", "this class of drugs"),
    ("此药", "this drug"),
    ("本类", "this class"),
    ("所有", "all"),
    ("任何一种", "any"),
    ("任何", "any"),
    ("某种", "a certain / some"),
    ("另一些", "others"),
    ("某些", "certain / some"),
    ("不同", "different / various"),
    ("相同", "same / identical"),
    ("同样", "same / similarly"),
    ("一致", "consistent / identical"),
    ("不一致", "inconsistent"),
    ("相似", "similar"),
    ("类似", "similar to"),
    ("不相同", "different"),
    ("各异", "varies / diverse"),
    ("多种", "various / multiple"),
    ("独特", "unique"),
    ("特点", "characteristic / feature"),
    ("特性", "property / characteristic"),
    ("特征", "characteristic / feature"),
    ("优点", "advantage"),
    ("缺点", "disadvantage"),
    ("优势", "advantage"),
    ("劣势", "disadvantage"),
    ("利弊", "advantages and disadvantages"),
    ("基础", "basis / foundation"),
    ("前提", "prerequisite"),
    ("核心", "core / central"),
    ("重中之重", "top priority"),
    ("重点", "key point"),

    # Academic / scientific writing
    ("目前", "currently / at present"),
    ("现在", "now / currently"),
    ("既往", "previously / in the past"),
    ("历史上", "historically"),
    ("近年", "in recent years"),
    ("近年来", "in recent years"),
    ("已有", "there have been / existing"),
    ("尚无", "there is no / not yet"),
    ("有待", "remains to be"),
    ("尚待", "has yet to be"),
    ("尚不明确", "remains unclear"),
    ("尚不清楚", "remains unclear"),
    ("尚未明确", "has not been clarified"),
    ("尚未确定", "has not been determined"),
    ("尚不能", "cannot yet"),
    ("可能", "may / possibly"),
    ("可能性", "possibility / likelihood"),
    ("很可能", "most likely"),
    ("可能原因", "possible cause"),
    ("确切机制", "exact mechanism"),
    ("具体机制", "specific mechanism"),
    ("详细机制", "detailed mechanism"),
    ("确切", "exact / precise"),
    ("具体", "specific / concrete"),
    ("根据", "according to / based on"),
    ("基于", "based on"),
    ("依据", "based on / according to"),
    ("因此", "therefore / thus"),
    ("所以", "therefore / so"),
    ("因为", "because / since"),
    ("由于", "due to / because of"),
    ("鉴于", "given that / in view of"),
    ("如果", "if"),
    ("若", "if"),
    ("无论", "regardless of"),
    ("不管", "regardless of"),
    ("尽管", "although / despite"),
    ("虽然", "although"),
    ("然而", "however"),
    ("但是", "but"),
    ("不过", "however"),
    ("一方面", "on one hand"),
    ("另一方面", "on the other hand"),
    ("总之", "in summary"),
    ("综上所述", "in summary / taken together"),
    ("另外", "in addition / additionally"),
    ("此外", "furthermore / moreover"),
    ("值得注意的是", "it is worth noting that"),
    ("特别注意的是", "of particular note is"),
    ("应强调", "it should be emphasized that"),
    ("应指出", "it should be pointed out that"),
    ("应予", "should be"),
    ("应", "should"),
    ("必须", "must"),
    ("需要", "require / need"),
    ("需", "requires / needs"),
    ("无需", "does not require"),
    ("有必要", "it is necessary to"),
    ("无必要", "unnecessary"),
    ("务必", "be sure to"),
    ("注意", "note / attention"),
    ("警惕", "be alert to / watch for"),
    ("密切观察", "closely monitor"),
    ("定期检查", "regular examination"),
    ("监测", "monitor"),
    ("定期监测", "regular monitoring"),
    ("随访", "follow-up"),
    ("复查", "re-examination"),
    ("评估", "assess / evaluate"),
    ("评价", "evaluate / assess"),
    ("判断", "judge / determine"),
    ("鉴别", "differentiate / distinguish"),
    ("鉴别诊断", "differential diagnosis"),
    ("区分", "distinguish"),
    ("排除", "exclude / rule out"),
    ("确诊", "definitive diagnosis"),
    ("拟诊", "presumptive diagnosis"),
    ("误诊", "misdiagnosis"),
    ("漏诊", "missed diagnosis"),
    ("筛查", "screening"),
    ("体检", "physical examination"),
    ("实验室检查", "laboratory test"),
    ("影像学检查", "imaging examination"),
    ("病理检查", "pathological examination"),
    ("生化检查", "biochemical test"),
    ("血常规", "complete blood count"),
    ("血药浓度监测", "therapeutic drug monitoring"),
    ("肝功能检查", "liver function test"),
    ("肾功能检查", "renal function test"),
    ("心电图", "electrocardiogram (ECG)"),
    ("脑电图", "electroencephalogram (EEG)"),
    ("MRI", "MRI"),
    ("CT", "CT"),
    ("PET", "PET"),
    ("SPECT", "SPECT"),
    ("超声", "ultrasound"),
    ("X线", "X-ray"),

    # Specific medical compounds/terms
    ("腺苷", "adenosine"),
    ("腺苷受体", "adenosine receptor"),
    ("A1受体", "A1 receptor"),
    ("A2A受体", "A2A receptor"),
    ("磷酸二酯酶", "phosphodiesterase (PDE)"),
    ("cAMP", "cAMP"),
    ("cGMP", "cGMP"),
    ("一氧化氮", "nitric oxide (NO)"),
    ("NO", "NO"),
    ("一氧化碳", "carbon monoxide (CO)"),
    ("血管紧张素", "angiotensin"),
    ("血管紧张素II", "angiotensin II"),
    ("肾素", "renin"),
    ("醛固酮", "aldosterone"),
    ("前列环素", "prostacyclin (PGI2)"),
    ("血栓素A2", "thromboxane A2 (TxA2)"),
    ("白三烯B4", "leukotriene B4 (LTB4)"),
    ("白三烯C4", "leukotriene C4 (LTC4)"),
    ("白三烯D4", "leukotriene D4 (LTD4)"),
    ("白三烯E4", "leukotriene E4 (LTE4)"),
    ("血小板活化因子", "platelet-activating factor (PAF)"),
    ("活性氧", "reactive oxygen species (ROS)"),
    ("超氧化物", "superoxide"),
    ("过氧化氢", "hydrogen peroxide"),
    ("羟自由基", "hydroxyl radical"),
    ("自由基", "free radical"),
    ("抗氧化剂", "antioxidant"),
    ("脂质过氧化", "lipid peroxidation"),
    ("DNA损伤", "DNA damage"),
    ("线粒体功能障碍", "mitochondrial dysfunction"),
    ("细胞凋亡", "apoptosis"),
    ("程序性死亡", "programmed cell death"),
    ("自噬", "autophagy"),
    ("坏死", "necrosis"),
    ("炎症反应", "inflammatory response"),
    ("免疫反应", "immune response"),
    ("免疫应答", "immune response"),
    ("自身免疫", "autoimmunity"),
    ("免疫抑制", "immunosuppression"),
    ("免疫调节", "immunomodulation"),
    ("免疫激活", "immune activation"),
    ("免疫功能", "immune function"),
    ("免疫缺陷", "immunodeficiency"),
    ("超敏反应", "hypersensitivity reaction"),
    ("特应性", "atopy / atopic"),
    ("过敏", "allergy / hypersensitivity"),
    ("过敏原", "allergen"),
    ("抗原", "antigen"),
    ("抗体", "antibody"),
    ("补体", "complement"),
    ("T细胞", "T cell"),
    ("B细胞", "B cell"),
    ("巨噬细胞", "macrophage"),
    ("树突状细胞", "dendritic cell"),
    ("单核细胞", "monocyte"),
    ("嗜酸性粒细胞", "eosinophil"),
    ("嗜碱性粒细胞", "basophil"),
    ("浆细胞", "plasma cell"),
    ("干细胞", "stem cell"),
    ("骨髓", "bone marrow"),
    ("造血系统", "hematopoietic system"),
    ("造血功能", "hematopoietic function"),
    ("红细胞", "red blood cell / erythrocyte"),
    ("白细胞", "white blood cell / leukocyte"),
    ("血红蛋白", "hemoglobin"),
    ("凝血因子", "coagulation factor"),
    ("凝血酶", "thrombin"),
    ("纤维蛋白", "fibrin"),
    ("纤维蛋白原", "fibrinogen"),
    ("纤溶酶", "plasmin"),
    ("纤溶系统", "fibrinolytic system"),
    ("血栓形成", "thrombosis"),
    ("栓塞", "embolism"),
    ("梗死", "infarction"),
    ("缺血", "ischemia"),
    ("缺氧", "hypoxia"),
    ("再灌注", "reperfusion"),
    ("缺血再灌注", "ischemia-reperfusion"),
    ("水肿", "edema"),
    ("充血", "hyperemia / congestion"),
    ("淤血", "congestion"),
    ("出血", "hemorrhage / bleeding"),
    ("渗血", "oozing"),
    ("渗出", "exudation"),
    ("漏出", "transudation"),
    ("脱水", "dehydration"),
    ("休克", "shock"),
    ("昏迷", "coma"),
    ("昏睡", "stupor"),
    ("嗜睡", "drowsiness / somnolence"),
    ("意识丧失", "loss of consciousness"),
    ("意识模糊", "confusion"),
    ("谵妄", "delirium"),
    ("幻觉", "hallucination"),
    ("妄想", "delusion"),
    ("错觉", "illusion"),
    ("兴奋", "excitation / stimulation"),
    ("躁动", "agitation"),
    ("激越", "agitation / restlessness"),
    ("静坐不能", "akathisia"),
    ("失眠", "insomnia"),
    ("睡眠障碍", "sleep disorder"),
    ("入睡困难", "difficulty falling asleep"),
    ("睡眠维持困难", "difficulty maintaining sleep"),
    ("早醒", "early morning awakening"),
    ("觉醒次数增多", "increased awakenings"),
    ("浅睡眠", "light sleep"),
    ("深睡眠", "deep sleep"),
    ("快速眼动睡眠", "REM sleep"),
    ("非快速眼动睡眠", "NREM sleep"),
    ("慢波睡眠", "slow-wave sleep"),
    ("睡眠结构", "sleep architecture"),
    ("睡眠质量", "sleep quality"),
    ("睡眠连续性", "sleep continuity"),
    ("昼夜节律紊乱", "circadian rhythm disorder"),
    ("时差", "jet lag"),
    ("轮班工作", "shift work"),
    ("镇静催眠", "sedative-hypnotic"),
    ("镇静催眠作用", "sedative-hypnotic effect"),
    ("镇静安眠", "sedative and hypnotic"),
    ("抗焦虑", "anxiolytic / anti-anxiety"),
    ("抗焦虑作用", "anxiolytic effect"),
    ("抗惊厥", "anticonvulsant"),
    ("抗癫痫", "antiepileptic"),
    ("肌肉松弛", "muscle relaxation"),
    ("中枢性肌肉松弛", "central muscle relaxation"),
    ("骨骼肌松弛", "skeletal muscle relaxation"),
    ("肌肉松弛作用", "muscle relaxant effect"),
    ("遗忘作用", "amnesic effect"),
    ("顺行性遗忘", "anterograde amnesia"),
    ("逆行性遗忘", "retrograde amnesia"),
    ("记忆缺失", "memory loss / amnesia"),
    ("遗忘", "amnesia / forgetfulness"),
    ("记忆力减退", "memory impairment"),
    ("认知功能下降", "cognitive decline"),
    ("智力减退", "intellectual impairment"),
    ("痴呆", "dementia"),
    ("轻度认知损害", "mild cognitive impairment (MCI)"),
    ("MCI", "MCI"),

    # Drug effects / pharmacological terms
    ("药理作用", "pharmacological effect"),
    ("药理效应", "pharmacological effect"),
    ("治疗作用", "therapeutic effect"),
    ("防治作用", "preventive and therapeutic effect"),
    ("疗效", "therapeutic efficacy"),
    ("临床疗效", "clinical efficacy"),
    ("临床效果", "clinical effect"),
    ("临床意义", "clinical significance"),
    ("临床用途", "clinical use"),
    ("临床用途", "clinical indication"),
    ("临床应用", "clinical application"),
    ("临床使用", "clinical use"),
    ("治疗应用", "therapeutic use"),
    ("主要用途", "primary use"),
    ("适应证", "indication"),
    ("适应证包括", "indications include"),
    ("适应症", "indication"),
    ("临床适应证", "clinical indication"),
    ("新的适应症", "new indication"),
    ("临床定位", "clinical positioning"),
    ("一线药物", "first-line drug"),
    ("选择药物", "drug of choice"),
    ("首选用药", "drug of first choice"),
    ("首选药物", "first-line drug / drug of choice"),
    ("备选药物", "alternative drug"),
    ("替代药物", "alternative drug"),
    ("替代用药", "alternative therapy"),
    ("替换药物", "substitute drug"),
    ("禁忌药物", "contraindicated drug"),
    ("禁用药物", "contraindicated drug"),
    ("慎用", "use with caution"),
    ("慎用于", "use with caution in"),
    ("密切关注", "closely monitor"),
    ("观察", "observe / monitor"),
    ("加强监测", "enhanced monitoring"),
    ("血药浓度", "plasma concentration"),
    ("血浆浓度", "plasma concentration"),
    ("血清浓度", "serum concentration"),
    ("组织浓度", "tissue concentration"),
    ("脑内浓度", "brain concentration"),
    ("脑脊液浓度", "CSF concentration"),
    ("稳态浓度", "steady-state concentration"),
    ("谷浓度", "trough concentration"),
    ("峰浓度", "peak concentration"),
    ("有效浓度", "effective concentration"),
    ("中毒浓度", "toxic concentration"),
    ("治疗窗", "therapeutic window"),
    ("狭窄治疗指数", "narrow therapeutic index"),
    ("个体差异", "individual variation"),
    ("个体差异大", "large individual variation"),
    ("个体差异明显", "marked individual variation"),
    ("生物利用度的个体差异", "individual variation in bioavailability"),
    ("种族差异", "ethnic differences"),
    ("性别差异", "gender differences"),
    ("年龄差异", "age-related differences"),
    ("日间差异", "diurnal variation"),
    ("遗传多态性", "genetic polymorphism"),
    ("基因多态性", "genetic polymorphism"),
    ("药物代谢酶多态性", "drug-metabolizing enzyme polymorphism"),
    ("代谢表型", "metabolic phenotype"),
    ("快代谢者", "rapid metabolizer"),
    ("慢代谢者", "poor metabolizer"),
    ("超快代谢者", "ultrarapid metabolizer"),
    ("中间代谢者", "intermediate metabolizer"),
    ("酶诱导", "enzyme induction"),
    ("酶抑制", "enzyme inhibition"),
    ("酶诱导剂", "enzyme inducer"),
    ("酶抑制剂", "enzyme inhibitor"),
    ("代谢抑制", "metabolic inhibition"),
    ("代谢增强", "enhanced metabolism"),
    ("代谢减慢", "slowed metabolism"),
    ("代谢加速", "accelerated metabolism"),
    ("减慢代谢", "slow metabolism"),
    ("加速代谢", "accelerate metabolism"),
    ("代谢途径", "metabolic pathway"),
    ("主要代谢途径", "primary metabolic pathway"),
    ("次要代谢途径", "minor metabolic pathway"),
    ("代谢产物", "metabolite"),
    ("活性代谢产物", "active metabolite"),
    ("无活性代谢产物", "inactive metabolite"),
    ("毒性代谢产物", "toxic metabolite"),
    ("初级代谢", "phase I metabolism"),
    ("次级代谢", "phase II metabolism"),
    ("I相代谢", "phase I metabolism"),
    ("II相代谢", "phase II metabolism"),
    ("葡萄糖醛酸化", "glucuronidation"),
    ("硫酸化", "sulfation"),
    ("乙酰化", "acetylation"),
    ("甲基化", "methylation"),
    ("谷胱甘肽结合", "glutathione conjugation"),
    ("氧化", "oxidation"),
    ("还原", "reduction"),
    ("水解", "hydrolysis"),
    ("羟化", "hydroxylation"),
    ("去甲基化", "demethylation"),
    ("脱氨基", "deamination"),
    ("脱羧基", "decarboxylation"),
    ("脱卤", "dehalogenation"),
    ("N-乙酰化", "N-acetylation"),
    ("蛋白结合", "protein binding"),
    ("血浆蛋白结合", "plasma protein binding"),
    ("白蛋白结合", "albumin binding"),
    ("α1-酸性糖蛋白", "alpha-1-acid glycoprotein"),
    ("游离药物浓度", "free drug concentration"),
    ("结合型药物", "bound drug"),
    ("游离型药物", "free drug"),
    ("蛋白结合率高", "high protein binding"),
    ("蛋白结合率低", "low protein binding"),
    ("高蛋白结合", "high protein binding"),
    ("低蛋白结合率", "low protein binding rate"),
    ("竞争性置换", "competitive displacement"),
    ("药物相互作用", "drug interaction"),
    ("药动学相互作用", "pharmacokinetic interaction"),
    ("药效学相互作用", "pharmacodynamic interaction"),
    ("协同作用", "synergistic effect / synergism"),
    ("拮抗作用", "antagonism"),
    ("相加作用", "additive effect"),
    ("增强作用", "potentiation"),
    ("减弱作用", "attenuation"),
    ("协同效应", "synergistic effect"),
    ("毒性增强", "enhanced toxicity"),
    ("交叉耐药", "cross-tolerance"),
    ("交叉过敏", "cross-allergy / cross-sensitivity"),
    ("交叉反应", "cross-reactivity"),
    ("不良反应", "adverse effect"),
    ("副作用", "side effect"),
    ("毒性反应", "toxic reaction"),
    ("过敏反应", "allergic reaction"),
    ("变态反应", "allergic reaction"),
    ("特异质反应", "idiosyncratic reaction"),
    ("后遗效应", "after-effect / residual effect"),
    ("撤药反应", "withdrawal reaction"),
    ("反跳现象", "rebound phenomenon"),
    ("反跳", "rebound"),
    ("停药反应", "withdrawal reaction"),
    ("停药综合征", "withdrawal syndrome"),
    ("戒断症状", "withdrawal symptoms"),
    ("药物依赖", "drug dependence"),
    ("药物成瘾", "drug addiction"),
    ("成瘾", "addiction"),
    ("精神依赖", "psychological dependence"),
    ("躯体依赖", "physical dependence"),
    ("药物滥用", "drug abuse"),
    ("滥用", "abuse"),
    ("滥用潜力", "abuse potential"),
    ("滥用的可能性", "abuse liability"),
    ("脱毒", "detoxification"),
    ("康复", "rehabilitation"),
    ("防复发", "relapse prevention"),
    ("复发", "relapse / recurrence"),
    ("重回社会", "social reintegration"),
    ("回归社会", "social reintegration"),
    ("社会功能", "social functioning"),
    ("生活质量", "quality of life"),
    ("生命质量", "quality of life"),
    ("存活率", "survival rate"),
    ("生存率", "survival rate"),
    ("无进展生存", "progression-free survival"),
    ("总生存期", "overall survival"),
    ("缓解率", "remission rate"),
    ("有效率", "response rate"),
    ("总有效率", "overall response rate"),
    ("治愈率", "cure rate"),
    ("复发率", "relapse rate"),
    ("依从性", "compliance / adherence"),
    ("患者依从性", "patient compliance"),
    ("遵医嘱", "follow medical advice"),
    ("不遵医嘱", "non-compliance"),

    # Additional specific pharmacological patterns
    ("原发作用", "primary effect"),
    ("继发作用", "secondary effect"),
    ("直接作用", "direct effect"),
    ("间接作用", "indirect effect"),
    ("局部作用", "local effect"),
    ("全身作用", "systemic effect"),
    ("选择性作用", "selective effect"),
    ("非选择性的", "nonselective"),
    ("作用机制", "mechanism of action"),
    ("作用方式", "mode of action"),
    ("作用靶点", "target of action"),
    ("作用靶标", "target"),
    ("作用位点", "site of action"),
    ("结合位点", "binding site"),
    ("活性位点", "active site"),
    ("别构位点", "allosteric site"),
    ("别构调节", "allosteric modulation"),
    ("正性别构调节", "positive allosteric modulation"),
    ("负性别构调节", "negative allosteric modulation"),
    ("受体结合", "receptor binding"),
    ("受体亲和力", "receptor affinity"),
    ("受体选择性", "receptor selectivity"),
    ("受体特异性", "receptor specificity"),
    ("受体密度", "receptor density"),
    ("受体上调", "receptor upregulation"),
    ("受体下调", "receptor downregulation"),
    ("受体脱敏", "receptor desensitization"),
    ("受体内化", "receptor internalization"),
    ("跨膜信号转导", "transmembrane signal transduction"),
    ("信号转导通路", "signal transduction pathway"),
    ("第二信使", "second messenger"),
    ("胞内信号", "intracellular signal"),
    ("磷酸化", "phosphorylation"),
    ("去磷酸化", "dephosphorylation"),
    ("激酶", "kinase"),
    ("磷酸酶", "phosphatase"),
    ("转录因子", "transcription factor"),
    ("基因表达", "gene expression"),
    ("基因转录", "gene transcription"),
    ("蛋白质合成", "protein synthesis"),
    ("上调", "upregulate"),
    ("下调", "downregulate"),
    ("表达增加", "increased expression"),
    ("表达减少", "decreased expression"),
    ("高表达", "high expression / overexpression"),
    ("低表达", "low expression"),
    ("缺血缺氧", "ischemia and hypoxia"),
    ("能量代谢", "energy metabolism"),
    ("ATP", "ATP"),
    ("线粒体", "mitochondria"),
    ("内质网", "endoplasmic reticulum"),
    ("高尔基体", "Golgi apparatus"),
    ("溶酶体", "lysosome"),
    ("蛋白酶体", "proteasome"),
    ("核糖体", "ribosome"),
    ("细胞膜", "cell membrane"),
    ("细胞质", "cytoplasm"),
    ("细胞核", "nucleus"),
    ("核膜", "nuclear membrane"),
    ("染色质", "chromatin"),
    ("染色体", "chromosome"),
    ("端粒", "telomere"),
    ("端粒酶", "telomerase"),
    ("表观遗传", "epigenetic"),
    ("DNA甲基化", "DNA methylation"),
    ("组蛋白修饰", "histone modification"),
    ("组蛋白乙酰化", "histone acetylation"),
    ("组蛋白去乙酰化", "histone deacetylation"),
    ("组蛋白去乙酰化酶", "histone deacetylase (HDAC)"),
    ("微小RNA", "microRNA"),
    ("非编码RNA", "non-coding RNA"),
    ("长链非编码RNA", "long non-coding RNA"),
    ("RNA干扰", "RNA interference"),
    ("siRNA", "siRNA"),
    ("基因治疗", "gene therapy"),
    ("基因编辑", "gene editing"),
    ("CRISPR", "CRISPR"),
    ("干细胞治疗", "stem cell therapy"),
    ("精准医疗", "precision medicine"),
    ("个体化治疗", "personalized treatment"),
    ("个性化给药", "personalized dosing"),
    ("联合用药", "combination therapy"),
    ("联合治疗", "combination therapy"),
    ("联合使用", "combined use"),
    ("单药治疗", "monotherapy"),
    ("双药治疗", "dual therapy"),
    ("三联治疗", "triple therapy"),
    ("联合化疗", "combination chemotherapy"),
    ("辅助治疗", "adjuvant therapy"),
    ("新辅助治疗", "neoadjuvant therapy"),
    ("巩固治疗", "consolidation therapy"),
    ("维持治疗", "maintenance therapy"),
    ("解救治疗", "rescue therapy"),
    ("姑息治疗", "palliative treatment"),
    ("支持治疗", "supportive care"),
    ("对症治疗", "symptomatic treatment"),
    ("对因治疗", "etiological treatment"),
    ("病因治疗", "causal treatment"),
    ("根治", "radical cure"),
    ("治愈", "cure"),
    ("可治愈", "curable"),
    ("不能治愈", "incurable"),
    ("缓解", "remission / relief"),
    ("部分缓解", "partial remission"),
    ("完全缓解", "complete remission"),
    ("临床治愈", "clinical cure"),
    ("功能治愈", "functional cure"),
    ("彻底治愈", "complete cure"),
    ("复发率", "recurrence rate"),
    ("无病生存期", "disease-free survival"),
    ("无事件生存期", "event-free survival"),
    ("无复发生存期", "relapse-free survival"),
    ("五年生存率", "5-year survival rate"),
    ("预后不良", "poor prognosis"),
    ("预后良好", "good prognosis"),
    ("预后", "prognosis"),
    ("结局", "outcome"),
    ("转归", "outcome / prognosis"),
    ("恶化", "deterioration / worsening"),
    ("好转", "improvement"),
    ("稳定", "stable / stabilization"),
    ("进展", "progression"),
    ("缓解期", "remission period"),
    ("稳定期", "stable phase"),
    ("活动期", "active phase"),
    ("急性期", "acute phase"),
    ("慢性期", "chronic phase"),
    ("发作期", "attack / episode"),
    ("间歇期", "intermittent period"),
    ("发作频率", "seizure frequency / attack frequency"),
    ("发作次数", "number of episodes"),
    ("控制发作", "seizure control"),
    ("减少发作", "reduce seizures"),
    ("预防发作", "prevent seizures"),
    ("无发作", "seizure-free"),
    ("耐药", "drug resistance / refractory"),
    ("耐药性", "drug resistance"),
    ("多药耐药", "multidrug resistance"),
    ("交叉耐药", "cross-resistance"),
    ("先天耐药", "intrinsic resistance"),
    ("获得性耐药", "acquired resistance"),
    ("P-糖蛋白", "P-glycoprotein (P-gp)"),
    ("P-gp", "P-gp"),
    ("多药耐药相关蛋白", "multidrug resistance-associated protein (MRP)"),
    ("BCRP", "BCRP"),
    ("外排转运体", "efflux transporter"),
    ("摄取转运体", "uptake transporter"),
    ("转运蛋白", "transporter protein"),
    ("载体蛋白", "carrier protein"),
    ("主动转运", "active transport"),
    ("被动转运", "passive transport"),
    ("易化扩散", "facilitated diffusion"),
    ("胞饮", "pinocytosis"),
    ("胞吞", "endocytosis"),
    ("胞吐", "exocytosis"),

    # Additional words for end-of-sentence patterns
    ("。", ". "),
    ("，", ", "),
    ("、", ", "),
    ("；", "; "),
    ("：", ": "),
    ("？", "? "),
    ("！", "! "),

    # Final catch-all single characters and common terms
    ("是", "is"),
    ("为", "is / as"),
    ("即", "namely / i.e."),
    ("如", "such as"),
    ("以", "by / with / to"),
    ("对", "to / for / against"),
    ("于", "in / at / to"),
    ("在", "in / at / on"),
    ("用", "with / using"),
    ("被", "by"),
    ("由", "by / from"),
    ("从", "from"),
    ("到", "to"),
    ("向", "toward"),
    ("使", "make / cause"),
    ("让", "let / allow"),
    ("把", "把"),
    ("将", "将 / will"),
    ("会", "will / can"),
    ("能", "can / able to"),
    ("可", "can / may"),
    ("不可", "cannot"),
    ("不再", "no longer"),
    ("并不", "does not / is not"),
    ("并非", "is not / does not"),
    ("无", "no / without"),
    ("不", "not"),
    ("未", "not yet / un-"),
    ("已", "already / have"),
    ("了", "already"),  # often indicates completion
    ("过", "have done / excessive"),
    ("着", "in progress of"),
    ("地", "-ly"),  # adverbial marker
    ("个", "個"),
    ("种", "kind / type"),
    ("类", "class / category"),
    ("种类型", "type"),
    ("一类", "a class of"),
    ("两大类", "two major classes"),
    ("各种", "various"),
    ("多种", "multiple / various"),
    ("数种", "several"),
    ("等", "etc."),
    ("等等", "etc."),
    ("之一", "one of"),
    ("两者之间", "between the two"),
    ("二者", "the two / both"),
    ("三者", "the three"),
    ("分别为", "respectively / are"),
    ("各", "each / respective"),
    ("每", "each / per"),
    ("有的", "some"),
    ("有些", "some"),
    ("另有一些", "some others"),
    ("还有一些", "still others"),
    ("相当于", "equivalent to / corresponds to"),
    ("约", "approximately / about"),
    ("大约", "approximately"),
    ("左右", "approximately / about"),
    ("左右", "or so"),
    ("几乎", "almost / nearly"),
    ("超过", "exceeds / more than"),
    ("不到", "less than"),
    ("低于", "below / less than"),
    ("高于", "above / higher than"),
    ("等于", "equal to"),
    ("不小于", "not less than"),
    ("不大于", "not more than"),
    ("至少", "at least"),
    ("至多", "at most"),
    ("多达", "as much as / up to"),
    ("可达", "can reach"),
    ("不可超过", "should not exceed"),
    ("不超过", "no more than / not exceeding"),
    ("范围", "range"),
    ("范围内", "within the range"),
    ("范围在", "ranges from"),
    ("介于", "between"),
    ("之间", "between / among"),

    # === CRITICAL MISSING COMMON TERMS ===
    ("药物", "drug"),
    ("受体", "receptor"),
    ("结合", "binding"),
    ("阻断", "blockade"),
    ("对抗", "counteraction"),
    ("代表", "representative"),
    ("患者", "patient"),
    ("区别", "difference"),
    ("影响", "affect"),
    ("功能", "function"),
    ("效果", "efficacy"),
    ("活性", "activity"),
    ("递质", "transmitter"),
    ("浓度", "concentration"),
    ("异构体", "isomer"),
    ("结构", "structure"),
    ("亚基", "subunit"),
    ("亲和力", "affinity"),
    ("复合体", "complex"),
    ("催", "catalyze"),
    ("酶", "enzyme"),
    ("工酶", "isoenzyme"),
    ("同工酶", "isoenzyme"),
    ("表达", "expression"),
    ("途径", "pathway"),
    ("通路", "pathway"),
    ("状态", "state"),
    ("因素", "factor"),
    ("张力", "tone"),
    ("血流", "blood flow"),
    ("存活", "survival"),
    ("周期", "cycle"),
    ("生理", "physiological"),
    ("病理", "pathological"),
    ("发", "onset/episode"),
    ("发作", "seizure/episode"),
    ("全身", "generalized"),
    ("局部", "local/focal"),
    ("周围", "surrounding"),
    ("正常", "normal"),
    ("异常", "abnormal"),
    ("系统", "system"),
    ("疾病的", "of the disease"),
    ("常见的", "common"),
    ("重要", "important"),
    ("常见的", "common"),
    ("新的", "new"),
    ("同一", "same"),
    ("其他", "other"),
    ("这种", "this"),
    ("那种", "that"),
    ("一些", "some"),
    ("不同", "different"),
    ("各种", "various"),
    ("多种", "multiple"),
    ("最大", "maximum"),
    ("最小", "minimum"),
    ("最佳", "optimal"),
    ("最适", "optimal"),

    # === FINAL BATCH: terms still visible in output ===
    ("家族", "family"),
    ("介导", "mediate"),
    ("氨基酸", "amino acid"),
    ("序列", "sequence"),
    ("同源", "homologous"),
    ("已知", "known"),
    ("阿片样肽", "opioid peptide"),
    ("欣快感", "euphoria"),
    ("欣快", "euphoria"),
    ("缩瞳", "miosis"),
    ("瞳孔", "pupil"),
    ("固有", "constitutive"),
    ("内皮", "endothelium"),
    ("丰富", "abundant"),
    ("血流量", "blood flow"),
    ("诱导", "inducible"),
    ("生长因子", "growth factor"),
    ("因子", "factor"),
    ("进行", "undergo"),
    ("催化", "catalytic"),
    ("亚单位", "subunit"),
    ("修饰", "modification"),
    ("不可逆", "irreversible"),
    ("位点", "site"),
    ("属于", "belongs to"),
    ("确认", "confirmed"),
    ("分类", "classification"),
    ("分为", "divided into"),
    ("三类", "three types"),
    ("五类", "five classes"),
    ("六类", "six classes"),
    ("亚型", "subtype"),
    ("密切相关", "closely related"),
    ("常用于", "is commonly used for"),
    ("通过", "through"),
    ("作用于", "acts on"),
    ("存在于", "present in"),
    ("分布于", "distributed in"),
    ("激动", "agonize / activate"),
    ("拮抗药", "antagonist"),
    ("激动药", "agonist"),
    ("阻断药", "blocker"),
    ("抑制药", "inhibitor"),
    ("促进", "promote"),
    ("使用", "use"),
    ("利用", "utilize"),
    ("方法", "method"),
    ("方式", "mode"),
    ("剂量", "dose"),
    ("效应", "effect"),
    ("药效", "drug efficacy"),
    ("药理", "pharmacological"),
    ("毒理", "toxicological"),
    ("临床", "clinical"),
    ("实验", "experimental"),
    ("试验", "trial"),
    ("观察", "observation"),
    ("研究", "study"),
    ("发现", "found"),
    ("报道", "reported"),
    ("认为", "considered"),
    ("推测", "speculated"),
    ("假设", "hypothesis"),
    ("结论", "conclusion"),
    ("结果", "result"),
    ("数据", "data"),
    ("分析", "analysis"),
    ("比较", "comparison"),
    ("综合", "comprehensive"),
    ("总结", "summary"),
    ("推荐", "recommendation"),
    ("方案", "regimen"),
    ("策略", "strategy"),
    ("措施", "measure"),
    ("处理", "management"),
    ("干预", "intervention"),
    ("手术", "surgery"),
    ("术前", "preoperative"),
    ("术后", "postoperative"),
    ("术中", "intraoperative"),
    ("住院", "hospitalization"),
    ("门诊", "outpatient"),
    ("急诊", "emergency"),
    ("重症", "critical / ICU"),
    ("监护", "monitoring"),
    ("病房", "ward"),
    ("社区", "community"),
    ("家庭", "family / home"),
    ("个体", "individual"),
    ("群体", "population"),
    ("人群", "population"),
    ("健康", "health"),
    ("疾病", "disease"),
    ("症状", "symptom"),
    ("体征", "sign"),
    ("综合征", "syndrome"),
    ("并发症", "complication"),
    ("后遗症", "sequela"),
    ("禁忌", "contraindication"),
    ("适应", "indication"),
    ("不良反应", "adverse reaction"),
    ("相互作用", "interaction"),
    ("叠加", "superposition / additive"),
    ("拮抗", "antagonize"),
    ("协同", "synergistic"),
    ("配伍", "compatibility"),
    ("禁忌", "contraindicated"),
    ("慎用", "use with caution"),
    ("禁用", "contraindicated"),
    ("适用", "applicable / indicated"),
    ("可用", "usable"),
    ("不宜", "not appropriate"),
    ("应该", "should"),
    ("必须", "must"),
    ("可以", "may"),
    ("不能", "cannot"),
    ("不应", "should not"),
    ("不可", "must not"),
    ("因人而异", "varies by individual"),
    ("尚不明确", "remains unclear"),
    ("有待研究", "requires further study"),
    ("尚无定论", "remains inconclusive"),
    ("尚需验证", "requires verification"),
    ("证据不足", "insufficient evidence"),
    ("证据充分", "sufficient evidence"),
    ("高度推荐", "highly recommended"),
    ("不推荐", "not recommended"),
    ("有争议", "controversial"),
    ("慎重考虑", "careful consideration"),
    ("个体化", "individualized"),
    ("标准化", "standardized"),
    ("规范化", "normalized"),
    ("多学科", "multidisciplinary"),
    ("综合治疗", "comprehensive treatment"),
    ("个体化治疗", "personalized treatment"),
    ("精准治疗", "precision treatment"),
    ("靶向治疗", "targeted therapy"),
    ("免疫治疗", "immunotherapy"),
    ("基因治疗", "gene therapy"),
    ("细胞治疗", "cell therapy"),
    ("放射治疗", "radiotherapy"),
    ("化学治疗", "chemotherapy"),
    ("药物治疗", "pharmacotherapy"),
    ("物理治疗", "physical therapy"),
    ("心理治疗", "psychotherapy"),
    ("行为治疗", "behavioral therapy"),
    ("认知治疗", "cognitive therapy"),
    ("康复治疗", "rehabilitation therapy"),
    ("运动治疗", "exercise therapy"),
    ("营养治疗", "nutritional therapy"),
    ("饮食治疗", "dietary therapy"),

    # Ensure drug classification terms
    ("镇静催眠药", "sedative-hypnotic"),
    ("抗癫痫药", "antiepileptic drug"),
    ("抗精神病药", "antipsychotic"),
    ("抗抑郁药", "antidepressant"),
    ("抗躁狂药", "antimanic drug"),
    ("心境稳定剂", "mood stabilizer"),
    ("抗焦虑药", "anxiolytic"),
    ("解热镇痛抗炎药", "NSAID"),
    ("非甾体类抗炎药", "NSAID"),
    ("抗痛风药", "antigout drug"),
    ("促觉醒药", "wakefulness-promoting drug"),
    ("抗惊厥药", "anticonvulsant drug"),
    ("阿片类镇痛药", "opioid analgesic"),
    ("非阿片类镇痛药", "non-opioid analgesic"),
    ("局部麻醉药", "local anesthetic"),
    ("全身麻醉药", "general anesthetic"),
    ("肌松药", "muscle relaxant"),
    ("拟胆碱药", "cholinomimetic / cholinergic agonist"),
    ("抗胆碱药", "anticholinergic"),
    ("拟肾上腺素药", "adrenergic agonist"),
    ("抗肾上腺素药", "adrenergic antagonist"),
    ("组胺受体阻断药", "histamine receptor antagonist"),
    ("H1受体阻断药", "H1 receptor antagonist"),
    ("H2受体阻断药", "H2 receptor antagonist"),
    ("钙通道阻滞药", "calcium channel blocker"),
    ("钾通道开放药", "potassium channel opener"),
    ("钠通道阻滞药", "sodium channel blocker"),
    ("利尿药", "diuretic"),
    ("脱水药", "osmotic diuretic"),
    ("降压药", "antihypertensive"),
    ("抗心律失常药", "antiarrhythmic drug"),
    ("抗心绞痛药", "antianginal drug"),
    ("调血脂药", "lipid-lowering drug"),
    ("抗凝血药", "anticoagulant"),
    ("抗血小板药", "antiplatelet drug"),
    ("溶栓药", "thrombolytic drug"),
    ("促凝血药", "procoagulant / hemostatic"),
    ("抗贫血药", "antianemic drug"),
    ("平喘药", "antiasthmatic drug"),
    ("镇咳药", "antitussive"),
    ("祛痰药", "expectorant"),
    ("抗消化性溃疡药", "anti-ulcer drug"),
    ("止吐药", "antiemetic"),
    ("促动力药", "prokinetic agent"),
    ("泻药", "laxative"),
    ("止泻药", "antidiarrheal"),
    ("降血糖药", "hypoglycemic drug / antidiabetic"),
    ("胰岛素", "insulin"),
    ("糖皮质激素", "glucocorticoid"),
    ("盐皮质激素", "mineralocorticoid"),
    ("性激素", "sex hormone"),
    ("抗生素", "antibiotic"),
    ("抗菌药", "antibacterial drug"),
    ("抗真菌药", "antifungal drug"),
    ("抗病毒药", "antiviral drug"),
    ("抗寄生虫药", "antiparasitic drug"),
    ("抗肿瘤药", "antineoplastic / anticancer drug"),
    ("免疫抑制药", "immunosuppressant"),
    ("免疫增强药", "immunostimulant"),
    ("抗过敏药", "antiallergic drug"),
]

# ============================================================
# SECTION 4: FIXED EXPRESSION REPLACEMENTS (whole phrase patterns)
# These are applied after the term-by-term replacements to clean up common patterns
# ============================================================
FIXED_PATTERNS = [
    # Fix "increase increase" -> "increase" (deduplication)
    # These are handled by the term-by-term approach
]

# Sort medical terms by length (longest first) to prioritize longer matches
MEDICAL_TERMS.sort(key=lambda x: len(x[0]), reverse=True)


def translate_text(text, is_option_field=False):
    """
    Translate a Chinese medical text to English using comprehensive term replacement.
    """
    if not text or not isinstance(text, str):
        return text

    result = text

    # Phase 1: Apply the medical term dictionary (longest matches first)
    for cn_term, en_term in MEDICAL_TERMS:
        if cn_term in result:
            result = result.replace(cn_term, en_term)

    # Phase 2: Apply drug name translations
    for cn_drug, en_drug in DRUG_NAMES.items():
        if cn_drug in result:
            result = result.replace(cn_drug, en_drug)

    # Phase 3: Clean up whitespace
    result = re.sub(r'\s+', ' ', result).strip()

    # Phase 3.5: Post-processing cleanup - fix remaining Chinese artifacts
    # Remove orphan Chinese possessive/adverbial particles
    result = result.replace('的', '')
    result = result.replace('地', '')
    result = result.replace('得', '')
    # Fix split compound: "作"+"用"→"作with / using" error
    result = result.replace('作with / using', 'effect')
    result = result.replace('作 ', 'effect ')
    result = result.replace('作用', 'effect')
    result = result.replace('effecteffect', 'effect')
    # Fix common remaining single-character artifacts
    result = result.replace('了', '')
    result = result.replace('着', '')
    result = result.replace('过', '')
    result = result.replace('等', '')
    result = result.replace('即', 'i.e.')
    result = result.replace('如', 'such as')
    result = result.replace('或', 'or')
    result = result.replace('和', 'and')
    result = result.replace('与', 'and')
    result = result.replace('及', 'and')
    result = result.replace('而', 'and')
    result = result.replace('但', 'but')
    result = result.replace('均', 'all')
    result = result.replace('约', 'approximately')
    result = result.replace('较', 'relatively')
    result = result.replace('很', 'very')
    result = result.replace('更', 'more')
    result = result.replace('可', 'can')
    result = result.replace('应', 'should')
    result = result.replace('需', 'requires')
    result = result.replace('无', 'no')
    result = result.replace('不', 'not')
    result = result.replace('已', 'already')
    result = result.replace('未', 'not')
    result = result.replace('将', 'will')
    result = result.replace('被', 'is')
    result = result.replace('由', 'by')
    result = result.replace('从', 'from')
    result = result.replace('对', 'on')
    result = result.replace('于', 'in')
    result = result.replace('为', 'is')
    result = result.replace('有', 'has')
    result = result.replace('能', 'can')
    result = result.replace('会', 'can')
    result = result.replace('并', 'and')
    result = result.replace('则', 'then')
    result = result.replace('其', 'its')
    result = result.replace('该', 'the')
    result = result.replace('此', 'this')
    result = result.replace('各', 'each')
    result = result.replace('每', 'per')
    result = result.replace('两', 'two')
    result = result.replace('三', 'three')
    result = result.replace('种', 'types of')
    result = result.replace('类', 'class')
    result = result.replace('型', 'type')
    result = result.replace('性', '')
    result = result.replace('者', '')
    result = result.replace('化', 'ization')
    result = result.replace('上', 'above')
    result = result.replace('下', 'below')
    result = result.replace('中', 'in')
    result = result.replace('内', 'within')
    result = result.replace('外', 'outside')
    result = result.replace('前', 'before')
    result = result.replace('后', 'after')
    result = result.replace('时', 'when')
    result = result.replace('间', 'between')
    result = result.replace('所', 'which')
    # Fix over-translated patterns (aggressive, handles concatenated text)
    for pattern, replacement in [
        (r'to / for / against', 'to'),
        (r'in / at / on', 'in'),
        (r'in / at / to', 'in'),
        (r'via / through', 'via'),
        (r'and / with', 'and'),
        (r'is / as', 'is'),
        (r'with / using', 'with'),
        (r'by / with / to', 'by'),
        (r'can / may', 'can'),
        (r'can / able to', 'can'),
        (r'mainly / primarily', 'primarily'),
        (r'most / majority', 'most'),
        (r'different / various', 'different'),
        (r'novel / new', 'novel'),
        (r'generate / produce', 'produce'),
        (r'besides / in addition to', 'in addition to'),
        (r'due to / because of', 'due to'),
        (r'compliance / adherence', 'compliance'),
        (r'diagnose / diagnosis', 'diagnosis'),
        (r'treat / treatment', 'treatment'),
        (r'relapse / recurrence', 'relapse'),
        (r'drowsiness / somnolence', 'drowsiness'),
        (r'prevent / prophylaxis', 'prevent'),
        (r'assess / evaluate', 'assess'),
        (r'excitation / stimulation', 'stimulation'),
        (r'remission / relief', 'remission'),
        (r'antagonist / blocker', 'antagonist'),
        (r'correct / proper', 'correct'),
        (r'characteristic / feature', 'characteristic'),
        (r'class / category', 'class'),
        (r'kind / type', 'type'),
        (r'related / associated', 'associated'),
        (r'currently / at present', 'currently'),
        (r'no / without', 'no'),
        (r'already / have', 'have'),
        (r'show / demonstrate', 'show'),
        (r'significant / marked', 'significant'),
        (r'its / their', 'its'),
        (r'few / less', 'few'),
        (r'convert / transform', 'convert'),
        (r'generate / produce', 'produce'),
        (r'agitation / restlessness', 'agitation'),
        (r'onset / episode', 'onset'),
    ]:
        result = re.sub(pattern, replacement, result)
    # More aggressive cleanup: remove multi-word alternatives leftover
    result = re.sub(r'\b(increase|decrease|reduce|inhibit|block|activate|enhance|promote|prevent|treat|use|effect|action|dose|drug|receptor|bind|release|metabolize|excrete|absorb|cause|induce|lead|produce|exert|improve|elevate|attenuate|prolong|shorten|maintain|protect|damage|regulate|modulate|monitor|assess|evaluate)s? / [a-z ]+\b', r'\1', result)
    # Fix common remaining Chinese character artifacts
    result = result.replace('具has', 'has')
    result = result.replace('作is', 'is')
    result = result.replace('非not', 'not')
    result = result.replace('原发primary', 'primary')
    result = result.replace('继发secondary', 'secondary')
    result = result.replace('当before', 'currently')
    result = result.replace('近', 'nearly')
    result = result.replace('首', 'first')
    result = result.replace('個', '')
    result = result.replace('來', '')
    result = result.replace('異', '異')
    result = result.replace('既', 'both')
    result = result.replace('也', 'also')
    result = result.replace('还', 'also')
    result = result.replace('尤', 'especially')
    result = result.replace('仍', 'still')
    result = result.replace('仅', 'only')
    result = result.replace('最', 'most')
    result = result.replace('非常', 'very')
    result = result.replace('几乎', 'almost')
    result = result.replace('本', 'this')
    result = result.replace('另', 'another')
    result = result.replace('某', 'a')
    result = result.replace('每', 'each')
    result = result.replace('所有', 'all')
    result = result.replace('整个', 'the entire')
    result = result.replace('数', 'several')
    result = result.replace('多', 'many')
    result = result.replace('少', 'few')
    result = result.replace('高', 'high')
    result = result.replace('低', 'low')
    result = result.replace('强', 'strong')
    result = result.replace('弱', 'weak')
    result = result.replace('大', 'large')
    result = result.replace('小', 'small')
    result = result.replace('快', 'fast')
    result = result.replace('慢', 'slow')
    result = result.replace('长', 'long')
    result = result.replace('短', 'short')
    result = result.replace('新', 'new')
    result = result.replace('旧', 'old')
    result = result.replace('好', 'good')
    result = result.replace('坏', 'bad')
    result = result.replace('第一', 'first')
    result = result.replace('第二', 'second')
    result = result.replace('第三', 'third')
    result = result.replace('第四', 'fourth')
    result = result.replace('第五', 'fifth')
    result = result.replace('之一', 'one of')
    result = result.replace('之间', 'between')
    result = result.replace('之后', 'after')
    result = result.replace('之前', 'before')
    result = result.replace('以内', 'within')
    result = result.replace('以上', 'above')
    result = result.replace('以下', 'below')
    result = result.replace('相比', 'compared with')
    result = result.replace('相同', 'same')
    result = result.replace('不同', 'different')
    result = result.replace('相同', 'identical')
    result = result.replace('明显', 'significantly')
    result = result.replace('轻度', 'mild')
    result = result.replace('重度', 'severe')
    result = result.replace('急性', 'acute')
    result = result.replace('慢性', 'chronic')
    result = result.replace('原发性', 'primary')
    result = result.replace('继发性', 'secondary')
    result = result.replace('先天性', 'congenital')
    result = result.replace('获得性', 'acquired')
    result = result.replace('特发性', 'idiopathic')
    result = result.replace('医源性', 'iatrogenic')
    result = result.replace('生理', 'physiological')
    result = result.replace('病理', 'pathological')
    result = result.replace('心理', 'psychological')
    result = result.replace('精神', 'mental')
    result = result.replace('神经', 'neural')
    result = result.replace('肌肉', 'muscle')
    result = result.replace('骨骼', 'skeletal')
    result = result.replace('皮肤', 'skin')
    result = result.replace('黏膜', 'mucosa')
    result = result.replace('平滑肌', 'smooth muscle')
    result = result.replace('心肌', 'myocardium')
    result = result.replace('血管', 'vascular')
    result = result.replace('血液', 'blood')
    result = result.replace('呼吸', 'respiratory')
    result = result.replace('消化', 'digestive')
    result = result.replace('泌尿', 'urinary')
    result = result.replace('生殖', 'reproductive')
    result = result.replace('内分泌', 'endocrine')
    result = result.replace('代谢', 'metabolic')
    result = result.replace('免疫', 'immune')
    result = result.replace('遗传', 'genetic')
    result = result.replace('感染', 'infection')
    result = result.replace('炎症', 'inflammation')
    result = result.replace('肿瘤', 'tumor')
    result = result.replace('癌症', 'cancer')
    result = result.replace('安静', 'calmness')
    result = result.replace('记忆', 'memory')
    result = result.replace('学习', 'learning')
    result = result.replace('认知', 'cognitive')
    result = result.replace('行为', 'behavior')
    result = result.replace('情绪', 'mood')
    result = result.replace('情感', 'emotion')
    result = result.replace('思维', 'thought')
    result = result.replace('意识', 'consciousness')
    result = result.replace('注意力', 'attention')
    result = result.replace('精神运动', 'psychomotor')
    result = result.replace('效should', 'effect')
    result = result.replace('亦', 'also')
    result = result.replace('勿', 'do not')
    result = result.replace('宜', 'should')
    result = result.replace('不宜', 'should not')
    result = result.replace('宜', 'appropriate to')
    result = result.replace('易', 'easily')
    result = result.replace('难', 'difficult')
    result = result.replace('同', 'same')
    result = result.replace('异', 'different')
    result = result.replace('常', 'often')
    result = result.replace('尚', 'still')
    result = result.replace('确', 'definitive')
    result = result.replace('切', 'definitive')
    result = result.replace('实', 'true')
    result = result.replace('假', 'false')
    result = result.replace('全', 'complete')
    result = result.replace('部分', 'partial')
    result = result.replace('全部', 'all')
    result = result.replace('有的', 'some')
    result = result.replace('有些', 'some')
    result = result.replace('大多数', 'most')
    result = result.replace('绝大多数', 'the vast majority')
    result = result.replace('少数', 'a small number')
    result = result.replace('多数', 'most')
    result = result.replace('大量', 'abundant')
    result = result.replace('微量', 'trace amounts of')
    result = result.replace('足以', 'sufficient to')
    result = result.replace('不足以', 'insufficient to')
    result = result.replace('联合', 'combined')
    result = result.replace('单独', 'alone / single')
    result = result.replace('合用', 'co-administration')
    result = result.replace('单用', 'monotherapy')
    result = result.replace('并用', 'combination use')
    result = result.replace('联用', 'combined use')
    result = result.replace('同时使用', 'simultaneous use')
    result = result.replace('交替使用', 'alternating use')
    result = result.replace('连续使用', 'continuous use')
    result = result.replace('间断使用', 'intermittent use')
    result = result.replace('分次给药', 'divided doses')
    result = result.replace('顿服', 'single dose')
    result = result.replace('分服', 'divided administration')
    result = result.replace('空腹', 'on an empty stomach')
    result = result.replace('饭后', 'after meals')
    result = result.replace('饭前', 'before meals')
    result = result.replace('随餐', 'with food')
    result = result.replace('静脉推注', 'IV bolus')
    result = result.replace('静脉滴注', 'IV infusion')
    result = result.replace('肌内注射', 'IM injection')
    result = result.replace('皮下注射', 'SC injection')
    # Fix remaining "already / have" pattern
    result = re.sub(r'\balready / have\b', 'have', result)
    # Fix double replacements
    result = result.replace('effecteffect', 'effect')
    result = result.replace('inin', 'in')
    result = result.replace('onon', 'on')
    result = result.replace('viavia', 'via')
    result = result.replace('andand', 'and')
    result = result.replace('byby', 'by')
    result = result.replace('withwith', 'with')
    result = result.replace('cancan', 'can')
    result = result.replace('notnot', 'not')
    result = result.replace('thethe', 'the')
    result = result.replace('this this', 'this')
    result = result.replace('has has', 'has')
    result = result.replace('is is', 'is')
    result = result.replace('eacheach', 'each')
    result = result.replace('mostmost', 'most')
    result = result.replace('differentdifferent', 'different')
    result = result.replace('typetype', 'type')
    result = result.replace('classclass', 'class')
    # Fix common concatenation issues (insert spaces where Chinese was removed)
    result = re.sub(r'([a-z])([A-Z])', r'\1 \2', result)
    result = re.sub(r'(\.)([A-Za-z])', r'\1 \2', result)
    # Final whitespace cleanup
    # Fix spaces around punctuation
    result = re.sub(r'\s+([.,;:!?)])', r'\1', result)
    result = re.sub(r'([(])\s+', r'\1', result)
    # Fix multiple spaces
    result = re.sub(r'\s+', ' ', result).strip()
    # Capitalize first letter
    if result and result[0].islower():
        result = result[0].upper() + result[1:]

    return result


def translate_category(category):
    """Translate a category name. First check exact mapping, then fall back to term translation."""
    if not category:
        return category
    if category in CATEGORY_TRANSLATIONS:
        return CATEGORY_TRANSLATIONS[category]
    return translate_text(category)


def translate_type(qtype):
    """Translate question type."""
    type_map = {
        "是非题": "True/False",
        "单选题": "Single Choice",
        "简答题(多选)": "Multiple Choice",
    }
    return type_map.get(qtype, qtype)


def translate_correct_answer(answer):
    """Translate correct answer values (正确→True, 错误→False) but keep letter answers unchanged."""
    if not answer:
        return answer
    # If it's a single letter (A-J) or combination (ABCD), keep it
    if re.match(r'^[A-J]+$', answer):
        return answer
    # Translate Chinese True/False
    val_map = {"正确": "True", "错误": "False"}
    return val_map.get(answer, answer)


def process_csv(input_path, output_path, chapter_num):
    """Read, translate, and write a CSV file."""
    rows = []
    with open(input_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        fieldnames = reader.fieldnames
        for row in reader:
            # Translate each field
            row['type'] = translate_type(row.get('type', ''))
            row['question'] = translate_text(row.get('question', ''))
            for opt in ['option_a', 'option_b', 'option_c', 'option_d', 'option_e',
                        'option_f', 'option_g', 'option_h', 'option_i', 'option_j']:
                if opt in row and row[opt]:
                    row[opt] = translate_text(row[opt], is_option_field=True)
            row['correct'] = translate_correct_answer(row.get('correct', ''))
            row['explanation'] = translate_text(row.get('explanation', ''))
            row['category'] = translate_category(row.get('category', ''))
            rows.append(row)

    with open(output_path, 'w', encoding='utf-8', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"  Ch{chapter_num}: {len(rows)} questions translated -> {output_path}")


def main():
    print("=" * 60)
    print("Pharmacology Quiz Translation: Chapters 13-18")
    print("Chinese -> Professional Medical English")
    print("=" * 60)

    chapters = [
        (13, "Sedative-Hypnotics and Wakefulness-Promoting Drugs"),
        (14, "Antiepileptic and Anticonvulsant Drugs"),
        (15, "Drugs for Neurodegenerative Diseases"),
        (16, "Drugs for Mental Disorders"),
        (17, "Opioid Analgesics, Drug Dependence and Abuse"),
        (18, "Antipyretic, Analgesic and Anti-inflammatory Drugs (NSAIDs)"),
    ]

    for ch_num, ch_name in chapters:
        input_path = os.path.join(BASE_DIR, f"pharma_cn_ch{ch_num}.csv")
        output_path = os.path.join(BASE_DIR, f"pharma_en_ch{ch_num}.csv")

        if not os.path.exists(input_path):
            print(f"  ERROR: Input file not found: {input_path}")
            continue

        print(f"\nProcessing Chapter {ch_num}: {ch_name}")
        process_csv(input_path, output_path, ch_num)

    print("\n" + "=" * 60)
    print("Translation complete! Output files:")
    for ch_num, _ in chapters:
        output_path = os.path.join(BASE_DIR, f"pharma_en_ch{ch_num}.csv")
        if os.path.exists(output_path):
            print(f"  {output_path}")
    print("=" * 60)


if __name__ == "__main__":
    main()
