#!/usr/bin/env python3
"""
Translate pharmacology quiz banks from Chinese to English for Chapters 7-12.
Ch7: Anticholinesterase Drugs and Cholinesterase Reactivators
Ch8: Cholinergic Receptor Blockers
Ch9: Adrenoceptor Agonists
Ch10: Adrenoceptor Blockers
Ch11: Local Anesthetics
Ch12: General Anesthetics

The translation dictionary is sorted by Chinese string length (descending)
at runtime to prevent short-substring matches from breaking longer terms.
"""

import csv
import os
import re

WORK_DIR = "/Users/weixu/Downloads/pnas"

# ── Translation dictionary (raw, will be length-sorted at boot) ──
_TRANS_RAW = [

    # ═══════════════════════════════════════════════════════════════
    # DRUG NAMES (longest-first to prevent partial matches)
    # ═══════════════════════════════════════════════════════════════
    ("硝苯呋海因（丹曲林）", "dantrolene"),
    ("去甲肾上腺素（NA）", "norepinephrine (NA)"),
    ("美曲膦酯（敌百虫）", "trichlorfon (dipterex)"),
    ("蛛网膜下腔麻醉（腰麻）", "subarachnoid anesthesia (spinal anesthesia)"),
    ("最低肺泡有效浓度（MAC）", "minimum alveolar concentration (MAC)"),
    ("利斯的明（卡巴拉汀）", "rivastigmine"),
    ("氯解磷定（PAM-Cl）", "pralidoxime chloride (PAM-Cl)"),
    ("真性胆碱酯酶（AChE）", "acetylcholinesterase (AChE)"),
    ("假性胆碱酯酶（BChE）", "butyrylcholinesterase (BChE)"),
    ("乙酰胆碱（ACh）", "acetylcholine (ACh)"),
    ("硝苯呋海因", "dantrolene"),
    ("丹曲林", "dantrolene"),
    ("艾司氯胺酮", "esketamine"),
    ("氯解磷定", "pralidoxime chloride"),
    ("碘解磷定", "pralidoxime iodide"),
    ("卡巴拉汀", "rivastigmine"),
    ("利斯的明", "rivastigmine"),
    ("新斯的明", "neostigmine"),
    ("毒扁豆碱", "physostigmine"),
    ("加兰他敏", "galantamine"),
    ("吡斯的明", "pyridostigmine"),
    ("依酚氯铵", "edrophonium"),
    ("石杉碱甲", "huperzine A"),
    ("安贝氯铵", "ambenonium"),
    ("山莨菪碱", "anisodamine"),
    ("东莨菪碱", "scopolamine"),
    ("阿托品", "atropine"),
    ("筒箭毒碱", "tubocurarine"),
    ("琥珀胆碱", "succinylcholine"),
    ("琥珀酰胆碱", "succinylcholine"),
    ("阿曲库铵", "atracurium"),
    ("罗库溴铵", "rocuronium"),
    ("毛果芸香碱", "pilocarpine"),
    ("后马托品", "homatropine"),
    ("异丙托溴铵", "ipratropium bromide"),
    ("噻托溴铵", "tiotropium bromide"),
    ("溴丙胺太林", "propantheline bromide"),
    ("哌仑西平", "pirenzepine"),
    ("达非那新", "darifenacin"),
    ("托特罗定", "tolterodine"),
    ("异丙肾上腺素", "isoproterenol"),
    ("去甲肾上腺素", "norepinephrine (NA)"),
    ("多巴酚丁胺", "dobutamine"),
    ("肾上腺素", "epinephrine"),
    ("多巴胺", "dopamine"),
    ("去氧肾上腺素", "phenylephrine"),
    ("间羟胺", "metaraminol"),
    ("麻黄碱", "ephedrine"),
    ("沙丁胺醇", "salbutamol"),
    ("特布他林", "terbutaline"),
    ("沙美特罗", "salmeterol"),
    ("福莫特罗", "formoterol"),
    ("酚妥拉明", "phentolamine"),
    ("酚苄明", "phenoxybenzamine"),
    ("育亨宾", "yohimbine"),
    ("哌唑嗪", "prazosin"),
    ("普萘洛尔", "propranolol"),
    ("噻吗洛尔", "timolol"),
    ("纳多洛尔", "nadolol"),
    ("吲哚洛尔", "pindolol"),
    ("美托洛尔", "metoprolol"),
    ("阿替洛尔", "atenolol"),
    ("艾司洛尔", "esmolol"),
    ("拉贝洛尔", "labetalol"),
    ("卡维地洛", "carvedilol"),
    ("布新洛尔", "bucindolol"),
    ("利多卡因", "lidocaine"),
    ("普鲁卡因", "procaine"),
    ("丁卡因", "tetracaine"),
    ("布比卡因", "bupivacaine"),
    ("罗哌卡因", "ropivacaine"),
    ("依替卡因", "etidocaine"),
    ("奥布卡因", "oxybuprocaine"),
    ("苯佐卡因", "benzocaine"),
    ("硫喷妥钠", "thiopental sodium"),
    ("丙泊酚", "propofol"),
    ("氯胺酮", "ketamine"),
    ("依托咪酯", "etomidate"),
    ("七氟烷", "sevoflurane"),
    ("异氟烷", "isoflurane"),
    ("恩氟烷", "enflurane"),
    ("地氟烷", "desflurane"),
    ("氟烷", "halothane"),
    ("乙醚", "diethyl ether"),
    ("氧化亚氮", "nitrous oxide"),
    ("氯丙嗪", "chlorpromazine"),
    ("吗啡", "morphine"),
    ("芬太尼", "fentanyl"),
    ("瑞芬太尼", "remifentanil"),
    ("敌百虫", "trichlorfon"),
    ("敌敌畏", "dichlorvos (DDVP)"),
    ("对硫磷", "parathion"),
    ("对氧磷", "paraoxon"),
    ("内吸磷", "demeton"),
    ("甲拌磷", "phorate"),
    ("乐果", "dimethoate"),
    ("特普", "TEPP"),
    ("卡那霉素", "kanamycin"),
    ("多黏菌素", "polymyxin"),
    ("环磷酰胺", "cyclophosphamide"),
    ("阿司匹林", "aspirin"),
    ("地西泮", "diazepam"),
    ("高锰酸钾", "potassium permanganate"),
    ("碳酸氢钠", "sodium bicarbonate"),

    # ═══════════════════════════════════════════════════════════════
    # CHAPTER-SPECIFIC CATEGORY & SUBJECT TERMS
    # ═══════════════════════════════════════════════════════════════
    ("单烷氧基磷酰化胆碱酯酶", "monoalkoxyphosphorylated cholinesterase"),
    ("α受体激动药与β受体激动药比较", "comparison of alpha- and beta-adrenoceptor agonists"),
    ("选择性M受体亚型阻断药", "selective M receptor subtype blockers"),
    ("M受体阻断药（阿托品相关）", "M receptor blockers (atropine-related)"),
    ("beta受体阻断药（血管舒张性）", "beta-adrenoceptor blockers (vasodilatory)"),
    ("beta受体阻断药分类", "beta-adrenoceptor blocker classification"),
    ("alpha受体阻断药", "alpha-adrenoceptor blockers"),
    ("beta受体阻断药", "beta-adrenoceptor blockers"),
    ("影响局部麻醉药作用的因素", "factors affecting local anesthetic action"),
    ("局部麻醉药作用机制", "mechanism of action of local anesthetics"),
    ("局部麻醉药分类", "classification of local anesthetics"),
    ("常用局部麻醉药", "commonly used local anesthetics"),
    ("吸入麻醉药不良反应", "inhaled anesthetic adverse reactions"),
    ("全身麻醉药概述", "overview of general anesthetics"),
    ("有机磷中毒防治", "organophosphate poisoning management"),
    ("局部麻醉方法", "methods of local anesthesia"),
    ("构效关系与分类", "structure-activity relationship and classification"),
    ("化学结构及分类", "chemical structure and classification"),
    ("局部麻醉作用", "local anesthetic action"),
    ("胆碱酯酶复活药", "cholinesterase reactivators"),
    ("抗胆碱酯酶药", "anticholinesterase drugs"),
    ("难逆性抗胆碱酯酶药", "irreversible anticholinesterase agents"),
    ("易逆性抗胆碱酯酶药", "reversible anticholinesterase agents"),
    ("肾上腺素受体激动药", "adrenoceptor agonists"),
    ("肾上腺素受体阻断药", "adrenoceptor blockers"),
    ("胆碱受体阻断药", "cholinergic receptor blockers"),
    ("局部麻醉药", "local anesthetics"),
    ("全身麻醉药", "general anesthetics"),
    ("吸入麻醉药", "inhaled anesthetics"),
    ("静脉麻醉药", "intravenous anesthetics"),
    ("M受体阻断药", "M receptor blockers"),
    ("N受体阻断药", "N receptor blockers"),
    ("α、β受体激动药", "alpha,beta-adrenoceptor agonists"),
    ("α受体阻断药", "alpha-adrenoceptor blockers"),
    ("α受体激动药", "alpha-adrenoceptor agonists"),
    ("β受体阻断药", "beta-adrenoceptor blockers"),
    ("β受体激动药", "beta-adrenoceptor agonists"),
    ("合成代用品", "synthetic substitutes"),
    ("合成扩瞳药", "synthetic mydriatics"),
    ("合成解痉药", "synthetic antispasmodics"),
    ("综合比较", "comprehensive comparison"),
    ("胆碱酯酶", "cholinesterase"),
    ("复合麻醉", "combined anesthesia"),
    ("诱导麻醉", "induction of anesthesia"),
    ("维持麻醉", "maintenance of anesthesia"),
    ("基础麻醉", "basal anesthesia"),
    ("低温麻醉", "hypothermic anesthesia"),
    ("分离麻醉", "dissociative anesthesia"),
    ("表面麻醉", "topical anesthesia"),
    ("浸润麻醉", "infiltration anesthesia"),
    ("硬膜外麻醉", "epidural anesthesia"),
    ("蛛网膜下腔麻醉", "subarachnoid anesthesia"),
    ("神经阻滞麻醉", "nerve block anesthesia"),
    ("全身静脉麻醉", "total intravenous anesthesia"),
    ("腰麻", "spinal anesthesia"),
    ("麻醉前给药", "preanesthetic medication"),
    ("触发麻醉", "trigger anesthesia"),

    # ═══════════════════════════════════════════════════════════════
    # COMPLEX MULTI-CHARACTER TERMS
    # ═══════════════════════════════════════════════════════════════
    ("电压门控钠离子通道", "voltage-gated sodium channels"),
    ("电压门控钠通道", "voltage-gated sodium channels"),
    ("神经肌肉接头处", "neuromuscular junction"),
    ("神经肌肉接头", "neuromuscular junction"),
    ("氨基糖苷类抗生素", "aminoglycoside antibiotics"),
    ("多肽类抗生素", "polypeptide antibiotics"),
    ("肝微粒体酶", "hepatic microsomal enzymes"),
    ("磷酰化胆碱酯酶", "phosphorylated cholinesterase"),
    ("乙酰化胆碱酯酶", "acetylated cholinesterase"),
    ("胆碱能神经元", "cholinergic neurons"),
    ("肾上腺素作用翻转", "epinephrine reversal"),
    ("有机磷酸酯类农药", "organophosphate pesticides"),
    ("有机磷酸酯类中毒", "organophosphate poisoning"),
    ("有机磷酸酯类", "organophosphates"),
    ("有机磷中毒", "organophosphate poisoning"),
    ("最低肺泡有效浓度", "minimum alveolar concentration (MAC)"),
    ("阵发性室上性心动过速", "paroxysmal supraventricular tachycardia"),
    ("闭角型青光眼", "angle-closure glaucoma"),
    ("胃肠道平滑肌", "gastrointestinal smooth muscle"),
    ("支气管平滑肌", "bronchial smooth muscle"),
    ("血管平滑肌", "vascular smooth muscle"),
    ("内脏平滑肌", "visceral smooth muscle"),
    ("骨骼肌纤维颤动", "skeletal muscle fasciculation"),
    ("骨骼肌松弛药", "skeletal muscle relaxant"),
    ("骨骼肌松弛", "skeletal muscle relaxation"),
    ("去极化型肌松药", "depolarizing muscle relaxant"),
    ("非去极化型肌松药", "non-depolarizing muscle relaxant"),
    ("胆碱能危象", "cholinergic crisis"),
    ("肌无力危象", "myasthenic crisis"),
    ("重症肌无力", "myasthenia gravis"),
    ("阿尔茨海默病", "Alzheimer disease (AD)"),
    ("帕金森病", "Parkinson disease (PD)"),
    ("支气管哮喘", "bronchial asthma"),
    ("感染性休克", "septic shock"),
    ("过敏性休克", "anaphylactic shock"),
    ("心源性休克", "cardiogenic shock"),
    ("缓慢型心律失常", "bradyarrhythmia"),
    ("窦性心动过缓", "sinus bradycardia"),
    ("窦房传导阻滞", "sinoatrial block"),
    ("房室传导阻滞", "atrioventricular block"),
    ("呼吸衰竭", "respiratory failure"),
    ("心血管功能障碍", "cardiovascular dysfunction"),
    ("恶性高热", "malignant hyperthermia"),
    ("氟烷性肝炎", "halothane hepatitis"),
    ("有效不应期", "effective refractory period"),
    ("首剂效应", "first-dose phenomenon"),
    ("调节麻痹", "cycloplegia"),
    ("调节痉挛", "spasm of accommodation"),
    ("术后腹气胀", "postoperative abdominal distension"),
    ("术后尿潴留", "postoperative urinary retention"),
    ("术后肌肉酸痛", "postoperative muscle pain"),
    ("前列腺增生", "benign prostatic hyperplasia"),
    ("肾功能衰竭", "renal failure"),
    ("肾上腺皮质功能", "adrenocortical function"),
    ("快速耐受性", "tachyphylaxis"),
    ("老化的胆碱酯酶", "aged cholinesterase"),
    ("老化过程", "aging process"),
    ("内在拟交感活性（ISA）", "intrinsic sympathomimetic activity (ISA)"),
    ("内在拟交感活性", "intrinsic sympathomimetic activity (ISA)"),
    ("血/气分配系数", "blood/gas partition coefficient"),
    ("脑/血分配系数", "brain/blood partition coefficient"),
    ("分配系数", "partition coefficient"),
    ("药理作用特点", "pharmacological characteristics"),
    ("体内过程", "pharmacokinetics"),
    ("临床应用", "clinical application"),
    ("补充血容量", "volume expansion"),
    ("洗胃禁忌", "contraindicated for gastric lavage"),
    ("对氨基化合物", "para-amino compound"),
    ("季铵类化合物", "quaternary ammonium compound"),
    ("叔铵类化合物", "tertiary ammonium compound"),
    ("双季铵类化合物", "bis-quaternary ammonium compound"),
    ("酰胺类局部麻醉药", "amide-type local anesthetics"),
    ("酯类局部麻醉药", "ester-type local anesthetics"),
    ("酰胺类局麻药", "amide local anesthetics"),
    ("酯类局麻药", "ester local anesthetics"),
    ("中枢神经系统", "central nervous system (CNS)"),
    ("瞳孔括约肌", "pupillary sphincter muscle"),
    ("虹膜括约肌", "iris sphincter muscle"),
    ("心肌收缩力", "myocardial contractility"),
    ("心肌耗氧量", "myocardial oxygen consumption"),
    ("运动神经末梢", "motor nerve ending"),
    ("感觉神经末梢", "sensory nerve ending"),
    ("神经末梢", "nerve ending"),
    ("动作电位", "action potential"),
    ("神经冲动", "nerve impulse"),
    ("运动终板", "motor end plate"),
    ("副交感神经", "parasympathetic nerve"),
    ("交感神经", "sympathetic nerve"),
    ("迷走神经", "vagus nerve"),
    ("边缘系统", "limbic system"),
    ("大脑皮质", "cerebral cortex"),
    ("前房角", "anterior chamber angle"),
    ("房水", "aqueous humor"),
    ("睫状肌", "ciliary muscle"),
    ("膀胱逼尿肌", "detrusor muscle of the bladder"),
    ("呼吸中枢", "respiratory center"),
    ("体温下降", "hypothermia"),
    ("基础代谢率", "basal metabolic rate"),

    # ═══════════════════════════════════════════════════════════════
    # RECEPTOR / ENZYME / MOLECULAR TERMS (medium-length)
    # ═══════════════════════════════════════════════════════════════
    ("GABAA受体", "GABAA receptor"),
    ("NMDA受体", "NMDA receptor"),
    ("M胆碱受体", "muscarinic cholinergic receptor"),
    ("N胆碱受体", "nicotinic cholinergic receptor"),
    ("M1受体", "M1 receptor"),
    ("M2受体", "M2 receptor"),
    ("M3受体", "M3 receptor"),
    ("M4受体", "M4 receptor"),
    ("M5受体", "M5 receptor"),
    ("NM受体", "NM receptor"),
    ("NN受体", "NN receptor"),
    ("α1受体", "alpha1-adrenoceptor"),
    ("α2受体", "alpha2-adrenoceptor"),
    ("β1受体", "beta1-adrenoceptor"),
    ("β2受体", "beta2-adrenoceptor"),
    ("β3受体", "beta3-adrenoceptor"),
    ("α受体", "alpha-adrenoceptor"),
    ("β受体", "beta-adrenoceptor"),
    ("M受体", "M receptor"),
    ("N受体", "N receptor"),
    ("D1受体", "D1 receptor"),
    ("受体", "receptor"),

    ("乙酰化AChE", "acetylated AChE"),
    ("酯解部位", "esteratic site"),
    ("丝氨酸羟基", "serine hydroxyl group"),
    ("季铵阳离子", "quaternary ammonium cation"),
    ("阴离子部位", "anionic site"),
    ("羰基碳", "carbonyl carbon"),
    ("氯化烷基胺", "chloroalkylamine"),
    ("共价键", "covalent bond"),
    ("苯乙胺", "phenylethylamine"),
    ("儿茶酚胺类", "catecholamines"),
    ("儿茶酚胺", "catecholamine"),
    ("半抗原", "hapten"),

    # ═══════════════════════════════════════════════════════════════
    # ANATOMY / PHYSIOLOGY (medium-length)
    # ═══════════════════════════════════════════════════════════════
    ("支气管腺体", "bronchial glands"),
    ("支气管痉挛", "bronchospasm"),
    ("支气管扩张", "bronchodilation"),
    ("喉头痉挛", "laryngospasm"),
    ("腺体分泌", "glandular secretion"),
    ("唾液腺", "salivary glands"),
    ("汗腺", "sweat glands"),
    ("肠梗阻", "intestinal obstruction"),
    ("泌尿道梗阻", "urinary tract obstruction"),
    ("血管收缩", "vasoconstriction"),
    ("血管扩张", "vasodilation"),
    ("血管痉挛", "vasospasm"),
    ("微循环", "microcirculation"),
    ("肝衰竭", "hepatic failure"),
    ("肝功能", "liver function"),
    ("肝微粒体", "hepatic microsomes"),
    ("肌质网", "sarcoplasmic reticulum"),
    ("红细胞", "erythrocytes"),
    ("血脑屏障", "blood-brain barrier"),
    ("脑组织", "brain tissue"),
    ("突触前膜", "presynaptic membrane"),
    ("突触后膜", "postsynaptic membrane"),
    ("神经节", "ganglion"),
    ("突触", "synapse"),
    ("心肌", "myocardium"),
    ("肝肾", "liver and kidney"),
    ("肝脏", "liver"),
    ("肾脏", "kidney"),
    ("血浆", "plasma"),
    ("血液", "blood"),
    ("血清", "serum"),
    ("脂肪", "adipose tissue"),
    ("黏膜", "mucous membrane"),
    ("粘膜", "mucous membrane"),
    ("肌肉", "muscle"),
    ("皮肤", "skin"),
    ("瞳孔", "pupil"),
    ("眼内压", "intraocular pressure"),
    ("收缩压", "systolic blood pressure"),
    ("舒张压", "diastolic blood pressure"),
    ("心率", "heart rate"),
    ("心律", "cardiac rhythm"),
    ("血压", "blood pressure"),
    ("气道", "airway"),
    ("呼吸道", "respiratory tract"),
    ("胃肠道", "gastrointestinal tract"),
    ("消化道", "digestive tract"),
    ("胃酸", "gastric acid"),
    ("胃蛋白酶", "pepsin"),
    ("消化性溃疡", "peptic ulcer"),
    ("胃食管反流", "gastroesophageal reflux"),
    ("外周阻力", "peripheral resistance"),
    ("心输出量", "cardiac output"),
    ("肾血流量", "renal blood flow"),
    ("肾素", "renin"),
    ("尿量", "urine output"),
    ("体温", "body temperature"),
    ("肺", "lung"),
    ("肝", "liver"),
    ("肾", "kidney"),
    ("肠", "intestine"),
    ("脑", "brain"),
    ("心", "heart"),
    ("血", "blood"),
    ("尿", "urine"),

    # ═══════════════════════════════════════════════════════════════
    # CLINICAL TERMINOLOGY (medium-length)
    # ═══════════════════════════════════════════════════════════════
    ("变态反应", "allergic reaction"),
    ("过敏反应", "anaphylactic reaction"),
    ("特异质反应", "idiosyncratic reaction"),
    ("肾上腺素作用翻转", "epinephrine reversal"),
    ("阿托品化", "atropinization"),
    ("给药途径", "route of administration"),
    ("静脉注射", "intravenous injection"),
    ("静脉滴注", "intravenous infusion"),
    ("肌内注射", "intramuscular injection"),
    ("皮下注射", "subcutaneous injection"),
    ("吸入给药", "inhalation administration"),
    ("局部给药", "topical administration"),
    ("口服给药", "oral administration"),
    ("人工呼吸", "artificial respiration"),
    ("吸氧", "oxygen therapy"),
    ("补液", "fluid replacement"),
    ("洗胃", "gastric lavage"),
    ("麻醉诱导", "anesthesia induction"),
    ("麻醉维持", "anesthesia maintenance"),
    ("麻醉效价", "anesthetic potency"),
    ("麻醉强度", "anesthetic potency"),
    ("麻醉深度", "depth of anesthesia"),
    ("最低致死量", "minimum lethal dose"),
    ("半数致死量", "median lethal dose (LD50)"),
    ("半数有效量", "median effective dose (ED50)"),
    ("第一个", "the first"),
    ("第二个", "the second"),
    ("第一步", "the first step"),
    ("第二步", "the second step"),
    ("第三步", "the third step"),
    ("第一步", "step 1"),
    ("第二步", "step 2"),
    ("第三步", "step 3"),

    # ═══════════════════════════════════════════════════════════════
    # MEDICAL / PHARMACOLOGICAL TERMS
    # ═══════════════════════════════════════════════════════════════
    ("竞争性", "competitive"),
    ("非竞争性", "non-competitive"),
    ("非选择性", "non-selective"),
    ("不可逆性", "irreversible"),
    ("选择性高", "high selectivity"),
    ("选择性低", "low selectivity"),
    ("可逆性", "reversible"),
    ("选择性", "selective"),
    ("特异性", "specificity"),
    ("敏感性", "sensitivity"),
    ("耐药性", "drug resistance"),
    ("依赖性", "dependence"),
    ("耐受性", "tolerance"),
    ("脂溶性", "lipid solubility"),
    ("水溶性", "water solubility"),
    ("代谢产物", "metabolites"),
    ("半衰期", "half-life"),
    ("生物利用度", "bioavailability"),
    ("适应证", "indication"),
    ("禁忌证", "contraindication"),
    ("副作用", "side effects"),
    ("毒性反应", "toxicity"),
    ("中毒反应", "toxic reaction"),
    ("作用机制", "mechanism of action"),
    ("不良反应", "adverse reactions"),
    ("药理作用", "pharmacological effects"),
    ("解药", "antidote"),
    ("解救", "rescue / antidotal treatment"),
    ("季铵类", "quaternary ammonium class"),
    ("叔铵类", "tertiary ammonium class"),
    ("酰胺类", "amide class"),
    ("酯类", "ester class"),
    ("酰胺键", "amide bond"),
    ("酯键", "ester bond"),
    ("解离型", "ionized form"),
    ("未解离型", "non-ionized form"),
    ("氧化代谢", "oxidative metabolism"),
    ("首过效应", "first-pass effect"),
    ("首关消除", "first-pass elimination"),
    ("肝肠循环", "enterohepatic circulation"),
    ("血浆蛋白结合率", "plasma protein binding rate"),

    # ═══════════════════════════════════════════════════════════════
    # DRUG NAME COMPONENTS / CHEMICAL GROUPS
    # ═══════════════════════════════════════════════════════════════
    ("季铵化合物", "quaternary ammonium compound"),
    ("季铵", "quaternary ammonium"),
    ("烷基", "alkyl group"),
    ("烷氧基", "alkoxy group"),
    ("肟基", "oxime group"),
    ("吡啶环", "pyridine ring"),
    ("咪唑啉", "imidazoline"),
    ("磷原子", "phosphorus atom"),
    ("苯环", "benzene ring"),
    ("羟基", "hydroxyl group"),
    ("羧基", "carboxyl group"),
    ("胺基", "amino group"),
    ("氨基", "amino group"),
    ("芳香环", "aromatic ring"),
    ("中间链", "intermediate chain"),
    ("亲脂性", "lipophilic"),
    ("亲水性", "hydrophilic"),
    ("疏水性", "hydrophobic"),
    ("亚基", "subunit"),

    # ═══════════════════════════════════════════════════════════════
    # MEMBRANE / ION CHANNEL TERMS
    # ═══════════════════════════════════════════════════════════════
    ("钠通道", "sodium channel"),
    ("钾通道", "potassium channel"),
    ("钙通道", "calcium channel"),
    ("氯通道", "chloride channel"),
    ("离子通道", "ion channel"),
    ("细胞膜", "cell membrane"),
    ("神经细胞膜", "neuronal membrane"),
    ("超极化", "hyperpolarization"),
    ("去极化", "depolarization"),
    ("复极化", "repolarization"),
    ("静息电位", "resting potential"),
    ("阈电位", "threshold potential"),

    # ═══════════════════════════════════════════════════════════════
    # PATHOPHYSIOLOGY / MEDICAL CONDITIONS
    # ═══════════════════════════════════════════════════════════════
    ("呼吸抑制", "respiratory depression"),
    ("呼吸麻痹", "respiratory paralysis"),
    ("心肌梗死", "myocardial infarction"),
    ("心绞痛", "angina pectoris"),
    ("心律失常", "arrhythmia"),
    ("室性心律失常", "ventricular arrhythmia"),
    ("心力衰竭", "heart failure"),
    ("高血压", "hypertension"),
    ("低血压", "hypotension"),
    ("高眼压症", "ocular hypertension"),
    ("开角型青光眼", "open-angle glaucoma"),
    ("癫痫", "epilepsy"),
    ("脑缺氧", "cerebral hypoxia"),
    ("脑水肿", "cerebral edema"),
    ("脑血流量", "cerebral blood flow"),
    ("脑代谢", "cerebral metabolism"),
    ("颅内压", "intracranial pressure"),
    ("急性心肌梗死", "acute myocardial infarction"),
    ("猝死", "sudden death"),
    ("反跳现象", "rebound phenomenon"),
    ("胆碱能危象", "cholinergic crisis"),
    ("支气管高敏性", "bronchial hyperresponsiveness"),
    ("组织坏死", "tissue necrosis"),
    ("呼吸性酸中毒", "respiratory acidosis"),
    ("代谢性酸中毒", "metabolic acidosis"),
    ("炎症反应", "inflammatory response"),
    ("变态反应", "allergic reaction"),
    ("呼吸肌麻痹", "respiratory muscle paralysis"),
    ("房室传导", "atrioventricular conduction"),
    ("不应期", "refractory period"),
    ("清蛋白", "albumin"),
    ("球蛋白", "globulin"),
    ("凝血", "coagulation"),
    ("缺氧", "hypoxia"),
    ("缺血", "ischemia"),
    ("再灌注", "reperfusion"),
    ("氧化应激", "oxidative stress"),

    # ═══════════════════════════════════════════════════════════════
    # CLINICAL ACTIONS / PROCEDURES
    # ═══════════════════════════════════════════════════════════════
    ("气管内插管", "endotracheal intubation"),
    ("麻醉诱导", "anesthesia induction"),
    ("麻醉苏醒", "emergence from anesthesia"),
    ("术前用药", "preoperative medication"),
    ("术后镇痛", "postoperative analgesia"),
    ("物理降温", "physical cooling"),
    ("诊断支气管高敏性", "diagnosis of bronchial hyperresponsiveness"),
    ("鉴别诊断", "differential diagnosis"),
    ("对症治疗", "symptomatic treatment"),
    ("支持治疗", "supportive care"),
    ("脊柱后侧凸", "kyphoscoliosis"),
    ("内镜检查", "endoscopy"),
    ("心脏复律术", "cardioversion"),
    ("心导管术", "cardiac catheterization"),
    ("过敏试验", "allergy testing"),
    ("脊髓灰质炎后遗症", "post-polio sequelae"),
    ("表面麻醉", "topical anesthesia"),
    ("局部注射", "local injection"),
    ("硬膜外腔", "epidural space"),
    ("蛛网膜下腔", "subarachnoid space"),

    # ═══════════════════════════════════════════════════════════════
    # DISEASE ABBREVIATIONS / CONDITIONS
    # ═══════════════════════════════════════════════════════════════
    ("COPD", "COPD"),
    ("AD", "AD"),
    ("PD", "PD"),
    ("ACh", "ACh"),
    ("COMT", "COMT"),
    ("MAO", "MAO"),
    ("DDVP", "DDVP"),
    ("M样症状", "muscarinic symptoms"),
    ("N样症状", "nicotinic symptoms"),
    ("M样副作用", "muscarinic side effects"),
    ("N样副作用", "nicotinic side effects"),

    # ═══════════════════════════════════════════════════════════════
    # COMMON CHINESE VERBS / PHRASES IN TEST QUESTIONS
    # ═══════════════════════════════════════════════════════════════
    ("不包括下列哪项", "which of the following is NOT included"),
    ("下列哪项是错误的", "which of the following is INCORRECT"),
    ("下列哪项是正确的", "which of the following is CORRECT"),
    ("死亡的主要原因是什么", "what is the main cause of death"),
    ("属于下列哪类药物", "belongs to which of the following drug classes"),
    ("下列哪些属于", "which of the following belong to"),
    ("下列属于", "which of the following belong(s) to"),
    ("下列哪种药物", "which of the following drugs"),
    ("下列哪种", "which of the following"),
    ("下列哪项", "which of the following"),
    ("下列哪些", "which of the following"),
    ("正确的是", "is correct"),
    ("错误的是", "is incorrect"),
    ("不正确", "is incorrect"),
    ("不包括", "does NOT include"),
    ("不属于", "does NOT belong to"),
    ("不会引起", "does not cause"),
    ("不会产生", "does not produce"),
    ("不会出现", "does not occur"),
    ("不会导致", "does not lead to"),
    ("is not easily引起", "is not easily induced"),
    ("主要原因是", "the main reason / cause is"),
    ("主要特点", "the main characteristic"),
    ("主要作用", "the main effect"),
    ("主要机制", "the main mechanism"),
    ("主要表现", "the main manifestation"),
    ("主要区别", "the main difference"),
    ("主要临床应用", "the main clinical application"),
    ("首选药物", "drug of first choice"),
    ("首选给药途径", "route of administration of first choice"),
    ("作用特点", "pharmacological characteristics"),
    ("作用机制", "mechanism of action"),
    ("作用部位", "site of action"),
    ("持续时间为", "the duration is"),
    ("作用时间", "duration of action"),
    ("首选", "first choice"),
    ("禁用于", "is contraindicated for"),
    ("适用于", "is indicated for"),
    ("应增加", "should increase"),
    ("应减少", "should decrease"),
    ("应避免", "should avoid"),
    ("应停用", "should be discontinued"),
    ("不应", "should not"),
    ("不能", "cannot"),
    ("不会", "will not / does not"),
    ("不可", "must not / cannot"),
    ("不易", "is not readily"),
    ("is not easily", "is not readily"),
    ("可用于", "can be used for"),
    ("主要用于", "is mainly used for"),
    ("常用于", "is commonly used for"),
    ("用于", "is used for"),
    ("正确的", "correct"),
    ("错误的", "incorrect"),
    ("正确的是", "is correct"),
    ("错误的是", "is incorrect"),
    ("必需", "is necessary / required"),
    ("无需", "is not necessary / not required"),
    ("可", "can / may"),
    ("均", "all / are all"),
    ("以", "by / in order to / with"),
    ("仅", "only / merely"),
    ("除", "except / besides"),
    ("即", "namely / i.e."),
    ("故", "therefore"),
    ("则", "then / whereas"),
    ("尚", "still / yet"),
    ("等", "etc. / and others"),
    ("各", "each / various"),
    ("某", "a certain"),
    ("另", "another / other"),
    ("把", "(object marker)"),
    ("被", "by (passive voice)"),
    ("使", "cause / make / allow"),
    ("让", "let / allow"),
    ("将", "will / shall"),
    ("会", "will / can"),
    ("要", "need / must"),
    ("可要", "may need"),
    ("都需要", "all require"),
    ("特别是", "especially / in particular"),
    ("尤其是", "especially"),
    ("此外", "in addition / furthermore"),
    ("另外", "additionally"),
    ("同时", "simultaneously / also"),
    ("然后", "then / subsequently"),
    ("首先", "first / firstly"),
    ("其次", "second / secondly"),
    ("最后", "finally / lastly"),
    ("一般", "generally / usually"),
    ("通常", "usually / typically"),
    ("往往", "often / tend to"),
    ("可能", "may / possibly"),
    ("很可能", "very likely"),
    ("必须", "must / have to"),
    ("需要", "require / need"),
    ("需", "need / require"),
    ("不需要", "do not need / not required"),

    # ═══════════════════════════════════════════════════════════════
    # VERBS (action words)
    # ═══════════════════════════════════════════════════════════════
    ("存在于", "is present in / exists in"),
    ("表现为", "manifests as"),
    ("表现为", "presents as"),
    ("作用于", "acts on"),
    ("存在", "present / existing"),
    ("参与", "participate in"),
    ("形成", "form"),
    ("生成", "produce / generate"),
    ("产生", "produce / generate"),
    ("造成", "cause / result in"),
    ("导致", "lead to / cause"),
    ("引起", "cause / induce / trigger"),
    ("诱发", "induce / provoke"),
    ("触发", "trigger"),
    ("出现", "appear / occur / emerge"),
    ("消失", "disappear / resolve"),
    ("发生", "occur / happen / take place"),
    ("恢复", "restore / recover"),
    ("促进", "promote / facilitate"),
    ("抑制", "inhibit / suppress"),
    ("阻断", "block"),
    ("激动", "stimulate / activate"),
    ("兴奋", "excite / stimulate"),
    ("增强", "enhance / strengthen / increase"),
    ("减弱", "weaken / reduce / diminish"),
    ("减轻", "alleviate / reduce"),
    ("加重", "aggravate / worsen"),
    ("改善", "improve"),
    ("延缓", "delay / slow"),
    ("提高", "increase / elevate / raise"),
    ("升高", "increase / elevate / raise"),
    ("降低", "decrease / reduce / lower"),
    ("增加", "increase / raise"),
    ("减少", "decrease / reduce / diminish"),
    ("缩短", "shorten"),
    ("延长", "prolong / extend"),
    ("加快", "accelerate / speed up"),
    ("减慢", "slow down / decelerate"),
    ("松弛", "relax"),
    ("舒张", "relax / dilate"),
    ("收缩", "contract / constrict"),
    ("扩张", "dilate / expand"),
    ("缩小", "constrict / narrow / reduce"),
    ("扩大", "dilate / enlarge / expand"),
    ("开放", "open"),
    ("关闭", "close"),
    ("激活", "activate"),
    ("失活", "inactivate / deactivate"),
    ("灭活", "inactivate"),
    ("水解", "hydrolyze"),
    ("分解", "decompose / break down"),
    ("合成", "synthesize"),
    ("释放", "release"),
    ("摄取", "uptake / reuptake"),
    ("再摄取", "reuptake"),
    ("分泌", "secrete / secretion"),
    ("排泄", "excrete / excretion"),
    ("排出", "excrete / eliminate"),
    ("消除", "eliminate / clear"),
    ("吸收", "absorb"),
    ("分布", "distribute"),
    ("代谢", "metabolize"),
    ("蓄积", "accumulate"),
    ("积聚", "accumulate"),
    ("结合", "bind / combine"),
    ("解离", "dissociate"),
    ("穿透", "penetrate / cross"),
    ("透过", "pass through / cross"),
    ("通过", "pass through / via"),
    ("转运", "transport"),
    ("流入", "influx / flow into"),
    ("内流", "influx / inward flow"),
    ("外流", "efflux / outward flow"),
    ("进入", "enter / entry into"),
    ("离开", "leave / exit from"),
    ("达到", "reach / achieve / attain"),
    ("超过", "exceed / surpass"),
    ("低于", "below / lower than"),
    ("高于", "above / higher than"),
    ("维持", "maintain"),
    ("保持", "maintain / keep"),
    ("发挥", "exert / play (a role)"),
    ("影响", "affect / influence"),
    ("包括", "include / including"),
    ("含有", "contain / containing"),
    ("应用", "apply / application / use"),
    ("使用", "use / utilize"),
    ("用药", "medication / drug administration"),
    ("给药", "administer / administration"),
    ("注射", "inject / injection"),
    ("滴注", "infusion / intravenous drip"),
    ("口服", "oral administration"),
    ("吸入", "inhale / inhalation"),
    ("滴眼", "eye drop / ophthalmic instillation"),
    ("治疗", "treat / treatment / therapy"),
    ("预防", "prevent / prevention / prophylaxis"),
    ("诊断", "diagnose / diagnosis"),
    ("缓解", "relieve / alleviate"),
    ("对抗", "counteract / oppose"),
    ("拮抗", "antagonize"),
    ("协同", "synergize / potentiate"),
    ("合用", "coadministration / combined use"),
    ("联合用药", "combination therapy"),
    ("单用", "use alone / monotherapy"),
    ("避免", "avoid"),
    ("注意", "note / attention"),
    ("评价", "evaluate / assess"),
    ("监测", "monitor"),
    ("检测", "detect / test"),
    ("测定", "measure / determine"),
    ("记录", "record / document"),
    ("描述", "describe / description"),
    ("解释", "explain / interpretation"),
    ("证实", "confirm / verify"),
    ("提示", "indicate / suggest"),
    ("表明", "indicate / demonstrate"),
    ("显示", "show / demonstrate / reveal"),
    ("证明", "prove / demonstrate"),
    ("称", "referred to as / called"),
    ("称为", "is called / is referred to as"),
    ("称之为", "is referred to as"),
    ("所谓", "so-called"),
    ("即", "namely / i.e. / that is"),
    ("是指", "refers to / is defined as"),
    ("定义为", "is defined as"),
    ("相当于", "is equivalent to / corresponds to"),
    ("取决于", "depends on"),
    ("受---影响", "is affected by"),
    ("与---相关", "is associated with / related to"),
    ("与---有关", "is related to / associated with"),
    ("与---相似", "is similar to"),
    ("与---相反", "is opposite to / in contrast to"),
    ("与---比较", "compared with"),
    ("与---合用", "combined with / coadministered with"),
    ("成正比", "is directly proportional to"),
    ("成反比", "is inversely proportional to"),
    ("至关重要", "is critical / is crucial"),
    ("决定", "determine"),
    ("具有", "have / possess"),
    ("缺乏", "lack / be deficient in"),
    ("丧失", "lose / loss of"),
    ("取代", "replace / substitute"),
    ("替代", "replace / substitute for"),
    ("代谢", "metabolize / metabolism"),
    ("转化", "convert / transform"),
    ("转变为", "convert to / transform into"),
    ("变化", "change / variation"),
    ("改变", "change / alter / modify"),
    ("翻转", "reverse / reversal"),
    ("反转", "reverse"),
    ("逆转", "reverse"),
    ("叠加", "superimpose / additive effect"),
    ("抵消", "offset / counteract"),
    ("削弱", "weaken / attenuate"),
    ("冲洗", "flush / wash out"),
    ("清除", "clear / eliminate"),
    ("洗脱", "wash out / elute"),
    ("停用", "discontinue / stop"),
    ("减量", "dose reduction"),
    ("加量", "dose increase"),
    ("过量", "excessive dose / overdose"),
    ("过量中毒", "overdose toxicity"),
    ("禁用", "is contraindicated"),
    ("慎用", "use with caution"),
    ("禁用禁忌", "contraindicated"),
    ("中毒", "poisoning / toxicity / intoxication"),
    ("过量时", "in case of overdose"),
    ("中毒时", "in case of poisoning"),
    ("抢救", "rescue / emergency treatment"),

    # ═══════════════════════════════════════════════════════════════
    # ADVERBS & ADVERBIAL PHRASES
    # ═══════════════════════════════════════════════════════════════
    ("不可逆地", "irreversibly"),
    ("选择性地", "selectively"),
    ("非选择性地", "non-selectively"),
    ("竞争性地", "competitively"),
    ("直接", "directly"),
    ("间接", "indirectly"),
    ("迅速", "rapidly / quickly"),
    ("缓慢", "slowly"),
    ("逐渐", "gradually"),
    ("显著", "significantly / markedly"),
    ("明显", "markedly / obviously"),
    ("轻微", "mildly / slightly"),
    ("严重", "severely / seriously"),
    ("极易", "very easily / readily"),
    ("罕见", "rarely"),
    ("频繁", "frequently"),
    ("永久性", "permanently"),
    ("暂时性", "temporarily / transiently"),
    ("一过性", "transient / temporary"),
    ("部分", "partially / partly"),
    ("完全", "completely / fully / entirely"),
    ("全部", "all / entirely"),
    ("充分", "fully / sufficiently"),
    ("足够", "sufficiently / adequately"),
    ("不足", "insufficiently / inadequately"),
    ("逐渐", "gradually / progressively"),
    ("迅速", "rapidly / promptly"),
    ("主要", "mainly / primarily"),
    ("大多", "mostly"),
    ("绝大部分", "the vast majority"),
    ("绝大多数", "the vast majority"),
    ("强烈", "strongly / potently / intensely"),
    ("轻度", "mildly / slightly"),
    ("中度", "moderately"),
    ("重度", "severely / heavily"),
    ("共同", "commonly / together"),
    ("常常", "often / frequently"),
    ("总是", "always"),
    ("从不", "never"),
    ("偶尔", "occasionally"),
    ("有时", "sometimes"),
    ("反复", "repeatedly"),
    ("突然", "suddenly / abruptly"),
    ("持续", "continuously / persistently"),
    ("持续地", "continuously / persistently"),
    ("长期", "long-term / chronic"),
    ("短期", "short-term / acute"),
    ("定期", "regularly / periodically"),

    # ═══════════════════════════════════════════════════════════════
    # SENSATION / PERCEPTION TERMS
    # ═══════════════════════════════════════════════════════════════
    ("感觉", "sensation"),
    ("痛觉", "pain sensation"),
    ("温觉", "temperature sensation"),
    ("冷觉", "cold sensation"),
    ("热觉", "heat sensation"),
    ("触觉", "touch sensation"),
    ("压觉", "pressure sensation"),
    ("本体感觉", "proprioception"),
    ("痛觉消失", "loss of pain sensation / analgesia"),
    ("感觉消失", "loss of sensation / anesthesia"),
    ("感觉异常", "paresthesia"),
    ("麻木", "numbness"),
    ("疼痛", "pain"),
    ("刺痛", "stinging pain"),
    ("烧灼感", "burning sensation"),
    ("注射痛", "injection pain"),
    ("注射部位疼痛", "injection site pain"),

    # ═══════════════════════════════════════════════════════════════
    # SYSTEM / FUNCTION WORDS (use single clear equivalents)
    # ═══════════════════════════════════════════════════════════════
    ("的", ""),
    ("了", ""),
    ("着", ""),
    ("是", "is"),
    ("在", "in"),
    ("和", "and"),
    ("与", "and"),
    ("或", "or"),
    ("对", "for"),
    ("为", "as"),
    ("由", "by"),
    ("从", "from"),
    ("到", "to"),
    ("向", "toward"),
    ("用", "with"),
    ("把", ""),
    ("所", ""),
    ("其", "its"),
    ("其中", "among which / of which"),
    ("这", "this"),
    ("那", "that"),
    ("这些", "these"),
    ("那些", "those"),
    ("这种", "this type of"),
    ("两种", "both types / two types"),
    ("三种", "three types / three"),
    ("多种", "multiple / various"),
    ("以下几种", "the following"),
    ("以上", "above / the above"),
    ("以下", "below / the following"),
    ("以内", "within"),
    ("以外", "outside of / beyond"),
    ("之后", "after / thereafter"),
    ("之前", "before / prior to"),
    ("之后", "after"),
    ("之时", "at the time of / when"),
    ("之间", "between / among"),
    ("之中", "among / within"),
    ("之内", "within / inside"),
    ("之外", "outside / beyond"),
    ("之内", "within"),
    ("之上", "above"),
    ("之下", "below / under"),
    ("左右", "approximately / about"),
    ("大约", "approximately / about"),
    ("分别", "respectively"),
    ("各自", "each / respectively"),
    ("均", "all"),
    ("都", "all / both"),
    ("每", "each / every"),
    ("每次", "each time / per dose"),
    ("每日", "daily / per day"),
    ("每小时", "per hour"),
    ("每分钟", "per minute"),
    ("每公斤", "per kilogram"),
    ("至少", "at least"),
    ("最多", "at most / maximum"),
    ("最少", "at minimum / least"),
    ("很多", "many / numerous"),
    ("很大", "very large / substantial"),
    ("很小", "very small / minimal"),
    ("较快", "relatively fast / faster"),
    ("较慢", "relatively slow / slower"),
    ("较强", "relatively strong / stronger"),
    ("较弱", "relatively weak / weaker"),
    ("较多", "relatively more / greater"),
    ("较少", "relatively less / fewer"),
    ("较好", "relatively good / better"),
    ("较差", "relatively poor / worse"),
    ("更高", "higher"),
    ("更低", "lower"),
    ("最大", "maximum / maximal"),
    ("最小", "minimum / minimal"),
    ("最高", "highest / maximum"),
    ("最低", "lowest / minimum"),
    ("最优", "optimal / best"),
    ("最差", "worst"),
    ("最常", "most commonly"),
    ("非常", "very / extremely"),
    ("极其", "extremely / exceedingly"),
    ("特别", "especially / particularly"),
    ("尤其", "especially / in particular"),
    ("甚至", "even"),
    ("更加", "more / even more"),
    ("越来", "increasingly"),
    ("较为", "relatively / comparatively"),
    ("相当", "quite / fairly / considerably"),
    ("基本上", "basically / essentially"),
    ("几乎", "almost / nearly"),
    ("完全", "completely / fully"),
    ("根本", "fundamentally / at all"),
    ("不大", "not very / not significantly"),
    ("不太", "not very"),

    # ═══════════════════════════════════════════════════════════════
    # QUANTITY / MEASUREMENT
    # ═══════════════════════════════════════════════════════════════
    ("剂量", "dose / dosage"),
    ("治疗量", "therapeutic dose"),
    ("中毒量", "toxic dose"),
    ("致死量", "lethal dose"),
    ("小剂量", "low dose"),
    ("大剂量", "high dose"),
    ("常规剂量", "conventional dose"),
    ("首次剂量", "initial dose / first dose"),
    ("首次用药", "first dose / initial administration"),
    ("最大剂量", "maximum dose"),
    ("一次最大允许剂量", "maximum single allowable dose"),
    ("一次最大允许", "maximum single allowable"),
    ("维持剂量", "maintenance dose"),
    ("负荷剂量", "loading dose"),
    ("有效剂量", "effective dose"),
    ("中毒剂量", "toxic dose"),
    ("阈剂量", "threshold dose"),
    ("浓度", "concentration"),
    ("血浆浓度", "plasma concentration"),
    ("血药浓度", "plasma drug concentration"),
    ("有效浓度", "effective concentration"),
    ("中毒浓度", "toxic concentration"),
    ("稳态浓度", "steady-state concentration"),
    ("峰浓度", "peak concentration"),
    ("谷浓度", "trough concentration"),
    ("肺泡浓度", "alveolar concentration"),
    ("脑内浓度", "brain concentration"),
    ("最低肺泡有效浓度", "minimum alveolar concentration (MAC)"),
    ("用药", "use / administration"),
    ("用量", "dosage / amount used"),
    ("药量", "drug dose / amount"),
    ("用量不得超过", "the dose must not exceed"),
    ("给药量", "administered dose"),
    ("总剂量", "total dose"),
    ("日剂量", "daily dose"),
    ("单次剂量", "single dose"),
    ("分次小剂量", "divided small doses"),
    ("分次给药", "divided doses"),

    # ═══════════════════════════════════════════════════════════════
    # TIME-RELATED
    # ═══════════════════════════════════════════════════════════════
    ("起效时间", "onset time"),
    ("达峰时间", "time to peak"),
    ("起效", "onset of action"),
    ("达峰", "peak / reach peak"),
    ("持续时间", "duration"),
    ("作用时间", "duration of action"),
    ("维持时间", "duration"),
    ("诱导时间", "induction time"),
    ("苏醒时间", "recovery time / emergence time"),
    ("半衰期", "half-life"),
    ("清除半衰期", "elimination half-life"),
    ("小时", "hours"),
    ("分钟", "minutes"),
    ("秒", "seconds"),
    ("天", "days"),
    ("周", "weeks"),
    ("月", "months"),
    ("年", "years"),
    ("24小时内", "within 24 hours"),
    ("24 h内", "within 24 hours"),
    ("短时间内", "within a short time"),
    ("长期", "long-term"),
    ("短期", "short-term"),
    ("急性", "acute"),
    ("慢性", "chronic"),
    ("亚急性", "subacute"),
    ("急性期", "acute phase"),
    ("慢性期", "chronic phase"),
    ("恢复期", "recovery phase"),
    ("潜伏期", "incubation period / latent period"),
    ("诱导期", "induction period"),
    ("麻醉期", "anesthesia period"),
    ("围手术期", "perioperative period"),
    ("术前", "preoperative"),
    ("术中", "intraoperative"),
    ("术后", "postoperative"),

    # ═══════════════════════════════════════════════════════════════
    # NUMBERS & UNITS
    # ═══════════════════════════════════════════════════════════════
    ("一个大气压", "one atmosphere"),
    ("大气压", "atmosphere"),
    ("倍", "times / -fold"),
    ("百分之", "percent"),
    ("个", " "),
    ("次", "times / episodes"),
    ("mol", "mol"),
    ("vol%", "vol%"),
    ("°C", "degree C"),
    ("℃", "degree C"),
    ("mg", "mg"),
    ("min", "min"),
    ("t1/2", "half-life (t1/2)"),

    # ═══════════════════════════════════════════════════════════════
    # QUESTION METADATA / MARKERS
    # ═══════════════════════════════════════════════════════════════
    ("【简答题】", ""),
    ("（多选）", " (Select all that apply)"),
    ("（单选）", ""),
    ("【", ""),
    ("】", ""),
    ("简答题", "Short-answer / Multiple Choice"),
    ("单选题", "Single Choice"),
    ("是非题", "True/False"),

    # ═══════════════════════════════════════════════════════════════
    # DRUG NAMES / TERMS that are single chars or short - place LAST
    # ═══════════════════════════════════════════════════════════════
    ("有机磷", "organophosphorus"),
    ("激动药", "agonist"),
    ("阻断药", "antagonist / blocker"),
    ("抑制药", "inhibitor"),
    ("复活药", "reactivator"),
    ("麻醉药", "anesthetic"),
    ("镇痛药", "analgesic"),
    ("肌松药", "muscle relaxant"),
    ("镇静药", "sedative"),
    ("局麻药", "local anesthetic"),
    ("全麻药", "general anesthetic"),
    ("抗胆碱药", "anticholinergic drug"),
    ("拟胆碱药", "cholinomimetic drug"),
    ("拟交感药", "sympathomimetic drug"),
    ("抗交感药", "sympatholytic drug"),
    ("利尿药", "diuretic"),
    ("抗生素", "antibiotic"),
    ("糖皮质激素", "glucocorticoid"),
    ("激素", "hormone"),
    ("避孕药", "contraceptive"),
    ("抗凝药", "anticoagulant"),
    ("降压药", "antihypertensive"),
    ("升压药", "vasopressor"),
    ("平喘药", "antiasthmatic"),
    ("解痉药", "antispasmodic"),
    ("扩瞳药", "mydriatic"),
    ("缩瞳药", "miotic"),

    # ── Short common words ──
    ("兴奋作用", "stimulatory effect"),
    ("抑制作用", "inhibitory effect"),
    ("阻断作用", "blocking effect"),
    ("麻痹作用", "paralytic effect"),
    ("麻醉作用", "anesthetic effect"),
    ("镇痛作用", "analgesic effect"),
    ("镇静作用", "sedative effect"),
    ("抗焦虑作用", "anxiolytic effect"),
    ("肌肉松弛作用", "muscle relaxant effect"),
    ("拟交感活性", "sympathomimetic activity"),
    ("作用", "effect / action"),
    ("活性", "activity"),
    ("记住缺失", "memory loss / amnesia"),
    ("记忆缺失", "amnesia"),
    ("意识丧失", "loss of consciousness"),
    ("反射消失", "loss of reflexes"),
    ("运动麻痹", "motor paralysis"),
    ("感觉麻痹", "sensory paralysis"),
    ("气道刺激", "airway irritation"),
    ("呼吸道刺激", "respiratory tract irritation"),
    ("呼吸频率", "respiratory rate"),
    ("潮气量", "tidal volume"),
    ("分钟通气量", "minute ventilation"),
    ("屏气", "breath-holding"),
    ("嗜睡", "drowsiness"),
    ("困倦", "fatigue / drowsiness"),
    ("多梦", "frequent dreaming"),
    ("少梦", "reduced dreaming"),
    ("快速眼动睡眠", "REM sleep"),
    ("失眠", "insomnia"),
    ("遗忘", "forgetfulness / amnesia"),
    ("恶心", "nausea"),
    ("呕吐", "vomiting"),
    ("腹泻", "diarrhea"),
    ("便秘", "constipation"),
    ("腹痛", "abdominal pain"),
    ("发热", "fever"),
    ("厌食", "anorexia"),
    ("食欲", "appetite"),
    ("黄疸", "jaundice"),
    ("皮疹", "rash"),
    ("荨麻疹", "urticaria"),
    ("瘙痒", "pruritus"),
    ("多汗", "diaphoresis / excessive sweating"),
    ("流涎", "salivation"),
    ("流泪", "lacrimation"),
    ("瞳孔缩小", "miosis"),
    ("瞳孔扩大", "mydriasis"),
    ("视物模糊", "blurred vision"),
    ("口干", "dry mouth"),
    ("皮肤干燥", "dry skin"),
    ("颜面潮红", "facial flushing"),
    ("皮肤潮红", "skin flushing"),
    ("震颤", "tremor"),
    ("焦虑", "anxiety"),
    ("惊厥", "convulsions / seizures"),
    ("痉挛", "spasm"),
    ("强直", "rigidity"),
    ("瘫痪", "paralysis"),
    ("昏迷", "coma"),
    ("晕厥", "syncope"),
    ("心悸", "palpitation"),
    ("心悸动", "palpitation"),
    ("休克", "shock"),
    ("死亡", "death"),
    ("咳嗽", "cough"),
    ("喷嚏", "sneeze"),
    ("窒息", "asphyxia"),
    ("肺水肿", "pulmonary edema"),
    ("呼吸窘迫", "respiratory distress"),
    ("呼吸困难", "dyspnea"),
    ("肺通气", "pulmonary ventilation"),
    ("肺换气", "pulmonary gas exchange"),
    ("啰音", "rales / crackles"),
    ("肺部啰音", "pulmonary rales / crackles"),
    ("痰", "sputum"),
    ("分泌物", "secretions"),
    ("排尿", "urination"),
    ("尿潴留", "urinary retention"),
    ("尿失禁", "urinary incontinence"),
    ("排便", "defecation"),
    ("排气", "flatus"),
    ("腹胀", "abdominal distension"),
    ("腹气胀", "abdominal distension"),
    ("嗳气", "belching"),
    ("吞咽", "swallowing"),
    ("咀嚼", "mastication"),
    ("发声", "phonation"),
    ("发音", "articulation"),
    ("吞咽困难", "dysphagia"),
    ("发音困难", "dysarthria"),
    ("声音嘶哑", "hoarseness"),
    ("声带", "vocal cords"),
    ("喉", "larynx"),
    ("会厌", "epiglottis"),
    ("喉痉挛", "laryngospasm"),
    ("支气管收缩", "bronchoconstriction"),
    ("气雾吸入", "aerosol inhalation"),

    # ── Other clinical terms ──
    ("嗜酸粒细胞", "eosinophil"),
    ("嗜碱粒细胞", "basophil"),
    ("中性粒细胞", "neutrophil"),
    ("淋巴细胞", "lymphocyte"),
    ("单核细胞", "monocyte"),
    ("血小板", "platelet"),
    ("粒细胞", "granulocyte"),
    ("肥大细胞", "mast cell"),
    ("组胺", "histamine"),
    ("促组胺释放", "histamine release"),
    ("膜稳定作用", "membrane stabilizing effect"),
    ("膜稳定性", "membrane stabilizing property"),
    ("奎尼丁样作用", "quinidine-like effect"),
    ("局部作用", "local effect"),
    ("全身作用", "systemic effect"),
    ("中枢作用", "central effect"),
    ("外周作用", "peripheral effect"),
    ("直接作用", "direct effect"),
    ("间接作用", "indirect effect"),

    # ── Single characters for cleanup ──
    ("有", "has / have / there is"),
    ("无", "has no / without / lacks"),
    ("较", "relatively / comparatively"),
    ("更", "more / further"),
    ("最", "most / -est"),
    ("很", "very"),
    ("太", "too / excessively"),
    ("过", "overly / excessively"),
    ("极", "extremely"),
    ("也", "also / too"),
    ("再", "again / re-"),
    ("又", "again / also"),
    ("还", "still / also / yet"),
    ("就", "then / just / namely"),
    ("才", "only then / just"),
    ("只", "only / merely"),
    ("仅", "only / merely"),
    ("约", "approximately / about"),
    ("共", "total / in total / together"),
    ("各", "each / respectively"),
    ("每", "each / per"),
    ("本", "this / the present"),
    ("该", "this / the"),
    ("此", "this / the"),
    ("某", "a certain / some"),
    ("其他", "other"),
    ("其他药物", "other drugs"),
    ("另", "another / other"),
    ("同", "same / identical"),
    ("不同", "different"),
    ("相同", "same"),
    ("相反", "opposite / contrary"),
    ("而异", "varies depending on"),
    ("区别", "difference / distinction"),
    ("不同点", "difference / distinguishing feature"),
    ("共同点", "common feature / similarity"),
    ("异常", "abnormal / abnormality"),
    ("正常", "normal / normal level"),
    ("恶性", "malignant"),
    ("良性", "benign"),
    ("阳性", "positive"),
    ("阴性", "negative"),
    ("早期", "early stage / early"),
    ("晚期", "late stage / advanced"),
    ("末期", "end stage / terminal"),
    ("新生儿", "neonate / newborn"),
    ("婴儿", "infant"),
    ("儿童", "child / children / pediatric"),
    ("成人", "adult"),
    ("老年人", "elderly"),
    ("老人", "elderly"),
    ("男性", "male"),
    ("女性", "female"),
    ("患者", "patient"),
    ("动物", "animal"),
    ("正常人", "healthy individual"),
    ("志愿者", "volunteer"),
    ("健康人", "healthy individual"),
    ("遗传易感人群", "genetically susceptible population"),
    ("人群", "population / individuals"),
    ("个体", "individual"),
    ("常染色体异常", "autosomal abnormality"),
    ("遗传", "genetic / hereditary"),
    ("先天", "congenital"),
    ("后天", "acquired"),
    ("家族性", "familial"),
    ("散发性", "sporadic"),
    ("自发性", "spontaneous"),
    ("继发性", "secondary"),
    ("原发性", "primary"),
    ("获得性", "acquired"),

    # ── Organ/system function ──
    ("肝功能异常", "abnormal liver function"),
    ("肝细胞合成功能", "hepatocellular synthetic function"),
    ("肝微粒体酶活性", "hepatic microsomal enzyme activity"),
    ("细胞色素P450", "cytochrome P450"),
    ("肝脏代谢", "hepatic metabolism"),
    ("肾排泄", "renal excretion"),
    ("肺排泄", "pulmonary excretion"),
    ("经肾排出", "excreted via the kidneys"),
    ("经肺排出", "excreted via the lungs"),
    ("以原型排出", "excreted unchanged"),
    ("经肝脏代谢后排出", "excreted after hepatic metabolism"),
    ("从尿液中排出", "excreted in the urine"),
    ("从粪便排出", "excreted in the feces"),
    ("药品", "drug / pharmaceutical"),
    ("原药", "parent drug"),
    ("原型药物", "unchanged drug / parent compound"),
    ("活性代谢物", "active metabolite"),

    # ── Question answer patterns ──
    ("答案", "answer"),
    ("选项", "option"),
    ("作为", "as / serve as"),
    ("判断", "judge / determine"),
    ("是否", "whether or not"),
    ("以及", "and / as well as"),
    ("等多种", "and other"),
    ("分为", "divided into / classified into"),
    ("统称", "collectively referred to as"),
    ("分为两类", "divided into two categories"),
    ("分为三步", "divided into three steps"),
    ("分为以下几步", "divided into the following steps"),
    ("依次", "in sequence / successively"),
    ("顺序", "sequence / order"),
    ("过程", "process"),
    ("包括以下", "including the following"),
    ("归纳为", "summarized as"),
    ("综上所述", "in summary"),
    ("总之", "in summary / in conclusion"),
    ("因此", "therefore / thus / consequently"),
    ("所以", "so / therefore"),
    ("因为", "because / since / as"),
    ("由于", "due to / because of / owing to"),
    ("虽然", "although / though / while"),
    ("但是", "but / however"),
    ("然而", "however / nevertheless"),
    ("如果", "if"),
    ("如", "if / if the / such as / for example"),
    ("否则", "otherwise"),
    ("无论", "regardless of / no matter"),
    ("除非", "unless"),
    ("即使", "even if / even though"),
    ("尽管", "although / despite"),
    ("不论", "regardless of / whether"),
    ("不过", "however / but"),
    ("而且", "moreover / furthermore / and"),
    ("并且", "and / also / moreover"),
    ("不仅", "not only"),
    ("同样", "likewise / similarly"),
    ("此外", "furthermore / in addition"),
    ("另外", "additionally / in addition"),
    ("例如", "for example / e.g."),
    ("比方", "for example"),
    ("特别是", "in particular / especially"),
    ("典型", "typical / classic"),
    ("常见", "common / commonly seen"),
    ("经典", "classic / classical"),
    ("严重", "severe / serious"),
    ("轻重", "severity"),
    ("轻重程度", "degree of severity"),
    ("好转", "improve / improvement"),
    ("恶化", "deteriorate / worsen"),
    ("加重", "aggravate / worsen"),
    ("缓解", "relieve / alleviate"),
    ("不缓解", "not relieved / persistent"),
    ("治愈", "cure"),
    ("康复", "recovery / rehabilitation"),
    ("复发", "recurrence / relapse"),
    ("预后", "prognosis"),
    ("病死率", "case fatality rate / mortality rate"),

    # ── Writing / educational terms ──
    ("教材", "textbook"),
    ("指出", "indicates / points out"),
    ("强调", "emphasize / emphasis"),
    ("提示", "suggest / indicate"),
    ("注意", "note / note that / pay attention"),
    ("记住", "remember / memorize"),
    ("了解", "understand / know"),
    ("掌握", "master / grasp"),
    ("考核", "assessment / examination"),
    ("考点", "key point / exam focus"),
    ("区别", "distinguish / differentiate"),
    ("鉴别", "differentiate / distinguish"),
    ("记忆", "memory / memorize"),
    ("口诀", "mnemonic"),
    ("总结", "summary / summarize"),
    ("归纳", "summarize / generalization"),
    ("分类", "classification / classify"),
    ("特点", "characteristics / features"),
    ("优点", "advantage"),
    ("缺点", "disadvantage / drawback"),
    ("优劣", "advantages and disadvantages"),
    ("重要性", "importance / significance"),
    ("临床意义", "clinical significance"),
    ("指导意义", "guiding significance"),
    ("参考价值", "reference value"),
    ("评估", "evaluate / assess / assessment"),
    ("辅助指标", "auxiliary indicator"),
    ("指标", "indicator / index / parameter"),
    ("参数", "parameter"),
    ("金标准", "gold standard"),
    ("替代指标", "surrogate endpoint"),
    ("实验室检查", "laboratory test"),
    ("辅助检查", "auxiliary examination"),
    ("物理检查", "physical examination"),
    ("影像学", "imaging"),
    ("心电图", "electrocardiogram (ECG)"),
    ("超声", "ultrasound"),
    ("X线", "X-ray"),
    ("CT", "CT"),
    ("MRI", "MRI"),

    # ── Special considerations ──
    ("联合应用", "combined use / coadministration"),
    ("配伍禁忌", "incompatibility"),
    ("药物相互作用", "drug interaction"),
    ("相互作用", "interaction"),
    ("相加作用", "additive effect"),
    ("协同作用", "synergistic effect"),
    ("拮抗作用", "antagonistic effect"),
    ("增强作用", "potentiating effect"),
    ("无关", "unrelated / not related"),
    ("有关", "related / associated"),
    ("相反", "opposite"),
    ("相符", "consistent with"),
    ("符合", "consistent with / in accordance with"),
    ("矛盾", "contradictory / conflicting"),
    ("不一致", "inconsistent / discordant"),
    ("一致性", "consistency"),
    ("可比性", "comparability"),
    ("不适用", "not applicable"),
    ("不适宜", "not suitable / inappropriate"),
    ("适宜", "suitable / appropriate"),
    ("可用于", "can be used for"),
    ("不可用于", "cannot be used for"),
    ("不宜用于", "should not be used for"),

    # ── Critical compound organ/symptom terms ──
    ("心脏", "heart"),
    ("血管", "blood vessels"),
    ("症状", "symptoms"),
    ("病情", "disease condition"),
    ("肌力", "muscle strength"),
    ("肌无力", "muscle weakness"),
    ("肌张力", "muscle tone"),
    ("肌纤维", "muscle fiber"),
    ("骨骼肌纤维", "skeletal muscle fiber"),
    ("肌束", "muscle bundle"),
    ("神经肌肉传递", "neuromuscular transmission"),
    ("神经肌肉", "neuromuscular"),
    ("运动功能", "motor function"),
    ("感觉功能", "sensory function"),
    ("认知功能", "cognitive function"),
    ("记忆功能", "memory function"),
    ("学习能力", "learning ability"),
    ("工作记忆", "working memory"),
    ("长期记忆", "long-term memory"),
    ("短期记忆", "short-term memory"),
    ("空间记忆", "spatial memory"),
    ("情景记忆", "episodic memory"),
    ("语义记忆", "semantic memory"),
    ("程序性记忆", "procedural memory"),
    ("陈述性记忆", "declarative memory"),
    ("记忆巩固", "memory consolidation"),
    ("记忆障碍", "memory impairment"),
    ("记忆缺失", "amnesia / memory loss"),
    ("认知障碍", "cognitive impairment"),
    ("行为障碍", "behavioral disorder"),
    ("精神障碍", "mental disorder"),
    ("情绪障碍", "mood disorder"),
    ("焦虑症", "anxiety disorder"),
    ("抑郁症", "depression"),
    ("精神分裂症", "schizophrenia"),
    ("双相障碍", "bipolar disorder"),
    ("注意缺陷多动障碍", "attention deficit hyperactivity disorder (ADHD)"),
    ("自闭症", "autism"),
    ("睡眠障碍", "sleep disorder"),
    ("快速眼动睡眠", "REM sleep"),
    ("非快速眼动睡眠", "non-REM sleep"),
    ("慢波睡眠", "slow-wave sleep"),
    ("失眠", "insomnia"),
    ("嗜睡症", "narcolepsy"),
    ("镇静催眠", "sedative-hypnotic"),
    ("疼痛", "pain"),
    ("慢性疼痛", "chronic pain"),
    ("急性疼痛", "acute pain"),
    ("神经病理性疼痛", "neuropathic pain"),
    ("炎性疼痛", "inflammatory pain"),
    ("癌性疼痛", "cancer pain"),
    ("内脏痛", "visceral pain"),
    ("躯体痛", "somatic pain"),
    ("牵涉痛", "referred pain"),
    ("痛觉过敏", "hyperalgesia"),
    ("痛觉超敏", "allodynia"),
    ("痛觉减退", "hypoalgesia"),
    ("镇痛", "analgesia"),
    ("抗炎", "anti-inflammatory"),
    ("解热", "antipyretic"),
    ("解热镇痛", "antipyretic-analgesic"),
    ("消化系统", "digestive system"),
    ("呼吸系统", "respiratory system"),
    ("循环系统", "circulatory system"),
    ("心血管系统", "cardiovascular system"),
    ("泌尿系统", "urinary system"),
    ("生殖系统", "reproductive system"),
    ("内分泌系统", "endocrine system"),
    ("免疫系统", "immune system"),
    ("淋巴系统", "lymphatic system"),
    ("造血系统", "hematopoietic system"),
    ("骨骼系统", "skeletal system"),
    ("肌内", "intramuscular"),
    ("肌肉注射", "intramuscular injection"),
    ("肌肉松弛", "muscle relaxation"),
    ("肌肉松弛剂", "muscle relaxant"),
    ("肌肉松弛作用", "muscle relaxant effect"),
    ("肌肉麻痹", "muscle paralysis"),
    ("肌松", "muscle relaxation"),
    ("神经传导", "nerve conduction"),
    ("神经冲动传导", "nerve impulse conduction"),
    ("神经传递", "neurotransmission"),
    ("突触传递", "synaptic transmission"),
    ("突触间隙", "synaptic cleft"),
    ("突触囊泡", "synaptic vesicle"),
    ("神经递质", "neurotransmitter"),
    ("神经调质", "neuromodulator"),
    ("神经肽", "neuropeptide"),
    ("兴奋性递质", "excitatory neurotransmitter"),
    ("抑制性递质", "inhibitory neurotransmitter"),
    ("谷氨酸", "glutamate"),
    ("天冬氨酸", "aspartate"),
    ("甘氨酸", "glycine"),
    ("牛磺酸", "taurine"),
    ("一氧化氮", "nitric oxide"),
    ("一氧化碳", "carbon monoxide"),
    ("硫化氢", "hydrogen sulfide"),
    ("腺苷", "adenosine"),
    ("ATP", "ATP"),
    ("ADP", "ADP"),
    ("AMP", "AMP"),
    ("cAMP", "cAMP"),
    ("cGMP", "cGMP"),
    ("IP3", "IP3"),
    ("DAG", "DAG"),
    ("PIP2", "PIP2"),
    ("钙离子", "calcium ion"),
    ("钠离子", "sodium ion"),
    ("钾离子", "potassium ion"),
    ("氯离子", "chloride ion"),
    ("氢离子", "hydrogen ion / proton"),
    ("镁离子", "magnesium ion"),
    ("铁离子", "iron ion"),
    ("锌离子", "zinc ion"),
    ("钙调蛋白", "calmodulin"),
    ("钙调神经磷酸酶", "calcineurin"),
    ("蛋白激酶A", "protein kinase A (PKA)"),
    ("蛋白激酶C", "protein kinase C (PKC)"),
    ("蛋白激酶G", "protein kinase G (PKG)"),
    ("酪氨酸激酶", "tyrosine kinase"),
    ("丝氨酸/苏氨酸激酶", "serine/threonine kinase"),
    ("磷酸酶", "phosphatase"),
    ("磷酸二酯酶", "phosphodiesterase"),
    ("腺苷酸环化酶", "adenylyl cyclase"),
    ("鸟苷酸环化酶", "guanylyl cyclase"),
    ("磷脂酶C", "phospholipase C"),
    ("磷脂酶A2", "phospholipase A2"),
    ("环氧合酶", "cyclooxygenase (COX)"),
    ("脂氧合酶", "lipoxygenase"),
    ("一氧化氮合酶", "nitric oxide synthase (NOS)"),
    ("超氧化物歧化酶", "superoxide dismutase (SOD)"),
    ("过氧化氢酶", "catalase"),
    ("谷胱甘肽过氧化物酶", "glutathione peroxidase"),
    ("单胺氧化酶", "monoamine oxidase (MAO)"),
    ("儿茶酚氧位甲基转移酶", "catechol-O-methyltransferase (COMT)"),

    # ── Critical missing general terms ──
    ("骨骼肌", "skeletal muscle"),
    ("平滑肌", "smooth muscle"),
    ("心肌", "cardiac muscle"),
    ("横纹肌", "striated muscle"),
    ("神经元", "neurons"),
    ("运动神经", "motor nerve"),
    ("感觉神经", "sensory nerve"),
    ("胆碱能神经", "cholinergic nerve"),
    ("肾上腺素能神经", "adrenergic nerve"),
    ("神经纤维", "nerve fiber"),
    ("有髓鞘", "myelinated"),
    ("无髓鞘", "unmyelinated"),
    ("节后纤维", "postganglionic fiber"),
    ("节前纤维", "preganglionic fiber"),
    ("化学结构", "chemical structure"),
    ("基本化学结构", "basic chemical structure"),
    ("基本结构", "basic structure"),
    ("分子结构", "molecular structure"),
    ("空间结构", "spatial structure"),
    ("立体结构", "three-dimensional structure"),
    ("血管", "blood vessel"),
    ("毛细管", "capillary"),
    ("小动脉", "arteriole"),
    ("小静脉", "venule"),
    ("动脉", "artery"),
    ("静脉", "vein"),
    ("细胞", "cell"),
    ("组织", "tissue"),
    ("器官", "organ"),
    ("系统", "system"),
    ("分子", "molecule"),
    ("离子", "ion"),
    ("原子", "atom"),
    ("电子", "electron"),
    ("质子", "proton"),
    ("自由基", "free radical"),
    ("物质", "substance"),
    ("成分", "component"),
    ("元素", "element"),
    ("化合物", "compound"),
    ("衍生物", "derivative"),
    ("异构体", "isomer"),
    ("同分异构体", "isomer"),
    ("左旋异构体", "levorotatory isomer"),
    ("右旋异构体", "dextrorotatory isomer"),
    ("消旋体", "racemic mixture"),
    ("高", "high"),
    ("低", "low"),
    ("强", "potent / strong"),
    ("弱", "weak"),
    ("大", "large"),
    ("小", "small"),
    ("快", "fast"),
    ("慢", "slow"),
    ("多", "many"),
    ("少", "few / little"),
    ("新", "new"),
    ("旧", "old"),
    ("好", "good"),
    ("差", "poor"),
    ("容易", "easy"),
    ("困难", "difficult"),
    ("简单", "simple"),
    ("复杂", "complex"),
    ("重要", "important"),
    ("必要", "necessary"),
    ("基础", "basic / fundamental"),
    ("关键", "key / critical"),
    ("核心", "core / central"),
    ("主要", "main / primary"),
    ("次要", "secondary"),
    ("主要表现", "main manifestation"),
    ("主要区别", "main difference"),
    ("重要区别", "important difference"),
    ("显著性差异", "significant difference"),
    ("本质区别", "essential difference"),
    ("根本区别", "fundamental difference"),
    ("类似于", "similar to"),
    ("不同于", "different from"),
    ("优于", "superior to"),
    ("次于", "inferior to"),
    ("多于", "more than"),
    ("少于", "less than"),
    ("大于", "greater than"),
    ("小于", "less than"),
    ("接近", "close to / near"),
    ("远离", "far from"),
    ("快于", "faster than"),
    ("慢于", "slower than"),
    ("强于", "stronger than"),
    ("弱于", "weaker than"),
    ("等于", "equal to"),
    ("约等于", "approximately equal to"),
    ("不亚于", "no less than"),
    ("不低于", "not lower than"),
    ("不高于", "not higher than"),
    ("目前", "currently"),
    ("过去", "in the past / previously"),
    ("将来", "in the future"),
    ("以前", "previously / before"),
    ("以后", "afterward / later"),
    ("至今", "to date"),
    ("迄今", "to date / so far"),
    ("至今为止", "to date"),
    ("一直以来", "historically / consistently"),
    ("逐渐", "gradually"),
    ("逐步", "step by step / progressively"),
    ("慢慢", "slowly"),
    ("快快", "quickly"),
    ("立即", "immediately"),
    ("马上", "immediately / at once"),
    ("迅速", "rapidly"),
    ("快速", "rapid / fast"),
    ("均", "all / uniformly"),
    ("都", "all"),
    ("也", "also"),
    ("还", "also / still"),
    ("仅", "only"),
    ("只", "only"),
    ("中", "in / among / medium"),
    ("内", "within / inside"),
    ("外", "outside / external"),
    ("上", "above / upper / on"),
    ("下", "below / lower / under"),
    ("前", "before / anterior / front"),
    ("后", "after / posterior / rear"),
    ("左", "left"),
    ("右", "right"),
    ("单", "single / mono-"),
    ("双", "double / bi- / dual"),
    ("三", "three / tri-"),
    ("四", "four / tetra-"),
    ("多", "multiple / poly-"),
    ("半", "half / semi-"),
    ("全", "full / total / pan-"),
    ("超", "ultra / super / hyper-"),
    ("亚", "sub- / hypo-"),
    ("抗", "anti-"),
    ("非", "non-"),
    ("无", "no / without / a-"),
    ("有", "with / has"),
    ("含", "containing"),
    ("富含", "rich in"),
    ("缺乏", "deficient in"),
    ("过多", "excessive"),
    ("过少", "insufficient"),
    ("过度", "excessive / over-"),
    ("不足", "insufficient / inadequate"),
    ("正常", "normal"),
    ("异常", "abnormal"),
    ("典型", "typical"),
    ("非典型", "atypical"),
    ("理想", "ideal"),
    ("最佳", "optimal"),
    ("适宜", "appropriate / suitable"),
    ("不适宜", "inappropriate / unsuitable"),
    ("充足", "sufficient / adequate"),
    ("不足", "insufficient / inadequate"),
    ("广泛", "widespread / extensive"),
    ("局限", "localized / limited"),
    ("普遍", "universal / general"),
    ("特殊", "special / particular"),
    ("特定", "specific / particular"),
    ("一般", "general / common"),
    ("个别", "individual / occasional"),
    ("部分", "part / partial / some"),
    ("大部分", "most / the majority of"),
    ("小部分", "a small part / minority of"),
    ("全部", "all / entire / whole"),
    ("一半", "half"),
    ("三分之一", "one third"),
    ("四分之一", "one quarter"),
    ("一定", "certain / definite / a given"),
    ("可能", "possible / may"),
    ("必然", "inevitable / certain"),
    ("偶然", "accidental / occasional"),
    ("经常", "often / frequently"),
    ("偶尔", "occasionally"),
    ("总是", "always"),
    ("从不", "never"),
    ("首次", "first / initial"),
    ("再次", "again / re-"),
    ("反复", "repeatedly"),
    ("持续", "continuous / persistent"),
    ("间断", "intermittent"),
    ("一次性", "single-use / one-time"),
    ("多次", "multiple / repeated"),
    ("一次", "once / one time"),
    ("两次", "twice"),
    ("三次", "three times"),
    ("每次", "each time / per dose"),
    ("一日", "once daily"),
    ("每日三次", "three times daily"),
    ("每日一次", "once daily"),
    ("必要时", "as needed / when necessary"),
    ("按需", "as needed"),
    ("务必", "must / be sure to"),
    ("千万", "absolutely / by all means"),
    ("切勿", "never / do not"),
    ("严禁", "strictly prohibited"),
    ("推荐", "recommended"),
    ("建议", "suggested / recommended"),
    ("常规", "routine / conventional"),
    ("常用", "commonly used / common"),
    ("罕用", "rarely used"),
    ("备用", "reserve / backup"),
    ("替用", "alternative / substitute"),
    ("首选", "first-line / first choice"),
    ("二线", "second-line"),
    ("三线", "third-line"),
    ("用作", "used as"),
    ("充当", "serve as / act as"),
    ("视为", "regarded as / considered"),
    ("看作", "viewed as"),
    ("当作", "treated as"),
    ("被认为", "is considered / regarded"),
    ("被看作", "is viewed as"),
    ("被当作", "is treated as"),
    ("被发现", "was found / discovered"),
    ("被证明", "was proven / demonstrated"),
    ("被报道", "was reported"),
    ("被证实", "was confirmed"),
    ("被认为是", "is considered to be"),
    ("不认为是", "is not considered"),
    ("被误认为", "is mistaken for"),
    ("与---比较", "compared with"),
    ("与---相比", "compared with"),
    ("比较", "compared with / comparison"),
    ("前者", "the former"),
    ("后者", "the latter"),
    ("两者", "both / the two"),
    ("三者", "all three / the three"),
    ("之间", "between"),
    ("之中", "among"),
    ("之一", "one of"),
    ("之二", "two of"),
    ("之三", "three of"),
    ("之一", "one of"),
    ("等", "etc."),
    ("---等", ", etc."),
    ("如", "such as"),
    ("例如", "for example"),
    ("即", "i.e."),
    ("等等", "etc."),
    ("所谓", "so-called"),
    ("换句话说", "in other words"),
    ("也就是说", "that is to say"),
    ("简而言之", "in short / briefly"),
    ("总而言之", "in summary"),
    ("总的来讲", "overall / in general"),
    ("综上所述", "in summary"),
    ("通过以下", "through the following"),
    ("如下", "as follows"),
    ("具体如下", "specifically as follows"),
    ("如下所述", "as described below"),
    ("如上所述", "as described above"),
    ("如前所述", "as previously described"),
    ("详见", "see details in / for details see"),
    ("参考", "refer to / see"),
    ("据介绍", "according to reports"),
    ("据报道", "according to reports"),
    ("据文献", "according to the literature"),
    ("据统计", "according to statistics"),
    ("资料显示", "data show / evidence indicates"),
    ("研究表明", "studies show / research indicates"),
    ("实验证明", "experiments demonstrate"),
    ("临床观察", "clinical observation"),
    ("临床试验", "clinical trial"),
    ("流行病学", "epidemiology"),
    ("荟萃分析", "meta-analysis"),
    ("系统评价", "systematic review"),
    ("循证医学", "evidence-based medicine"),
    ("随机对照试验", "randomized controlled trial"),
    ("大样本", "large sample"),
    ("小样本", "small sample"),
    ("多中心", "multicenter"),
    ("单中心", "single-center"),
    ("双盲", "double-blind"),
    ("安慰剂", "placebo"),
    ("对照", "control / controlled"),
    ("实验组", "experimental group"),
    ("对照组", "control group"),
    ("观察组", "observation group"),
    ("模型组", "model group"),
    ("给药组", "treatment group / drug group"),
    ("空白组", "blank group"),
    ("假手术组", "sham operation group"),
    ("预处理", "pretreatment"),
    ("预给药", "preadministration"),
    ("预注射", "preinjection"),
    ("预处理组", "pretreatment group"),
    ("分为", "divided into"),
    ("分为两组", "divided into two groups"),
    ("分为三组", "divided into three groups"),
    ("将---分为", "divide --- into"),
    ("属于", "belongs to"),
    ("不属于", "does not belong to"),
    ("包括", "includes"),
    ("不包括", "does not include"),
    ("含有", "contains"),
    ("富含", "rich in"),
    ("涉及", "involves"),
    ("涵盖", "covers / encompasses"),
    ("局限于", "limited to"),
    ("扩大到", "expanded to"),
    ("可导致", "can lead to"),
    ("可致", "can cause"),
    ("可引起", "can induce"),
    ("可产生", "can produce"),
    ("可诱发", "can provoke"),
    ("可加重", "can aggravate"),
    ("可减轻", "can alleviate"),
    ("可缓解", "can relieve"),
    ("可改善", "can improve"),
    ("可恢复", "can restore"),
    ("可促进", "can promote"),
    ("可抑制", "can inhibit"),
    ("可阻断", "can block"),
    ("可增强", "can enhance"),
    ("可减弱", "can weaken"),
    ("可加快", "can accelerate"),
    ("可减慢", "can slow"),
    ("可增加", "can increase"),
    ("可减少", "can reduce"),
    ("可升高", "can elevate"),
    ("可降低", "can lower"),
    ("可延长", "can prolong"),
    ("可缩短", "can shorten"),
    ("可保持", "can maintain"),
    ("可预防", "can prevent"),
    ("可治疗", "can treat"),
    ("可诊断", "can diagnose"),
    ("可监测", "can monitor"),
    ("可检测", "can detect"),
    ("可测", "measurable / can be measured"),
    ("不可测", "unmeasurable / cannot be measured"),
    ("可见", "visible / can be seen"),
    ("不可见", "invisible"),
    ("可逆", "reversible"),
    ("不可逆", "irreversible"),
    ("可溶", "soluble"),
    ("不可溶", "insoluble"),
    ("稳定", "stable"),
    ("不稳定", "unstable"),
    ("易", "easily / prone to"),
    ("不易", "not easily"),
    ("难", "difficult to / resistant to"),
    ("好", "well / good"),
    ("不好", "poorly / not well"),
    ("良", "good / benign"),
    ("恶", "malignant / bad"),
    ("对---有效", "effective against / effective for"),
    ("对---无效", "ineffective against"),
    ("对---敏感", "sensitive to"),
    ("对---耐药", "resistant to"),
    ("对---过敏", "allergic to"),
    ("对---有作用", "has an effect on"),
    ("对---无作用", "has no effect on"),
    ("在---条件下", "under --- conditions"),
    ("在---情况下", "in the case of / under --- circumstances"),
    ("在---同时", "while / at the same time as"),
    ("在---之前", "before / prior to"),
    ("在---之后", "after / following"),
    ("在---期间", "during"),
    ("在---基础加用", "added on top of ---"),
    ("基于", "based on"),
    ("依据", "according to / based on"),
    ("根据不同", "depending on / according to different"),
    ("视---而定", "depending on / determined by"),
    ("随---而变化", "varies with"),
    ("随---增加而", "increases with / as --- increases"),
    ("随---减少而", "decreases with / as --- decreases"),
    ("呈", "presents as / shows"),
    ("呈---性", "shows a --- pattern / nature"),
    ("呈---状", "appears --- / presents as ---"),
    ("呈正比", "is directly proportional"),
    ("呈反比", "is inversely proportional"),
    ("呈线性", "is linear"),
    ("呈非线性", "is nonlinear"),
    ("呈剂量依赖性", "is dose-dependent"),
    ("呈时间依赖性", "is time-dependent"),
    ("呈浓度依赖性", "is concentration-dependent"),
    ("呈pH依赖性", "is pH-dependent"),
    ("呈温度依赖性", "is temperature-dependent"),
    ("无明显的", "without obvious"),
    ("伴有", "accompanied by / with"),
    ("不伴有", "without / not accompanied by"),
    ("合并", "combined with / concurrent"),
    ("伴有或不伴有", "with or without"),
    ("合并或不合并", "with or without concurrent"),
    ("同时伴有", "simultaneously accompanied by"),
    ("另外还有", "additionally there is/are"),
    ("除此之外", "apart from this / besides"),
    ("与此同时", "at the same time / meanwhile"),
    ("与此相反", "in contrast / on the contrary"),
    ("相对来说", "relatively speaking"),
    ("相对而言", "relatively / comparatively"),
    ("相比之下", "by comparison / in contrast"),
    ("对比之下", "in contrast / by comparison"),
    ("在大多数情况下", "in most cases"),
    ("在少数情况下", "in a few cases"),
    ("在极少数情况下", "in very rare cases"),
    ("在极端情况下", "in extreme cases"),
    ("在最佳条件下", "under optimal conditions"),
    ("在实际应用中", "in clinical practice"),
    ("在临床实践中", "in clinical practice"),
    ("在实验条件下", "under experimental conditions"),
    ("在体外", "in vitro"),
    ("在体内", "in vivo"),
    ("在体实验", "in vivo experiment"),
    ("离体实验", "in vitro experiment"),
    ("动物实验", "animal experiment"),
    ("人体试验", "human trial"),
    ("临床试验", "clinical trial"),
    ("患者", "patient"),
    ("健康志愿者", "healthy volunteer"),
    ("健康受试者", "healthy subject"),
    ("病例报告", "case report"),
    ("病例系列", "case series"),
    ("队列研究", "cohort study"),
    ("病例对照研究", "case-control study"),
    ("横断面研究", "cross-sectional study"),
    ("回顾性研究", "retrospective study"),
    ("前瞻性研究", "prospective study"),
    ("随访", "follow-up"),
    ("长期随访", "long-term follow-up"),
    ("短期随访", "short-term follow-up"),
    ("预后", "prognosis"),
    ("转归", "outcome"),
    ("结局", "outcome / endpoint"),
    ("主要结局", "primary outcome"),
    ("次要结局", "secondary outcome"),
    ("替代结局", "surrogate outcome"),
    ("硬终点", "hard endpoint"),
    ("软终点", "soft endpoint"),
    ("复合终点", "composite endpoint"),
    ("安全性", "safety"),
    ("有效性", "efficacy"),
    ("耐受性", "tolerability"),
    ("依从性", "compliance / adherence"),
    ("生活质量", "quality of life"),
    ("生存率", "survival rate"),
    ("无进展生存", "progression-free survival"),
    ("总生存", "overall survival"),
    ("无病生存", "disease-free survival"),
    ("缓解率", "remission rate"),
    ("有效率", "response rate"),
    ("控制率", "control rate"),
    ("治愈率", "cure rate"),
    ("复发率", "recurrence rate"),
    ("转移率", "metastasis rate"),
    ("致残率", "disability rate"),
    ("致死率", "fatality rate"),
    ("发病率", "incidence"),
    ("患病率", "prevalence"),
    ("死亡率", "mortality"),
    ("病死率", "case fatality rate"),
    ("出生率", "birth rate"),
    ("人群", "population"),
    ("样本", "sample"),
    ("标本", "specimen / sample"),
    ("取样", "sampling"),
    ("采血", "blood collection"),
    ("采尿", "urine collection"),
    ("粪便", "feces"),
    ("痰液", "sputum"),
    ("脑脊液", "cerebrospinal fluid"),
    ("胸水", "pleural effusion"),
    ("腹水", "ascites"),
    ("滑液", "synovial fluid"),
    ("渗出液", "exudate"),
    ("漏出液", "transudate"),
    ("细胞外液", "extracellular fluid"),
    ("细胞内液", "intracellular fluid"),
    ("组织间液", "interstitial fluid"),
    ("跨细胞液", "transcellular fluid"),
    ("体液", "body fluid"),
    ("内环境", "internal environment"),
    ("稳态", "homeostasis"),
    ("失衡", "imbalance / dysregulation"),
    ("紊乱", "disorder / disturbance"),
    ("障碍", "disorder / impairment"),
    ("衰竭", "failure"),
    ("不全", "insufficiency"),
    ("亢进", "hyperfunction / hyperactivity"),
    ("减退", "hypofunction / decline"),
    ("萎缩", "atrophy"),
    ("肥大", "hypertrophy"),
    ("增生", "hyperplasia"),
    ("化生", "metaplasia"),
    ("异型增生", "dysplasia"),
    ("坏死", "necrosis"),
    ("凋亡", "apoptosis"),
    ("自噬", "autophagy"),
    ("老化", "aging / senescence"),
    ("退化", "degeneration"),
    ("变性", "degeneration"),
    ("变质", "degeneration / alteration"),
    ("渗出", "exudation"),
    ("浸润", "infiltration"),
    ("增生", "proliferation"),
    ("纤维化", "fibrosis"),
    ("硬化", "sclerosis"),
    ("钙化", "calcification"),
    ("骨化", "ossification"),
    ("角化", "keratinization"),
    ("溃疡", "ulceration"),
    ("糜烂", "erosion"),
    ("穿孔", "perforation"),
    ("梗阻", "obstruction"),
    ("狭窄", "stenosis"),
    ("扩张", "dilatation"),
    ("破裂", "rupture"),
    ("出血", "bleeding / hemorrhage"),
    ("血栓", "thrombosis"),
    ("栓塞", "embolism"),
    ("梗塞", "infarction"),
    ("缺血", "ischemia"),
    ("淤血", "congestion"),
    ("水肿", "edema"),
    ("脱水", "dehydration"),
    ("休克", "shock"),
    ("发热", "fever"),
    ("炎症", "inflammation"),
    ("感染", "infection"),
    ("肿瘤", "tumor / neoplasm"),
    ("癌症", "cancer"),
    ("癌", "carcinoma"),
    ("肉瘤", "sarcoma"),
    ("淋巴瘤", "lymphoma"),
    ("白血病", "leukemia"),
    ("骨髓瘤", "myeloma"),
    ("转移", "metastasis"),
    ("复发", "recurrence"),
    ("缓解", "remission"),
    ("进展", "progression"),
    ("稳定", "stable"),
    ("部分缓解", "partial remission"),
    ("完全缓解", "complete remission"),
    ("轻微缓解", "minor remission"),
    ("无缓解", "no remission"),
    ("进展期", "advanced stage"),
    ("晚期", "advanced / late stage"),
    ("早期", "early stage"),
    ("中期", "intermediate stage"),
    ("终末期", "terminal stage"),
    ("手术", "surgery / operation"),
    ("放疗", "radiotherapy"),
    ("化疗", "chemotherapy"),
    ("靶向治疗", "targeted therapy"),
    ("免疫治疗", "immunotherapy"),
    ("基因治疗", "gene therapy"),
    ("细胞治疗", "cell therapy"),
    ("干细胞治疗", "stem cell therapy"),
    ("支持治疗", "supportive care"),
    ("姑息治疗", "palliative care"),
    ("康复治疗", "rehabilitation therapy"),
    ("物理治疗", "physical therapy"),
    ("心理治疗", "psychotherapy"),
    ("行为治疗", "behavioral therapy"),
    ("认知治疗", "cognitive therapy"),
    ("综合治疗", "comprehensive treatment"),
    ("个体化治疗", "personalized treatment"),
    ("精准医学", "precision medicine"),
    ("个体化医学", "personalized medicine"),
    ("转化医学", "translational medicine"),
    ("再生医学", "regenerative medicine"),
    ("整合医学", "integrative medicine"),
    ("补充医学", "complementary medicine"),
    ("替代医学", "alternative medicine"),
    ("传统医学", "traditional medicine"),
    ("现代医学", "modern medicine"),
    ("中医", "traditional Chinese medicine"),
    ("西医", "Western medicine"),
    ("中西医结合", "integrated Chinese and Western medicine"),

    # ── Remaining single chars (cleanup helpers -- last resort) ──
    # These are placed at the very end since they are shortest

    ("假性", "butyryl- (pseudo)"),
    ("真性", "acetyl- (true)"),
    ("脏", "organ"),
    ("症状", "symptom"),
    ("病情", "condition"),
    ("体征", "sign"),
    ("综合征", "syndrome"),
    ("征象", "sign"),
    ("综合征", "syndrome"),
    ("副作用少", "fewer side effects"),
    ("副作用多", "more side effects"),
    ("选择性高", "high selectivity"),
    ("选择性低", "low selectivity"),
    ("副作用低", "low side effects"),
    ("副作用更少", "even fewer side effects"),
    ("扩瞳", "mydriasis"),
    ("缩瞳", "miosis"),
    ("相似", "similar"),
    ("疲劳", "fatigue"),
    ("时相", "phase"),
    ("浅麻醉", "light anesthesia"),
    ("状态", "state"),
    ("效应", "effect"),
    ("间隙", "space"),
    ("变窄", "narrows"),
    ("阻碍", "obstructs"),
    ("回流", "outflow"),
    ("进一步", "further"),
    ("病情", "condition"),
    ("加重病情", "worsen the condition"),
    ("副作用", "side effect"),
    ("常规", "routine"),
    ("紧急", "emergency"),
    ("阻止", "prevents"),
    ("公认", "recognized"),
    ("相互作用", "interacts"),
    ("分类", "classification"),
    ("分为", "classified as"),
    ("两类", "two categories"),
    ("三类", "three categories"),
    ("一", "a"),
    ("两", "two"),
    ("几", "several"),
    ("些", ""),
    ("内", ""),
    ("催", "catalyzes"),
    ("化水解", "the hydrolysis of"),
    ("自行", "spontaneously"),
    ("若不", "if not"),
    ("及时", "promptly"),
    ("否则", "otherwise"),
    ("难以", "difficult to"),
    ("无法", "unable to"),
    ("优于", "superior to"),
    ("次于", "inferior to"),
    ("限于", "limited to"),
    ("力强", "potent"),
    ("力弱", "weak"),
    ("力", "potency"),
    ("频", "frequency"),
    ("率", "rate"),
    ("压", "pressure"),
    ("上升", "rises"),
    ("下降", "falls"),
    ("上升缓慢", "rises slowly"),
    ("平", "level"),
    ("便", "convenient"),
    ("特", "unique"),
    ("殊", "special"),
    ("需要", "requiring"),
    ("不需", "not requiring"),
    ("不需要", "does not require"),
    ("需特", "requiring special"),
    ("设备", "equipment"),
    ("不燃", "non-flammable"),
    ("烧、", ""),
    ("不爆", "non-explosive"),
    ("不爆", ""),
    ("炸、", ""),
    ("不污", "does not contaminate"),
    ("空气", "air"),
    ("手术室", "operating room"),
    ("完善", "complete"),
    ("良好", "good"),
    ("几乎无", "has almost no"),
    ("肌松", "muscle relaxant"),
    ("分", "stage"),
    ("期不", "not"),
    ("明显", "clear"),
    ("不明显", "unclear"),
    ("恢复快", "rapid recovery"),
    ("起效时间", "onset time"),
    ("效应达峰时间", "time to peak effect"),
    ("起效快", "rapid onset"),
    ("苏醒迅速", "rapid recovery"),
    ("苏醒", "recovery"),
    ("效价", "potency"),
    ("诱导迅速", "rapid induction"),
    ("诱导", "induction"),
    ("平稳", "smooth"),
    ("舒适", "comfortable"),
    ("迅", "rapid"),
    ("速", "rapid"),
    ("便", "and"),
    ("免", "prevent"),
    ("破坏", "damage"),
    ("酶", "enzyme"),
    ("型", "type"),
    ("类", "class"),
    ("位", "position"),
    ("意识", "consciousness"),
    ("药物", "agent"),
    ("升", "elevates"),
    ("降", "lowers"),
    ("升压", "pressor"),
    ("降压", "depressor"),
    ("体", "the body"),
    ("持久", "persistent"),
    ("减半", "halved"),
    ("睡前", "at bedtime"),
    ("前", "before"),
    ("临床", "clinical"),
    ("相关", "related"),
    ("完全阐明", "fully elucidated"),
    ("认", "believed"),
    ("取消", "abolished"),
    ("充分", "fully"),
    ("一般", "generally"),
    ("不", "not"),
    ("会", "may"),
    ("能", "can"),
    ("够", "sufficient"),
    ("需", "requires"),
    ("应", "should"),
    ("可", "can"),
    ("但", "but"),
    ("而", "whereas"),
    ("且", "and"),
    ("虽", "although"),
    ("然", ""),
    ("并", "and"),
    ("亦", "also"),
    ("略", "slightly"),
    ("稍", "slightly"),
    ("极", "extremely"),
    ("越", "the more"),
    ("非常", "very"),
    ("十分", "very"),
    ("相当", "quite"),
    ("特别", "particularly"),
    ("尤其", "especially"),
    ("最为", "most"),
    ("极其", "extremely"),
    ("高达", "as high as"),
    ("低至", "as low as"),
    ("多至", "as many as"),
    ("少至", "as few as"),
    ("快至", "as fast as"),
    ("慢至", "as slow as"),
    ("可达", "can reach"),
    ("约为", "approximately"),
    ("即为", "which is"),
    ("统称为", "collectively called"),
    ("广泛用于", "widely used for"),
    ("普遍认为", "generally believed"),
    ("已被证实", "has been confirmed"),
    ("研究表明", "studies show"),
    ("实验结果", "experimental results"),
    ("临床研究", "clinical studies"),
    ("动物研究", "animal studies"),
    ("体外研究", "in vitro studies"),
    ("体内研究", "in vivo studies"),
    ("目前认为", "currently believed"),
    ("多数研究", "most studies"),
    ("少数研究", "a few studies"),
    ("部分研究", "some studies"),
    ("大量研究", "numerous studies"),
    ("需要指出", "it should be noted"),
    ("值得注意", "noteworthy"),
    ("需要注意的是", "it should be noted that"),
    ("强调", "emphasizes"),
    ("换言之", "in other words"),
    ("也即", "that is"),
    ("理由如下", "for the following reasons"),
    ("机制如下", "the mechanism is as follows"),
    ("原因如下", "the reasons are as follows"),
    ("包括以下", "including the following"),
    ("归纳起来", "in summary"),
    ("总体来讲", "overall"),
    ("平均", "average"),
    ("范围", "range"),
    ("约", "about"),

    # ── Cleanup: remove common noise characters ──
    # (Keep these at the very end)
]

# Sort by Chinese string length descending at module load time
TRANSLATIONS = sorted(_TRANS_RAW, key=lambda x: len(x[0]), reverse=True)

# ── Type mapping ──
TYPE_MAP = {
    "是非题": "True/False",
    "单选题": "Single Choice",
    "简答题(多选)": "Multiple Choice",
}

# ── Category mapping ──
CATEGORY_MAP = {
    # Ch7
    "胆碱酯酶": "Cholinesterase",
    "易逆性抗胆碱酯酶药": "Reversible Anticholinesterase Agents",
    "难逆性抗胆碱酯酶药": "Irreversible Anticholinesterase Agents",
    "胆碱酯酶复活药": "Cholinesterase Reactivators",
    "有机磷中毒防治": "Organophosphate Poisoning Management",
    # Ch8
    "M受体阻断药": "M Receptor Blockers",
    "M受体阻断药（阿托品相关）": "M Receptor Blockers (Atropine-Related)",
    "N受体阻断药": "N Receptor Blockers",
    "合成代用品": "Synthetic Substitutes",
    "合成扩瞳药": "Synthetic Mydriatics",
    "合成解痉药": "Synthetic Antispasmodics",
    "选择性M受体亚型阻断药": "Selective M Receptor Subtype Blockers",
    # Ch9
    "化学结构及分类": "Chemical Structure and Classification",
    "alpha受体激动药": "Alpha-Adrenoceptor Agonists",
    "α受体激动药": "Alpha-Adrenoceptor Agonists",
    "beta受体激动药": "Beta-Adrenoceptor Agonists",
    "β受体激动药": "Beta-Adrenoceptor Agonists",
    "alpha、beta受体激动药": "Alpha,Beta-Adrenoceptor Agonists",
    "α、β受体激动药": "Alpha,Beta-Adrenoceptor Agonists",
    "α受体激动药与β受体激动药比较": "Alpha vs. Beta Adrenoceptor Agonists",
    "综合比较": "Comprehensive Comparison",
    # Ch10
    "alpha受体阻断药": "Alpha-Adrenoceptor Blockers",
    "beta受体阻断药": "Beta-Adrenoceptor Blockers",
    "beta受体阻断药分类": "Beta-Adrenoceptor Blocker Classification",
    "beta受体阻断药（血管舒张性）": "Beta-Adrenoceptor Blockers (Vasodilatory)",
    # Ch11
    "局部麻醉药作用机制": "Mechanism of Action of Local Anesthetics",
    "局部麻醉药分类": "Classification of Local Anesthetics",
    "局部麻醉作用": "Local Anesthetic Action",
    "局部麻醉方法": "Methods of Local Anesthesia",
    "影响局部麻醉药作用的因素": "Factors Affecting Local Anesthetic Action",
    "常用局部麻醉药": "Commonly Used Local Anesthetics",
    "构效关系与分类": "Structure-Activity Relationship and Classification",
    "不良反应": "Adverse Reactions",
    # Ch12
    "全身麻醉药概述": "Overview of General Anesthetics",
    "吸入麻醉药": "Inhaled Anesthetics",
    "吸入麻醉药不良反应": "Inhaled Anesthetic Adverse Reactions",
    "静脉麻醉药": "Intravenous Anesthetics",
    "复合麻醉": "Combined Anesthesia / Balanced Anesthesia",
}


def translate_text(text):
    """Apply translation dictionary (already length-sorted) to a text string,
    then clean up common artifacts from the word-substitution process."""
    if not text:
        return text
    result = text
    for cn, en in TRANSLATIONS:
        if cn in result:
            result = result.replace(cn, en)

    # Post-processing cleanup to fix common artifacts
    # Remove common slash-heavy alternatives that survived
    cleanup_patterns = [
        ("is present in / exists in", "is present in"),
        ("is present in / exists in", "is present in"),
        ("present / existing", "present"),
        ("produce / generate", "produces"),
        ("produce / generates", "produces"),
        ("produces / generate", "produces"),
        ("lead to / cause", "lead to"),
        ("lead to / leads to", "leads to"),
        ("cause / induce / trigger", "induce"),
        ("induce / provoke / trigger", "induce"),
        ("induce / provoke", "induce"),
        ("appear / occur / emerge", "occur"),
        ("disappear / resolve", "resolve"),
        ("occur / happen / take place", "occur"),
        ("restore / recover", "restore"),
        ("promote / facilitate", "promote"),
        ("inhibit / suppress", "inhibit"),
        ("stimulate / activate", "activate"),
        ("excite / stimulate", "stimulate"),
        ("enhance / strengthen / increase", "enhance"),
        ("weaken / reduce / diminish", "reduce"),
        ("alleviate / reduce", "alleviate"),
        ("aggravate / worsen", "aggravate"),
        ("increase / elevate / raise", "increase"),
        ("decrease / reduce / lower", "decrease"),
        ("increase / raise", "increase"),
        ("decrease / reduce / diminish", "decrease"),
        ("prolong / extend", "prolong"),
        ("accelerate / speed up", "accelerate"),
        ("slow down / decelerate", "slow"),
        ("relax / dilate", "dilate"),
        ("contract / constrict", "constrict"),
        ("dilate / expand", "dilate"),
        ("constrict / narrow / reduce", "constrict"),
        ("dilate / enlarge / expand", "dilate"),
        ("inactivate / deactivate", "inactivate"),
        ("decompose / break down", "break down"),
        ("excrete / secretion", "secrete"),
        ("excrete / eliminate", "excrete"),
        ("eliminate / clear", "eliminate"),
        ("bind / combine", "bind to"),
        ("penetrate / cross", "cross"),
        ("pass through / cross", "pass through"),
        ("pass through / via", "via"),
        ("influx / flow into", "influx"),
        ("influx / inward flow", "influx"),
        ("efflux / outward flow", "efflux"),
        ("enter / entry into", "enter"),
        ("leave / exit from", "exit"),
        ("reach / achieve / attain", "reach"),
        ("exceed / surpass", "exceed"),
        ("maintain / keep", "maintain"),
        ("exert / play (a role)", "exert"),
        ("affect / influence", "affect"),
        ("include / including", "including"),
        ("contain / containing", "containing"),
        ("apply / application / use", "application"),
        ("use / utilize", "use"),
        ("medication / drug administration", "administration"),
        ("administer / administration", "administration"),
        ("inject / injection", "injection"),
        ("infusion / intravenous drip", "infusion"),
        ("inhale / inhalation", "inhaled"),
        ("eye drop / ophthalmic instillation", "ophthalmic administration"),
        ("treat / treatment / therapy", "treatment"),
        ("prevent / prevention / prophylaxis", "prevention"),
        ("diagnose / diagnosis", "diagnosis"),
        ("relieve / alleviate", "relieve"),
        ("counteract / oppose", "counteract"),
        ("synergize / potentiate", "synergize"),
        ("coadministration / combined use", "coadministration"),
        ("use alone / monotherapy", "monotherapy"),
        ("note / attention", "note"),
        ("evaluate / assess", "assess"),
        ("detect / test", "detect"),
        ("measure / determine", "measure"),
        ("record / document", "document"),
        ("describe / description", "described as"),
        ("explain / interpretation", "explain"),
        ("confirm / verify", "confirm"),
        ("indicate / suggest", "indicate"),
        ("indicate / demonstrate", "demonstrate"),
        ("show / demonstrate / reveal", "demonstrate"),
        ("prove / demonstrate", "demonstrate"),
        ("is called / is referred to as", "is called"),
        ("is referred to as", "is called"),
        ("refers to / is defined as", "is defined as"),
        ("is equivalent to / corresponds to", "corresponds to"),
        ("is associated with / related to", "is associated with"),
        ("is related to / associated with", "is related to"),
        ("is opposite to / in contrast to", "in contrast to"),
        ("combined with / coadministered with", "coadministered with"),
        ("is critical / is crucial", "is critical"),
        ("have / possess", "have"),
        ("lack / be deficient in", "lack"),
        ("replace / substitute", "replace"),
        ("replace / substitute for", "substitute for"),
        ("convert / transform", "convert"),
        ("convert to / transform into", "convert to"),
        ("change / variation", "change"),
        ("change / alter / modify", "alter"),
        ("reverse / reversal", "reversal"),
        ("superimpose / additive effect", "superimpose"),
        ("offset / counteract", "offset"),
        ("weaken / attenuate", "attenuate"),
        ("flush / wash out", "wash out"),
        ("clear / eliminate", "clear"),
        ("wash out / elute", "elute"),
        ("discontinue / stop", "discontinue"),
        ("excessive dose / overdose", "overdose"),
        ("poisoning / toxicity / intoxication", "poisoning"),
        ("rescue / emergency treatment", "emergency treatment"),
        ("rescue / antidotal treatment", "antidotal treatment"),
        ("antagonist / blocker", "antagonist"),
        ("have / has", "has"),
        ("mainly / primarily", "primarily"),
        ("markedly / obviously", "markedly"),
        ("significantly / markedly", "significantly"),
        ("rapidly / quickly", "rapidly"),
        ("above / higher than", "higher than"),
        ("below / lower than", "lower than"),
        ("relatively / comparatively", "relatively"),
        ("usually / typically", "typically"),
        ("generally / usually", "generally"),
        ("often / tend to", "tend to"),
        ("may / possibly", "may"),
        ("must / have to", "must"),
        ("require / need", "require"),
        ("need / require", "need"),
        ("also / too", "also"),
        ("still / yet", "still"),
        ("also / still", "also"),
        ("especially / in particular", "especially"),
        ("in addition / furthermore", "furthermore"),
        ("simultaneously / also", "simultaneously"),
        ("then / subsequently", "subsequently"),
        ("first / firstly", "first"),
        ("second / secondly", "second"),
        ("finally / lastly", "finally"),
        ("etc. / and others", "etc."),
        ("if / if the / such as / for example", "such as"),
        ("is / are", "is"),
        ("is / as / for", "is"),
        ("all / are all", "are all"),
        ("so / therefore", "therefore"),
        ("therefore / thus / consequently", "therefore"),
        ("forgetfulness / amnesia", "amnesia"),
        ("fatigue / drowsiness", "drowsiness"),
        ("diaphoresis / excessive sweating", "excessive sweating"),
        ("amnesia / memory loss", "amnesia"),
        ("aging / senescence", "aging"),
        ("disorder / impairment", "disorder"),
        ("disorder / disturbance", "disorder"),
        ("widespread / extensive", "extensive"),
        ("potent / strong", "potent"),
        ("most / -est", "most"),
        ("three / tri-", "three"),
        ("double / bi- / dual", "dual"),
        ("no / without / a-", "no"),
        ("single / mono-", "single"),
        ("multiple / poly-", "multiple"),
        # More comprehensive cleanups for remaining artifacts
        ("can / may", "can"),
        ("in / among / medium", "in"),
        ("above / upper / on", "on"),
        ("upper / on", "on"),
        ("has / have / there is", "has"),
        ("after / posterior / rear", "after"),
        ("posterior / rear", "after"),
        ("will / shall", "will"),
        ("effect / action", "effect"),
        ("by / in order to / with", "by"),
        ("cause / make / allow", "cause"),
        ("even if / even though", "even if"),
        ("then / whereas", "then"),
        ("almost / nearly", "nearly"),
        ("easily / prone to", "readily"),
        ("outside / external", "peripheral"),
        ("external / outside", "external"),
        ("within / inside", "within"),
        ("as / serve as", "as"),
        ("difficult to / resistant to", "difficult to"),
        ("short-term / acute", "short-term"),
        ("few / little", "few"),
        ("basic / fundamental", "basic"),
        ("key / critical", "critical"),
        ("main / primary", "primary"),
        ("close to / near", "near"),
        ("dose / dosage", "dose"),
        ("with / has", "with"),
        ("no / without / a-", "without"),
        ("is / are", "is"),
        ("has no / without / lacks", "lacks"),
        ("by (passive voice)", "by"),
        ("by (passive voice)in / among / medium", "in"),
        ("foroutside / externalweeks", "peripherally"),
        ("outside / externalweeksand", "peripheral and"),
        ("in / among / medium枢", "central"),
        ("by / from", "by"),
        ("all / both", "both"),
        ("  ", " "),
    ]
    for old, new in cleanup_patterns:
        result = result.replace(old, new)

    # Regex-based cleanup: strip "/"-separated alternatives, keeping the first
    # Multi-word slash alternatives: "a / b / c" → "a"
    result = re.sub(r'\b(\w+(?:-[A-Za-z]+)?)\s*/\s*\w+(?:\s*/\s*\w+)*\b(?!\s*(?:coefficient|partition))', r'\1', result)
    # Clean up multiple consecutive spaces
    result = re.sub(r'\s{2,}', ' ', result)
    # Remove spaces before punctuation
    result = re.sub(r'\s+([.,;:!?)])', r'\1', result)
    result = re.sub(r'([(])\s+', r'\1', result)
    # Fix common awkward patterns
    result = result.replace("in枢", "central")
    result = result.replace("peripheralweeks", "peripheral")
    result = result.replace("peripheralweeksand", "peripheral and")

    # Clean up excessive whitespace one final time
    result = " ".join(result.split())
    return result.strip()


def translate_row(row):
    """Translate all fields in a CSV row."""
    translated = {}
    for key, value in row.items():
        if value is None:
            value = ""
        if key == "type":
            translated[key] = TYPE_MAP.get(value.strip(), value.strip())
        elif key == "category":
            stripped = value.strip()
            translated[key] = CATEGORY_MAP.get(stripped, translate_text(stripped))
        elif key == "correct":
            # Keep answer letters unchanged
            translated[key] = value.strip()
        elif key == "id":
            translated[key] = value.strip()
        elif key in ("option_a", "option_b"):
            # For True/False questions, translate option values directly
            stripped = value.strip()
            if stripped == "正确":
                translated[key] = "True"
            elif stripped == "错误":
                translated[key] = "False"
            else:
                translated[key] = translate_text(stripped)
        else:
            translated[key] = translate_text(value.strip() if value else "")
    return translated


def process_chapter(ch_num_str):
    """Read Chinese CSV, translate, write English CSV."""
    in_path = os.path.join(WORK_DIR, f"pharma_cn_ch{ch_num_str}.csv")
    out_path = os.path.join(WORK_DIR, f"pharma_en_ch{ch_num_str}.csv")

    with open(in_path, "r", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        fieldnames = reader.fieldnames
        rows = list(reader)

    translated_rows = [translate_row(r) for r in rows]

    with open(out_path, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(translated_rows)

    print(f"  Ch{ch_num_str}: {len(rows)} rows translated -> {out_path}")
    return len(rows)


def main():
    chapters = ["07", "08", "09", "10", "11", "12"]
    total = 0
    print("Translating pharmacology quiz banks Chapters 7-12...")
    print(f"  Dictionary size: {len(TRANSLATIONS)} entries")
    print()
    for ch in chapters:
        n = process_chapter(ch)
        total += n
    print()
    print(f"Done. {total} total rows translated across 6 chapters.")


if __name__ == "__main__":
    main()
