#!/usr/bin/env python3
"""Generate 100 MCQs for Chapter 44: Antiviral Drugs."""
import csv

questions = [
    # ===== Section 1: General Principles & Broad-spectrum Antivirals (Q1-Q10) =====
    {
        "id": 1,
        "question": "关于抗病毒药的作用机制，下列哪项是错误的？",
        "option_a": "阻断病毒与宿主细胞受体的结合",
        "option_b": "阻止病毒穿入和脱壳",
        "option_c": "直接杀灭细胞外的游离病毒颗粒",
        "option_d": "抑制病毒生物合成过程",
        "option_e": "抑制新病毒颗粒的释放",
        "correct": "C",
        "explanation": "抗病毒药通过阻断病毒与受体结合、阻止穿入脱壳、抑制生物合成、抑制释放及增强宿主抗病能力发挥作用，并不能直接杀灭细胞外的游离病毒颗粒。",
        "category": "总论"
    },
    {
        "id": 2,
        "question": "利巴韦林（ribavirin）的抗病毒机制不包括下列哪一项？",
        "option_a": "抑制肌苷一磷酸（IMP）脱氢酶",
        "option_b": "选择性抑制病毒RNA聚合酶",
        "option_c": "抑制病毒神经氨酸酶活性",
        "option_d": "抑制GMP转移酶",
        "option_e": "影响mRNA 5'-帽的合成",
        "correct": "C",
        "explanation": "利巴韦林通过抑制IMP脱氢酶、RNA聚合酶、GMP转移酶和影响mRNA帽结构发挥作用。抑制神经氨酸酶是奥司他韦等抗流感病毒药的作用机制。",
        "category": "广谱抗病毒药"
    },
    {
        "id": 3,
        "question": "利巴韦林临床应用的主要适应证是？",
        "option_a": "巨细胞病毒感染",
        "option_b": "呼吸道合胞病毒引起的肺炎及支气管炎",
        "option_c": "单纯疱疹病毒感染",
        "option_d": "乙型脑炎",
        "option_e": "狂犬病",
        "correct": "B",
        "explanation": "利巴韦林主要用于呼吸道合胞病毒引起的肺炎及支气管炎，也用于甲型及丙型肝炎等病毒感染。",
        "category": "广谱抗病毒药"
    },
    {
        "id": 4,
        "question": "下列关于干扰素（IFN）的药理作用，哪项是错误的？",
        "option_a": "诱导2',5'-寡聚腺苷酸合成酶的产生",
        "option_b": "增强NK细胞的抗病毒活性",
        "option_c": "直接水解病毒DNA",
        "option_d": "激活巨噬细胞的吞噬活力",
        "option_e": "抑制多肽链的起始阶段和延伸",
        "correct": "C",
        "explanation": "干扰素通过诱导效应蛋白（如2',5'-寡聚腺苷酸合成酶、蛋白激酶等）发挥抗病毒作用，并非直接水解病毒DNA。",
        "category": "广谱抗病毒药"
    },
    {
        "id": 5,
        "question": "干扰素禁用于下列哪种情况？",
        "option_a": "慢性乙型肝炎",
        "option_b": "尖锐湿疣",
        "option_c": "严重心脏病患者",
        "option_d": "小儿病毒性肺炎",
        "option_e": "肿瘤",
        "correct": "C",
        "explanation": "干扰素禁用于过敏体质、严重心脏病、肾功能不全、中枢神经系统功能紊乱患者。",
        "category": "广谱抗病毒药"
    },
    {
        "id": 6,
        "question": "利巴韦林治疗丙型肝炎时，宜与下列哪种药物合用？",
        "option_a": "阿昔洛韦",
        "option_b": "金刚烷胺",
        "option_c": "重组IFN-α",
        "option_d": "齐多夫定",
        "option_e": "奥司他韦",
        "correct": "C",
        "explanation": "利巴韦林治疗丙型肝炎时宜与重组IFN-α合用，以增强抗病毒疗效。",
        "category": "广谱抗病毒药"
    },
    {
        "id": 7,
        "question": "利巴韦林最重要的禁忌证是？",
        "option_a": "高血压",
        "option_b": "糖尿病",
        "option_c": "妊娠",
        "option_d": "肾功能不全",
        "option_e": "肝功能不全",
        "correct": "C",
        "explanation": "利巴韦林有致畸作用，孕妇禁用。",
        "category": "广谱抗病毒药"
    },
    {
        "id": 8,
        "question": "根据主要临床用途，抗病毒药可分为以下哪几类？",
        "option_a": "抗流感病毒药、抗疱疹病毒药、抗肝炎病毒药、抗HIV药",
        "option_b": "核苷类、非核苷类、蛋白酶抑制药、整合酶抑制药",
        "option_c": "广谱类、窄谱类、免疫增强类",
        "option_d": "DNA病毒抑制药、RNA病毒抑制药",
        "option_e": "预防用药、治疗用药、根治用药",
        "correct": "A",
        "explanation": "根据主要临床用途，抗病毒药可分为抗流感病毒药、抗疱疹病毒药、抗肝炎病毒药及抗HIV药等。",
        "category": "总论"
    },
    {
        "id": 9,
        "question": "干扰素分为哪三种类型？",
        "option_a": "IFN-α、IFN-β、IFN-δ",
        "option_b": "IFN-α、IFN-β、IFN-γ",
        "option_c": "IFN-α、IFN-γ、IFN-ε",
        "option_d": "IFN-β、IFN-γ、IFN-λ",
        "option_e": "IFN-α、IFN-δ、IFN-λ",
        "correct": "B",
        "explanation": "干扰素分为IFN-α、IFN-β、IFN-γ三种类型。",
        "category": "广谱抗病毒药"
    },
    {
        "id": 10,
        "question": "下列关于利巴韦林不良反应的描述，哪项是正确的？",
        "option_a": "主要不良反应为肾功能损伤",
        "option_b": "可引起骨髓抑制，表现为白细胞减少",
        "option_c": "常见乏力、贫血、食欲减退等",
        "option_d": "主要引起周围神经炎",
        "option_e": "长期使用可导致视网膜病变",
        "correct": "C",
        "explanation": "利巴韦林不良反应包括乏力、贫血、食欲减退、胃部不适、轻度腹泻和便秘等。骨髓抑制是齐多夫定的主要不良反应。",
        "category": "广谱抗病毒药"
    },

    # ===== Section 2: Anti-influenza Virus Drugs (Q11-Q22) =====
    {
        "id": 11,
        "question": "金刚烷胺抗流感病毒的作用机制是？",
        "option_a": "抑制神经氨酸酶",
        "option_b": "抑制病毒RNA聚合酶",
        "option_c": "作用于M2蛋白，抑制病毒脱壳",
        "option_d": "抑制病毒DNA聚合酶",
        "option_e": "阻断病毒与宿主细胞受体结合",
        "correct": "C",
        "explanation": "金刚烷胺通过作用于M2蛋白，抑制病毒在宿主细胞内的脱壳，从而抑制复制过程。",
        "category": "抗流感病毒药"
    },
    {
        "id": 12,
        "question": "金刚烷胺对下列哪种病毒有效？",
        "option_a": "乙型流感病毒",
        "option_b": "甲型流感病毒",
        "option_c": "丙型肝炎病毒",
        "option_d": "单纯疱疹病毒",
        "option_e": "呼吸道合胞病毒",
        "correct": "B",
        "explanation": "金刚烷胺仅对甲型流感病毒有抑制作用，对乙型流感病毒及其他病毒无效。",
        "category": "抗流感病毒药"
    },
    {
        "id": 13,
        "question": "奥司他韦（oseltamivir）的抗病毒机制是？",
        "option_a": "抑制M2蛋白",
        "option_b": "抑制病毒RNA聚合酶PA亚基",
        "option_c": "抑制神经氨酸酶，阻止病毒释放",
        "option_d": "抑制病毒DNA聚合酶",
        "option_e": "抑制逆转录酶",
        "correct": "C",
        "explanation": "奥司他韦是神经氨酸酶抑制药，通过抑制流感病毒表面的神经氨酸酶活性，阻止子代病毒从宿主细胞释放。",
        "category": "抗流感病毒药"
    },
    {
        "id": 14,
        "question": "下列关于奥司他韦的描述，哪项是错误的？",
        "option_a": "为前体药物",
        "option_b": "口服生物利用度高",
        "option_c": "是目前治疗流感的常用药物之一",
        "option_d": "对乙型流感病毒无效",
        "option_e": "常见不良反应为恶心和呕吐",
        "correct": "D",
        "explanation": "奥司他韦对甲型流感病毒和乙型流感病毒均有活性，并非对乙型流感病毒无效。",
        "category": "抗流感病毒药"
    },
    {
        "id": 15,
        "question": "玛巴洛沙韦（baloxavir marboxil）的抗病毒靶点是？",
        "option_a": "M2蛋白",
        "option_b": "神经氨酸酶",
        "option_c": "病毒RNA聚合酶PA亚基的内切酶活性",
        "option_d": "病毒RNA聚合酶PB1亚基",
        "option_e": "血凝素",
        "correct": "C",
        "explanation": "玛巴洛沙韦通过抑制流感病毒RNA聚合酶PA亚基的内切酶活性，阻止病毒mRNA的复制。法匹拉韦则抑制PB1亚基。",
        "category": "抗流感病毒药"
    },
    {
        "id": 16,
        "question": "下列关于扎那米韦的描述，哪项是正确的？",
        "option_a": "口服生物利用度高",
        "option_b": "对哮喘或COPD患者安全有效",
        "option_c": "通过抑制流感病毒的神经氨酸酶发挥作用",
        "option_d": "属于M2通道阻滞药",
        "option_e": "对甲型流感无效",
        "correct": "C",
        "explanation": "扎那米韦是神经氨酸酶抑制药，口服生物利用度低，对哮喘或COPD患者可能无效甚至引起危险。",
        "category": "抗流感病毒药"
    },
    {
        "id": 17,
        "question": "法匹拉韦（favipiravir）的抗病毒作用靶点是？",
        "option_a": "神经氨酸酶",
        "option_b": "M2蛋白",
        "option_c": "病毒RNA聚合酶PB1亚基",
        "option_d": "病毒RNA聚合酶PA亚基",
        "option_e": "血凝素",
        "correct": "C",
        "explanation": "法匹拉韦作为核苷类似物，有效抑制流感病毒PB1亚基活性，阻断病毒RNA合成。",
        "category": "抗流感病毒药"
    },
    {
        "id": 18,
        "question": "与金刚烷胺相比，金刚乙胺的特点是什么？",
        "option_a": "抗病毒作用更强",
        "option_b": "对乙型流感病毒有效",
        "option_c": "中枢神经系统不良反应较少",
        "option_d": "半衰期更短",
        "option_e": "口服不吸收",
        "correct": "C",
        "explanation": "金刚乙胺不易透过血脑屏障，故中枢神经系统不良反应较金刚烷胺少。",
        "category": "抗流感病毒药"
    },
    {
        "id": 19,
        "question": "目前公认的抗禽流感、甲型H1N1流感最有效的药物之一是？",
        "option_a": "金刚烷胺",
        "option_b": "利巴韦林",
        "option_c": "阿昔洛韦",
        "option_d": "奥司他韦",
        "option_e": "阿糖腺苷",
        "correct": "D",
        "explanation": "奥司他韦是公认的抗禽流感、甲型H1N1流感最有效的药物之一。",
        "category": "抗流感病毒药"
    },
    {
        "id": 20,
        "question": "巴洛沙韦玛波西酯的半衰期约为？",
        "option_a": "2~4 h",
        "option_b": "6~10 h",
        "option_c": "12~17 h",
        "option_d": "约79 h",
        "option_e": "约120 h",
        "correct": "D",
        "explanation": "巴洛沙韦玛波西酯的t1/2较长，约为79.1 h。金刚烷胺t1/2为12～17 h，奥司他韦活性代谢物t1/2为6～10 h。",
        "category": "抗流感病毒药"
    },
    {
        "id": 21,
        "question": "流感病毒RNA聚合酶的三个亚基不包括？",
        "option_a": "PB1",
        "option_b": "PB2",
        "option_c": "PA",
        "option_d": "M2",
        "option_e": "以上都是亚基",
        "correct": "D",
        "explanation": "流感病毒RNA聚合酶由PB1、PB2和PA三个亚基组成，M2是病毒包膜上的离子通道蛋白，不是聚合酶亚基。",
        "category": "抗流感病毒药"
    },
    {
        "id": 22,
        "question": "下列关于M2通道阻滞药的特点，错误的是？",
        "option_a": "金刚烷胺口服易吸收",
        "option_b": "主要以原型经肾排出",
        "option_c": "对甲型和乙型流感病毒均有效",
        "option_d": "金刚烷胺耐药性较普遍，已很少使用",
        "option_e": "金刚乙胺中枢不良反应较少",
        "correct": "C",
        "explanation": "M2通道阻滞药仅对甲型流感病毒有效，对乙型流感病毒无效。",
        "category": "抗流感病毒药"
    },

    # ===== Section 3: Anti-herpesvirus Drugs (Q23-Q38) =====
    {
        "id": 23,
        "question": "阿昔洛韦抗疱疹病毒作用机制的关键步骤是？",
        "option_a": "直接抑制病毒蛋白质合成",
        "option_b": "在感染细胞内经病毒胸苷激酶（TK）磷酸化后发挥作用",
        "option_c": "阻断病毒与宿主细胞膜融合",
        "option_d": "抑制病毒神经氨酸酶",
        "option_e": "直接降解病毒mRNA",
        "correct": "B",
        "explanation": "阿昔洛韦在感染细胞内经病毒胸苷激酶（TK）磷酸化后，生成三磷酸阿昔洛韦，抑制病毒DNA聚合酶。",
        "category": "抗疱疹病毒药"
    },
    {
        "id": 24,
        "question": "阿昔洛韦对下列哪种病毒的抑制作用最弱？",
        "option_a": "HSV-1",
        "option_b": "HSV-2",
        "option_c": "VZV",
        "option_d": "EBV",
        "option_e": "CMV",
        "correct": "E",
        "explanation": "CMV（巨细胞病毒）无胸苷激酶（TK），故阿昔洛韦抑制CMV的活性较低。",
        "category": "抗疱疹病毒药"
    },
    {
        "id": 25,
        "question": "下列关于阿昔洛韦的描述，错误的是？",
        "option_a": "又称无环鸟苷",
        "option_b": "口服生物利用度为10%～30%",
        "option_c": "在肾中药物浓度最高",
        "option_d": "对缺乏TK的HSV突变株有效",
        "option_e": "抗疱疹病毒作用比碘苷强10倍",
        "correct": "D",
        "explanation": "阿昔洛韦对缺乏TK（胸苷激酶）的HSV突变株无作用，因为其活化依赖于病毒TK的磷酸化。",
        "category": "抗疱疹病毒药"
    },
    {
        "id": 26,
        "question": "与阿昔洛韦相比，更昔洛韦的显著特点是？",
        "option_a": "口服生物利用度高",
        "option_b": "抗CMV作用强于阿昔洛韦约100倍",
        "option_c": "毒性更小",
        "option_d": "对HSV无抑制作用",
        "option_e": "不需经磷酸化激活",
        "correct": "B",
        "explanation": "更昔洛韦抗CMV作用强于阿昔洛韦约100倍，但毒性较大，可诱发骨髓抑制，仅用于严重CMV感染。",
        "category": "抗疱疹病毒药"
    },
    {
        "id": 27,
        "question": "伐昔洛韦（valaciclovir）与阿昔洛韦的关系是？",
        "option_a": "伐昔洛韦是阿昔洛韦的代谢产物",
        "option_b": "伐昔洛韦是阿昔洛韦的前药",
        "option_c": "两者化学结构完全不同",
        "option_d": "伐昔洛韦抗病毒谱更广",
        "option_e": "两者无关联",
        "correct": "B",
        "explanation": "伐昔洛韦是阿昔洛韦的前药（L-缬氨酸酯），口服后在体内迅速水解为阿昔洛韦而发挥作用。",
        "category": "抗疱疹病毒药"
    },
    {
        "id": 28,
        "question": "泛昔洛韦（famciclovir）在体内转化为哪种活性物质？",
        "option_a": "阿昔洛韦",
        "option_b": "更昔洛韦",
        "option_c": "喷昔洛韦",
        "option_d": "伐昔洛韦",
        "option_e": "曲氟尿苷",
        "correct": "C",
        "explanation": "泛昔洛韦是喷昔洛韦的前药，口服后在体内转化为喷昔洛韦发挥抗病毒作用。",
        "category": "抗疱疹病毒药"
    },
    {
        "id": 29,
        "question": "喷昔洛韦的主要临床应用是？",
        "option_a": "口服治疗带状疱疹",
        "option_b": "静脉注射治疗CMV感染",
        "option_c": "外用治疗复发性唇和生殖器疱疹",
        "option_d": "口服治疗流感",
        "option_e": "治疗乙型肝炎",
        "correct": "C",
        "explanation": "喷昔洛韦口服生物利用度仅约5%，主要外用治疗复发性唇和生殖器疱疹。",
        "category": "抗疱疹病毒药"
    },
    {
        "id": 30,
        "question": "膦甲酸（foscarnet）的作用机制是？",
        "option_a": "抑制病毒胸苷激酶",
        "option_b": "抑制病毒DNA聚合酶和逆转录酶",
        "option_c": "抑制神经氨酸酶",
        "option_d": "抑制病毒吸附",
        "option_e": "掺入病毒DNA终止链延长",
        "correct": "B",
        "explanation": "膦甲酸为焦磷酸类似物，能特异性抑制病毒DNA聚合酶和逆转录酶，为非核苷类抗病毒药。",
        "category": "抗疱疹病毒药"
    },
    {
        "id": 31,
        "question": "曲氟尿苷（trifluridine）主要用于治疗？",
        "option_a": "慢性乙型肝炎",
        "option_b": "流感",
        "option_c": "疱疹性角膜炎和结膜炎",
        "option_d": "艾滋病",
        "option_e": "丙型肝炎",
        "correct": "C",
        "explanation": "曲氟尿苷局部应用治疗眼部感染，包括疱疹性角膜炎和结膜炎及其他疱疹性眼病。",
        "category": "抗疱疹病毒药"
    },
    {
        "id": 32,
        "question": "阿昔洛韦大剂量静脉滴注最需要关注的不良反应是？",
        "option_a": "骨髓抑制",
        "option_b": "周围神经炎",
        "option_c": "可逆性肾损害及肾功能减退",
        "option_d": "胰腺炎",
        "option_e": "肝衰竭",
        "correct": "C",
        "explanation": "阿昔洛韦大剂量静脉滴注时，少数患者可发生可逆性肾损害、肾小管内结晶及肾功能减退。",
        "category": "抗疱疹病毒药"
    },
    {
        "id": 33,
        "question": "下列抗疱疹病毒药中，口服生物利用度最高的是？",
        "option_a": "阿昔洛韦（10%～30%）",
        "option_b": "喷昔洛韦（约5%）",
        "option_c": "泛昔洛韦（约70%）",
        "option_d": "膦甲酸（口服生物利用度低）",
        "option_e": "更昔洛韦（口服吸收差）",
        "correct": "C",
        "explanation": "泛昔洛韦口服生物利用度约70%，远高于阿昔洛韦（10%～30%）、喷昔洛韦（约5%）和更昔洛韦（吸收差）。",
        "category": "抗疱疹病毒药"
    },
    {
        "id": 34,
        "question": "下列关于阿昔洛韦体内过程的描述，错误的是？",
        "option_a": "肾中药物浓度为血药浓度的10倍",
        "option_b": "脑脊液浓度为血药浓度的50%",
        "option_c": "血浆蛋白结合率为50%～60%",
        "option_d": "主要经肾排泄",
        "option_e": "无尿患者t1/2可延长至18h",
        "correct": "C",
        "explanation": "阿昔洛韦血浆蛋白结合率为9%～23%，而非50%～60%。",
        "category": "抗疱疹病毒药"
    },
    {
        "id": 35,
        "question": "更昔洛韦最严重的不良反应是？",
        "option_a": "周围神经炎",
        "option_b": "骨髓抑制",
        "option_c": "肝功能异常",
        "option_d": "肾功能损害",
        "option_e": "胰腺炎",
        "correct": "B",
        "explanation": "更昔洛韦毒性较大，可诱发骨髓抑制，这是其最严重的不良反应。",
        "category": "抗疱疹病毒药"
    },
    {
        "id": 36,
        "question": "膦甲酸常见的不良反应是？",
        "option_a": "骨髓抑制",
        "option_b": "胰腺炎",
        "option_c": "肾功能损伤和电解质紊乱",
        "option_d": "周围神经炎",
        "option_e": "视网膜病变",
        "correct": "C",
        "explanation": "膦甲酸常见不良反应有肾功能损伤、电解质紊乱和静脉炎。",
        "category": "抗疱疹病毒药"
    },
    {
        "id": 37,
        "question": "导致水痘和带状疱疹的病毒是？",
        "option_a": "HSV-1",
        "option_b": "HSV-2",
        "option_c": "VZV（HHV-3）",
        "option_d": "CMV",
        "option_e": "EBV",
        "correct": "C",
        "explanation": "VZV（水痘-带状疱疹病毒/HHV-3）主要引起水痘和带状疱疹。HSV-1引起口唇疱疹，HSV-2引起生殖器疱疹。",
        "category": "抗疱疹病毒药"
    },
    {
        "id": 38,
        "question": "不宜与齐多夫定合用的抗HIV药物是？",
        "option_a": "拉米夫定",
        "option_b": "去羟肌苷",
        "option_c": "司他夫定",
        "option_d": "扎西他滨",
        "option_e": "阿巴卡韦",
        "correct": "C",
        "explanation": "司他夫定不宜与齐多夫定合用，因为齐多夫定能减少司他夫定的磷酸化，两者互相拮抗。",
        "category": "抗HIV药"
    },

    # ===== Section 4: Anti-hepatitis Virus Drugs (Q39-Q60) =====
    {
        "id": 39,
        "question": "阿德福韦酯属于哪类抗病毒药物？",
        "option_a": "干扰素类",
        "option_b": "神经氨酸酶抑制药",
        "option_c": "无环腺嘌呤核苷类似物",
        "option_d": "非核苷类逆转录酶抑制药",
        "option_e": "蛋白酶抑制药",
        "correct": "C",
        "explanation": "阿德福韦酯为无环腺嘌呤核苷类似物，在体内水解为阿德福韦，抑制HBV DNA聚合酶。",
        "category": "抗肝炎病毒药"
    },
    {
        "id": 40,
        "question": "恩替卡韦的抗病毒靶点是？",
        "option_a": "HCV NS5B聚合酶",
        "option_b": "HBV DNA聚合酶",
        "option_c": "HIV逆转录酶",
        "option_d": "流感病毒RNA聚合酶",
        "option_e": "疱疹病毒DNA聚合酶",
        "correct": "B",
        "explanation": "恩替卡韦在体内磷酸化后抑制HBV DNA聚合酶的启动、前基因组mRNA逆转录负链形成及HBV DNA正链合成。",
        "category": "抗肝炎病毒药"
    },
    {
        "id": 41,
        "question": "替诺福韦的描述，下列哪项是正确的？",
        "option_a": "仅用于治疗HIV感染",
        "option_b": "属于非核苷类逆转录酶抑制药",
        "option_c": "在体内磷酸化后抑制HIV-1逆转录酶和HBV逆转录酶",
        "option_d": "对乙型肝炎无效",
        "option_e": "属于蛋白酶抑制药",
        "correct": "C",
        "explanation": "替诺福韦在体内磷酸化形成二磷酸替诺福韦，可抑制HIV-1逆转录酶和HBV逆转录酶活性，用于治疗慢性乙型肝炎和HIV-1感染。",
        "category": "抗肝炎病毒药"
    },
    {
        "id": 42,
        "question": "丙酚替诺福韦（TAF）与替诺福韦（TDF）相比，主要优势是？",
        "option_a": "抗病毒作用更弱",
        "option_b": "仅对HIV有效",
        "option_c": "在骨代谢和肾脏安全性方面优于替诺福韦",
        "option_d": "不需要磷酸化激活",
        "option_e": "口服吸收更差",
        "correct": "C",
        "explanation": "丙酚替诺福韦是替诺福韦前药，抗病毒疗效较替诺福韦强，不良反应减少，在骨代谢和肾脏安全性方面优于替诺福韦。",
        "category": "抗肝炎病毒药"
    },
    {
        "id": 43,
        "question": "索磷布韦（sofosbuvir）的抗病毒靶点是？",
        "option_a": "HCV NS3/4A蛋白酶",
        "option_b": "HCV NS5A蛋白",
        "option_c": "HCV NS5B聚合酶",
        "option_d": "HBV DNA聚合酶",
        "option_e": "HIV整合酶",
        "correct": "C",
        "explanation": "索磷布韦是HCV NS5B聚合酶抑制药，在体内转化为活性尿苷三磷酸类似物，整合入延长的RNA中使链终止。",
        "category": "抗肝炎病毒药"
    },
    {
        "id": 44,
        "question": "下列哪组是NS3/4A蛋白酶抑制药？",
        "option_a": "艾尔巴韦、哌仑他韦、达拉他韦",
        "option_b": "格拉瑞韦、格卡瑞韦、西美瑞韦",
        "option_c": "索磷布韦、达塞布韦",
        "option_d": "拉米夫定、恩替卡韦",
        "option_e": "利巴韦林、干扰素",
        "correct": "B",
        "explanation": "格拉瑞韦、格卡瑞韦和西美瑞韦属于NS3/4A蛋白酶抑制药。艾尔巴韦、哌仑他韦、达拉他韦属于NS5A抑制药。",
        "category": "抗肝炎病毒药"
    },
    {
        "id": 45,
        "question": "格卡瑞韦/哌仑他韦复方制剂的组成是？",
        "option_a": "NS3/4A蛋白酶抑制药 + NS5B聚合酶抑制药",
        "option_b": "NS3/4A蛋白酶抑制药 + NS5A抑制药",
        "option_c": "NS5A抑制药 + NS5B聚合酶抑制药",
        "option_d": "两种NS5B聚合酶抑制药",
        "option_e": "NS5A抑制药 + 核苷类似物",
        "correct": "B",
        "explanation": "格卡瑞韦/哌仑他韦是NS3/4A蛋白酶抑制药（格卡瑞韦100mg）和NS5A抑制药（哌仑他韦40mg）组成的复方制剂。",
        "category": "抗肝炎病毒药"
    },
    {
        "id": 46,
        "question": "下列关于索磷布韦的描述，错误的是？",
        "option_a": "为NS5B聚合酶抑制药",
        "option_b": "联合利巴韦林用于基因2型和3型慢性丙肝",
        "option_c": "口服吸收受饮食影响较大",
        "option_d": "在体内转化为活性尿苷三磷酸类似物",
        "option_e": "t1/2为0.4 h",
        "correct": "C",
        "explanation": "索磷布韦口服吸收不受饮食的影响，0.5～2 h血药浓度达峰值。",
        "category": "抗肝炎病毒药"
    },
    {
        "id": 47,
        "question": "艾尔巴韦/格拉瑞韦复方制剂主要用于治疗？",
        "option_a": "慢性乙型肝炎",
        "option_b": "基因1型和4型慢性丙型肝炎",
        "option_c": "所有基因型慢性丙型肝炎",
        "option_d": "艾滋病",
        "option_e": "流感",
        "correct": "B",
        "explanation": "艾尔巴韦/格拉瑞韦主要用于治疗基因1型和4型慢性丙型肝炎成人患者。而格卡瑞韦/哌仑他韦对所有基因型（1～6型）HCV均有活性。",
        "category": "抗肝炎病毒药"
    },
    {
        "id": 48,
        "question": "关于乙型肝炎的治疗，下列说法正确的是？",
        "option_a": "抗病毒药物对乙型肝炎可起到根治作用",
        "option_b": "目前抗病毒药物对乙型肝炎只能达到抑制病毒的目的",
        "option_c": "乙型肝炎急性期后很少转为慢性",
        "option_d": "干扰素对乙型肝炎无效",
        "option_e": "索磷布韦是治疗乙肝的首选药",
        "correct": "B",
        "explanation": "目前抗病毒药物对乙型肝炎只能达到抑制病毒的目的，对丙型肝炎可起到根治作用。",
        "category": "抗肝炎病毒药"
    },
    {
        "id": 49,
        "question": "艾米替诺福韦与丙酚替诺福韦相比，结构上的特点是？",
        "option_a": "在酰胺化基团上增加了一个甲基",
        "option_b": "缺少磷酸基团",
        "option_c": "增加了苯环结构",
        "option_d": "改为口服混悬剂",
        "option_e": "无结构差异",
        "correct": "A",
        "explanation": "艾米替诺福韦与丙酚替诺福韦相比，在酰胺化基团上增加了一个甲基，提升药物血浆稳定性和肝细胞内药物释放效率。",
        "category": "抗肝炎病毒药"
    },
    {
        "id": 50,
        "question": "下列哪项不是HCV的非结构蛋白？",
        "option_a": "NS3",
        "option_b": "NS4A",
        "option_c": "NS5A",
        "option_d": "NS5B",
        "option_e": "HBsAg",
        "correct": "E",
        "explanation": "HBsAg是HBV的表面抗原，不是HCV编码的蛋白。HCV的非结构蛋白包括p7、NS2、NS3、NS4A、NS4B、NS5A和NS5B。",
        "category": "抗肝炎病毒药"
    },
    {
        "id": 51,
        "question": "下列关于阿德福韦酯的描述，正确的是？",
        "option_a": "与拉米夫定存在交叉耐药",
        "option_b": "HBV对其不易耐药，与拉米夫定无交叉耐药",
        "option_c": "仅对HCV有抑制作用",
        "option_d": "属于蛋白酶抑制药",
        "option_e": "口服后不需要代谢激活",
        "correct": "B",
        "explanation": "阿德福韦酯HBV不易耐药，与拉米夫定无交叉耐药。联合拉米夫定对耐拉米夫定的慢性乙肝患者能有效抑制HBV DNA。",
        "category": "抗肝炎病毒药"
    },
    {
        "id": 52,
        "question": "慢性乙型肝炎治疗中，连续服药2年或以上可促进HBsAg消失的药物是？",
        "option_a": "拉米夫定",
        "option_b": "阿德福韦酯",
        "option_c": "恩替卡韦",
        "option_d": "干扰素",
        "option_e": "利巴韦林",
        "correct": "C",
        "explanation": "恩替卡韦连续服用2年或以上可促进HBV表面抗原（HBsAg）消失，改善肝脏炎症，长期治疗可改善肝硬化患者组织学病变。",
        "category": "抗肝炎病毒药"
    },
    {
        "id": 53,
        "question": "下列抗HCV药物中，属于NS5A抑制药的是？",
        "option_a": "格拉瑞韦",
        "option_b": "格卡瑞韦",
        "option_c": "索磷布韦",
        "option_d": "达拉他韦",
        "option_e": "西美瑞韦",
        "correct": "D",
        "explanation": "达拉他韦属于NS5A抑制药。格拉瑞韦、格卡瑞韦、西美瑞韦属于NS3/4A蛋白酶抑制药，索磷布韦属于NS5B聚合酶抑制药。",
        "category": "抗肝炎病毒药"
    },
    {
        "id": 54,
        "question": "甲型肝炎病毒（HAV）感染的治疗策略是？",
        "option_a": "使用索磷布韦治疗",
        "option_b": "使用恩替卡韦治疗",
        "option_c": "急性期通常采用对症治疗",
        "option_d": "必须使用干扰素",
        "option_e": "使用利巴韦林根治",
        "correct": "C",
        "explanation": "甲型和戊型病毒性肝炎起病急，一般不会转化为慢性，急性期通常采用对症治疗。",
        "category": "抗肝炎病毒药"
    },
    {
        "id": 55,
        "question": "下列关于拉米夫定的描述，正确的是？",
        "option_a": "仅对HIV有效，对HBV无效",
        "option_b": "抑制HIV复制并对HBV有很强的抑制作用",
        "option_c": "属于蛋白酶抑制药",
        "option_d": "口服生物利用度低",
        "option_e": "与干扰素有拮抗作用",
        "correct": "B",
        "explanation": "拉米夫定能抑制HIV复制，并对HBV有很强的抑制作用，与干扰素有协同作用。",
        "category": "抗HIV药"
    },
    {
        "id": 56,
        "question": "HCV RNA聚合酶由下列哪个非结构蛋白编码？",
        "option_a": "NS3",
        "option_b": "NS4A",
        "option_c": "NS5A",
        "option_d": "NS5B",
        "option_e": "p7",
        "correct": "D",
        "explanation": "NS5B在HCV复制过程中编码RNA聚合酶（RNA-dependent RNA polymerase）。",
        "category": "抗肝炎病毒药"
    },
    {
        "id": 57,
        "question": "索磷布韦联合聚乙二醇干扰素α和利巴韦林用于治疗？",
        "option_a": "基因2型和3型慢性丙型肝炎",
        "option_b": "基因1型和4型慢性丙型肝炎",
        "option_c": "慢性乙型肝炎",
        "option_d": "艾滋病",
        "option_e": "所有类型肝炎",
        "correct": "B",
        "explanation": "索磷布韦联合聚乙二醇干扰素α和利巴韦林用于基因1型和4型慢性丙型肝炎初治患者；联合利巴韦林用于基因2型和3型。",
        "category": "抗肝炎病毒药"
    },
    {
        "id": 58,
        "question": "下列关于阿德福韦酯临床应用适应证，正确的是？",
        "option_a": "适用于所有慢性丙型肝炎患者",
        "option_b": "适用于HBeAg和HBV DNA阳性、ALT增高的慢性乙型肝炎",
        "option_c": "适用于流感预防",
        "option_d": "适用于CMV感染",
        "option_e": "适用于HIV感染",
        "correct": "B",
        "explanation": "阿德福韦酯适用于HBeAg和HBV DNA阳性、丙氨酸转氨酶增高的慢性乙型肝炎。",
        "category": "抗肝炎病毒药"
    },
    {
        "id": 59,
        "question": "下列药物中，既可治疗HBV又可治疗HIV的是？",
        "option_a": "恩替卡韦",
        "option_b": "阿德福韦酯",
        "option_c": "索磷布韦",
        "option_d": "替诺福韦",
        "option_e": "利巴韦林",
        "correct": "D",
        "explanation": "替诺福韦可抑制HIV-1逆转录酶和HBV逆转录酶的活性，既可治疗慢性乙型肝炎，也可与其他抗逆转录病毒药物合用治疗HIV-1感染。",
        "category": "抗肝炎病毒药"
    },
    {
        "id": 60,
        "question": "下列哪种抗病毒药能促进ALT恢复正常并改善肝组织炎症和纤维化？",
        "option_a": "阿德福韦酯",
        "option_b": "金刚烷胺",
        "option_c": "奥司他韦",
        "option_d": "阿昔洛韦",
        "option_e": "曲氟尿苷",
        "correct": "A",
        "explanation": "阿德福韦酯可促进丙氨酸转氨酶（ALT）恢复至正常水平，改善肝组织炎症、坏死和纤维化。",
        "category": "抗肝炎病毒药"
    },

    # ===== Section 5: Anti-HIV Drugs (Q61-Q95) =====
    {
        "id": 61,
        "question": "HIV复制过程中，负责将病毒RNA逆转录为DNA的酶是？",
        "option_a": "整合酶",
        "option_b": "蛋白酶",
        "option_c": "逆转录酶",
        "option_d": "RNA聚合酶",
        "option_e": "DNA聚合酶",
        "correct": "C",
        "explanation": "HIV的逆转录酶（依赖RNA的DNA聚合酶）负责将病毒RNA逆转录合成为病毒DNA。",
        "category": "抗HIV药"
    },
    {
        "id": 62,
        "question": "第一个获批准的抗HIV药物是？",
        "option_a": "拉米夫定",
        "option_b": "司他夫定",
        "option_c": "齐多夫定",
        "option_d": "去羟肌苷",
        "option_e": "阿巴卡韦",
        "correct": "C",
        "explanation": "齐多夫定（zidovudine）是第一个获批准的抗HIV药，为胸腺嘧啶核苷类似物，属于NRTI。",
        "category": "抗HIV药"
    },
    {
        "id": 63,
        "question": "齐多夫定最主要的不良反应是？",
        "option_a": "周围神经炎",
        "option_b": "胰腺炎",
        "option_c": "骨髓抑制",
        "option_d": "肾功能损害",
        "option_e": "肝毒性",
        "correct": "C",
        "explanation": "齐多夫定的主要不良反应为骨髓抑制，表现为贫血、白细胞减少等，发生率与剂量和疗程有关。",
        "category": "抗HIV药"
    },
    {
        "id": 64,
        "question": "齐多夫定能显著减少HIV感染的母婴传播率，需要从妊娠第几周开始给药？",
        "option_a": "第4周到第8周",
        "option_b": "第8周到第12周",
        "option_c": "第14周到第34周",
        "option_d": "第36周到第40周",
        "option_e": "仅在分娩时给药",
        "correct": "C",
        "explanation": "齐多夫定显著减少HIV感染的母婴传播率，需从妊娠第14周给药到34周。",
        "category": "抗HIV药"
    },
    {
        "id": 65,
        "question": "拉米夫定的口服生物利用度约为？",
        "option_a": "30%～40%",
        "option_b": "52%～75%",
        "option_c": "80%～88%",
        "option_d": "95%以上",
        "option_e": "10%～20%",
        "correct": "C",
        "explanation": "拉米夫定口服生物利用度为80%～88%，不受食物影响。齐多夫定生物利用度为52%～75%。",
        "category": "抗HIV药"
    },
    {
        "id": 66,
        "question": "司他夫定最常见的不良反应是？",
        "option_a": "骨髓抑制",
        "option_b": "周围神经炎",
        "option_c": "肾毒性",
        "option_d": "肝毒性",
        "option_e": "胰腺炎",
        "correct": "B",
        "explanation": "司他夫定的主要不良反应为周围神经炎，与扎西他滨和去羟肌苷等合用时发生率明显增加。",
        "category": "抗HIV药"
    },
    {
        "id": 67,
        "question": "扎西他滨在细胞内t1/2长达约？",
        "option_a": "2h",
        "option_b": "5h",
        "option_c": "10h",
        "option_d": "24h",
        "option_e": "40h",
        "correct": "C",
        "explanation": "扎西他滨血浆t1/2为2 h，但细胞内t1/2可长达10 h。去羟肌苷细胞内t1/2可达25～40 h。",
        "category": "抗HIV药"
    },
    {
        "id": 68,
        "question": "去羟肌苷细胞内t1/2最长可达？",
        "option_a": "2 h",
        "option_b": "10 h",
        "option_c": "25～40 h",
        "option_d": "80 h",
        "option_e": "超过100 h",
        "correct": "C",
        "explanation": "去羟肌苷血浆t1/2为0.6～1.5 h，但细胞内t1/2可长达25～40 h。",
        "category": "抗HIV药"
    },
    {
        "id": 69,
        "question": "下列哪种NRTI在肾功能不全（肌酐清除率<30ml/min）时不宜使用？",
        "option_a": "齐多夫定",
        "option_b": "司他夫定",
        "option_c": "拉米夫定",
        "option_d": "去羟肌苷",
        "option_e": "阿巴卡韦",
        "correct": "C",
        "explanation": "拉米夫定主要以原型经肾排泄，肌酐清除率<30 mL/min者不宜使用。",
        "category": "抗HIV药"
    },
    {
        "id": 70,
        "question": "下列哪个药物能减少司他夫定的磷酸化，导致两者不宜合用？",
        "option_a": "拉米夫定",
        "option_b": "去羟肌苷",
        "option_c": "齐多夫定",
        "option_d": "阿巴卡韦",
        "option_e": "扎西他滨",
        "correct": "C",
        "explanation": "齐多夫定能减少司他夫定的磷酸化，两者互相拮抗，不宜合用。",
        "category": "抗HIV药"
    },
    {
        "id": 71,
        "question": "NRTI类药物的共同作用机制是？",
        "option_a": "直接结合逆转录酶破坏催化位点",
        "option_b": "抑制HIV蛋白酶",
        "option_c": "被磷酸化为活性三磷酸代谢物，竞争逆转录酶并终止DNA链合成",
        "option_d": "阻断病毒进入宿主细胞",
        "option_e": "抑制整合酶活性",
        "correct": "C",
        "explanation": "所有NRTI类药物均需在宿主细胞内被磷酸化为活性三磷酸代谢物，与内源性核苷三磷酸盐竞争逆转录酶，并插入病毒DNA导致链合成中止。",
        "category": "抗HIV药"
    },
    {
        "id": 72,
        "question": "下列关于NNRTI的描述，哪项是正确的？",
        "option_a": "需要经宿主细胞磷酸化激活",
        "option_b": "可直接结合到逆转录酶并破坏催化位点",
        "option_c": "属于核苷类似物",
        "option_d": "单用不易产生耐药性",
        "option_e": "对HIV-2的抑制作用强于HIV-1",
        "correct": "B",
        "explanation": "NNRTI不需要磷酸化激活，可直接结合到逆转录酶并破坏催化位点，抑制其活性。但不单独应用，因可迅速产生耐药性。",
        "category": "抗HIV药"
    },
    {
        "id": 73,
        "question": "利匹韦林（rilpivirine）属于？",
        "option_a": "第一代NRTI",
        "option_b": "第一代NNRTI",
        "option_c": "第二代NNRTI",
        "option_d": "蛋白酶抑制药",
        "option_e": "整合酶抑制药",
        "correct": "C",
        "explanation": "利匹韦林为第二代NNRTI，对现有NNRTI耐药毒株具有较强的抗病毒活性，交叉耐药性小。",
        "category": "抗HIV药"
    },
    {
        "id": 74,
        "question": "下列哪一组全部属于HIV蛋白酶抑制药？",
        "option_a": "齐多夫定、拉米夫定、司他夫定",
        "option_b": "依非韦伦、奈韦拉平、利匹韦林",
        "option_c": "利托那韦、沙奎那韦、茚地那韦",
        "option_d": "拉替拉韦、多替拉韦、艾维雷韦",
        "option_e": "马拉维若、恩夫韦肽",
        "correct": "C",
        "explanation": "利托那韦、沙奎那韦、茚地那韦均属于HIV蛋白酶抑制药（PIs）。A组为NRTI，B组为NNRTI，D组为整合酶抑制药，E组为进入抑制药。",
        "category": "抗HIV药"
    },
    {
        "id": 75,
        "question": "蛋白酶抑制药最常见的不良反应是？",
        "option_a": "骨髓抑制和贫血",
        "option_b": "周围神经炎",
        "option_c": "高血糖症和高脂血症",
        "option_d": "肾功能损伤",
        "option_e": "皮疹和过敏反应",
        "correct": "C",
        "explanation": "蛋白酶抑制药最常见的不良反应为高血糖症和高脂血症。此外，PIs主要经肝CYP代谢，可抑制CYP3A4，易发生药物相互作用。",
        "category": "抗HIV药"
    },
    {
        "id": 76,
        "question": "第一个被批准用于治疗HIV感染的整合酶抑制药是？",
        "option_a": "多替拉韦",
        "option_b": "艾维雷韦",
        "option_c": "拉替拉韦",
        "option_d": "比克替拉韦",
        "option_e": "卡博特韦",
        "correct": "C",
        "explanation": "拉替拉韦（raltegravir）是第一个被批准用于治疗HIV感染的整合酶抑制药。",
        "category": "抗HIV药"
    },
    {
        "id": 77,
        "question": "卡替拉韦（cabotegravir）纳米注射制剂的t1/2约为？",
        "option_a": "2～4 h",
        "option_b": "约40 h",
        "option_c": "5.6～11.5 周",
        "option_d": "约7天",
        "option_e": "24 h",
        "correct": "C",
        "explanation": "卡替拉韦纳米注射制剂（肌内注射）t1/2为5.6～11.5周，是一种新型长效整合酶抑制药。口服制剂t1/2约40 h。",
        "category": "抗HIV药"
    },
    {
        "id": 78,
        "question": "马拉维若（maraviroc）的作用机制是？",
        "option_a": "抑制HIV逆转录酶",
        "option_b": "抑制HIV蛋白酶",
        "option_c": "阻断宿主CD4+细胞上的CCR5蛋白，阻止HIV-1进入T细胞",
        "option_d": "抑制HIV整合酶",
        "option_e": "抑制病毒gp41与细胞膜融合",
        "correct": "C",
        "explanation": "马拉维若是CCR5拮抗药，可阻断宿主CD4+细胞上的CCR5蛋白，阻止HIV-1进入T细胞。恩夫韦肽则阻止gp41介导的膜融合。",
        "category": "抗HIV药"
    },
    {
        "id": 79,
        "question": "恩夫韦肽（enfuvirtide）属于哪类抗HIV药物？",
        "option_a": "NRTI",
        "option_b": "NNRTI",
        "option_c": "蛋白酶抑制药",
        "option_d": "进入抑制药（融合抑制药）",
        "option_e": "整合酶抑制药",
        "correct": "D",
        "explanation": "恩夫韦肽为HIV-1跨膜融合蛋白gp41衍生的人工合成多肽，属于进入抑制药（融合抑制药）。",
        "category": "抗HIV药"
    },
    {
        "id": 80,
        "question": "下列哪种药物与更昔洛韦同服可增加其吸收，但降低更昔洛韦的吸收？",
        "option_a": "齐多夫定",
        "option_b": "去羟肌苷",
        "option_c": "司他夫定",
        "option_d": "拉米夫定",
        "option_e": "阿巴卡韦",
        "correct": "B",
        "explanation": "去羟肌苷与更昔洛韦同服可增加去羟肌苷的吸收，但降低更昔洛韦的吸收。",
        "category": "抗HIV药"
    },
    {
        "id": 81,
        "question": "下列关于齐多夫定的描述，错误的是？",
        "option_a": "口服吸收迅速，0.5～1h达峰",
        "option_b": "易透过血脑屏障",
        "option_c": "可抗HIV-1和HIV-2",
        "option_d": "常与司他夫定合用增强疗效",
        "option_e": "t1/2为1 h，无蓄积作用",
        "correct": "D",
        "explanation": "齐多夫定不能与司他夫定合用，因齐多夫定能减少司他夫定的磷酸化，二者互相拮抗。",
        "category": "抗HIV药"
    },
    {
        "id": 82,
        "question": "下列哪种NRTI的脑脊液浓度约为血清浓度的20%？",
        "option_a": "齐多夫定（50%～60%）",
        "option_b": "司他夫定（55%）",
        "option_c": "扎西他滨（约20%）",
        "option_d": "拉米夫定（可透过血脑屏障）",
        "option_e": "阿巴卡韦",
        "correct": "C",
        "explanation": "扎西他滨脑脊液浓度约为血清浓度的20%。齐多夫定脑脊液浓度为血药浓度的50%～60%，司他夫定为55%。",
        "category": "抗HIV药"
    },
    {
        "id": 83,
        "question": "下列关于NRTI耐药的描述，正确的是？",
        "option_a": "NRTI类药物不会产生耐药性",
        "option_b": "耐药主要与编码逆转录酶的基因突变有关",
        "option_c": "单药长期治疗不易发生耐药",
        "option_d": "耐药后所有NRTI均交叉耐药",
        "option_e": "联合用药不能防止HIV复制和耐药",
        "correct": "B",
        "explanation": "HIV-1耐药主要与编码逆转录酶的基因突变有关，单一药物长期治疗更易发生。联合用药是目前避免耐药的唯一途径。",
        "category": "抗HIV药"
    },
    {
        "id": 84,
        "question": "目前治疗艾滋病的标准方案是？",
        "option_a": "单一NRTI治疗",
        "option_b": "单一蛋白酶抑制药治疗",
        "option_c": "2～3种抗HIV药物联合使用",
        "option_d": "干扰素单药治疗",
        "option_e": "仅使用进入抑制药",
        "correct": "C",
        "explanation": "当前抗HIV药物需2～3种联合使用，虽无法根治HIV，但可长期抑制HIV复制，保存患者免疫功能及延长生存期。",
        "category": "抗HIV药"
    },
    {
        "id": 85,
        "question": "下列抗HIV药物中，主要经肝CYP代谢并可抑制CYP3A4的是？",
        "option_a": "齐多夫定",
        "option_b": "拉米夫定",
        "option_c": "替诺福韦",
        "option_d": "利托那韦",
        "option_e": "拉替拉韦",
        "correct": "D",
        "explanation": "蛋白酶抑制药（PIs）如利托那韦主要经肝CYP代谢，可不同程度地抑制肝CYP3A4，故可与其他许多药物发生相互作用。",
        "category": "抗HIV药"
    },
    {
        "id": 86,
        "question": "齐多夫定在脑脊液中的浓度为血药浓度的？",
        "option_a": "约10%",
        "option_b": "约20%",
        "option_c": "50%～60%",
        "option_d": "约80%",
        "option_e": "几乎相等",
        "correct": "C",
        "explanation": "齐多夫定易透过血脑屏障，脑脊液中浓度为血药浓度的50%～60%。",
        "category": "抗HIV药"
    },
    {
        "id": 87,
        "question": "关于去羟肌苷，下列描述正确的是？",
        "option_a": "口服生物利用度高（>80%）",
        "option_b": "进食可增加其吸收",
        "option_c": "可作为严重HIV感染的一线药物",
        "option_d": "脑脊液浓度为血药浓度的50%以上",
        "option_e": "血浆蛋白结合率高",
        "correct": "C",
        "explanation": "去羟肌苷可作为严重HIV感染的一线药物，特别适合齐多夫定不耐受或治疗无效的患者。其口服生物利用度为30%～40%，进食干扰吸收。",
        "category": "抗HIV药"
    },
    {
        "id": 88,
        "question": "扎西他滨的主要不良反应是？",
        "option_a": "骨髓抑制",
        "option_b": "剂量依赖性周围神经炎",
        "option_c": "高血糖",
        "option_d": "高血脂",
        "option_e": "肾毒性",
        "correct": "B",
        "explanation": "扎西他滨主要不良反应为剂量依赖性周围神经炎，发生率为10%～20%，停药后逐渐恢复。",
        "category": "抗HIV药"
    },
    {
        "id": 89,
        "question": "下列关于整合酶抑制药的描述，错误的是？",
        "option_a": "拉替拉韦是首个被批准的整合酶抑制药",
        "option_b": "通过抑制链转移反应阻断HIV复制",
        "option_c": "卡替拉韦是长效整合酶抑制药",
        "option_d": "整合酶催化HIV DNA整合到宿主DNA中",
        "option_e": "整合酶抑制药需要经宿主细胞磷酸化激活",
        "correct": "E",
        "explanation": "整合酶抑制药不需要经宿主细胞磷酸化激活，它们通过与整合酶中的金属辅助因子（如Mg2+或Mn2+）结合来抑制整合过程。需要磷酸化激活的是NRTI类药物。",
        "category": "抗HIV药"
    },
    {
        "id": 90,
        "question": "卡替拉韦与利匹韦林联合使用可用于？",
        "option_a": "治疗急性流感",
        "option_b": "治疗慢性乙型肝炎",
        "option_c": "接受稳定ART方案后病毒被抑制的HIV-1感染成人患者",
        "option_d": "预防流感",
        "option_e": "治疗丙型肝炎",
        "correct": "C",
        "explanation": "卡替拉韦与利匹韦林联合使用，治疗接受稳定抗逆转录病毒治疗方案后病毒被抑制（HIV-1 RNA<每毫升50拷贝）的HIV-1感染成人患者，也可用于HIV暴露前预防。",
        "category": "抗HIV药"
    },

    # ===== Mixed/Comprehensive Questions with Distractors from Other Chapters (Q91-Q100) =====
    {
        "id": 91,
        "question": "下列药物中，属于神经氨酸酶抑制药的是？",
        "option_a": "金刚烷胺（M2通道阻滞药）",
        "option_b": "氯喹（抗疟药）",
        "option_c": "甲硝唑（抗阿米巴药）",
        "option_d": "奥司他韦",
        "option_e": "吡喹酮（抗血吸虫药）",
        "correct": "D",
        "explanation": "奥司他韦属于神经氨酸酶抑制药。金刚烷胺是M2通道阻滞药，氯喹是抗疟药，甲硝唑是抗阿米巴药，吡喹酮是抗血吸虫药。",
        "category": "综合"
    },
    {
        "id": 92,
        "question": "下列药物中，作用于病毒DNA聚合酶的是？",
        "option_a": "奥司他韦（神经氨酸酶抑制药）",
        "option_b": "伯氨喹（抗疟药，作用于线粒体）",
        "option_c": "阿昔洛韦",
        "option_d": "乙胺嗪（抗丝虫药）",
        "option_e": "阿苯达唑（驱肠虫药）",
        "correct": "C",
        "explanation": "阿昔洛韦经病毒TK磷酸化后抑制病毒DNA聚合酶。奥司他韦抑制神经氨酸酶，伯氨喹抑制线粒体氧化磷酸化，乙胺嗪杀微丝蚴，阿苯达唑抑制微管聚合。",
        "category": "综合"
    },
    {
        "id": 93,
        "question": "下列哪个组合中的两种药物作用机制最相似？",
        "option_a": "阿昔洛韦与氯喹",
        "option_b": "齐多夫定与乙胺嘧啶",
        "option_c": "奥司他韦与扎那米韦",
        "option_d": "金刚烷胺与甲氟喹",
        "option_e": "利巴韦林与青蒿素",
        "correct": "C",
        "explanation": "奥司他韦和扎那米韦均为神经氨酸酶抑制药，作用机制相同。其他组合的药物作用机制不同。",
        "category": "综合"
    },
    {
        "id": 94,
        "question": "下列关于核苷类似物抗病毒药的描述，哪个组合中两者的作用靶酶相同？",
        "option_a": "齐多夫定与利托那韦",
        "option_b": "拉米夫定与索磷布韦",
        "option_c": "阿昔洛韦与膦甲酸",
        "option_d": "恩替卡韦与阿德福韦酯",
        "option_e": "奥司他韦与玛巴洛沙韦",
        "correct": "D",
        "explanation": "恩替卡韦和阿德福韦酯均抑制HBV DNA聚合酶。齐多夫定抑制逆转录酶而利托那韦抑制蛋白酶；拉米夫定抑制逆转录酶而索磷布韦抑制NS5B聚合酶；阿昔洛韦和膦甲酸均可抑制DNA聚合酶但机制不同；奥司他韦抑制神经氨酸酶而玛巴洛沙韦抑制PA亚基内切酶。",
        "category": "综合"
    },
    {
        "id": 95,
        "question": "需要经病毒胸苷激酶（TK）磷酸化才能激活的抗病毒药是？",
        "option_a": "利巴韦林",
        "option_b": "膦甲酸",
        "option_c": "阿昔洛韦",
        "option_d": "奥司他韦",
        "option_e": "金刚烷胺",
        "correct": "C",
        "explanation": "阿昔洛韦需在感染细胞内经病毒胸苷激酶（TK）磷酸化后才能发挥抗病毒作用。利巴韦林由腺苷激酶磷酸化，膦甲酸直接抑制DNA聚合酶不需磷酸化。",
        "category": "综合"
    },
    {
        "id": 96,
        "question": "下列药物与其主要抗病毒谱的配对，错误的是？",
        "option_a": "阿昔洛韦——HSV、VZV",
        "option_b": "更昔洛韦——CMV",
        "option_c": "奥司他韦——甲型和乙型流感",
        "option_d": "索磷布韦——HBV",
        "option_e": "齐多夫定——HIV",
        "correct": "D",
        "explanation": "索磷布韦是抗HCV（丙型肝炎病毒）药物，而非抗HBV（乙型肝炎病毒）药物。抗HBV的药物包括恩替卡韦、阿德福韦酯、替诺福韦等。",
        "category": "综合"
    },
    {
        "id": 97,
        "question": "下列哪种情况不属于抗病毒药的合理应用？",
        "option_a": "奥司他韦用于治疗甲型H1N1流感",
        "option_b": "阿昔洛韦用于治疗带状疱疹",
        "option_c": "金刚烷胺用于治疗乙型流感",
        "option_d": "齐多夫定联合拉米夫定治疗HIV",
        "option_e": "索磷布韦联合利巴韦林治疗基因2型丙肝",
        "correct": "C",
        "explanation": "金刚烷胺仅对甲型流感病毒有效，对乙型流感病毒无效，因此不应用于治疗乙型流感。",
        "category": "综合"
    },
    {
        "id": 98,
        "question": "关于抗病毒药的描述，下列哪项是正确的？",
        "option_a": "利巴韦林孕妇可用",
        "option_b": "更昔洛韦无明显骨髓毒性",
        "option_c": "干扰素可用于严重心脏病患者",
        "option_d": "阿昔洛韦对CMV的抑制作用较弱",
        "option_e": "奥司他韦仅对甲型流感有效",
        "correct": "D",
        "explanation": "CMV缺乏病毒胸苷激酶（TK），因此阿昔洛韦对CMV抑制作用较弱。利巴韦林孕妇禁用，更昔洛韦有骨髓抑制毒性，干扰素禁用于严重心脏病患者，奥司他韦对甲型和乙型流感均有效。",
        "category": "综合"
    },
    {
        "id": 99,
        "question": "下列药物中，口服后需要经体内代谢才能转化为活性形式的药物组是？",
        "option_a": "阿昔洛韦、膦甲酸",
        "option_b": "伐昔洛韦、奥司他韦、泛昔洛韦、巴洛沙韦玛波西酯",
        "option_c": "金刚烷胺、扎那米韦",
        "option_d": "恩替卡韦、干扰素",
        "option_e": "齐多夫定、利巴韦林",
        "correct": "B",
        "explanation": "伐昔洛韦（→阿昔洛韦）、奥司他韦（→奥司他韦羧酸盐）、泛昔洛韦（→喷昔洛韦）、巴洛沙韦玛波西酯（→巴洛沙韦酸）均为前体药物，需在体内代谢转化为活性形式。",
        "category": "综合"
    },
    {
        "id": 100,
        "question": "HIV感染后，病毒DNA整合到宿主细胞基因组中需要哪种酶的参与？",
        "option_a": "逆转录酶",
        "option_b": "蛋白酶",
        "option_c": "整合酶",
        "option_d": "RNA聚合酶",
        "option_e": "拓扑异构酶",
        "correct": "C",
        "explanation": "HIV双链DNA转运到细胞核后，在整合酶的作用下，病毒DNA基因组插入到宿主细胞基因组中。整合酶抑制药如拉替拉韦通过抑制链转移反应阻断此过程。",
        "category": "抗HIV药"
    },
]

# Write CSV
csv_path = "/Users/weixu/Downloads/pnas/antiviral.csv"
with open(csv_path, "w", newline="", encoding="utf-8-sig") as f:
    writer = csv.writer(f)
    writer.writerow(["id", "question", "option_a", "option_b", "option_c", "option_d", "option_e", "correct", "explanation", "category"])
    for q in questions:
        writer.writerow([
            q["id"], q["question"], q["option_a"], q["option_b"],
            q["option_c"], q["option_d"], q["option_e"],
            q["correct"], q["explanation"], q["category"]
        ])

print(f"Generated {len(questions)} questions to {csv_path}")

# Print category counts
from collections import Counter
cats = Counter(q["category"] for q in questions)
for cat, count in cats.items():
    print(f"  {cat}: {count} questions")
