#!/usr/bin/env python3
"""
Translates pharmacology quiz CSVs from Chinese to English (Chapters 42-46).
Uses compound-word dictionaries + removes remaining Chinese characters.
"""

import csv, re, os

BASE = "/Users/weixu/Downloads/pnas"

TYPE_MAP = {"是非题":"True/False","单选题":"Single Choice","简答题(多选)":"Multiple Choice"}
CORRECT_MAP = {"正确":"True","错误":"False"}

CAT_MAP = {
    "一线抗结核药-异烟肼":"First-line Antituberculosis Drugs: Isoniazid",
    "一线抗结核药-利福平":"First-line Antituberculosis Drugs: Rifampin",
    "一线抗结核药-乙胺丁醇":"First-line Antituberculosis Drugs: Ethambutol",
    "一线抗结核药-吡嗪酰胺":"First-line Antituberculosis Drugs: Pyrazinamide",
    "一线抗结核药-链霉素":"First-line Antituberculosis Drugs: Streptomycin",
    "抗结核药应用原则":"Principles of Antituberculosis Therapy",
    "二线抗结核药-对氨基水杨酸钠":"Second-line Drugs: Sodium Aminosalicylate",
    "二线抗结核药-乙硫异烟胺/丙硫异烟胺":"Second-line Drugs: Ethionamide/Protionamide",
    "二线抗结核药-卷曲霉素":"Second-line Drugs: Capreomycin",
    "抗结核药分类":"Classification of Antituberculosis Drugs",
    "新型抗结核药":"Novel Antituberculosis Drugs",
    "新型抗结核药-贝达喹啉":"Novel Drugs: Bedaquiline",
    "抗麻风药":"Antileprosy Drugs",
    "抗麻风药-氨苯砜":"Antileprosy Drugs: Dapsone",
    "抗麻风药-氯法齐明":"Antileprosy Drugs: Clofazimine",
    "抗麻风药-沙利度胺":"Antileprosy Drugs: Thalidomide",
    "抗麻风药-利福平":"Antileprosy Drugs: Rifampin",
    "抗真菌药总论":"Antifungal Drugs: General Principles",
    "多烯类":"Polyenes",
    "唑类":"Azoles",
    "棘白菌素类":"Echinocandins",
    "嘧啶类":"Pyrimidine Antifungals",
    "丙烯胺类/苄胺类":"Allylamines/Benzylamines",
    "吗啉类/其他":"Morpholines/Others",
    "总论":"General Principles",
    "抗流感病毒药":"Anti-Influenza Virus Drugs",
    "广谱抗病毒药":"Broad-Spectrum Antiviral Drugs",
    "抗疱疹病毒药":"Anti-Herpesvirus Drugs",
    "抗肝炎病毒药":"Anti-Hepatitis Virus Drugs",
    "抗HIV药":"Anti-HIV Drugs",
    "综合":"Comprehensive Review",
    "抗疟药":"Antimalarial Drugs",
    "抗阿米巴药及抗滴虫药":"Anti-Amebic and Anti-Trichomonal Drugs",
    "驱肠虫药":"Anthelmintic Drugs",
    "抗血吸虫药和抗丝虫药":"Antischistosomal and Antifilarial Drugs",
    "细胞周期与药物分类":"Cell Cycle and Drug Classification",
    "抗代谢药":"Antimetabolites",
    "烷化剂及铂类":"Alkylating Agents and Platinum Compounds",
    "抗肿瘤抗生素":"Antitumor Antibiotics",
    "植物药及蛋白合成抑制":"Plant-Derived Drugs and Protein Synthesis Inhibitors",
    "拓扑异构酶抑制药":"Topoisomerase Inhibitors",
    "内分泌治疗":"Endocrine Therapy",
    "分子靶向药物":"Molecular Targeted Therapy",
    "免疫治疗":"Immunotherapy",
    "其他抗肿瘤药":"Other Antineoplastic Drugs",
    "耐药性机制":"Drug Resistance Mechanisms",
    "耐药性及不良反应":"Drug Resistance and Adverse Effects",
    "不良反应":"Adverse Effects",
    "抗肿瘤药合理应用":"Rational Use of Antineoplastic Drugs",
}

# ===== COMPREHENSIVE DICTIONARY - compound words only (2+ chars) =====
D = {
    # === DRUG NAMES (longest first) ===
    "巴洛沙韦玛波西酯":"baloxavir marboxil",
    "丙酚替诺福韦":"tenofovir alafenamide",
    "艾米替诺福韦":"tenofovir amibufenamide",
    "对氨基水杨酸钠":"sodium aminosalicylate",
    "两性霉素B":"amphotericin B",
    "阿基仑赛注射液":"axicabtagene ciloleucel injection",
    "阿德福韦酯":"adefovir dipivoxil",
    "磷酸氟达拉滨":"fludarabine phosphate",
    "格卡瑞韦/哌仑他韦":"glecaprevir/pibrentasvir",
    "艾尔巴韦/格拉瑞韦":"elbasvir/grazoprevir",
    "索磷布韦":"sofosbuvir",
    "格卡瑞韦":"glecaprevir",
    "哌仑他韦":"pibrentasvir",
    "艾尔巴韦":"elbasvir",
    "格拉瑞韦":"grazoprevir",
    "达拉他韦":"daclatasvir",
    "达塞布韦":"dasabuvir",
    "巴洛沙韦":"baloxavir",
    "法匹拉韦":"favipiravir",
    "洛匹那韦":"lopinavir",
    "利托那韦":"ritonavir",
    "沙奎那韦":"saquinavir",
    "拉替拉韦":"raltegravir",
    "多替拉韦":"dolutegravir",
    "卡替拉韦":"cabotegravir",
    "马拉维若":"maraviroc",
    "恩夫韦肽":"enfuvirtide",
    "齐多夫定":"zidovudine",
    "司他夫定":"stavudine",
    "拉米夫定":"lamivudine",
    "去羟肌苷":"didanosine",
    "依非韦伦":"efavirenz",
    "奈韦拉平":"nevirapine",
    "利匹韦林":"rilpivirine",
    "扎西他滨":"zalcitabine",
    "奥司他韦":"oseltamivir",
    "扎那米韦":"zanamivir",
    "金刚烷胺":"amantadine",
    "金刚乙胺":"rimantadine",
    "利巴韦林":"ribavirin",
    "阿昔洛韦":"acyclovir",
    "更昔洛韦":"ganciclovir",
    "伐昔洛韦":"valacyclovir",
    "泛昔洛韦":"famciclovir",
    "喷昔洛韦":"penciclovir",
    "曲氟尿苷":"trifluridine",
    "阿糖腺苷":"vidarabine",
    "阿德福韦":"adefovir",
    "恩替卡韦":"entecavir",
    "替诺福韦":"tenofovir",
    "聚乙二醇干扰素":"pegylated interferon",
    "聚乙二醇干扰素α":"pegylated interferon-alpha",
    "异烟肼":"isoniazid",
    "利福平":"rifampin",
    "乙胺丁醇":"ethambutol",
    "吡嗪酰胺":"pyrazinamide",
    "链霉素":"streptomycin",
    "利福喷丁":"rifapentine",
    "德拉马尼":"delamanid",
    "普托马尼":"pretomanid",
    "利奈唑胺":"linezolid",
    "环丝氨酸":"cycloserine",
    "贝达喹啉":"bedaquiline",
    "卷曲霉素":"capreomycin",
    "氨苯砜":"dapsone",
    "氯法齐明":"clofazimine",
    "沙利度胺":"thalidomide",
    "两性霉素":"amphotericin",
    "制霉菌素":"nystatin",
    "酮康唑":"ketoconazole",
    "氟康唑":"fluconazole",
    "伊曲康唑":"itraconazole",
    "伏立康唑":"voriconazole",
    "艾沙康唑":"isavuconazole",
    "奥特康唑":"oteseconazole",
    "克霉唑":"clotrimazole",
    "卡泊芬净":"caspofungin",
    "米卡芬净":"micafungin",
    "阿尼芬净":"anidulafungin",
    "氟胞嘧啶":"flucytosine",
    "特比萘芬":"terbinafine",
    "布替萘芬":"butenafine",
    "阿莫罗芬":"amorolfine",
    "灰黄霉素":"griseofulvin",
    "氯喹":"chloroquine",
    "奎宁":"quinine",
    "伯氨喹":"primaquine",
    "乙胺嘧啶":"pyrimethamine",
    "青蒿素":"artemisinin",
    "蒿甲醚":"artemether",
    "青蒿琥酯":"artesunate",
    "甲氟喹":"mefloquine",
    "甲硝唑":"metronidazole",
    "替硝唑":"tinidazole",
    "奥硝唑":"ornidazole",
    "依米丁":"emetine",
    "喹碘方":"chiniofon",
    "双碘喹啉":"diiodohydroxyquinoline",
    "二氯尼特":"diloxanide",
    "巴龙霉素":"paromomycin",
    "乙酰胂胺":"acetarsone",
    "吡喹酮":"praziquantel",
    "乙胺嗪":"diethylcarbamazine",
    "甲苯达唑":"mebendazole",
    "阿苯达唑":"albendazole",
    "左旋咪唑":"levamisole",
    "噻嘧啶":"pyrantel",
    "氯硝柳胺":"niclosamide",
    "伊维菌素":"ivermectin",
    "环磷酰胺":"cyclophosphamide",
    "白消安":"busulfan",
    "卡莫司汀":"carmustine",
    "噻替派":"thiotepa",
    "美法仑":"melphalan",
    "顺铂":"cisplatin",
    "卡铂":"carboplatin",
    "达卡巴嗪":"dacarbazine",
    "丙卡巴肼":"procarbazine",
    "氟尿嘧啶":"fluorouracil",
    "甲氨蝶呤":"methotrexate",
    "阿糖胞苷":"cytarabine",
    "羟基脲":"hydroxyurea",
    "巯嘌呤":"mercaptopurine",
    "卡培他滨":"capecitabine",
    "阿扎胞苷":"azacitidine",
    "克拉屈滨":"cladribine",
    "氟达拉滨":"fludarabine",
    "多柔比星":"doxorubicin",
    "柔红霉素":"daunorubicin",
    "放线菌素D":"dactinomycin",
    "博来霉素":"bleomycin",
    "丝裂霉素":"mitomycin",
    "丝裂霉素C":"mitomycin C",
    "长春碱":"vinblastine",
    "长春新碱":"vincristine",
    "依托泊苷":"etoposide",
    "鬼臼毒素":"podophyllotoxin",
    "喜树碱":"camptothecin",
    "拓扑替康":"topotecan",
    "羟喜树碱":"hydroxycamptothecin",
    "紫杉醇":"paclitaxel",
    "多西他赛":"docetaxel",
    "三尖杉酯碱":"harringtonine",
    "高三尖杉酯碱":"homoharringtonine",
    "L-门冬酰胺酶":"L-asparaginase",
    "他莫昔芬":"tamoxifen",
    "雷洛昔芬":"raloxifene",
    "泼尼松":"prednisone",
    "地塞米松":"dexamethasone",
    "氟他胺":"flutamide",
    "比卡鲁胺":"bicalutamide",
    "氨鲁米特":"aminoglutethimide",
    "戈舍瑞林":"goserelin",
    "己烯雌酚":"diethylstilbestrol",
    "甲羟孕酮":"medroxyprogesterone",
    "甲地孕酮":"megestrol",
    "伊马替尼":"imatinib",
    "吉非替尼":"gefitinib",
    "厄洛替尼":"erlotinib",
    "埃克替尼":"icotinib",
    "阿法替尼":"afatinib",
    "达可替尼":"dacomitinib",
    "奥希替尼":"osimertinib",
    "伏美替尼":"furmonertinib",
    "阿美替尼":"almonertinib",
    "索拉非尼":"sorafenib",
    "曲妥珠单抗":"trastuzumab",
    "贝伐珠单抗":"bevacizumab",
    "利妥昔单抗":"rituximab",
    "硼替佐米":"bortezomib",
    "伊布替尼":"ibrutinib",
    "泽布替尼":"zanubrutinib",
    "奥拉帕利":"olaparib",
    "伊匹木单抗":"ipilimumab",
    "纳武利尤单抗":"nivolumab",
    "帕博利珠单抗":"pembrolizumab",
    "特瑞普利单抗":"toripalimab",
    "信迪利单抗":"sintilimab",
    "阿替利珠单抗":"atezolizumab",
    "卡度尼利单抗":"cadonilimab",
    "阿基仑赛":"axicabtagene ciloleucel",
    "三氧化二砷":"arsenic trioxide",
    "维A酸":"tretinoin",
    "乙硫异烟胺":"ethionamide",
    "丙硫异烟胺":"protionamide",
    "华法林":"warfarin",
    "美沙酮":"methadone",
    "普萘洛尔":"propranolol",
    "地高辛":"digoxin",
    "别嘌醇":"allopurinol",
    "维生素B6":"vitamin B6",
    "维生素B12":"vitamin B12",
    "苯妥英钠":"phenytoin sodium",
    "青霉素G":"penicillin G",
    "红霉素":"erythromycin",
    "林可霉素":"lincomycin",
    "四环素":"tetracycline",
    "氯霉素":"chloramphenicol",
    "膦甲酸":"foscarnet",

    # === PATHOGENS / DISEASES ===
    "结核分枝杆菌":"Mycobacterium tuberculosis",
    "麻风分枝杆菌":"Mycobacterium leprae",
    "白色念珠菌":"Candida albicans",
    "烟曲霉菌":"Aspergillus fumigatus",
    "新生隐球菌":"Cryptococcus neoformans",
    "溶组织内阿米巴":"Entamoeba histolytica",
    "阴道毛滴虫":"Trichomonas vaginalis",
    "蓝氏贾第鞭毛虫":"Giardia lamblia",
    "日本血吸虫":"Schistosoma japonicum",
    "华支睾吸虫":"Clonorchis sinensis",
    "牛带绦虫":"Taenia saginata",
    "猪带绦虫":"Taenia solium",
    "阔节裂头绦虫":"Diphyllobothrium latum",
    "粪类圆线虫":"Strongyloides stercoralis",
    "甲型流感病毒":"influenza A virus",
    "乙型流感病毒":"influenza B virus",
    "呼吸道合胞病毒":"respiratory syncytial virus (RSV)",
    "单纯疱疹病毒1型":"HSV-1",
    "单纯疱疹病毒2型":"HSV-2",
    "单纯疱疹病毒":"herpes simplex virus (HSV)",
    "水痘-带状疱疹病毒":"varicella-zoster virus (VZV)",
    "爱泼斯坦-巴尔病毒":"Epstein-Barr virus (EBV)",
    "乙型肝炎病毒":"hepatitis B virus (HBV)",
    "丙型肝炎病毒":"hepatitis C virus (HCV)",
    "人类免疫缺陷病毒":"human immunodeficiency virus (HIV)",
    "慢性髓细胞性白血病":"chronic myeloid leukemia (CML)",
    "慢性髓细胞白血病":"chronic myeloid leukemia (CML)",
    "慢性淋巴细胞白血病":"chronic lymphocytic leukemia (CLL)",
    "慢性淋巴细胞性白血病":"chronic lymphocytic leukemia (CLL)",
    "急性髓细胞白血病":"acute myeloid leukemia (AML)",
    "急性淋巴细胞白血病":"acute lymphoblastic leukemia (ALL)",
    "急性早幼粒细胞白血病":"acute promyelocytic leukemia (APL)",
    "急性单核细胞白血病":"acute monocytic leukemia",
    "毛细胞白血病":"hairy cell leukemia (HCL)",
    "霍奇金淋巴瘤":"Hodgkin lymphoma",
    "非小细胞肺癌":"non-small cell lung cancer (NSCLC)",
    "多发性骨髓瘤":"multiple myeloma",
    "胃肠道间质肿瘤":"gastrointestinal stromal tumor (GIST)",
    "绒毛膜上皮癌":"choriocarcinoma",
    "神经母细胞瘤":"neuroblastoma",
    "横纹肌肉瘤":"rhabdomyosarcoma",
    "肾母细胞瘤":"Wilms tumor",
    "套细胞淋巴瘤":"mantle cell lymphoma",
    "大B细胞淋巴瘤":"large B-cell lymphoma",
    "小细胞肺癌":"small cell lung cancer",
    "恶性淋巴瘤":"malignant lymphoma",
    "骨髓发育不良":"myelodysplasia",
    "慢性阻塞性肺疾病":"chronic obstructive pulmonary disease (COPD)",
    "子宫内膜异位症":"endometriosis",
    "结核性脑膜炎":"tuberculous meningitis",
    "粟粒性结核":"miliary tuberculosis",
    "初治肺结核":"newly diagnosed pulmonary tuberculosis",
    "慢性空洞性肺结核":"chronic cavitary pulmonary tuberculosis",
    "侵袭性曲霉病":"invasive aspergillosis",
    "侵袭性肺曲霉病":"invasive pulmonary aspergillosis",
    "念珠菌血症":"candidemia",
    "隐球菌性脑膜炎":"cryptococcal meningitis",
    "复发性外阴阴道念珠菌病":"recurrent vulvovaginal candidiasis (RVVC)",
    "侵袭性念珠菌病":"invasive candidiasis",
    "皮肤黏膜念珠菌感染":"mucocutaneous candidiasis",
    "播散性组织胞浆菌病":"disseminated histoplasmosis",
    "阿米巴痢疾":"amebic dysentery",
    "阿米巴肝脓肿":"amebic liver abscess",
    "肠外阿米巴病":"extraintestinal amebiasis",
    "急性阿米巴痢疾":"acute amebic dysentery",
    "眼囊尾蚴病":"ocular cysticercosis",
    "阿米巴肺脓肿":"amebic lung abscess",
    "血吸虫病":"schistosomiasis",
    "丝虫病":"filariasis",
    "带状疱疹":"herpes zoster",
    "尖锐湿疣":"condyloma acuminatum",
    "生殖器疱疹":"genital herpes",
    "带状疱疹后神经痛":"postherpetic neuralgia",
    "巨细胞病毒视网膜炎":"CMV retinitis",
    "乙型肝炎":"hepatitis B",
    "丙型肝炎":"hepatitis C",
    "甲型肝炎":"hepatitis A",
    "丁型肝炎":"hepatitis D",
    "戊型肝炎":"hepatitis E",
    "原发性肝细胞癌":"hepatocellular carcinoma (HCC)",
    "慢性乙型肝炎":"chronic hepatitis B",
    "慢性丙型肝炎":"chronic hepatitis C",
    "糖尿病":"diabetes mellitus",
    "高血压":"hypertension",
    "肝硬化":"liver cirrhosis",
    "肝纤维化":"liver fibrosis",
    "肺外结核":"extrapulmonary tuberculosis",
    "耐多药结核病":"multidrug-resistant tuberculosis",
    "流行性乙型脑炎":"Japanese encephalitis",
    "急性化脓性扁桃体炎":"acute suppurative tonsillitis",

    # === FULL-LENGTH TECHNICAL PHRASES (longest first) ===
    "过氧化氢-过氧化物酶":"catalase-peroxidase (KatG)",
    "烯酰酰基载体蛋白还原酶":"enoyl-ACP reductase (InhA)",
    "阿拉伯糖基转移酶":"arabinosyl transferase",
    "电压门控钙通道":"voltage-gated calcium channel",
    "葡萄糖-6-磷酸脱氢酶":"glucose-6-phosphate dehydrogenase (G6PD)",
    "次黄嘌呤-鸟嘌呤磷酸核糖转移酶":"HGPRT",
    "谷胱甘肽硫转移酶":"glutathione S-transferase",
    "黄嘌呤氧化酶":"xanthine oxidase",
    "促性腺激素释放激素":"gonadotropin-releasing hormone (GnRH)",
    "Raf-MEK-ERK信号通路":"Raf-MEK-ERK signaling pathway",
    "非核苷类逆转录酶抑制药":"non-nucleoside reverse transcriptase inhibitor (NNRTI)",
    "核苷类逆转录酶抑制药":"nucleoside reverse transcriptase inhibitor (NRTI)",
    "细胞周期非特异性药物":"cell cycle-nonspecific agent (CCNSA)",
    "细胞周期特异性药物":"cell cycle-specific agent (CCSA)",
    "还原型硝基咪唑化合物":"reduced nitroimidazole compound",
    "免疫检查点抑制药":"immune checkpoint inhibitor",
    "蛋白酶体抑制药":"proteasome inhibitor",
    "泛素-蛋白酶体系统":"ubiquitin-proteasome system",
    "二氢叶酸还原酶抑制药":"dihydrofolate reductase inhibitor",
    "胸苷酸合成酶抑制药":"thymidylate synthase inhibitor",
    "嘌呤核苷酸互变抑制药":"purine nucleotide interconversion inhibitor",
    "核糖核苷酸还原酶抑制药":"ribonucleotide reductase inhibitor",
    "拓扑异构酶抑制药":"topoisomerase inhibitor",
    "芳香化酶抑制药":"aromatase inhibitor",
    "神经氨酸酶抑制药":"neuraminidase inhibitor",
    "酪氨酸激酶抑制药":"tyrosine kinase inhibitor (TKI)",
    "DNA聚合酶抑制药":"DNA polymerase inhibitor",
    "ATP依赖性药物外排泵":"ATP-dependent drug efflux pump",
    "非甾体类抗雄激素药":"nonsteroidal antiandrogen",
    "去极化神经肌肉阻滞药":"depolarizing neuromuscular blocker",
    "二氢叶酸合成酶":"dihydropteroate synthase",
    "二氢蝶酸合酶":"dihydropteroate synthase",
    "二氢叶酸还原酶":"dihydrofolate reductase",
    "核糖核苷酸还原酶":"ribonucleotide reductase",
    "琥珀酸脱氢酶":"succinate dehydrogenase",
    "延胡索酸还原酶":"fumarate reductase",
    "胸苷酸合成酶":"thymidylate synthase",
    "胞嘧啶脱氨酶":"cytosine deaminase",
    "碱性磷酸酶":"alkaline phosphatase",
    "雌激素受体部分激动药":"estrogen receptor partial agonist",
    "促黄体生成素":"luteinizing hormone (LH)",
    "促红细胞生成素":"erythropoietin",
    "粒细胞集落刺激因子":"G-CSF",
    "全反式维甲酸":"all-trans retinoic acid",
    "高铁血红蛋白血症":"methemoglobinemia",
    "急性溶血性贫血":"acute hemolytic anemia",
    "急性乙醛中毒":"acute acetaldehyde poisoning",
    "醇脱氢酶抑制药":"alcohol dehydrogenase inhibitor",
    "肾上腺皮质激素":"adrenocortical hormones",
    "二氢睾酮受体":"dihydrotestosterone receptor",
    "粒细胞缺乏症":"agranulocytosis",
    "再生障碍性贫血":"aplastic anemia",
    "嗜酸性粒细胞增多":"eosinophilia",
    "第二原发恶性肿瘤":"second primary malignancy",
    "磷酰胺氮芥":"phosphoramide mustard",
    "醛磷酰胺":"aldophosphamide",
    "脂质过氧化物":"lipid peroxides",
    "巯乙磺酸钠":"sodium 2-mercaptoethanesulfonate",
    "出血性膀胱炎":"hemorrhagic cystitis",
    "球后视神经炎":"retrobulbar neuritis",
    "周围神经炎":"peripheral neuritis",
    "周围神经病变":"peripheral neuropathy",
    "间质性肺炎":"interstitial pneumonia",
    "间质性肾炎":"interstitial nephritis",
    "流感样综合征":"flu-like syndrome",
    "麻风结节性红斑":"erythema nodosum leprosum (ENL)",
    "氨苯砜综合征":"dapsone syndrome",
    "剥脱性皮炎":"exfoliative dermatitis",
    "高尿酸血症":"hyperuricemia",
    "高血糖症":"hyperglycemia",
    "高脂血症":"hyperlipidemia",
    "口腔黏膜炎":"oral mucositis",
    "尖端扭转型室速":"torsades de pointes",
    "全血细胞减少":"pancytopenia",
    "粒细胞缺乏":"agranulocytosis",
    "白细胞减少":"leukopenia",
    "血小板减少":"thrombocytopenia",
    "嗜酸性粒细胞":"eosinophils",
    "色素沉着":"pigmentation",
    "红棕色色素沉着":"reddish-brown pigmentation",
    "过敏反应":"hypersensitivity reaction",
    "胃肠道反应":"gastrointestinal reactions",
    "药物相互作用":"drug interactions",
    "交叉耐药性":"cross-resistance",
    "多药耐药性":"multidrug resistance (MDR)",
    "获得性耐药性":"acquired resistance",
    "天然耐药性":"intrinsic resistance",
    "中枢神经系统":"central nervous system (CNS)",
    "造血系统":"hematopoietic system",
    "免疫缺陷":"immunodeficiency",
    "暴露前预防":"pre-exposure prophylaxis (PrEP)",
    "母婴传播":"mother-to-child transmission",
    "机会性感染":"opportunistic infection",
    "病毒载量":"viral load",
    "感觉神经节":"sensory ganglia",
    "视觉障碍":"visual disturbance",
    "听力减退":"hearing loss",
    "视力减退":"visual impairment",
    "视力模糊":"blurred vision",
    "色觉异常":"color vision abnormality",
    "肌肉酸痛":"myalgia",
    "结节红斑":"erythema nodosum",
    "淋巴结肿大":"lymphadenopathy",
    "呼吸困难":"dyspnea",
    "心力衰竭":"heart failure",
    "急性心力衰竭":"acute heart failure",
    "QT间期延长":"QT interval prolongation",
    "液体潴留":"fluid retention",
    "外周性水肿":"peripheral edema",
    "胸腔积液":"pleural effusion",
    "肾功能不全":"renal insufficiency",
    "肾功能减退":"decreased renal function",
    "肝功能不全":"hepatic insufficiency",
    "肾小球滤过率":"glomerular filtration rate",
    "肾小管损伤":"renal tubular injury",
    "氮质血症":"azotemia",
    "嗜酸性粒细胞":"eosinophils",
    "短暂性":"transient",

    # === MID-LENGTH COMPOUNDS (3-5 chars) ===
    "口服生物利用度":"oral bioavailability",
    "血浆消除半衰期":"plasma elimination half-life",
    "消除半衰期":"elimination half-life",
    "血浆蛋白结合率":"plasma protein binding",
    "首关效应":"first-pass effect",
    "首过消除":"first-pass elimination",
    "生物利用度":"bioavailability",
    "肠肝循环":"enterohepatic circulation",
    "剂量限制性毒性":"dose-limiting toxicity",
    "药代动力学":"pharmacokinetics",
    "肝药酶诱导剂":"hepatic enzyme inducer",
    "肝药酶抑制剂":"hepatic enzyme inhibitor",
    "脂质体制剂":"liposomal formulation",
    "标准治疗方案":"standard treatment regimen",
    "短程化疗":"short-course chemotherapy",
    "作用机制":"mechanism of action",
    "全效杀菌药":"fully bactericidal drug",
    "广谱杀菌药":"broad-spectrum bactericidal drug",
    "广谱抗病毒药":"broad-spectrum antiviral drug",
    "广谱抗真菌药":"broad-spectrum antifungal drug",
    "广谱驱虫药":"broad-spectrum anthelmintic",
    "核苷类似物":"nucleoside analog",
    "核苷酸类似物":"nucleotide analog",
    "鸟嘌呤核苷类似物":"guanosine nucleoside analog",
    "嘧啶类似物":"pyrimidine analog",
    "焦磷酸类似物":"pyrophosphate analog",
    "唾液酸类似物":"sialic acid analog",
    "单克隆抗体":"monoclonal antibody",
    "双特异性抗体":"bispecific antibody",
    "小分子化合物":"small-molecule compound",
    "多肽类抗生素":"polypeptide antibiotic",
    "氨基糖苷类抗生素":"aminoglycoside antibiotic",
    "一线抗结核药":"first-line antituberculosis drug",
    "二线抗结核药":"second-line antituberculosis drug",
    "一线抗结核病药":"first-line antituberculosis drug",
    "二线抗结核病药":"second-line antituberculosis drug",
    "一线推荐":"first-line recommendation",
    "二线推荐":"second-line recommendation",
    "抗结核病化疗":"antituberculosis chemotherapy",
    "抗结核治疗":"antituberculosis therapy",
    "卡介苗":"BCG vaccine",
    "一线治疗":"first-line treatment",
    "二线治疗":"second-line treatment",
    "首选治疗":"first-line treatment",
    "替代治疗":"alternative treatment",
    "联合用药":"combination therapy",
    "联合用药疗法":"combination chemotherapy",
    "大剂量间歇疗法":"high-dose intermittent therapy",
    "序贯疗法":"sequential therapy",
    "招募作用":"recruitment effect",
    "同步化作用":"synchronization effect",
    "诱导缓解":"remission induction",
    "维持治疗":"maintenance therapy",
    "靶向治疗":"targeted therapy",
    "放射治疗":"radiation therapy",
    "大剂量间歇":"high-dose intermittent",
    "间歇给药":"intermittent dosing",
    "间歇疗法":"intermittent therapy",
    "连续使用":"continuous use",
    "长期使用":"long-term use",
    "短期使用":"short-term use",
    "生长旺盛":"actively growing",
    "静止期":"stationary phase",
    "繁殖期":"replicating phase",
    "胞内结核菌":"intracellular M. tuberculosis",
    "胞内菌":"intracellular bacteria",
    "巨噬细胞":"macrophages",
    "酸性吞噬溶酶体":"acidic phagolysosome",
    "酸性环境":"acidic environment",
    "碱性环境":"alkaline environment",
    "中性环境":"neutral environment",
    "渗出性病灶":"exudative lesions",
    "纤维化病灶":"fibrotic lesions",
    "空洞病灶":"cavitary lesions",
    "早期病灶":"early lesions",
    "环死":"necrosis",
    "干酪样":"caseous",
    "急性期":"acute phase",
    "慢性期":"chronic phase",
    "缓解期":"remission phase",
    "复发期":"relapse phase",
    "终末期":"terminal stage",
    "稳定期":"stable phase",
    "进展期":"progressive phase",
    "休息期":"resting phase",
    "发作期":"acute episode",
    "缓慢慢":"slow",
    "迅速速":"rapid",

    # Antimicrobial specific
    "麦角固醇":"ergosterol",
    "胆固醇":"cholesterol",
    "羊毛固醇":"lanosterol",
    "分枝菌酸":"mycolic acid",
    "细胞色素P450":"cytochrome P450 (CYP450)",
    "过氧化氢":"hydrogen peroxide",
    "血红蛋白":"hemoglobin",
    "血红素铁":"heme iron",
    "活性氧":"reactive oxygen species",
    "自由基":"free radicals",
    "过氧桥":"peroxide bridge",
    "溶酶体":"lysosome",
    "梭菌":"Clostridium",
    "金鸡纳反应":"cinchonism",
    "纺锤体":"mitotic spindle",
    "微管蛋白":"tubulin",
    "纺锤体形成":"spindle formation",
    "微管蛋白聚合":"tubulin polymerization",
    "微管蛋白解聚":"tubulin depolymerization",
    "微管解聚":"microtubule depolymerization",
    "微管聚合":"microtubule polymerization",
    "煤焦油":"coal tar",
    "叶酸代谢":"folate metabolism",
    "嘌呤代谢":"purine metabolism",
    "嘧啶代谢":"pyrimidine metabolism",
    "一碳单位转移":"one-carbon unit transfer",
    "掺伪机制":"fraudulent incorporation mechanism",
    "伪核苷酸":"pseudonucleotide",
    "四氢叶酸":"tetrahydrofolate (FH4)",
    "二氢叶酸":"dihydrofolate (FH2)",
    "甲酰四氢叶酸":"folinic acid (leucovorin)",
    "亚叶酸钙":"calcium folinate",
    "拯救剂":"rescue agent",
    "右丙亚胺":"dexrazoxane",
    "右雷佐生":"dexrazoxane",
    "美司钠":"mesna",
    "丙烯醛":"acrolein",
    "氧自由基":"oxygen free radicals",
    "辅酶Q10":"coenzyme Q10",
    "苯醌":"benzoquinone",
    "乙撑亚胺基":"ethyleneimine group",
    "氨甲酰基":"carbamoyl group",
    "三磷酸胞苷":"CTP",
    "脱氧胞苷激酶":"deoxycytidine kinase",
    "活性二磷酸盐":"active diphosphate",
    "尿苷三磷酸类似物":"uridine triphosphate analog",
    "脱氧胸苷酸":"dTMP",
    "脱氧尿苷酸":"dUMP",
    "6-硫代肌苷酸":"6-thioinosinic acid (T-IMP)",
    "环孢素A":"cyclosporine A",
    "腺苷脱氨酶":"adenosine deaminase",
    "DNA引物酶":"DNA primase",
    "DNA连接酶":"DNA ligase",
    "活性三磷酸代谢物":"active triphosphate metabolite",
    "IMP脱氢酶":"IMP dehydrogenase",
    "GMP转移酶":"GMP transferase",
    "mRNA帽结构":"mRNA cap structure",
    "三磷酸":"triphosphate",
    "二磷酸":"diphosphate",
    "单磷酸":"monophosphate",
    "磷酸化":"phosphorylation",
    "磷酸化激酶":"phosphorylation kinase",
    "水溶性的":"water-soluble",

    # Drug classes
    "烷化剂":"alkylating agent",
    "抗代谢药":"antimetabolite",
    "抗肿瘤抗生素":"antitumor antibiotic",
    "铂类配合物":"platinum coordination compound",
    "长春碱类":"vinca alkaloids",
    "鬼臼毒素类":"podophyllotoxins",
    "喜树碱类":"camptothecins",
    "紫杉醇类":"taxanes",
    "三尖杉酯碱类":"harringtonines",
    "拓扑异构酶":"topoisomerase",
    "分子靶向药物":"molecular targeted drug",
    "分子靶向":"molecular targeted",
    "内分泌治疗":"endocrine therapy",
    "硝基咪唑类":"nitroimidazoles",
    "苯并咪唑类":"benzimidazoles",
    "二氯乙酰胺类":"dichloroacetamide derivatives",
    "卤化喹啉类":"halogenated quinolines",
    "水杨酰胺类":"salicylamide derivatives",
    "亚硝脲类":"nitrosoureas",
    "三氮烯类":"triazenes",
    "双环硝基咪唑类":"bicyclic nitroimidazoles",
    "二芳基喹啉类":"diarylquinolines",
    "异烟酸衍生物":"isonicotinic acid derivative",
    "氨基糖苷类":"aminoglycosides",

    # Viral targets
    "逆转录酶":"reverse transcriptase",
    "神经氨酸酶":"neuraminidase",
    "胸苷激酶":"thymidine kinase (TK)",
    "整合酶":"integrase",
    "蛋白酶":"protease",
    "PA亚基":"PA subunit",
    "PB1亚基":"PB1 subunit",
    "PB2亚基":"PB2 subunit",
    "内切酶活性":"endonuclease activity",
    "M2蛋白":"M2 protein",
    "质子通道":"proton channel",
    "前体蛋白":"precursor protein",
    "链终止":"chain termination",
    "链转移反应":"strand transfer reaction",
    "NS3/4A蛋白酶":"NS3/4A protease",
    "NS5B聚合酶":"NS5B polymerase",
    "NS5A抑制药":"NS5A inhibitor",
    "直接抗病毒药":"direct-acting antiviral (DAA)",
    "M2通道阻滞药":"M2 channel blocker",
    "RNA聚合酶抑制药":"RNA polymerase inhibitor",
    "YMDD基序":"YMDD motif",
    "基因突变":"gene mutation",
    "katG基因":"katG gene",
    "rpoB基因":"rpoB gene",
    "gyrA基因":"gyrA gene",
    "inhA基因":"inhA gene",
    "kasA基因":"kasA gene",
    "ndh基因":"ndh基因",
    "mecA基因":"mecA gene",
    "DNA旋转酶":"DNA gyrase",
    "DNA聚合酶":"DNA polymerase",
    "RNA聚合酶":"RNA polymerase",
    "DNA合成":"DNA synthesis",
    "DNA复制":"DNA replication",
    "DNA修复":"DNA repair",
    "DNA链断裂":"DNA strand breaks",
    "DNA链再连接":"DNA strand re-ligation",
    "DNA链延长终止":"DNA chain termination",
    "DNA烷化":"DNA alkylation",
    "DNA交联":"DNA cross-linking",
    "DNA甲基化":"DNA methylation",
    "RNA合成":"RNA synthesis",
    "mRNA合成":"mRNA synthesis",
    "mRNA转录":"mRNA transcription",
    "核酸合成":"nucleic acid synthesis",
    "蛋白质合成":"protein synthesis",
    "有丝分裂":"mitosis",
    "胸苷酸激酶":"thymidylate kinase",

    # Cancer targets
    "血管生成":"angiogenesis",
    "抗血管生成":"anti-angiogenesis",
    "肿瘤血管形成":"tumor angiogenesis",
    "新血管形成":"neovascularization",
    "营养供应":"nutrient supply",
    "抗肿瘤血管增生":"anti-angiogenesis",
    "抗肿瘤转移":"anti-metastatic",
    "诱导分化":"induce differentiation",
    "诱导凋亡":"induce apoptosis",
    "完全缓解":"complete remission",
    "协同作用":"synergistic effect",
    "增敏作用":"sensitization effect",
    "药物外排泵":"drug efflux pump",
    "耐药机制":"resistance mechanism",
    "耐药菌株":"resistant strains",
    "耐药毒株":"resistant strains",
    "耐药菌":"resistant bacteria",
    "敏感菌":"sensitive bacteria",
    "敏感株":"sensitive strain",
    "耐药株":"resistant strain",
    "休眠菌":"dormant bacteria",
    "非复制期":"non-replicating phase",
    "耐药性产生":"development of resistance",
    "多药耐药":"multidrug-resistant",
    "棘白菌素":"echinocandin",

    # Routes/admin
    "口服给药":"oral administration",
    "静脉给药":"intravenous administration",
    "静脉注射":"intravenous injection",
    "静脉滴注":"intravenous infusion",
    "静脉输注":"intravenous infusion",
    "局部外用":"topical use",
    "局部治疗":"local treatment",
    "全身给药":"systemic administration",
    "全身用药":"systemic use",
    "全身治疗":"systemic treatment",
    "鞘内注射":"intrathecal injection",
    "每日一次":"once daily",
    "每周一次":"once weekly",
    "每日给药":"once daily dosing",
    "每周给药":"weekly dosing",
    "每日多次给药":"multiple daily doses",
    "单次给药":"single administration",
    "单剂口服":"single oral dose",
    "空腹":"on an empty stomach",
    "半空腹":"semi-fasting",
    "不与食物同服":"not taken with food",
    "周期性停药":"periodic drug discontinuation",
    "口服不吸收":"is not orally absorbed",
    "口服吸收": "oral absorption",
    "口服吸收差":"poorly absorbed orally",
    "口服无效":"is orally ineffective",
    "口服有效":"is orally effective",
    "必须静脉给药":"must be given intravenously",
    "可口服给药":"can be given orally",
    "仅静脉给药":"only given intravenously",
    "禁止静脉给药":"intravenous administration is contraindicated",

    # Pharmacokinetics
    "经肝代谢":"hepatic metabolism",
    "经肾排泄":"renal excretion",
    "经肝脏代谢":"is hepatically metabolized",
    "经肾脏排泄":"is renally excreted",
    "以原形":"in unchanged form",
    "以原形排泄":"excreted unchanged",
    "代谢产物":"metabolite",
    "活性代谢物":"active metabolite",
    "血药浓度":"plasma drug concentration",
    "脑脊液中浓度":"concentration in CSF",
    "有效血药浓度":"effective plasma concentration",
    "半衰期":"half-life",
    "终末半衰期":"terminal half-life",
    "首过消除":"first-pass elimination",
    "首关效应":"first-pass effect",
    "分布容积":"volume of distribution",
    "组织分布":"tissue distribution",
    "生物等效":"bioequivalent",
    "治疗指数":"therapeutic index",
    "安全范围":"safety margin",
    "蓄积中毒":"accumulation toxicity",
    "蓄积":"accumulation",
    "峰值浓度":"peak concentration",
    "谷浓度":"trough concentration",
    "起效":"onset of action",
    "达峰时间":"time to peak",

    # Organs/systems
    "肝脏":"liver",
    "肾脏":"kidney",
    "心脏":"heart",
    "肺部":"lung",
    "脑部":"brain",
    "肠道":"intestine",
    "肠道内":"intestinal lumen",
    "肠腔":"intestinal lumen",
    "肠壁":"intestinal wall",
    "神经系统":"nervous system",
    "免疫功能":"immune function",
    "造血功能":"hematopoietic function",
    "内分泌系统":"endocrine system",
    "皮肤及毛发":"skin and hair",
    "消化道":"digestive tract",
    "毛囊":"hair follicles",

    # Common symptoms/adverse effects
    "不良反应":"adverse effects",
    "最常见不良反应":"most common adverse effect",
    "最严重不良反应":"most serious adverse effect",
    "特征性不良反应":"characteristic adverse effect",
    "剂量限制性":"dose-limiting",
    "骨髓抑制":"myelosuppression",
    "心脏毒性":"cardiotoxicity",
    "肺毒性":"pulmonary toxicity",
    "肺纤维化":"pulmonary fibrosis",
    "肾毒性":"nephrotoxicity",
    "耳毒性":"ototoxicity",
    "肝毒性":"hepatotoxicity",
    "神经毒性":"neurotoxicity",
    "骨髓毒性":"myelotoxicity",
    "血液系统毒性":"hematologic toxicity",
    "远期毒性":"delayed toxicity",
    "近期毒性":"acute toxicity",
    "肝损害":"hepatic injury",
    "肾损害":"renal damage",
    "肝功能检查":"liver function tests",
    "肾功能检查":"renal function tests",
    "可逆性肾损害":"reversible renal damage",
    "不可逆耳聋":"irreversible deafness",
    "暂时性耳聋":"temporary deafness",
    "周围神经":"peripheral nerve",
    "视神经":"optic nerve",
    "视神经炎":"optic neuritis",
    "肝功能异常":"abnormal liver function",
    "眼科检查":"ophthalmologic examination",
    "定期检查":"regular monitoring",
    "视网膜病变":"retinopathy",
    "心律失常":"arrhythmia",
    "血压下降":"hypotension",
    "心电图异常":"ECG abnormalities",
    "意识模糊":"confusion",
    "反射亢进":"hyperreflexia",
    "记忆力减退":"memory impairment",
    "感觉异常":"paresthesia",
    "手指麻木":"finger numbness",
    "足趾麻木":"toe numbness",
    "腱反射迟钝":"diminished tendon reflexes",
    "腱反射消失":"absent tendon reflexes",
    "注意力不集中":"poor concentration",
    "精神错乱":"confusion",
    "致命性肝坏死":"fatal hepatic necrosis",
    "男生乳房发育":"gynecomastia",
    "肾上腺功能不全":"adrenal insufficiency",
    "药物热":"drug fever",
    "空调新月征":"air crescent sign",
    "眼科检查":"ophthalmologic examination",

    # Question/answer patterns
    "【简答题】":"",
    "下列关于":"Which of the following regarding",
    "下列描述中错误的是":"Which of the following descriptions is INCORRECT?",
    "下列描述中正确的是":"Which of the following descriptions is CORRECT?",
    "下列描述哪项是错误的":"which description is INCORRECT?",
    "下列描述哪项是正确的":"which description is CORRECT?",
    "下列哪项是错误的":"which of the following is INCORRECT?",
    "下列哪项是正确的":"which of the following is CORRECT?",
    "下列哪项描述是错误的":"which of the following descriptions is INCORRECT?",
    "下列哪项描述是正确的":"which of the following descriptions is CORRECT?",
    "下列哪项描述":"which of the following descriptions",
    "下列描述":"which of the following descriptions",
    "下列哪种":"which of the following",
    "下列哪项":"which of the following",
    "下列哪些是正确的":"which of the following are CORRECT?",
    "下列哪些描述是正确的":"which of the following descriptions are CORRECT?",
    "下列哪些描述是正确":"which of the following descriptions are correct",
    "下列哪些":"which of the following",
    "下列哪组配对":"which of the following pairings",
    "下列哪组配对是正确的":"which of the following pairings is correct?",
    "下列哪项配对":"which of the following pairs",
    "下列哪项是错的":"which of the following is incorrect",
    "下列哪项是对的":"which of the following is correct",
    "哪项是错误的":"is INCORRECT?",
    "哪项是正确的":"is CORRECT?",
    "哪些是正确的":"are CORRECT?",
    "哪些是错误":"are INCORRECT?",
    "错误的是":"is INCORRECT",
    "正确的是":"is CORRECT",
    "错误的描述":"incorrect description",
    "正确的描述":"correct description",
    "错误选项":"incorrect options",
    "正确选项":"correct options",
    "以上均正确":"all of the above are correct",
    "以上均错误":"all of the above are incorrect",
    "以上都是":"all of the above",
    "以上均":"all of the above",
    "以上配对均正确":"all of the above pairings are correct",
    "不包括下列哪项":"does NOT include which of the following?",
    "不包括下列":"does NOT include the following",
    "不包括":"does not include",
    "均正确":"are all correct",
    "均错误":"are all incorrect",
    "均正确描述":"are all correctly described",
    "均正确描述了":"are all correctly described",
    "分别":"respectively",
    "分别为":"are respectively",

    # === MISSING COMPOUNDS from output review ===
    "干扰素":"interferon",
    "干扰素α":"interferon alpha",
    "周期":"cycle",
    "增殖周期":"proliferation cycle",
    "体内":"in vivo",
    "体外":"in vitro",
    "而非":"rather than",
    "前体药物":"prodrug",
    "前体":"precursor",
    "各型":"each type of",
    "各型各":"each type of",
    "细胞内":"intracellular",
    "细胞外":"extracellular",
    "胞内":"intracellular",
    "胞外":"extracellular",
    "肠腔内":"in the intestinal lumen",
    "脑脊液":"cerebrospinal fluid (CSF)",
    "脑脊液中":"in the cerebrospinal fluid",
    "透过血脑屏障":"cross the blood-brain barrier",
    "血脑屏障":"blood-brain barrier",
    "不易透过":"does not readily cross",
    "易于透过":"readily crosses",
    "口服吸收良好":"is well absorbed orally",
    "口服吸收迅速":"is rapidly absorbed orally",
    "口服吸收完全":"is completely absorbed orally",
    "口服不吸收":"is not orally absorbed",
    "难以吸收":"is poorly absorbed",
    "不易吸收":"is not readily absorbed",
    "静脉滴注":"intravenous infusion",
    "缓慢静脉":"slow intravenous",
    "肌肉注射":"intramuscular injection",
    "皮下注射":"subcutaneous injection",
    "鞘内":"intrathecal",
    "用药期间":"during treatment",
    "治疗期间":"during treatment",
    "服药期间":"during medication",
    "服药后":"after taking the drug",
    "给药后":"after administration",
    "停药后":"after drug discontinuation",
    "复发率":"relapse rate",
    "治愈率":"cure rate",
    "缓解率":"remission rate",
    "有效率":"response rate",
    "生存率":"survival rate",
    "死亡率":"mortality rate",
    "发病率":"incidence rate",
    "患病率":"prevalence rate",
    "易产生":"readily develops",
    "不易产生":"does not readily develop",
    "容易产生":"readily produces",
    "最常用":"most commonly used",
    "最常":"most commonly",
    "常用药物":"commonly used drug",
    "首选药物":"drug of choice",
    "次选药物":"second-line drug",
    "替代药物":"alternative drug",
    "严禁":"is strictly contraindicated",
    "严禁用于":"is strictly contraindicated for",
    "绝对禁止":"is absolutely contraindicated",
    "相对禁止":"is relatively contraindicated",
    "慎用于":"should be used with caution in",
    "宜用于":"is suitable for",
    "主要不良反应":"main adverse effect",
    "最主要不良反应":"most important adverse effect",
    "特征性不良反应":"characteristic adverse effect",
    "特异质反应":"idiosyncratic reaction",
    "变态反应":"allergic reaction",
    "胃肠道反应":"gastrointestinal reaction",
    "消化道反应":"gastrointestinal reaction",
    "恶心":"nausea",
    "呕吐":"vomiting",
    "腹泻":"diarrhea",
    "便秘":"constipation",
    "食欲减退":"loss of appetite",
    "食欲不振":"poor appetite",
    "皮疹":"rash",
    "瘙痒":"pruritus",
    "脱发":"alopecia",
    "发热":"fever",
    "头痛":"headache",
    "头晕":"dizziness",
    "乏力":"fatigue",
    "失眠":"insomnia",
    "嗜睡":"drowsiness",
    "关节痛":"arthralgia",
    "肌肉痛":"myalgia",
    "注射部位反应":"injection site reaction",
    "静脉炎":"phlebitis",
    "口腔炎":"stomatitis",
    "口腔溃疡":"oral ulcer",
    "黏膜炎":"mucositis",
    "口腔黏膜炎":"oral mucositis",
    "食管炎":"esophagitis",
    "胃炎":"gastritis",
    "肠炎":"enteritis",
    "胰腺炎":"pancreatitis",
    "肝炎":"hepatitis",
    "肾炎":"nephritis",
    "心肌炎":"myocarditis",
    "心包炎":"pericarditis",
    "肺炎":"pneumonia",
    "支气管痉挛":"bronchospasm",
    "呼吸抑制":"respiratory depression",
    "呼吸衰竭":"respiratory failure",
    "肾功能衰竭":"renal failure",
    "肝功能衰竭":"hepatic failure",
    "心力衰竭":"heart failure",
    "休克":"shock",
    "过敏性休克":"anaphylactic shock",
    "昏迷":"coma",
    "惊厥":"convulsion",
    "癫痫":"epilepsy",
    "精神症状":"psychiatric symptoms",
    "幻觉":"hallucination",
    "抑郁":"depression",
    "焦虑":"anxiety",
    "兴奋":"excitation",
    "镇静":"sedation",
    "嗜酸性粒细胞增多":"eosinophilia",

    # ===== HIGH-FREQUENCY 2-CHARACTER COMPOUNDS =====
    "作用":"effect",
    "机制":"mechanism",
    "活性":"activity",
    "毒性":"toxicity",
    "耐药":"drug-resistant",
    "耐药性":"drug resistance",
    "交叉耐药":"cross-resistance",
    "固有耐药":"intrinsic resistance",
    "获得性耐药":"acquired resistance",
    "天然耐药":"innate resistance",
    "敏感":"sensitive",
    "耐受":"tolerant",
    "选择性":"selectivity",
    "特异性":"specificity",
    "敏感性":"sensitivity",
    "稳定性":"stability",
    "安全性":"safety",
    "有效性":"effectiveness",
    "耐受性":"tolerability",
    "完整性":"integrity",
    "渗透性":"permeability",
    "通透性":"permeability",
    "生物利用":"bioavailability",
    "利用度":"availability",
    "代谢":"metabolism",
    "排泄":"excretion",
    "吸收":"absorption",
    "分布":"distribution",
    "清除":"clearance",
    "消除":"elimination",
    "透过":"penetrate",
    "穿透":"penetrate",
    "渗入":"penetrate into",
    "进入":"enter",
    "排出":"excrete",
    "释放":"release",
    "摄取":"uptake",
    "外排":"efflux",
    "结合":"binding",
    "抑制":"inhibit",
    "抑制剂":"inhibitor",
    "抑制药":"inhibitor",
    "阻断":"block",
    "阻止":"prevent",
    "破坏":"disrupt",
    "干扰":"interfere with",
    "杀灭":"kill",
    "增强":"enhance",
    "降低":"reduce",
    "减少":"reduce",
    "增加":"increase",
    "减轻":"alleviate",
    "加重":"aggravate",
    "加速":"accelerate",
    "减慢":"slow down",
    "延长":"prolong",
    "缩短":"shorten",
    "消失":"disappear",
    "出现":"occur",
    "发生":"develop",
    "产生":"produce",
    "导致":"lead to",
    "引起":"cause",
    "造成":"result in",
    "影响":"affect",
    "改变":"alter",
    "促进":"promote",
    "发挥":"exert",
    "调节":"regulate",
    "维持":"maintain",
    "保护":"protect",
    "恢复":"recover",
    "修复":"repair",
    "取代":"replace",
    "激活":"activate",
    "活化":"activation",
    "失活":"inactivation",
    "诱导":"induce",
    "诱导剂":"inducer",
    "合成":"synthesis",
    "复制":"replication",
    "转录":"transcription",
    "翻译":"translation",
    "降解":"degradation",
    "形成":"formation",
    "结构":"structure",
    "功能":"function",
    "过程":"process",
    "反应":"reaction",
    "表达":"expression",
    "过度表达":"overexpression",
    "分泌":"secretion",
    "定位":"localization",
    "保守":"conserved",
    "变异":"mutation",
    "突变":"mutation",
    "沉默":"silencing",
    "启动":"initiation",
    "延长":"elongation",
    "终止":"termination",
    "掺入":"incorporate into",
    "整合":"integrate",
    "融合":"fusion",
    "进入":"entry",
    "吸附":"adsorption",
    "脱壳":"uncoating",
    "包装":"assembly",
    "出芽":"budding",
    "释放":"release",
    "溶解":"lysis",
    "裂解":"lysis",

    # Effects/activities
    "杀菌":"bactericidal",
    "杀菌作用":"bactericidal activity",
    "杀菌药":"bactericidal drug",
    "抑菌":"bacteriostatic",
    "抑菌作用":"bacteriostatic activity",
    "抑菌药":"bacteriostatic drug",
    "抗菌":"antibacterial",
    "抗菌作用":"antibacterial activity",
    "抗菌活性":"antibacterial activity",
    "抗菌谱":"antibacterial spectrum",
    "抗真菌":"antifungal",
    "抗真菌作用":"antifungal activity",
    "抗真菌药":"antifungal drug",
    "抗病毒":"antiviral",
    "抗病毒作用":"antiviral activity",
    "抗病毒药":"antiviral drug",
    "抗结核":"antituberculosis",
    "抗肿瘤":"antineoplastic",
    "抗肿瘤药":"antineoplastic drug",
    "抗肿瘤作用":"antineoplastic activity",
    "抗寄生虫":"antiparasitic",
    "抗疟":"antimalarial",
    "抗疟药":"antimalarial drug",
    "驱虫":"anthelmintic",
    "驱虫药":"anthelmintic drug",
    "驱肠虫":"anthelmintic",
    "驱肠虫药":"anthelmintic drug",
    "广谱":"broad-spectrum",
    "窄谱":"narrow-spectrum",
    "强效":"potent",
    "高效":"highly effective",
    "速效":"rapid-acting",
    "长效":"long-acting",
    "短效":"short-acting",

    # Infections/diseases
    "感染":"infection",
    "传染":"contagious",
    "传播":"transmission",
    "复发":"recurrence",
    "播散":"dissemination",
    "潜伏":"latent",
    "结核":"tuberculosis",
    "麻风":"leprosy",
    "疟疾":"malaria",
    "阿米巴病":"amebiasis",
    "阿米巴":"amebic",
    "滴虫病":"trichomoniasis",
    "血吸虫":"schistosome",
    "蛔虫病":"ascariasis",
    "钩虫病":"hookworm infection",
    "鞭虫病":"trichuriasis",
    "蛲虫病":"enterobiasis",
    "锥虫病":"trypanosomiasis",
    "利什曼病":"leishmaniasis",
    "白血球":"leukocyte",
    "恶性肿瘤":"malignant tumor",
    "白血病":"leukemia",
    "淋巴瘤":"lymphoma",
    "腺癌":"adenocarcinoma",
    "鳞癌":"squamous cell carcinoma",
    "黑色素瘤":"melanoma",
    "肉瘤":"sarcoma",
    "乳腺癌":"breast cancer",
    "卵巢癌":"ovarian cancer",
    "前列腺癌":"prostate cancer",
    "胃癌":"gastric cancer",
    "结肠癌":"colon cancer",
    "结直肠癌":"colorectal cancer",
    "肝癌":"hepatocellular carcinoma",
    "肾癌":"renal cell carcinoma",
    "肺癌":"lung cancer",
    "食管癌":"esophageal cancer",
    "宫颈癌":"cervical cancer",
    "阴茎癌":"penile cancer",
    "外阴癌":"vulvar cancer",
    "睾丸癌":"testicular cancer",
    "口腔癌":"oral cancer",
    "头颈部癌":"head and neck cancer",
    "胰脏癌":"pancreatic cancer",
    "疱疹":"herpes",
    "水痘":"chickenpox",
    "狂犬病":"rabies",
    "哮喘":"asthma",
    "支气管炎":"bronchitis",
    "扁桃体炎":"tonsillitis",
    "痛风":"gout",
    "艾滋病":"AIDS",

    # Microorganism-related
    "细菌":"bacteria",
    "真菌":"fungi",
    "真菌细胞":"fungal cell",
    "真菌感染":"fungal infection",
    "病毒感染":"viral infection",
    "细菌感染":"bacterial infection",
    "病原体":"pathogen",
    "寄生虫":"parasite",
    "蠕虫":"helminth",
    "线虫":"nematode",
    "吸虫":"trematode",
    "绦虫":"tapeworm",
    "原虫":"protozoa",
    "孢子":"spore",
    "菌丝":"hyphae",
    "酵母":"yeast",
    "霉菌":"mold",
    "革兰阳性菌":"Gram-positive bacteria",
    "革兰阴性菌":"Gram-negative bacteria",
    "格兰阳性菌":"Gram-positive bacteria",
    "格兰阴性菌":"Gram-negative bacteria",

    # Cell/tissue
    "细胞膜":"cell membrane",
    "细胞壁":"cell wall",
    "细胞核":"nucleus",
    "细胞质":"cytoplasm",
    "线粒体":"mitochondria",
    "核糖体":"ribosome",
    "内质网":"endoplasmic reticulum",
    "溶酶体":"lysosome",
    "蛋白酶体":"proteasome",
    "高尔基体":"Golgi apparatus",
    "微管":"microtubule",
    "微丝":"microfilament",
    "纺锤丝":"spindle fiber",
    "着丝粒":"centromere",
    "端粒":"telomere",
    "染色体":"chromosome",
    "质粒":"plasmid",
    "染色质":"chromatin",
    "基因组":"genome",
    "表观遗传":"epigenetic",
    "宿主细胞":"host cells",
    "正常细胞":"normal cells",
    "肿瘤细胞":"tumor cells",
    "癌细胞":"cancer cells",
    "增殖细胞":"proliferating cells",
    "干细胞":"stem cells",
    "祖细胞":"progenitor cells",
    "淋巴细胞":"lymphocytes",
    "T细胞":"T cells",
    "B细胞":"B cells",
    "NK细胞":"NK cells",
    "巨噬细胞":"macrophages",
    "中性粒细胞":"neutrophils",
    "酸性粒细胞":"eosinophils",
    "碱性粒细胞":"basophils",
    "单核细胞":"monocytes",
    "肥大细胞":"mast cells",
    "树突状细胞":"dendritic cells",
    "抗原递呈细胞":"antigen-presenting cells",
    "红细胞":"red blood cells",
    "血小板":"platelets",
    "肿瘤组织":"tumor tissue",
    "正常组织":"normal tissue",
    "癌组织":"cancer tissue",
    "结缔组织":"connective tissue",
    "上皮组织":"epithelial tissue",
    "角化组织":"keratinized tissue",
    "皮下组织":"subcutaneous tissue",
    "黏膜组织":"mucosal tissue",
    "纤维组织":"fibrous tissue",
    "肉芽组织":"granulation tissue",
    "坏死组织":"necrotic tissue",
    "休眠子":"hypnozoite",
    "裂殖体":"schizont",
    "裂殖子":"merozoite",
    "配子体":"gametocyte",
    "子孢子":"sporozoite",
    "滋养体":"trophozoite",
    "包囊":"cyst",
    "卵囊":"oocyst",
    "微丝蚴":"microfilariae",
    "成虫":"adult worm",
    "幼虫":"larva",
    "幼虫期":"larval stage",
    "虫卵":"egg",
    "尾蚴":"cercaria",
    "毛蚴":"miracidium",
    "胞蚴":"sporocyst",
    "雷蚴":"redia",
    "囊尾蚴":"cysticerci",
    "棘球蚴":"hydatid cyst",

    # Clinical management
    "治疗":"treatment",
    "治疗方案":"treatment regimen",
    "治疗策略":"treatment strategy",
    "首选药物":"drug of choice",
    "首选药":"drug of choice",
    "一线药物":"first-line drug",
    "二线药物":"second-line drug",
    "临床使用":"clinical use",
    "临床应用":"clinical use",
    "适应证":"indication",
    "禁忌证":"contraindication",
    "配伍禁忌":"incompatibility",
    "联合使用":"combined use",
    "联合应用":"combination use",
    "单药治疗":"monotherapy",
    "单用":"monotherapy",
    "合用":"coadministration",
    "联用":"combination",
    "禁用":"contraindicated",
    "慎用":"use with caution",
    "不宜":"should not be used",
    "不应":"should not",
    "必须":"must",
    "需要":"requires",
    "不能":"cannot",
    "可以":"can",
    "可能会":"may",
    "可能会引起":"may cause",
    "可用于":"can be used for",
    "适用于":"is indicated for",
    "不宜用于":"should not be used for",
    "禁用于":"is contraindicated in",
    "限用于":"is limited to",
    "主要用于":"is mainly used for",
    "常用于":"is commonly used for",
    "首选用于":"is the first choice for",
    "不用于":"is not used for",
    "不可用于":"cannot be used for",
    "不适用于":"is not suitable for",
    "属于":"belongs to",
    "不属于":"does not belong to",
    "被称为":"is known as",
    "称为":"is called",
    "表现为":"presents as",
    "作为":"as",
    "依赖于":"depends on",
    "取决于":"depends on",
    "基于":"based on",
    "根据":"according to",
    "针对":"targeting",
    "通过":"through",
    "由于":"due to",
    "因此":"therefore",
    "所以":"therefore",
    "但是":"but",
    "然而":"however",
    "虽然":"although",
    "因为":"because",
    "如果":"if",
    "一旦":"once",
    "无论":"regardless of",
    "不仅":"not only",
    "而且":"moreover",
    "同时":"simultaneously",
    "此外":"in addition",
    "另外":"additionally",
    "通常":"usually",
    "通常不":"usually not",
    "大多数":"most",
    "一部分":"some",
    "几乎全部":"almost all",
    "几乎":"nearly",
    "绝大多数":"the vast majority",
    "少数":"a few",
    "部分":"partial",
    "完全":"complete",
    "大部分":"the majority of",
    "明显":"significantly",
    "显著":"markedly",
    "特别":"especially",
    "尤其":"particularly",
    "非常":"very",
    "极度":"extremely",
    "高度":"highly",
    "轻微":"mild",
    "轻度":"mild",
    "中度":"moderate",
    "重度":"severe",
    "轻度到中度":"mild to moderate",
    "严重":"severe",
    "较严重":"relatively severe",
    "最严重":"most serious",
    "最常见":"most common",
    "最主要":"most important",
    "最重要":"most important",
    "最突出":"most prominent",
    "最有效":"most effective",
    "最合适":"most appropriate",
    "直接":"direct",
    "间接":"indirect",
    "迅速":"rapid",
    "缓慢":"slow",
    "逐渐":"gradually",
    "立即":"immediately",
    "早期":"early",
    "晚期":"late",
    "近期":"short-term",
    "远期":"long-term",
    "长期":"long-term",
    "短期":"short-term",
    "当前":"current",
    "目前":"currently",
    "既往":"previously",
    "未来":"future",
    "近年":"in recent years",
    "传统":"traditional",
    "新型":"novel",
    "经典":"classic",
    "常用":"commonly used",
    "常规":"routine",
    "紧急":"emergency",
    "危重":"critical",
    "预防":"prevention",
    "诊断":"diagnosis",
    "监测":"monitoring",
    "评估":"assessment",
    "筛查":"screening",
    "确认":"confirmation",
    "排除":"rule out",
    "预后":"prognosis",
    "并发症":"complication",
    "副作用":"side effect",
    "后遗症":"sequela",
    "死亡率":"mortality",
    "患病率":"prevalence",
    "发病率":"incidence",
    "缓解率":"remission rate",
    "治愈率":"cure rate",
    "有效率":"response rate",
    "复发率":"relapse rate",
    "生存率":"survival rate",
    "剂量":"dose",
    "高剂量":"high dose",
    "低剂量":"low dose",
    "负荷剂量":"loading dose",
    "维持剂量":"maintenance dose",
    "最大耐受剂量":"maximum tolerated dose",
    "治疗剂量":"therapeutic dose",
    "中毒剂量":"toxic dose",
    "致死剂量":"lethal dose",
    "剂量调整":"dose adjustment",
    "无需调整剂量":"no dose adjustment needed",
    "应减量":"should reduce dose",
    "应增量":"should increase dose",
    "给药途径":"route of administration",
    "给药频率":"dosing frequency",
    "给药间隔":"dosing interval",
    "口服给药":"orally administered",
    "静脉给药":"intravenously administered",
    "肌肉注射":"intramuscular injection",
    "皮下注射":"subcutaneous injection",
    "皮内注射":"intradermal injection",
    "吸入给药":"inhalation",
    "经皮给药":"transdermal",
    "局部用药":"topical application",
    "外用制剂":"topical formulation",
    "外用":"topical",
    "口服制剂":"oral formulation",
    "注射剂":"injection",
    "片剂":"tablet",
    "胶囊":"capsule",
    "乳膏":"cream",
    "软膏":"ointment",
    "搽剂":"liniment",
    "溶液":"solution",
    "混悬液":"suspension",
    "喷雾剂":"spray",
    "贴剂":"patch",
    "栓剂":"suppository",
    "控制症状":"control symptoms",
    "缓解症状":"relieve symptoms",
    "症状控制":"symptom control",
    "症状改善":"symptom improvement",
    "症状消失":"symptom resolution",
    "症状复发":"symptom recurrence",
    "症状加重":"symptom exacerbation",
    "无症状":"asymptomatic",
    "出现症状":"develop symptoms",
    "延长生存期":"prolong survival",
    "提高生活质量":"improve quality of life",
    "减轻痛苦":"alleviate suffering",
    "保存功能":"preserve function",

    # Molecular/cellular processes
    "信号通路":"signaling pathway",
    "信号转导":"signal transduction",
    "细胞周期":"cell cycle",
    "细胞分化":"cell differentiation",
    "细胞增殖":"cell proliferation",
    "细胞凋亡":"apoptosis",
    "细胞坏死":"necrosis",
    "细胞自噬":"autophagy",
    "细胞衰老":"cellular senescence",
    "细胞迁移":"cell migration",
    "细胞侵袭":"cell invasion",
    "细胞转移":"metastasis",
    "上皮间质转化":"epithelial-mesenchymal transition",
    "肿瘤微环境":"tumor microenvironment",
    "免疫逃逸":"immune evasion",
    "免疫监视":"immune surveillance",
    "免疫应答":"immune response",
    "免疫调节":"immune regulation",
    "免疫抑制":"immunosuppression",
    "免疫激活":"immune activation",
    "炎症反应":"inflammatory response",
    "氧化应激":"oxidative stress",
    "DNA损伤":"DNA damage",
    "DNA修复":"DNA repair",
    "端粒缩短":"telomere shortening",
    "基因组不稳定":"genomic instability",
    "基因扩增":"gene amplification",
    "基因缺失":"gene deletion",
    "基因重排":"gene rearrangement",
    "基因融合":"gene fusion",
    "点突变":"point mutation",
    "移码突变":"frameshift mutation",
    "错义突变":"missense mutation",
    "无义突变":"nonsense mutation",
    "沉默突变":"silent mutation",
    "启动子甲基化":"promoter methylation",
    "组蛋白修饰":"histone modification",
    "染色质重塑":"chromatin remodeling",
    "非编码RNA":"non-coding RNA",
    "微RNA":"microRNA",
    "长链非编码RNA":"long non-coding RNA",
    "表观遗传学":"epigenetics",
    "细胞分裂":"cell division",
    "有丝分裂":"mitosis",
    "减数分裂":"meiosis",
    "G1期":"G1 phase",
    "S期":"S phase",
    "G2期":"G2 phase",
    "M期":"M phase",
    "G0期":"G0 phase",
    "限制点":"restriction point",
    "检查点":"checkpoint",
    "纺锤体检查点":"spindle checkpoint",
    "DNA损伤检查点":"DNA damage checkpoint",

    # PK/PD concepts
    "药效学":"pharmacodynamics",
    "药动学":"pharmacokinetics",
    "量效关系":"dose-response relationship",
    "时效关系":"time-response relationship",
    "构效关系":"structure-activity relationship",
    "治疗窗":"therapeutic window",
    "最低抑菌浓度":"minimum inhibitory concentration (MIC)",
    "最低杀菌浓度":"minimum bactericidal concentration (MBC)",
    "峰浓度":"peak concentration (Cmax)",
    "谷浓度":"trough concentration (Cmin)",
    "药时曲线下面积":"area under the curve (AUC)",
    "时间依赖性":"time-dependent",
    "浓度依赖性":"concentration-dependent",
    "剂量依赖性":"dose-dependent",
    "pH依赖性":"pH-dependent",
    "时间-杀菌曲线":"time-kill curve",
    "抗生素后效应":"post-antibiotic effect (PAE)",
    "突变选择窗":"mutant selection window",
    "防突变浓度":"mutant prevention concentration (MPC)",
    "药敏试验":"antimicrobial susceptibility testing",
    "耐药临界值":"resistance breakpoint",
    "流行病学折点":"epidemiological cutoff value (ECOFF)",

    # Clinical trial/evidence terms
    "随机对照试验":"randomized controlled trial (RCT)",
    "荟萃分析":"meta-analysis",
    "系统评价":"systematic review",
    "队列研究":"cohort study",
    "病例对照研究":"case-control study",
    "临床指南":"clinical guideline",
    "专家共识":"expert consensus",
    "循证医学":"evidence-based medicine",
    "真实世界研究":"real-world study",
    "上市后监测":"post-marketing surveillance",
    "不良事件":"adverse event",
    "严重不良事件":"serious adverse event",
    "药物警戒":"pharmacovigilance",
    "风险收益比":"risk-benefit ratio",
    "成本效益":"cost-effectiveness",
    "药物经济学":"pharmacoeconomics",
    "个体化治疗":"personalized therapy",
    "精准医疗":"precision medicine",
    "基因组学":"genomics",
    "药物基因组学":"pharmacogenomics",
    "生物标志物":"biomarker",
    "伴随诊断":"companion diagnostic",
    "替代终点":"surrogate endpoint",
    "主要终点":"primary endpoint",
    "次要终点":"secondary endpoint",
    "总生存期":"overall survival (OS)",
    "无进展生存期":"progression-free survival (PFS)",
    "无病生存期":"disease-free survival (DFS)",
    "客观缓解率":"objective response rate (ORR)",
    "疾病控制率":"disease control rate (DCR)",
    "至进展时间":"time to progression (TTP)",

    # Drug development
    "先导化合物":"lead compound",
    "构效关系":"structure-activity relationship (SAR)",
    "高通量筛选":"high-throughput screening",
    "计算机辅助药物设计":"computer-aided drug design (CADD)",
    "分子对接":"molecular docking",
    "基于片段的药物设计":"fragment-based drug design",
    "合理药物设计":"rational drug design",
    "前药":"prodrug",
    "活性代谢物":"active metabolite",
    "软药":"soft drug",
    "硬药":"hard drug",
    "生物电子等排":"bioisostere",
    "药效团":"pharmacophore",
    "定量构效关系":"quantitative structure-activity relationship (QSAR)",
    "ADME":"ADME",
    "药物代谢":"drug metabolism",
    "细胞色素P450酶":"cytochrome P450 enzyme",
    "CYP3A4":"CYP3A4",
    "CYP2D6":"CYP2D6",
    "CYP2C9":"CYP2C9",
    "CYP2C19":"CYP2C19",
    "CYP1A2":"CYP1A2",
    "P-糖蛋白":"P-glycoprotein (P-gp)",
    "P-gp":"P-gp",
    "ATP结合盒转运体":"ATP-binding cassette transporter",
    "溶质载体":"solute carrier (SLC)",
    "有机阴离子转运多肽":"organic anion transporting polypeptide (OATP)",
    "有机阳离子转运体":"organic cation transporter (OCT)",
    "葡萄糖醛酸化":"glucuronidation",
    "硫酸化":"sulfation",
    "乙酰化":"acetylation",
    "甲基化":"methylation",
    "谷胱甘肽结合":"glutathione conjugation",
    "第I相代谢":"Phase I metabolism",
    "第II相代谢":"Phase II metabolism",
    "第III相转运":"Phase III transport",

    # Common connecting words / grammar
    "例如":"for example",
    "比如":"for instance",
    "包括":"includes",
    "包含":"contains",
    "含有":"contains",
    "具有":"has",
    "拥有":"possesses",
    "没有":"does not have",
    "缺乏":"lacks",
    "存在":"exists",
    "不存在":"does not exist",
    "产生":"produces",
    "生成":"generates",
    "表达":"expresses",
    "提供":"provides",
    "给予":"administer",
    "接受":"receive",
    "服用":"take",
    "使用":"use",
    "采用":"use",
    "利用":"utilize",
    "应用":"apply",
    "选择":"select",
    "排除":"exclude",
    "移除":"remove",
    "添加":"add",
    "停止":"stop",
    "继续":"continue",
    "开始":"begin",
    "完成":"complete",
    "实现":"achieve",
    "获得":"obtain",
    "失去":"lose",
    "出现":"appear",
    "消失":"disappear",
    "升高":"increase",
    "下降":"decrease",
    "保持":"maintain",
    "变化":"change",
    "稳定":"stabilize",
    "波动":"fluctuate",
    "转变为":"is converted to",
    "转化为":"is converted to",
    "显示":"show",
    "表明":"indicate",
    "证明":"prove",
    "证实":"confirm",
    "验证":"verify",
    "提示":"suggest",
    "支持":"support",
    "反对":"oppose",
    "与...相关":"is associated with",
    "与...无关":"is not associated with",
    "与...相似":"is similar to",
    "与...不同":"is different from",
    "与...相同":"is the same as",
    "与...相反":"is opposite to",
    "相一致":"consistent with",
    "相矛盾":"contradicts",
    "取决于":"depends on",
    "有助于":"contributes to",
    "有利于":"is beneficial for",
    "不利于":"is detrimental to",
    "伴随着":"accompanied by",
    "涉及到":"involves",
    "有关":"related",
    "相关":"relevant",
    "无关":"unrelated",
    "类似":"similar",
    "相同":"same",
    "不同":"different",
    "相反":"opposite",
    "相应":"corresponding",
    "一致":"consistent",
    "独特":"unique",
    "特殊":"special",
    "一般":"general",
    "普遍":"universal",
    "特异":"specific",
    "非特异":"nonspecific",
    "重要":"important",
    "关键":"critical",
    "必要":"essential",
    "可选":"optional",
    "优先":"priority",
    "主要":"main",
    "次要":"secondary",
    "基本":"basic",
    "核心":"core",
    "中心":"central",
    "周边":"peripheral",
    "上游":"upstream",
    "下游":"downstream",
    "内部":"internal",
    "外部":"external",
    "前面":"anterior",
    "后面":"posterior",
    "上面":"above",
    "下面":"below",
    "左面":"left",
    "右面":"right",
    "中间":"middle",
    "两侧":"bilateral",
    "单侧":"unilateral",
    "双侧":"bilateral",
    "对侧":"contralateral",
    "同侧":"ipsilateral",
    "第一次":"first",
    "第二次":"second",
    "第三次":"third",
    "多次":"multiple times",
    "反复":"repeated",
    "持续":"persistent",
    "间断":"intermittent",
    "连续":"continuous",
    "永久":"permanent",
    "暂时":"temporary",
    "暂时性":"transient",
    "可逆性":"reversible",
    "不可逆性":"irreversible",
    "一过性":"transient",
    "持久性":"durable",
    # Numbers/time
    "第一代":"first-generation",
    "第二代":"second-generation",
    "第三代":"third-generation",
    "第四代":"fourth-generation",
    "第一线":"first-line",
    "第二线":"second-line",
    "一线":"first-line",
    "二线":"second-line",
    "三线":"third-line",
    "数天":"several days",
    "数周":"several weeks",
    "数月":"several months",
    "数年":"several years",
    "数小时":"several hours",
    "数分钟":"several minutes",
    # Common single-char that still need translation (only those that cause issues)
    "可":"can",
    "能":"can",
    "会":"may",
    "应":"should",
    "需":"need",
    "已":"already",
    "将":"will",
    "被":"is",
    "由":"by",
    "对":"against",
    "在":"in",
    "从":"from",
    "向":"toward",
    "往":"to",
    "与":"and",
    "和":"and",
    "或":"or",
    "且":"and",
    "而":"and",
    "但":"but",
    "则":"then",
    "故":"thus",
    "因":"because",
    "若":"if",
    "如":"such",
    "仅":"only",
    "只":"only",
    "还":"also",
    "也":"also",
    "更":"more",
    "最":"most",
    "较":"relatively",
    "很":"very",
    "均":"all",
    "各":"each",
    "每":"every",
    "某":"certain",
    "其":"its",
    "此":"this",
    "该":"the",
    "哪":"which",
    "这":"this",
    "那":"that",
    "多":"many",
    "少":"few",
    "大":"large",
    "小":"small",
    "高":"high",
    "低":"low",
    "长":"long",
    "短":"short",
    "快":"fast",
    "慢":"slow",
    "新":"new",
    "旧":"old",
    "好":"good",
    "差":"poor",
    "强":"strong",
    "弱":"weak",
    "前":"before",
    "后":"after",
    "上":"above",
    "下":"below",
    "内":"inside",
    "外":"outside",
    "中":"in",
    "有":"has",
    "无":"no",
    "非":"non-",
    "不":"not",
    "是":"is",
    "为":"is",
    "即":"i.e.",
    "等":"etc.",
    "或":"or",
    # Times
    "小时":"hours",
    "分钟":"minutes",
    "天":"days",
    "周":"weeks",
    "月":"months",
    "年":"years",
    "患者":"patients",
    "用药":"medication",
    "停药":"drug discontinuation",
    "给药":"administration",
    "疗程":"treatment course",
    "剂量":"dose",
    "疗效":"efficacy",
    "药物":"drug",
    "药品":"medicine",
    "血药":"plasma drug",
    "酶":"enzyme",
    "受体":"receptor",
    "配体":"ligand",
    "抗原":"antigen",
    "抗体":"antibody",
    "激素":"hormone",
    "血糖":"blood glucose",
    "血脂":"blood lipid",
    "血压":"blood pressure",
    "体温":"body temperature",
    "体重":"body weight",
    "体表面积":"body surface area",
    "疗效":"efficacy",
    "安全":"safety",
    "有效":"effective",
    "无效":"ineffective",
    "获益":"benefit",
    "风险":"risk",
    "比值":"ratio",
    "评分":"score",
    "分级":"grade",
    "分期":"stage",
    "分型":"classification",
    "危险因素":"risk factor",
    "保护因素":"protective factor",
    "预后因素":"prognostic factor",
    "预测因素":"predictive factor",
    "独立危险因素":"independent risk factor",
    "混杂因素":"confounding factor",
    "偏倚":"bias",
    "调整":"adjustment",
    "校正":"correction",
    "分层":"stratification",
    "亚组":"subgroup",
    "相互作用":"interaction",
    "效应修饰":"effect modification",
    "中介效应":"mediation effect",
    "因果关系":"causal relationship",
    "相关性":"correlation",
    "剂量-反应":"dose-response",
    "趋势":"trend",
    "阈值":"threshold",
    "截断值":"cutoff value",
    "参考范围":"reference range",
    "正常范围":"normal range",
    "异常":"abnormal",
    "阳性":"positive",
    "阴性":"negative",
    "假阳性":"false positive",
    "假阴性":"false negative",
    "真阳性":"true positive",
    "真阴性":"true negative",
    "灵敏度":"sensitivity",
    "特异度":"specificity",
    "阳性预测值":"positive predictive value",
    "阴性预测值":"negative predictive value",
    "似然比":"likelihood ratio",
    "诊断比值比":"diagnostic odds ratio",
    "受试者工作特征曲线":"ROC curve",
    "曲线下面积":"area under the curve (AUC)",
    "准确度":"accuracy",
    "精密度":"precision",
    "重复性":"reproducibility",
    "可靠性":"reliability",
    "有效性":"validity",
    "一致性":"concordance",
    "差异性":"variability",
    "偏倚":"bias",
    "误差":"error",
    "标准差":"standard deviation",
    "标准误":"standard error",
    "可信区间":"confidence interval",
    "P值":"P value",
    "统计学意义":"statistical significance",
    "临床意义":"clinical significance",
    "样本量":"sample size",
    "检验效能":"statistical power",
    "I类错误":"type I error",
    "II类错误":"type II error",
    "多重比较":"multiple comparison",
    "意向性治疗":"intention-to-treat (ITT)",
    "符合方案集":"per-protocol (PP)",
    "安全性集":"safety population",
    "全分析集":"full analysis set",
    "缺失数据":"missing data",
    "末次观测值结转":"last observation carried forward (LOCF)",
    "多重插补":"multiple imputation",
    "敏感性分析":"sensitivity analysis",
}

# Additional cleanup: remove all specific single-char translations that cause compound-word breakage
# We exclude certain chars from single-char translation to prevent breakage
_SKIP_SINGLE = set()


def translate_text(text):
    if not text:
        return text

    # 1. Apply ALL dictionary entries, longest Chinese key first.
    #    Wrap each replacement in spaces so English words don't concatenate.
    items = sorted(D.items(), key=lambda x: -len(x[0]))
    for cn, en in items:
        if cn in text:
            text = text.replace(cn, f" {en} " if en else " ")

    # 2. Fix Chinese punctuation -> Latin equivalents with spacing
    text = text.replace("，", ", ")
    text = text.replace("、", ", ")
    text = text.replace("。", ". ")
    text = text.replace("；", "; ")
    text = text.replace("：", ": ")
    text = text.replace("（", " (")
    text = text.replace("）", ") ")
    text = text.replace("．", ". ")
    text = text.replace("？", "? ")
    text = text.replace("！", "! ")
    text = text.replace("——", " - ")
    text = text.replace("…", "...")
    text = text.replace("～", "-")
    text = text.replace("　", " ")

    # 3. Strip any remaining Chinese / fullwidth chars (replace with space)
    text = re.sub(r'[一-鿿]+', ' ', text)
    text = re.sub(r'[　-〿＀-￯]+', ' ', text)

    # 4. Normalise all whitespace and punctuation spacing
    text = re.sub(r'\s+', ' ', text)
    text = re.sub(r'\s*,\s*', ', ', text)
    text = re.sub(r'\s*\.\s*', '. ', text)
    text = re.sub(r'\s*;\s*', '; ', text)
    text = re.sub(r'\s*:\s*', ': ', text)
    text = re.sub(r'\(\s*', '(', text)
    text = re.sub(r'\s*\)', ')', text)

    # 5. Clean up doubled common words from translation artifacts
    for word in ['the', 'in', 'to', 'of', 'and', 'is', 'are', 'a', 'has',
                 'inhibit', 'drug', 'cell', 'can', 'not', 'only', 'also',
                 'each', 'every', 'effect', 'act', 'use']:
        text = re.sub(rf'\b{word} {word}\b', word, text)

    text = text.strip()

    # 6. Capitalise first letter
    if text and text[0].islower():
        text = text[0].upper() + text[1:]

    return text


def translate_row(row):
    result = {}
    for key, value in row.items():
        if key == "id":
            result[key] = value
        elif key == "type":
            result[key] = TYPE_MAP.get(value.strip(), value)
        elif key == "correct":
            val = value.strip()
            if all(c in "ABCDEFGHIJ" for c in val):
                result[key] = val
            else:
                result[key] = CORRECT_MAP.get(val, val)
        elif key == "category":
            result[key] = CAT_MAP.get(value.strip(), translate_text(value))
        elif key in ("option_a", "option_b"):
            result[key] = CORRECT_MAP.get(value.strip(), translate_text(value))
        else:
            result[key] = translate_text(value)
    return result


def process_chapter(ch_num):
    in_path = os.path.join(BASE, f"pharma_cn_ch{ch_num}.csv")
    out_path = os.path.join(BASE, f"pharma_en_ch{ch_num}.csv")

    with open(in_path, "r", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        fieldnames = reader.fieldnames
        rows = list(reader)

    translated = [translate_row(r) for r in rows]

    with open(out_path, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(translated)

    cn_remain = sum(len(re.findall(r'[一-鿿]', v))
                    for r in translated for k, v in r.items())
    return len(translated), cn_remain


if __name__ == "__main__":
    total = 0
    for ch in ["42", "43", "44", "45", "46"]:
        n, cn = process_chapter(ch)
        total += n
        print(f"Chapter {ch}: {n} questions, {cn} Chinese chars remain")
    print(f"Total: {total} questions across 5 chapters.")
