#!/usr/bin/env python3
"""translate_ch19_24.py - Translate pharmacology quiz CSVs from Chinese to English for Chapters 19-24.
Sorted by decreasing Chinese string length to ensure compound terms match before their component characters.
All translations use a SINGLE canonical English form (no slash alternatives).
Grammar particles (的, 了, 着, 过, 得, 地) map to empty/spaces.
"""

import csv, os, sys, re

# ============================================================
# QUESTION TYPE
# ============================================================
TYPE_MAP = {
    "是非题": "True/False",
    "单选题": "Single Choice",
    "简答题(多选)": "Multiple Choice",
}

# ============================================================
# CATEGORY TRANSLATIONS
# ============================================================
CAT_MAP = {
    # Ch19
    "组胺和抗组胺药": "Histamine and Antihistamines",
    "5-HT和抗5-HT药": "5-HT and Anti-5-HT Drugs",
    "前列腺素类": "Prostaglandins",
    "白三烯和抗白三烯药": "Leukotrienes and Antileukotriene Drugs",
    "多肽类": "Peptide Autacoids",
    "腺苷类": "Adenosine and Related Drugs",
    "一氧化氮及相关药物": "Nitric Oxide and Related Drugs",
    # Ch20
    "免疫调节药概述": "Overview of Immunomodulators",
    "免疫抑制药-抗生素类": "Immunosuppressants - Antibiotic Class",
    "免疫抑制药-抗代谢": "Immunosuppressants - Antimetabolites",
    "免疫抑制药-GC": "Immunosuppressants - Glucocorticoids",
    "免疫抑制药-烷化剂": "Immunosuppressants - Alkylating Agents",
    "免疫抑制药-抗体类": "Immunosuppressants - Antibody Class",
    "免疫抑制药-其他": "Immunosuppressants - Others",
    "免疫检查点抑制药": "Immune Checkpoint Inhibitors",
    "免疫增强药": "Immunostimulants",
    # Ch21
    "利尿药总论": "Diuretics - General Principles",
    "袢利尿药": "Loop Diuretics",
    "噻嗪类利尿药": "Thiazide Diuretics",
    "保钾利尿药": "Potassium-Sparing Diuretics",
    "脱水药": "Dehydrating Agents (Osmotic Diuretics)",
    "碳酸酐酶抑制药": "Carbonic Anhydrase Inhibitors",
    "血管升压素V2受体阻断药": "Vasopressin V2 Receptor Antagonists",
    "利尿药不良反应": "Diuretic Adverse Effects",
    # Ch22
    "心律失常发生机制": "Mechanisms of Arrhythmogenesis",
    "Vaughan Williams分类": "Vaughan Williams Classification",
    "Ia类药": "Class Ia Antiarrhythmics",
    "Ib类药": "Class Ib Antiarrhythmics",
    "Ic类药": "Class Ic Antiarrhythmics",
    "II类β受体阻断药": "Class II Beta-Blockers",
    "III类延长动作电位时程药": "Class III Drugs (Action Potential Prolongation)",
    "IV类钙通道阻滞药": "Class IV Calcium Channel Blockers",
    "其他类": "Other Antiarrhythmics",
    "合理用药": "Rational Drug Use in Arrhythmias",
    "各类药物不良反应": "Adverse Effects by Drug Class",
    # Ch23
    "心肌缺血总论": "Myocardial Ischemia - General Principles",
    "硝酸酯类": "Nitrates",
    "钙通道阻滞药": "Calcium Channel Blockers",
    "β受体阻断药": "Beta-Blockers",
    "抗血小板药": "Antiplatelet Drugs",
    "其他抗心肌缺血药": "Other Antianginal Drugs",
    "心绞痛药物联合应用": "Combination Therapy for Angina",
    # Ch24
    "脂代谢总论": "Lipid Metabolism - General Principles",
    "他汀类": "Statins",
    "胆汁酸螯合剂": "Bile Acid Sequestrants",
    "胆固醇吸收抑制药": "Cholesterol Absorption Inhibitors",
    "PCSK9抑制药": "PCSK9 Inhibitors",
    "贝特类": "Fibrates",
    "烟酸类": "Niacin Class",
    "抗氧化剂": "Antioxidants",
    "不饱和脂肪酸": "Unsaturated Fatty Acids",
    "黏多糖和多糖类": "Mucopolysaccharides and Polysaccharides",
    "调血脂药综合": "Lipid-Lowering Drugs - Comprehensive",
    "调血脂药分类": "Classification of Lipid-Lowering Drugs",
    "综合": "Comprehensive",
}

# ============================================================
# TRANSLATION DICTIONARY
# Each entry: (Chinese, English) with ONE canonical English translation.
# Will be automatically sorted by decreasing Chinese-string length at runtime
# to ensure longer compound matches apply before shorter sub-components.
# ============================================================
TRANS_RAW = [
    # ===== PUNCTUATION =====
    ("，", ", "),
    ("。", ". "),
    ("；", "; "),
    ("：", ": "),
    ("（", " ("),
    ("）", ")"),
    ("【", "["),
    ("】", "]"),
    ("“", '"'),
    ("”", '"'),
    ("、", ", "),

    # ===== LARGE PHRASES - QUESTION/ANSWER PATTERNS (must come early) =====
    ("下列哪一项是错误的", "Which of the following is INCORRECT?"),
    ("下列哪项是错误的", "Which of the following is INCORRECT?"),
    ("下列哪一项是正确的", "Which of the following is CORRECT?"),
    ("下列哪项是正确的", "Which of the following is CORRECT?"),
    ("下列哪些是正确的", "Which of the following are CORRECT?"),
    ("下列哪些配对是正确的", "Which of the following pairings are CORRECT?"),
    ("下列关于", "Regarding "),
    ("下列药物中", "Among the following drugs,"),
    ("【简答题】", "[Short Answer] "),

    # ===== DRUG NAMES =====
    # Ch19 autacoids
    ("依前列醇", "epoprostenol"),
    ("地诺前列酮", "dinoprostone"),
    ("地诺前列素", "dinoprost"),
    ("伊洛前列素", "iloprost"),
    ("左旋西替利嗪", "levocetirizine"),
    ("米索前列醇", "misoprostol"),
    ("孟鲁司特钠", "montelukast sodium"),
    ("非索非那定", "fexofenadine"),
    ("地氯雷他定", "desloratadine"),
    ("瑞玛奈珠单抗", "fremanezumab"),
    ("加卡奈珠单抗", "galcanezumab"),
    ("艾普奈珠单抗", "eptinezumab"),
    ("苯海拉明", "diphenhydramine"),
    ("氯苯那敏", "chlorpheniramine"),
    ("茶苯海明", "dimenhydrinate"),
    ("氯雷他定", "loratadine"),
    ("西替利嗪", "cetirizine"),
    ("特非那定", "terfenadine"),
    ("阿伐斯汀", "acrivastine"),
    ("曲吡那敏", "tripelennamine"),
    ("美吡拉敏", "mepyramine"),
    ("异丙嗪", "promethazine"),
    ("赛庚啶", "cyproheptadine"),
    ("苯噻啶", "pizotifen"),
    ("苯茚胺", "phenindamine"),
    ("酮色林", "ketanserin"),
    ("替洛利生", "pitolisant"),
    ("倍他司汀", "betahistine"),
    ("曲尼司特", "tranilast"),
    ("瑞吡司特", "repirinast"),
    ("丁螺环酮", "buspirone"),
    ("昂丹司琼", "ondansetron"),
    ("舒马曲普坦", "sumatriptan"),
    ("利扎曲普坦", "rizatriptan"),
    ("佐米曲普坦", "zolmitriptan"),
    ("西咪替丁", "cimetidine"),
    ("雷尼替丁", "ranitidine"),
    ("法莫替丁", "famotidine"),
    ("尼扎替丁", "nizatidine"),
    ("扎鲁司特", "zafirlukast"),
    ("孟鲁司特", "montelukast"),
    ("齐留通", "zileuton"),
    ("前列地尔", "alprostadil"),
    ("米非司酮", "mifepristone"),
    ("安立生坦", "ambrisentan"),
    ("马西腾坦", "macitentan"),
    ("波生坦", "bosentan"),
    ("西地那非", "sildenafil"),
    ("司来帕格", "selexipag"),
    ("艾替班特", "icatibant"),
    ("艾卡拉肽", "ecallantide"),
    ("阿瑞匹坦", "aprepitant"),
    ("双嘧达莫", "dipyridamole"),
    ("伦扎必利", "renzapride"),
    ("维立西呱", "vericiguat"),
    ("吉哌隆", "gepirone"),
    ("伊沙哌隆", "ipsapirone"),
    ("抑肽酶", "aprotinin"),
    ("麦角胺", "ergotamine"),
    ("氟西汀", "fluoxetine"),

    # Ch20 immunomodulators
    ("抗淋巴细胞球蛋白", "antilymphocyte globulin"),
    ("帕博利珠单抗", "pembrolizumab"),
    ("纳武利尤单抗", "nivolumab"),
    ("阿替利珠单抗", "atezolizumab"),
    ("英夫利昔单抗", "infliximab"),
    ("阿达木单抗", "adalimumab"),
    ("利妥昔单抗", "rituximab"),
    ("替利珠单抗", "teplizumab"),
    ("德瓦鲁单抗", "durvalumab"),
    ("阿维鲁单抗", "avelumab"),
    ("霉酚酸酯", "mycophenolate mofetil"),
    ("依那西普", "etanercept"),
    ("硫唑嘌呤", "azathioprine"),
    ("环磷酰胺", "cyclophosphamide"),
    ("甲氨蝶呤", "methotrexate"),
    ("左旋咪唑", "levamisole"),
    ("胸腺肽", "thymosin"),
    ("卡介苗", "BCG"),
    ("环孢素", "cyclosporine"),
    ("他克莫司", "tacrolimus"),
    ("西罗莫司", "sirolimus"),
    ("泼尼松", "prednisone"),
    ("地塞米松", "dexamethasone"),
    ("巯嘌呤", "mercaptopurine"),
    ("霉酚酸", "mycophenolic acid"),
    ("芬戈莫德", "fingolimod"),
    ("西尼莫德", "siponimod"),
    ("奥扎莫德", "ozanimod"),
    ("利巴韦林", "ribavirin"),
    ("干扰素", "interferon"),
    ("转移因子", "transfer factor"),
    ("集落刺激因子", "colony-stimulating factor"),
    ("白介素-2", "interleukin-2"),

    # Ch21 diuretics
    ("乙酰唑胺", "acetazolamide"),
    ("氢氯噻嗪", "hydrochlorothiazide"),
    ("卡立泊来德", "cariporide"),
    ("吲达帕胺", "indapamide"),
    ("依他尼酸", "ethacrynic acid"),
    ("布美他尼", "bumetanide"),
    ("托拉塞米", "torasemide"),
    ("阿佐塞米", "azosemide"),
    ("氯噻酮", "chlorthalidone"),
    ("美托拉宗", "metolazone"),
    ("喹乙宗", "quinethazone"),
    ("希帕胺", "xipamide"),
    ("氨苯蝶啶", "triamterene"),
    ("阿米洛利", "amiloride"),
    ("螺内酯", "spironolactone"),
    ("坎利酮", "canrenone"),
    ("甘露醇", "mannitol"),
    ("山梨醇", "sorbitol"),
    ("托伐普坦", "tolvaptan"),
    ("呋塞米", "furosemide"),

    # Ch22 antiarrhythmics
    ("N-乙酰普鲁卡因胺", "N-acetylprocainamide"),
    ("普鲁卡因胺", "procainamide"),
    ("异丙肾上腺素", "isoproterenol"),
    ("普罗帕酮", "propafenone"),
    ("苯妥英钠", "phenytoin"),
    ("利多卡因", "lidocaine"),
    ("普萘洛尔", "propranolol"),
    ("阿替洛尔", "atenolol"),
    ("艾司洛尔", "esmolol"),
    ("胺碘酮", "amiodarone"),
    ("索他洛尔", "sotalol"),
    ("决奈达隆", "dronedarone"),
    ("多非利特", "dofetilide"),
    ("维拉帕米", "verapamil"),
    ("硝苯地平", "nifedipine"),
    ("尼莫地平", "nimodipine"),
    ("非洛地平", "felodipine"),
    ("氨氯地平", "amlodipine"),
    ("氟桂利嗪", "flunarizine"),
    ("尼卡地平", "nicardipine"),
    ("苄普地尔", "bepridil"),
    ("加洛帕米", "gallopamil"),
    ("丙吡胺", "disopyramide"),
    ("奎尼丁", "quinidine"),
    ("美西律", "mexiletine"),
    ("氟卡尼", "flecainide"),
    ("地尔硫䓬", "diltiazem"),
    ("华法林", "warfarin"),
    ("地高辛", "digoxin"),
    ("溴苄铵", "bretylium"),
    ("阿托品", "atropine"),

    # Ch23 antianginals
    ("单硝酸异山梨酯", "isosorbide mononitrate"),
    ("硝酸异山梨酯", "isosorbide dinitrate"),
    ("硝酸甘油", "nitroglycerin"),
    ("曲美他嗪", "trimetazidine"),
    ("尼可地尔", "nicorandil"),
    ("吗多明", "molsidomine"),
    ("卡维地洛", "carvedilol"),
    ("阿司匹林", "aspirin"),
    ("氯吡格雷", "clopidogrel"),
    ("替格瑞洛", "ticagrelor"),
    ("替罗非班", "tirofiban"),
    ("依替巴肽", "eptifibatide"),
    ("阿昔单抗", "abciximab"),
    ("雷诺嗪", "ranolazine"),
    ("甲亚油酰胺", "melinamide"),

    # Ch24 lipid-lowering
    ("阿托伐他汀", "atorvastatin"),
    ("瑞舒伐他汀", "rosuvastatin"),
    ("洛伐他汀", "lovastatin"),
    ("辛伐他汀", "simvastatin"),
    ("普伐他汀", "pravastatin"),
    ("氟伐他汀", "fluvastatin"),
    ("依洛尤单抗", "evolocumab"),
    ("阿利西尤单抗", "alirocumab"),
    ("英克司兰", "inclisiran"),
    ("考来烯胺", "cholestyramine"),
    ("考来替泊", "colestipol"),
    ("依折麦布", "ezetimibe"),
    ("吉非罗齐", "gemfibrozil"),
    ("非诺贝特", "fenofibrate"),
    ("苯扎贝特", "bezafibrate"),
    ("阿昔莫司", "acipimox"),
    ("普罗布考", "probucol"),
    ("多沙唑嗪", "doxazosin"),
    ("保泰松", "phenylbutazone"),
    ("洋地黄毒苷", "digitoxin"),
    ("烟酸戊四醇酯", "niceritrol"),
    ("烟酸生育酚酯", "tocopheryl nicotinate"),
    ("低分子量肝素", "low molecular weight heparin"),
    ("冠心病舒", "Guanxinshu"),
    ("新霉素", "neomycin"),

    # ===== DISEASE/CONDITION NAMES =====
    ("尖端扭转型室性心动过速", "torsades de pointes"),
    ("阵发性室上性心动过速", "paroxysmal supraventricular tachycardia"),
    ("不稳定型心绞痛", "unstable angina"),
    ("稳定型心绞痛", "stable angina"),
    ("变异型心绞痛", "variant angina"),
    ("劳力性心绞痛", "effort angina"),
    ("混合型高脂血症", "mixed hyperlipidemia"),
    ("高甘油三酯血症", "hypertriglyceridemia"),
    ("高胆固醇血症", "hypercholesterolemia"),
    ("高脂蛋白血症", "hyperlipoproteinemia"),
    ("预激综合征", "WPW syndrome"),
    ("室上性心动过速", "supraventricular tachycardia"),
    ("室性心动过速", "ventricular tachycardia"),
    ("窦性心动过速", "sinus tachycardia"),
    ("窦性心动过缓", "sinus bradycardia"),
    ("室性期前收缩", "ventricular premature contraction"),
    ("房性期前收缩", "atrial premature contraction"),
    ("动脉粥样硬化斑块", "atherosclerotic plaque"),
    ("动脉粥样硬化", "atherosclerosis"),
    ("慢性心力衰竭", "chronic heart failure"),
    ("急性失代偿心力衰竭", "acute decompensated heart failure"),
    ("肺动脉高压", "pulmonary arterial hypertension"),
    ("缺血性心脏病", "ischemic heart disease"),
    ("系统性红斑狼疮", "systemic lupus erythematosus"),
    ("移植物抗宿主病", "graft-versus-host disease"),
    ("出血性膀胱炎", "hemorrhagic cystitis"),
    ("横纹肌溶解综合征", "rhabdomyolysis syndrome"),
    ("高铁血红蛋白血症", "methemoglobinemia"),
    ("甲状腺功能亢进", "hyperthyroidism"),
    ("甲状腺功能减退", "hypothyroidism"),
    ("甲状腺功能紊乱", "thyroid dysfunction"),
    ("粒细胞缺乏症", "agranulocytosis"),
    ("阵发性室上性", "paroxysmal supraventricular"),
    ("肾性尿崩症", "nephrogenic diabetes insipidus"),
    ("出血性膀胱", "hemorrhagic cystitis"),
    ("肺纤维化", "pulmonary fibrosis"),
    ("间质性肺炎", "interstitial pneumonitis"),
    ("代谢性酸中毒", "metabolic acidosis"),
    ("低氯性碱中毒", "hypochloremic alkalosis"),
    ("横纹肌溶解", "rhabdomyolysis"),
    ("高血压危象", "hypertensive crisis"),
    ("急性肾衰竭", "acute renal failure"),
    ("缺血再灌注损伤", "ischemia-reperfusion injury"),
    ("支气管哮喘", "bronchial asthma"),
    ("2型糖尿病", "type 2 diabetes mellitus"),
    ("勃起功能障碍", "erectile dysfunction"),
    ("过敏性鼻炎", "allergic rhinitis"),
    ("过敏性休克", "anaphylactic shock"),
    ("过敏反应", "allergic reaction"),
    ("体位性低血压", "orthostatic hypotension"),
    ("房室传导阻滞", "atrioventricular block"),
    ("恶性黑色素瘤", "malignant melanoma"),
    ("非小细胞肺癌", "non-small cell lung cancer"),
    ("小细胞肺癌", "small cell lung cancer"),
    ("霍奇金淋巴瘤", "Hodgkin lymphoma"),
    ("非霍奇金淋巴瘤", "non-Hodgkin lymphoma"),
    ("肾功能不全", "renal impairment"),
    ("肝功能不全", "hepatic impairment"),
    ("心功能不全", "cardiac insufficiency"),
    ("心血管事件", "cardiovascular events"),
    ("脑血管事件", "cerebrovascular events"),
    ("心搏骤停", "cardiac arrest"),
    ("心力衰竭", "heart failure"),
    ("心室重构", "ventricular remodeling"),
    ("血管重构", "vascular remodeling"),
    ("血液系统肿瘤", "hematologic malignancy"),
    ("尿路上皮癌", "urothelial carcinoma"),
    ("梅克尔细胞癌", "Merkel cell carcinoma"),
    ("高微卫星不稳定性", "high microsatellite instability"),
    ("错配修复缺陷", "mismatch repair deficiency"),
    ("肿瘤突变负荷", "tumor mutational burden"),
    ("新生血管", "neovascularization"),
    ("头颈部鳞癌", "head and neck squamous cell carcinoma"),
    ("结直肠癌", "colorectal cancer"),
    ("肾细胞癌", "renal cell carcinoma"),
    ("肝细胞癌", "hepatocellular carcinoma"),
    ("器官移植", "organ transplantation"),
    ("骨髓移植", "bone marrow transplantation"),
    ("免疫排斥", "immune rejection"),
    ("超急性排斥", "hyperacute rejection"),
    ("急性排斥", "acute rejection"),
    ("慢性排斥", "chronic rejection"),
    ("移植物抗宿主", "graft-versus-host"),
    ("宿主抗移植物", "host-versus-graft"),
    ("骨髓抑制", "myelosuppression"),
    ("白细胞减少", "leukopenia"),
    ("粒细胞减少", "neutropenia"),
    ("低钾血症", "hypokalemia"),
    ("高钾血症", "hyperkalemia"),
    ("低镁血症", "hypomagnesemia"),
    ("高尿酸血症", "hyperuricemia"),
    ("视力模糊", "blurred vision"),
    ("口腔干燥", "xerostomia"),
    ("皮肤潮红", "cutaneous flushing"),
    ("牙龈增生", "gingival hyperplasia"),
    ("男性乳房女性化", "gynecomastia"),
    ("乳腺增生", "gynecomastia"),
    ("心室颤动", "ventricular fibrillation"),
    ("心房扑动", "atrial flutter"),
    ("心房颤动", "atrial fibrillation"),
    ("心室扑动", "ventricular flutter"),
    ("心肌梗死", "myocardial infarction"),
    ("心肌缺血", "myocardial ischemia"),
    ("心绞痛", "angina pectoris"),
    ("血栓形成", "thrombosis"),
    ("血栓栓塞", "thromboembolism"),
    ("斑块破裂", "plaque rupture"),
    ("斑块稳定", "plaque stabilization"),
    ("斑块消退", "plaque regression"),
    ("前列腺癌", "prostate cancer"),
    ("乳腺癌", "breast cancer"),
    ("卵巢癌", "ovarian cancer"),
    ("胰腺癌", "pancreatic cancer"),
    ("膀胱癌", "bladder cancer"),
    ("胃癌", "gastric cancer"),
    ("内耳眩晕病", "Meniere disease"),
    ("过敏性", "allergic"),
    ("免疫相关不良事件", "immune-related adverse events"),
    ("细胞因子释放综合征", "cytokine release syndrome"),
    ("二尖瓣", "mitral valve"),
    ("花粉症", "hay fever"),
    ("荨麻疹", "urticaria"),
    ("偏头痛", "migraine"),
    ("麻风病", "leprosy"),
    ("青光眼", "glaucoma"),
    ("尿崩症", "diabetes insipidus"),
    ("高钙血症", "hypercalcemia"),
    ("高脂血症", "hyperlipidemia"),
    ("糖尿病", "diabetes mellitus"),
    ("高血压", "hypertension"),
    ("低血压", "hypotension"),
    ("高血糖", "hyperglycemia"),
    ("低血糖", "hypoglycemia"),
    ("高血钾", "hyperkalemia"),
    ("低血钾", "hypokalemia"),
    ("肝坏死", "hepatic necrosis"),
    ("心肌炎", "myocarditis"),
    ("心包炎", "pericarditis"),
    ("牙龈炎", "gingivitis"),
    ("鼻出血", "epistaxis"),
    ("肾结石", "renal calculi"),
    ("肺水肿", "pulmonary edema"),
    ("脑水肿", "cerebral edema"),
    ("脑卒中", "stroke"),
    ("淋巴瘤", "lymphoma"),
    ("实体瘤", "solid tumor"),
    ("黑色素瘤", "melanoma"),
    ("白细胞", "white blood cells"),
    ("白血病", "leukemia"),
    ("纤维化", "fibrosis"),
    ("硬化", "sclerosis"),
    ("痉挛", "spasm"),
    ("栓塞", "embolism"),
    ("血栓", "thrombus"),
    ("缺血", "ischemia"),
    ("缺氧", "hypoxia"),
    ("坏死", "necrosis"),
    ("发热", "fever"),
    ("头痛", "headache"),
    ("眩晕", "dizziness"),
    ("恶心", "nausea"),
    ("呕吐", "vomiting"),
    ("腹泻", "diarrhea"),
    ("便秘", "constipation"),
    ("乏力", "fatigue"),
    ("失眠", "insomnia"),
    ("癫痫", "seizure"),
    ("贫血", "anemia"),
    ("感染", "infection"),
    ("肥胖", "obesity"),
    ("吸烟", "smoking"),
    ("麻风", "leprosy"),
    ("哮喘", "asthma"),
    ("溃疡", "ulcer"),
    ("水肿", "edema"),
    ("耳聋", "deafness"),
    ("耳鸣", "tinnitus"),
    ("瘙痒", "pruritus"),
    ("疼痛", "pain"),
    ("癌症", "cancer"),
    ("肿瘤", "tumor"),
    ("肉瘤", "sarcoma"),
    ("乳溢", "galactorrhea"),
    ("多毛症", "hirsutism"),
    ("光敏", "photosensitivity"),
    ("猝死", "sudden death"),
    ("停搏", "cardiac arrest"),

    # ===== MEDICAL TERMS - PHYSIOLOGY/ANATOMY =====
    ("Vaughan Williams分类法", "Vaughan Williams classification"),
    ("Vaughan Williams分类", "Vaughan Williams classification"),
    ("Michaelis-Menten动力学", "Michaelis-Menten kinetics"),
    ("H+-K+-ATP酶", "H+-K+-ATPase"),
    ("Na+-K+-ATP酶", "Na+-K+-ATPase"),
    ("ATP敏感钾通道", "ATP-sensitive potassium channel"),
    ("ACh敏感钾通道", "acetylcholine-sensitive potassium channel"),
    ("延迟整流钾通道", "delayed rectifier potassium channel"),
    ("兴奋-收缩耦联", "excitation-contraction coupling"),
    ("希氏-浦肯野系统", "His-Purkinje system"),
    ("浦肯野纤维", "Purkinje fibers"),
    ("电压门控钙通道", "voltage-gated calcium channel"),
    ("G蛋白偶联受体", "G protein-coupled receptor"),
    ("配体门控离子通道", "ligand-gated ion channel"),
    ("窦房结", "sinoatrial node"),
    ("房室结", "atrioventricular node"),
    ("心肌细胞", "cardiomyocyte"),
    ("血管平滑肌", "vascular smooth muscle"),
    ("平滑肌细胞", "smooth muscle cell"),
    ("横纹肌", "striated muscle"),
    ("骨骼肌", "skeletal muscle"),
    ("平滑肌", "smooth muscle"),
    ("淋巴液", "endolymph"),
    ("脉络丛", "choroid plexus"),
    ("睫状体", "ciliary body"),
    ("海绵体", "corpus cavernosum"),
    ("三叉神经", "trigeminal nerve"),
    ("呕吐中枢", "vomiting center"),
    ("化学感受区", "chemoreceptor trigger zone"),
    ("基底膜", "basilar membrane"),
    ("内耳", "inner ear"),
    ("迷路", "labyrinth"),
    ("耳蜗", "cochlea"),
    ("角膜", "cornea"),
    ("脑脊液", "cerebrospinal fluid"),
    ("房水", "aqueous humor"),
    ("神经递质", "neurotransmitter"),
    ("神经末梢", "nerve terminal"),
    ("突触前膜", "presynaptic membrane"),
    ("突触后膜", "postsynaptic membrane"),
    ("突触", "synapse"),
    ("血脑屏障", "blood-brain barrier"),
    ("肾小球滤过率", "glomerular filtration rate"),
    ("髓袢升支粗段", "thick ascending limb of loop of Henle"),
    ("远曲小管远端", "late distal convoluted tubule"),
    ("远曲小管近端", "early distal convoluted tubule"),
    ("远曲小管", "distal convoluted tubule"),
    ("近曲小管", "proximal convoluted tubule"),
    ("集合管", "collecting duct"),
    ("髓袢升支", "ascending limb of loop of Henle"),
    ("顶端膜", "apical membrane"),
    ("基侧膜", "basolateral membrane"),
    ("冠状动脉", "coronary artery"),
    ("侧支循环", "collateral circulation"),
    ("容量血管", "capacitance vessels"),
    ("阻力血管", "resistance vessels"),
    ("心肌收缩力", "myocardial contractility"),
    ("心室壁张力", "ventricular wall tension"),
    ("射血时间", "ejection time"),
    ("外周阻力", "peripheral resistance"),
    ("回心血量", "venous return"),
    ("灌注压", "perfusion pressure"),
    ("动作电位时程", "action potential duration"),
    ("有效不应期", "effective refractory period"),
    ("动作电位", "action potential"),
    ("收缩压", "systolic blood pressure"),
    ("舒张压", "diastolic blood pressure"),
    ("不应期", "refractory period"),
    ("心肌耗氧量", "myocardial oxygen consumption"),
    ("每搏量", "stroke volume"),
    ("心室容积", "ventricular volume"),
    ("前负荷", "preload"),
    ("后负荷", "afterload"),
    ("窦性心律", "sinus rhythm"),
    ("胞质", "cytoplasm"),
    ("胞内", "intracellular"),
    ("胞外", "extracellular"),
    ("细胞", "cell"),
    ("细胞膜", "cell membrane"),
    ("细胞质", "cytoplasm"),
    ("细胞核", "nucleus"),
    ("线粒体", "mitochondria"),
    ("内质网", "endoplasmic reticulum"),
    ("核糖体", "ribosome"),
    ("溶酶体", "lysosome"),
    ("高尔基体", "Golgi apparatus"),
    ("内皮细胞", "endothelial cell"),
    ("上皮细胞", "epithelial cell"),
    ("间质细胞", "interstitial cell"),
    ("成纤维细胞", "fibroblast"),
    ("中性粒细胞", "neutrophils"),
    ("嗜碱性粒细胞", "basophils"),
    ("肥大细胞", "mast cells"),
    ("巨噬细胞", "macrophages"),
    ("单核细胞", "monocytes"),
    ("淋巴细胞", "lymphocytes"),
    ("粒细胞", "granulocytes"),
    ("血小板", "platelets"),
    ("骨髓", "bone marrow"),
    ("干细胞", "stem cell"),
    ("祖细胞", "progenitor cell"),
    ("毛细血管", "capillary"),
    ("静脉", "vein"),
    ("动脉", "artery"),
    ("小动脉", "arteriole"),
    ("小静脉", "venule"),
    ("血管", "blood vessel"),
    ("胃肠道", "gastrointestinal tract"),
    ("垂体", "pituitary gland"),
    ("肾上腺", "adrenal gland"),
    ("甲状腺", "thyroid gland"),
    ("胰腺", "pancreas"),
    ("脾脏", "spleen"),
    ("肝脏", "liver"),
    ("肾脏", "kidney"),
    ("心脏", "heart"),
    ("阴道", "vagina"),
    ("子宫", "uterus"),
    ("直肠", "rectum"),
    ("结肠", "colon"),
    ("小肠", "small intestine"),
    ("大肠", "large intestine"),
    ("肠道", "intestine"),
    ("食管", "esophagus"),
    ("气管", "trachea"),
    ("支气管", "bronchus"),
    ("皮肤", "skin"),
    ("组织", "tissue"),
    ("器官", "organ"),
    ("系统", "system"),
    ("胃", "stomach"),
    ("肺", "lung"),
    ("肾", "kidney"),

    # ===== RECEPTORS =====
    ("5-HT1D受体", "5-HT1D receptor"),
    ("5-HT1B受体", "5-HT1B receptor"),
    ("5-HT1A受体", "5-HT1A receptor"),
    ("5-HT2A受体", "5-HT2A receptor"),
    ("5-HT3受体", "5-HT3 receptor"),
    ("5-HT4受体", "5-HT4 receptor"),
    ("5-HT2受体", "5-HT2 receptor"),
    ("5-HT1受体", "5-HT1 receptor"),
    ("5-HT受体", "5-HT receptor"),
    ("H1受体", "H1 receptor"),
    ("H2受体", "H2 receptor"),
    ("H3受体", "H3 receptor"),
    ("H4受体", "H4 receptor"),
    ("AT1受体", "AT1 receptor"),
    ("ETA受体", "ETA receptor"),
    ("ETB受体", "ETB receptor"),
    ("NK1受体", "NK1 receptor"),
    ("B1受体", "B1 receptor"),
    ("B2受体", "B2 receptor"),
    ("V2受体", "V2 receptor"),
    ("CGRP受体", "CGRP receptor"),
    ("GABA受体", "GABA receptor"),
    ("β1受体", "beta-1 receptor"),
    ("β2受体", "beta-2 receptor"),
    ("α1受体", "alpha-1 receptor"),
    ("α受体", "alpha receptor"),
    ("β受体", "beta receptor"),
    ("M受体", "muscarinic receptor"),
    ("多巴胺受体", "dopamine receptor"),
    ("阿片受体", "opioid receptor"),
    ("醛固酮受体", "aldosterone receptor"),

    # ===== ION CHANNELS / TRANSPORTERS =====
    ("钠钙交换体", "Na+-Ca2+ exchanger"),
    ("钠氢交换体", "Na+/H+ exchanger"),
    ("水通道蛋白", "aquaporin"),
    ("共转运体", "cotransporter"),
    ("钠钾泵", "Na+-K+ pump"),
    ("钠通道", "sodium channel"),
    ("钾通道", "potassium channel"),
    ("钙通道", "calcium channel"),
    ("氯通道", "chloride channel"),
    ("L型钙通道", "L-type calcium channel"),
    ("T型钙通道", "T-type calcium channel"),
    ("N型钙通道", "N-type calcium channel"),
    ("P型钙通道", "P-type calcium channel"),
    ("电压门控", "voltage-gated"),

    # ===== ENZYMES =====
    ("HMG-CoA还原酶", "HMG-CoA reductase"),
    ("细胞色素P450酶系", "cytochrome P450 enzyme system"),
    ("细胞色素P450", "cytochrome P450"),
    ("腺苷酸环化酶", "adenylyl cyclase"),
    ("鸟苷酸环化酶", "guanylyl cyclase"),
    ("磷酸二酯酶", "phosphodiesterase"),
    ("黄嘌呤氧化酶", "xanthine oxidase"),
    ("组氨酸脱羧酶", "histidine decarboxylase"),
    ("脂蛋白脂肪酶", "lipoprotein lipase"),
    ("腺苷脱氨酶", "adenosine deaminase"),
    ("激肽释放酶", "kallikrein"),
    ("胰蛋白酶", "trypsin"),
    ("糜蛋白酶", "chymotrypsin"),
    ("纤溶酶", "plasmin"),
    ("碳酸酐酶", "carbonic anhydrase"),
    ("钙调磷酸酶", "calcineurin"),
    ("磷脂酶C", "phospholipase C"),
    ("蛋白激酶C", "protein kinase C"),
    ("蛋白激酶G", "protein kinase G"),
    ("蛋白激酶A", "protein kinase A"),
    ("葡萄糖醛酸转移酶", "glucuronosyltransferase"),
    ("硫酸转移酶", "sulfotransferase"),
    ("谷胱甘肽转移酶", "glutathione S-transferase"),
    ("N-乙酰转移酶", "N-acetyltransferase"),
    ("甲基转移酶", "methyltransferase"),
    ("还原酶", "reductase"),
    ("限制酶", "restriction enzyme"),
    ("合成酶", "synthetase"),
    ("氧化酶", "oxidase"),
    ("脱氢酶", "dehydrogenase"),
    ("转移酶", "transferase"),
    ("羟化酶", "hydroxylase"),
    ("脱羧酶", "decarboxylase"),
    ("环化酶", "cyclase"),
    ("水解酶", "hydrolase"),
    ("蛋白", "protein"),
    ("激素", "hormone"),
    ("激酶", "kinase"),
    ("因子", "factor"),
    ("受体", "receptor"),
    ("配体", "ligand"),
    ("底物", "substrate"),
    ("产物", "product"),
    ("酶", "enzyme"),
    ("基因", "gene"),

    # ===== HORMONES / ENDOGENOUS SUBSTANCES =====
    ("促甲状腺激素", "thyroid-stimulating hormone"),
    ("血管紧张素", "angiotensin"),
    ("抗利尿激素", "antidiuretic hormone"),
    ("血管升压素", "vasopressin"),
    ("儿茶酚胺", "catecholamines"),
    ("前列腺素类", "prostaglandins"),
    ("内生肌酐", "endogenous creatinine"),
    ("肾上腺素", "epinephrine"),
    ("去甲肾上腺素", "norepinephrine"),
    ("乙酰胆碱", "acetylcholine"),
    ("醛固酮", "aldosterone"),
    ("胰岛素", "insulin"),
    ("雌激素", "estrogen"),
    ("孕激素", "progesterone"),
    ("升压素", "vasopressin"),
    ("睾酮", "testosterone"),
    ("组胺", "histamine"),
    ("5-HT", "5-HT"),
    ("P物质", "substance P"),
    ("缓激肽", "bradykinin"),
    ("内皮素", "endothelin"),
    ("前列腺素", "prostaglandin"),
    ("白三烯", "leukotrienes"),
    ("腺苷", "adenosine"),
    ("强心苷", "cardiac glycoside"),
    ("肝素", "heparin"),
    ("烟碱", "nicotine"),
    ("烟酸", "niacin"),
    ("叶酸", "folic acid"),
    ("磺胺", "sulfonamide"),
    ("奎宁", "quinine"),

    # ===== LIPIDS / LIPOPROTEINS =====
    ("脂代谢紊乱", "lipid metabolism disorder"),
    ("脂代谢", "lipid metabolism"),
    ("载脂蛋白", "apolipoprotein"),
    ("脂蛋白(a)", "lipoprotein(a)"),
    ("脂蛋白", "lipoprotein"),
    ("甘油三酯", "triglycerides"),
    ("胆汁酸螯合剂", "bile acid sequestrants"),
    ("胆固醇吸收抑制药", "cholesterol absorption inhibitors"),
    ("泡沫细胞", "foam cells"),
    ("甲羟戊酸", "mevalonic acid"),
    ("逆行转运", "reverse cholesterol transport"),
    ("氧化修饰", "oxidative modification"),
    ("氧自由基", "oxygen free radicals"),
    ("钙超载", "calcium overload"),
    ("氧化应激", "oxidative stress"),
    ("炎症反应", "inflammatory response"),
    ("炎症介质", "inflammatory mediators"),
    ("内皮功能", "endothelial function"),
    ("胆汁酸", "bile acids"),
    ("肝肠循环", "enterohepatic circulation"),
    ("脂肪酸", "fatty acids"),
    ("磷脂", "phospholipids"),
    ("胆固醇", "cholesterol"),
    ("血脂", "blood lipids"),
    ("尿酸", "uric acid"),
    ("溶血", "hemolysis"),

    # ===== DRUG CLASSES =====
    ("血管升压素V2受体阻断药", "vasopressin V2 receptor antagonist"),
    ("Vaughan Williams", "Vaughan Williams"),
    ("免疫检查点抑制药", "immune checkpoint inhibitor"),
    ("免疫检查点", "immune checkpoint"),
    ("免疫抑制药", "immunosuppressant"),
    ("免疫增强药", "immunostimulant"),
    ("免疫调节药", "immunomodulator"),
    ("渗透性利尿药", "osmotic diuretic"),
    ("抗血小板药", "antiplatelet drug"),
    ("抗心律失常药", "antiarrhythmic drug"),
    ("抗心肌缺血药", "antianginal drug"),
    ("抗心绞痛药", "antianginal drug"),
    ("二氢吡啶类", "dihydropyridine"),
    ("苯烷胺类", "phenylalkylamine"),
    ("苯并噻氮䓬类", "benzothiazepine"),
    ("抗组胺药", "antihistamine"),
    ("调血脂药", "lipid-lowering drug"),
    ("保钾利尿药", "potassium-sparing diuretic"),
    ("碳酸酐酶抑制药", "carbonic anhydrase inhibitor"),
    ("单克隆抗体", "monoclonal antibody"),
    ("多克隆抗体", "polyclonal antibody"),
    ("利尿药", "diuretic"),
    ("袢利尿药", "loop diuretic"),
    ("脱水药", "dehydrating agent"),
    ("抗凝药", "anticoagulant"),
    ("纤溶药", "fibrinolytic"),
    ("溶栓药", "thrombolytic"),
    ("抗血栓", "antithrombotic"),
    ("他汀类", "statin"),
    ("贝特类", "fibrate"),
    ("烟酸类", "niacin class"),
    ("硝酸酯类", "nitrate"),
    ("噻嗪类", "thiazide"),
    ("类噻嗪类", "thiazide-like"),
    ("抗生素类", "antibiotic class"),
    ("吩噻嗪类", "phenothiazine"),
    ("乙醇胺类", "ethanolamine"),
    ("乙二胺类", "ethylenediamine"),
    ("烷基胺类", "alkylamine"),
    ("哌嗪类", "piperazine"),
    ("哌啶类", "piperidine"),
    ("强心苷类", "cardiac glycoside"),
    ("钙拮抗", "calcium antagonist"),
    ("调血脂", "lipid-lowering"),
    ("抗组胺", "antihistamine"),
    ("抗心律失常", "antiarrhythmic"),
    ("抗心肌缺血", "antianginal"),
    ("抗心绞痛", "antianginal"),
    ("抑制药", "inhibitor"),
    ("阻断药", "blocker"),
    ("阻滞药", "blocker"),
    ("激动药", "agonist"),
    ("拮抗药", "antagonist"),
    ("激活药", "activator"),

    # ===== IMMUNE-RELATED =====
    ("免疫抑制", "immunosuppression"),
    ("免疫增强", "immunostimulation"),
    ("免疫调节", "immunomodulation"),
    ("自身免疫病", "autoimmune disease"),
    ("细胞因子", "cytokines"),
    ("细胞免疫", "cell-mediated immunity"),
    ("体液免疫", "humoral immunity"),
    ("先天免疫", "innate immunity"),
    ("适应性免疫", "adaptive immunity"),
    ("排斥反应", "rejection reaction"),
    ("免疫原性", "immunogenicity"),
    ("抗原性", "antigenicity"),
    ("亲环蛋白", "cyclophilin"),
    ("自身抗体", "autoantibody"),
    ("淋巴细胞", "lymphocytes"),
    ("粒细胞", "granulocytes"),
    ("T细胞", "T cell"),
    ("B细胞", "B cell"),
    ("NK细胞", "NK cell"),
    ("抗原", "antigen"),
    ("抗体", "antibody"),
    ("补体", "complement"),
    ("免疫", "immunity"),

    # ===== CELL BIOLOGY =====
    ("细胞周期", "cell cycle"),
    ("有丝分裂", "mitosis"),
    ("减数分裂", "meiosis"),
    ("G1期", "G1 phase"),
    ("S期", "S phase"),
    ("G2期", "G2 phase"),
    ("M期", "M phase"),
    ("G0期", "G0 phase"),
    ("凋亡", "apoptosis"),
    ("增殖", "proliferation"),
    ("分化", "differentiation"),
    ("成熟", "maturation"),
    ("归巢", "homing"),
    ("趋化", "chemotaxis"),
    ("黏附", "adhesion"),
    ("迁移", "migration"),
    ("浸润", "infiltration"),
    ("吞噬", "phagocytosis"),
    ("脱颗粒", "degranulation"),
    ("致敏", "sensitization"),

    # ===== PHARMACOKINETICS =====
    ("治疗药物监测", "therapeutic drug monitoring"),
    ("血药浓度监测", "plasma drug concentration monitoring"),
    ("药物基因组学", "pharmacogenomics"),
    ("药物遗传学", "pharmacogenetics"),
    ("绝对生物利用度", "absolute bioavailability"),
    ("相对生物利用度", "relative bioavailability"),
    ("药时曲线下面积", "area under the curve"),
    ("稳态血药浓度", "steady-state plasma concentration"),
    ("分布半衰期", "distribution half-life"),
    ("消除半衰期", "elimination half-life"),
    ("吸收半衰期", "absorption half-life"),
    ("终末半衰期", "terminal half-life"),
    ("非线性动力学", "nonlinear kinetics"),
    ("线性动力学", "linear kinetics"),
    ("零级动力学", "zero-order kinetics"),
    ("一级动力学", "first-order kinetics"),
    ("生物利用度", "bioavailability"),
    ("血浆蛋白结合率", "plasma protein binding rate"),
    ("分布容积", "volume of distribution"),
    ("清除率", "clearance"),
    ("个体化给药", "individualized dosing"),
    ("首过消除", "first-pass elimination"),
    ("首过效应", "first-pass effect"),
    ("负荷剂量", "loading dose"),
    ("起始剂量", "starting dose"),
    ("维持剂量", "maintenance dose"),
    ("最大耐受剂量", "maximum tolerated dose"),
    ("最低有效剂量", "minimum effective dose"),
    ("有效浓度范围", "effective concentration range"),
    ("剂量调整", "dose adjustment"),
    ("前体药物", "prodrug"),
    ("给药间隔", "dosing interval"),
    ("达峰浓度", "peak concentration"),
    ("达峰时间", "time to peak"),
    ("蛋白结合率", "protein binding rate"),
    ("血药浓度", "plasma drug concentration"),
    ("脂溶性", "lipid solubility"),
    ("水溶性", "water solubility"),
    ("分子量", "molecular weight"),
    ("解离度", "degree of ionization"),
    ("半衰期", "half-life"),
    ("治疗窗", "therapeutic window"),
    ("峰浓度", "peak concentration"),
    ("谷浓度", "trough concentration"),
    ("中毒浓度", "toxic concentration"),
    ("前药", "prodrug"),

    # ===== DRUG TRANSPORTERS =====
    ("P-糖蛋白", "P-glycoprotein"),
    ("有机阴离子转运体", "organic anion transporter"),
    ("有机阳离子转运体", "organic cation transporter"),
    ("多药耐药", "multidrug resistance"),
    ("药物外排泵", "drug efflux pump"),
    ("代谢酶", "metabolic enzyme"),
    ("代谢途径", "metabolic pathway"),
    ("转运体", "transporter"),

    # ===== PHARMACODYNAMICS =====
    ("电生理作用", "electrophysiological effect"),
    ("药理作用", "pharmacological effect"),
    ("毒副作用", "toxic side effect"),
    ("负性肌力作用", "negative inotropic effect"),
    ("负性频率作用", "negative chronotropic effect"),
    ("负性传导作用", "negative dromotropic effect"),
    ("致心律失常作用", "proarrhythmic effect"),
    ("缺血预适应", "ischemic preconditioning"),
    ("致心律失常", "proarrhythmic"),
    ("药物相互作用", "drug interaction"),
    ("竞争性抑制", "competitive inhibition"),
    ("非竞争性抑制", "noncompetitive inhibition"),
    ("不可逆抑制", "irreversible inhibition"),
    ("活性代谢产物", "active metabolite"),
    ("作用机制", "mechanism of action"),
    ("药理效应", "pharmacological effect"),
    ("信号通路", "signaling pathway"),
    ("第二信使", "second messenger"),
    ("配伍禁忌", "incompatibility"),
    ("继发反应", "secondary reaction"),
    ("后遗效应", "residual effect"),
    ("撤药反应", "withdrawal reaction"),
    ("不良反应", "adverse effect"),
    ("反跳现象", "rebound phenomenon"),
    ("临床应用", "clinical application"),
    ("临床用途", "clinical use"),
    ("临床试验", "clinical trial"),
    ("临床研究", "clinical study"),
    ("动物实验", "animal experiment"),
    ("给药途径", "route of administration"),
    ("结合位点", "binding site"),
    ("活性位点", "active site"),
    ("负性肌力", "negative inotropic"),
    ("负性频率", "negative chronotropic"),
    ("负性传导", "negative dromotropic"),
    ("正性肌力", "positive inotropic"),
    ("禁忌证", "contraindication"),
    ("适应证", "indication"),
    ("副作用", "side effect"),
    ("毒性反应", "toxic reaction"),
    ("治疗作用", "therapeutic effect"),
    ("临床", "clinical"),
    ("治疗", "treatment"),
    ("效力", "efficacy"),
    ("效价", "potency"),
    ("最大效应", "maximal effect"),
    ("剂量", "dose"),
    ("用量", "dosage"),
    ("疗程", "treatment course"),
    ("复合物", "complex"),
    ("代谢物", "metabolite"),
    ("共转运", "cotransport"),
    ("重吸收", "reabsorption"),
    ("拮抗", "antagonize"),
    ("激动", "agonize"),
    ("阻断", "block"),
    ("阻滞", "block"),
    ("激活", "activate"),
    ("抑制", "inhibit"),

    # ===== ADMINISTRATION / DOSING =====
    ("静脉注射给药", "intravenous administration"),
    ("玻璃体腔内注射", "intravitreal injection"),
    ("关节腔内注射", "intra-articular injection"),
    ("硬膜外注射", "epidural injection"),
    ("鞘内注射", "intrathecal injection"),
    ("海绵体内注射", "intracavernosal injection"),
    ("静脉注射后", "after intravenous injection"),
    ("静脉注射", "intravenous injection"),
    ("肌内注射", "intramuscular injection"),
    ("皮下注射", "subcutaneous injection"),
    ("舌下含服后", "after sublingual administration"),
    ("舌下含服", "sublingual administration"),
    ("口服后", "after oral administration"),
    ("口服吸收", "oral absorption"),
    ("口服给药", "oral administration"),
    ("吸入给药", "inhaled administration"),
    ("靶向给药", "targeted drug delivery"),
    ("经鼻给药", "intranasal administration"),
    ("经肺给药", "pulmonary administration"),
    ("经口给药", "oral administration"),
    ("透皮给药", "transdermal drug delivery"),
    ("经直肠给药", "rectal administration"),
    ("经阴道给药", "vaginal administration"),
    ("局部给药", "local administration"),
    ("全身给药", "systemic administration"),
    ("注射后", "after injection"),
    ("用药后", "after drug administration"),
    ("给药后", "after dosing"),
    ("停药后", "after drug discontinuation"),
    ("首剂给药后", "after the first dose"),
    ("起效后", "after onset of action"),
    ("脉冲释放", "pulsatile release"),
    ("口服", "orally"),
    ("静脉", "intravenously"),
    ("给药", "administration"),
    ("注射", "injection"),

    # ===== DOSAGE FORMS =====
    ("复方制剂", "combination preparation"),
    ("单方制剂", "single-drug preparation"),
    ("生物类似药", "biosimilar"),
    ("注射液", "injection"),
    ("注射剂", "injectable formulation"),
    ("颗粒剂", "granules"),
    ("气雾剂", "aerosol"),
    ("喷雾剂", "spray"),
    ("控释片", "controlled-release tablet"),
    ("缓释片", "extended-release tablet"),
    ("肠溶片", "enteric-coated tablet"),
    ("舌下片", "sublingual tablet"),
    ("口崩片", "orally disintegrating tablet"),
    ("泡腾片", "effervescent tablet"),
    ("咀嚼片", "chewable tablet"),
    ("滴眼液", "eye drops"),
    ("滴耳液", "ear drops"),
    ("滴鼻液", "nasal spray"),
    ("口服液", "oral solution"),
    ("混悬剂", "suspension"),
    ("软膏", "ointment"),
    ("霜剂", "cream"),
    ("贴剂", "patch"),
    ("栓剂", "suppository"),
    ("粉剂", "powder"),
    ("乳剂", "emulsion"),
    ("片剂", "tablet"),
    ("胶囊", "capsule"),
    ("缓释片", "extended-release tablet"),

    # ===== CLINICAL PROCEDURES =====
    ("心肺复苏", "cardiopulmonary resuscitation"),
    ("支架内血栓形成", "in-stent thrombosis"),
    ("血运重建", "revascularization"),
    ("再灌注", "reperfusion"),
    ("复律", "cardioversion"),
    ("除颤", "defibrillation"),
    ("电复律", "electrical cardioversion"),
    ("电除颤", "electrical defibrillation"),
    ("冠脉", "coronary artery"),
    ("造影", "angiography"),
    ("介入", "intervention"),
    ("支架", "stent"),
    ("搭桥", "bypass surgery"),
    ("移植", "transplantation"),
    ("移植术", "transplant"),

    # ===== LABORATORY TESTS =====
    ("活化部分凝血活酶时间", "activated partial thromboplastin time"),
    ("国际标准化比值", "international normalized ratio"),
    ("凝血酶原时间", "prothrombin time"),
    ("丙氨酸转氨酶", "alanine aminotransferase"),
    ("天冬氨酸转氨酶", "aspartate aminotransferase"),
    ("心肌肌钙蛋白", "cardiac troponin"),
    ("纤维蛋白原", "fibrinogen"),
    ("C反应蛋白", "C-reactive protein"),
    ("间接胆红素", "indirect bilirubin"),
    ("直接胆红素", "direct bilirubin"),
    ("总胆红素", "total bilirubin"),
    ("血清肌酐", "serum creatinine"),
    ("内生肌酐清除率", "creatinine clearance"),
    ("心电图", "electrocardiogram"),
    ("肌酸激酶", "creatine kinase"),
    ("转氨酶", "transaminase"),
    ("肌鈣蛋白", "troponin"),
    ("白细胞计数", "white blood cell count"),
    ("中性粒细胞计数", "absolute neutrophil count"),
    ("血小板计数", "platelet count"),
    ("血红蛋白", "hemoglobin"),
    ("血细胞比容", "hematocrit"),
    ("游离T4", "free T4"),
    ("游离T3", "free T3"),
    ("尿素氮", "blood urea nitrogen"),
    ("胆红素", "bilirubin"),
    ("白蛋白", "albumin"),
    ("球蛋白", "globulin"),
    ("总蛋白", "total protein"),
    ("肌酐", "creatinine"),
    ("血沉", "erythrocyte sedimentation rate"),
    ("凝血", "coagulation"),
    ("抗凝", "anticoagulation"),
    ("纤溶", "fibrinolysis"),
    ("血糖", "blood glucose"),
    ("血钾", "serum potassium"),
    ("血钠", "serum sodium"),
    ("血钙", "serum calcium"),
    ("血镁", "serum magnesium"),
    ("血肌酐", "serum creatinine"),
    ("肝功能", "liver function"),
    ("肾功能", "renal function"),
    ("肺功能", "pulmonary function"),
    ("甲状腺功能", "thyroid function"),

    # ===== EKG TERMS =====
    ("Q-T间期延长", "QT interval prolongation"),
    ("Q-T间期", "QT interval"),
    ("房室传导", "AV conduction"),
    ("室内传导", "intraventricular conduction"),

    # ===== NUMBERS =====
    ("第一代", "first-generation"),
    ("第二代", "second-generation"),
    ("第三代", "third-generation"),
    ("第I类", "Class I"),
    ("第II类", "Class II"),
    ("第III类", "Class III"),
    ("第IV类", "Class IV"),
    ("I类", "Class I"),
    ("II类", "Class II"),
    ("III类", "Class III"),
    ("IV类", "Class IV"),
    ("Ia类", "Class Ia"),
    ("Ib类", "Class Ib"),
    ("Ic类", "Class Ic"),
    ("I型", "type I"),
    ("II型", "type II"),
    ("III型", "type III"),
    ("IV型", "type IV"),

    # ===== TIME EXPRESSIONS =====
    ("20-30分钟", "20-30 minutes"),
    ("1-4周", "1-4 weeks"),
    ("1-2分钟", "1-2 minutes"),
    ("约2-3小时", "approximately 2-3 hours"),
    ("约4-6小时", "approximately 4-6 hours"),
    ("约14小时", "approximately 14 hours"),
    ("约30分钟", "approximately 30 minutes"),
    ("约10秒", "approximately 10 seconds"),
    ("约1小时", "approximately 1 hour"),
    ("24小时", "24 hours"),
    ("5分钟", "5 minutes"),
    ("30分钟", "30 minutes"),
    ("2-3小时", "2-3 hours"),
    ("4-6小时", "4-6 hours"),
    ("数分钟", "several minutes"),
    ("数小时", "several hours"),
    ("数天", "several days"),
    ("数周", "several weeks"),
    ("数月", "several months"),
    ("数年", "several years"),
    ("每天", "daily"),
    ("一天", "one day"),
    ("一周", "one week"),
    ("一月", "one month"),
    ("一年", "one year"),
    ("小时", "hours"),
    ("分钟", "minutes"),
    ("秒", "seconds"),
    ("天", "days"),
    ("周", "weeks"),
    ("月", "months"),
    ("年", "years"),

    # ===== TREATMENT TERMS =====
    ("预防性用药", "prophylactic medication"),
    ("经验性治疗", "empirical treatment"),
    ("个体化治疗", "individualized treatment"),
    ("综合治疗", "comprehensive treatment"),
    ("联合治疗", "combination therapy"),
    ("辅助治疗", "adjuvant therapy"),
    ("支持疗法", "supportive therapy"),
    ("序贯治疗", "sequential therapy"),
    ("交替治疗", "alternating therapy"),
    ("强化治疗", "intensification therapy"),
    ("巩固治疗", "consolidation therapy"),
    ("维持治疗", "maintenance therapy"),
    ("抢救治疗", "rescue therapy"),
    ("标准治疗", "standard treatment"),
    ("一线治疗", "first-line treatment"),
    ("二线治疗", "second-line treatment"),
    ("急性处理", "acute management"),
    ("长期管理", "long-term management"),
    ("二级预防", "secondary prevention"),
    ("早期发现", "early detection"),
    ("早期干预", "early intervention"),
    ("药物选择", "drug selection"),
    ("首选药物", "drug of first choice"),
    ("首选用药", "first-line drug"),
    ("首选药", "drug of choice"),
    ("代表药物", "representative drug"),
    ("药物浓度", "drug concentration"),

    # ===== ORDERING / COMPARISON =====
    ("下列哪项是错误的", "Which of the following is INCORRECT?"),
    ("下列哪项是正确的", "Which of the following is CORRECT?"),
    ("下列哪类", "Which of the following classes"),
    ("下列哪种", "Which of the following"),
    ("下列哪个", "Which of the following"),
    ("下列关于", "Regarding"),
    ("不包括", "does NOT include"),
    ("不含有", "does NOT contain"),
    ("不属于", "does NOT belong to"),
    ("不能用于", "cannot be used for"),
    ("不宜用于", "is not suitable for"),
    ("不可用于", "must NOT be used for"),
    ("不适合", "is NOT suitable for"),
    ("不会引起", "does NOT cause"),
    ("错误的是", "is INCORRECT"),
    ("正确的是", "is CORRECT"),
    ("不包活", "does NOT include"),
    ("不需要", "does NOT require"),
    ("不应", "should NOT"),
    ("不可", "must NOT"),
    ("不得", "must NOT"),
    ("禁止", "is PROHIBITED"),
    ("严禁", "is STRICTLY PROHIBITED"),

    # ===== STATISTICS / MATH =====
    ("越来越", "increasingly"),
    ("95%可信区间", "95% confidence interval"),
    ("可信区间", "confidence interval"),
    ("统计学意义", "statistical significance"),
    ("临床意义", "clinical significance"),
    ("显著性差异", "significant difference"),
    ("无显著性差异", "no significant difference"),
    ("呈正相关", "is positively correlated"),
    ("呈负相关", "is negatively correlated"),
    ("呈剂量依赖", "is dose-dependent"),
    ("呈时间依赖", "is time-dependent"),
    ("绝对危险降低", "absolute risk reduction"),
    ("相对危险降低", "relative risk reduction"),
    ("需要治疗人数", "number needed to treat"),
    ("需要伤害人数", "number needed to harm"),
    ("呈线性关系", "shows a linear relationship"),
    ("呈非线性关系", "shows a nonlinear relationship"),
    ("成正比", "is directly proportional to"),
    ("成反比", "is inversely proportional to"),
    ("正相关", "positively correlated"),
    ("负相关", "negatively correlated"),
    ("标准差", "standard deviation"),
    ("标准误", "standard error"),
    ("比值比", "odds ratio"),
    ("相对危险度", "relative risk"),
    ("风险比", "hazard ratio"),
    ("百分比", "percentage"),
    ("平均值", "mean"),
    ("中位数", "median"),

    # ===== VERBS - COMPLEX =====
    ("主要作用机制", "primary mechanism of action"),
    ("主要作用于", "primarily acts on"),
    ("主要作用", "primary action"),
    ("主要用于", "is primarily used for"),
    ("常用于", "is commonly used for"),
    ("可用于", "can be used for"),
    ("适用于", "is indicated for"),
    ("禁用于", "is contraindicated in"),
    ("慎用于", "should be used with caution in"),
    ("作用于", "acts on"),
    ("应用于", "is applied in"),
    ("表现为", "manifests as"),
    ("被称为", "is called"),
    ("称为", "is called"),
    ("视为", "is regarded as"),
    ("被认为", "is considered to be"),
    ("常被称为", "is often called"),
    ("定义为", "is defined as"),
    ("取决于", "depends on"),
    ("依赖于", "is dependent on"),
    ("独立于", "is independent of"),
    ("相当于", "is equivalent to"),
    ("不同于", "is different from"),
    ("相似于", "is similar to"),
    ("不亚于", "is not inferior to"),
    ("之所以", "because"),
    ("是因为", "because"),

    # ===== VERBS - SIMPLE =====
    ("所介导", "is mediated by"),
    ("所引起", "is caused by"),
    ("所导致", "is caused by"),
    ("所产生", "is produced by"),
    ("所诱发", "is induced by"),
    ("所抑制", "is inhibited by"),
    ("所阻断", "is blocked by"),
    ("所激活", "is activated by"),
    ("所增强", "is enhanced by"),
    ("所减弱", "is attenuated by"),
    ("所必需", "is essential for"),
    ("所特有", "is specific to"),
    ("所具有", "is inherent to"),
    ("所缺乏", "is deficient in"),
    ("所致", "is caused by"),
    ("中所含", "contained in"),
    ("中所见", "observed in"),
    ("中起重要作用", "plays an important role in"),
    ("中起关键作用", "plays a critical role in"),
    ("中发挥作用", "plays a role in"),
    ("中具有重要作用", "has an important role in"),
    ("参与", "participates in"),
    ("介导", "mediates"),
    ("导致", "causes"),
    ("引起", "causes"),
    ("造成", "causes"),
    ("促使", "promotes"),
    ("使得", "renders"),
    ("促进", "promotes"),
    ("竞争", "competes with"),
    ("增加", "increases"),
    ("增多", "increases"),
    ("增强", "enhances"),
    ("减弱", "attenuates"),
    ("升高", "elevates"),
    ("降低", "reduces"),
    ("减少", "reduces"),
    ("减小", "decreases"),
    ("减轻", "alleviates"),
    ("加重", "aggravates"),
    ("防止", "prevents"),
    ("预防", "prevents"),
    ("保护", "protects"),
    ("损害", "damages"),
    ("破坏", "destroys"),
    ("产生", "produces"),
    ("释放", "releases"),
    ("摄取", "takes up"),
    ("吸收", "absorbs"),
    ("分布", "distributes"),
    ("代谢", "metabolizes"),
    ("排泄", "excretes"),
    ("转运", "transports"),
    ("结合", "binds to"),
    ("分离", "dissociates from"),
    ("转化", "converts"),
    ("水解", "hydrolyzes"),
    ("氧化", "oxidizes"),
    ("还原", "reduces"),
    ("合成", "synthesizes"),
    ("分解", "degrades"),
    ("分泌", "secretes"),
    ("排出", "eliminates"),
    ("扩散", "diffuses"),
    ("进入", "enters"),
    ("透过", "crosses"),
    ("表达", "is expressed"),
    ("发挥", "exerts"),
    ("起到", "plays"),
    ("给予", "administer"),
    ("服用", "take"),
    ("滴注", "infuse"),
    ("合用", "coadminister"),
    ("联用", "combine with"),
    ("单用", "as monotherapy"),
    ("替换", "replace"),
    ("取代", "replace"),
    ("替代", "substitute for"),
    ("监测", "monitor"),
    ("检查", "check"),
    ("检测", "measure"),
    ("诊断", "diagnose"),
    ("抢救", "rescue"),
    ("预后", "prognosis of"),
    ("恢复", "restore"),
    ("维持", "maintain"),
    ("持续", "sustain"),
    ("停药", "discontinue"),
    ("耐受", "tolerate"),
    ("蓄积", "accumulate"),
    ("沉积", "deposit"),
    ("清除", "clear"),
    ("灭活", "inactivate"),
    ("失活", "inactivate"),
    ("活化", "activate"),
    ("调节", "regulate"),
    ("调控", "regulate"),
    ("调整", "adjust"),
    ("开放", "open"),
    ("关闭", "close"),
    ("延长", "prolongs"),
    ("缩短", "shortens"),
    ("减慢", "slows"),
    ("加快", "accelerates"),
    ("舒张", "dilates"),
    ("收缩", "constricts"),
    ("扩张", "dilates"),
    ("缩小", "reduces"),
    ("增高", "elevates"),
    ("排出体外", "is eliminated from the body"),
    ("改善", "improves"),
    ("恶化", "worsens"),
    ("消除", "eliminates"),
    ("具备", "possesses"),
    ("提供", "provides"),
    ("选择", "select"),
    ("确定", "determine"),
    ("确认", "confirm"),
    ("分析", "analyze"),
    ("评估", "evaluate"),
    ("评价", "evaluate"),
    ("观察", "observe"),
    ("了解", "understand"),
    ("研究", "study"),
    ("讨论", "discuss"),

    # ===== FREQUENCY / QUANTITY =====
    ("很常见", "very common"),
    ("最常见", "most common"),
    ("最为常见", "most common"),
    ("不太常见", "less common"),
    ("较为常见", "relatively common"),
    ("极为罕见", "extremely rare"),
    ("偶见", "occasionally seen"),
    ("偶尔", "occasionally"),
    ("经常", "frequently"),
    ("通常", "usually"),
    ("一般", "generally"),
    ("很少", "rarely"),
    ("极少", "very rarely"),
    ("从不", "never"),
    ("总是", "always"),
    ("常见", "common"),
    ("少见", "uncommon"),
    ("罕见", "rare"),
    ("偶有", "occasionally"),
    ("大多数", "most"),
    ("少数", "a few"),
    ("极少数", "very few"),
    ("全部", "all"),
    ("部分", "partially"),
    ("整体", "overall"),
    ("总体", "overall"),
    ("其余", "the remaining"),
    ("同样", "similarly"),
    ("不同", "different"),
    ("相同", "identical"),
    ("相反", "conversely"),
    ("类似", "similar to"),
    ("单一", "single"),
    ("双重", "dual"),
    ("三重", "triple"),

    # ===== MODALITY / CERTAINTY =====
    ("很可能", "very likely"),
    ("有可能", "possibly"),
    ("一定", "definitely"),
    ("必定", "inevitably"),
    ("必然", "necessarily"),
    ("肯定", "certainly"),
    ("或许", "perhaps"),
    ("大概", "probably"),
    ("几乎", "almost"),
    ("基本", "basically"),
    ("完全", "completely"),
    ("彻底", "thoroughly"),
    ("绝对", "absolutely"),
    ("相对", "relatively"),
    ("相当", "quite"),
    ("非常", "very"),
    ("十分", "extremely"),
    ("极其", "extremely"),
    ("尤其", "especially"),
    ("特别", "especially"),
    ("特意", "specifically"),
    ("专一", "specifically"),
    ("显然", "obviously"),
    ("确实", "indeed"),
    ("的确", "indeed"),
    ("真正", "truly"),
    ("其实", "actually"),
    ("事实上", "in fact"),
    ("实际上", "in practice"),
    ("根据", "according to"),
    ("基于", "based on"),
    ("按照", "according to"),
    ("通过", "via"),
    ("经过", "after"),
    ("可能", "may"),
    ("不能", "cannot"),
    ("没有", "does not have"),

    # ===== TIME / SEQUENCE =====
    ("随着时间的推移", "over time"),
    ("随着年龄增长", "with advancing age"),
    ("随着剂量增加", "with increasing dose"),
    ("随着病程进展", "as the disease progresses"),
    ("随着治疗进行", "as treatment proceeds"),
    ("越来越多的证据表明", "growing evidence suggests"),
    ("近年来研究显示", "recent studies have shown"),
    ("需要指出的是", "it should be pointed out that"),
    ("值得注意的是", "it is noteworthy that"),
    ("需要强调的是", "it should be emphasized that"),
    ("更为重要的是", "more importantly"),
    ("与此同时", "meanwhile"),
    ("除此之外", "besides"),
    ("不仅如此", "moreover"),
    ("尽管如此", "nevertheless"),
    ("与之相反", "in contrast"),
    ("综上所述", "in summary"),
    ("总而言之", "in summary"),
    ("总的来说", "overall"),
    ("迄今为止", "to date"),
    ("近年来", "in recent years"),
    ("长期", "long-term"),
    ("短期", "short-term"),
    ("瞬间", "instantaneous"),
    ("短暂", "brief"),
    ("持久", "sustained"),
    ("即刻", "immediately"),
    ("立即", "immediately"),
    ("迅速", "rapidly"),
    ("缓慢", "slowly"),
    ("逐渐", "gradually"),
    ("急剧", "sharply"),
    ("显著", "significantly"),
    ("明显", "markedly"),
    ("不明显", "not obvious"),
    ("容易", "easily"),
    ("不易", "not easily"),
    ("稍微", "slightly"),
    ("首先", "first"),
    ("其次", "secondly"),
    ("最后", "finally"),
    ("最终", "ultimately"),
    ("此前", "previously"),
    ("先前", "previously"),
    ("此后", "thereafter"),
    ("然后", "then"),
    ("此外", "furthermore"),
    ("另外", "additionally"),
    ("况且", "moreover"),
    ("进而", "thereby"),
    ("从而", "thereby"),
    ("仍然", "still"),
    ("始终", "always"),
    ("一直", "continuously"),
    ("继续", "continues to"),
    ("及时", "in a timely manner"),
    ("随时", "at any time"),
    ("临时", "temporarily"),
    ("目前", "currently"),
    ("以往", "previously"),
    ("今后", "in the future"),
    ("目前临床", "currently in clinical"),

    # ===== SPECIFIC TIMING =====
    ("约10秒", "approximately 10 seconds"),
    ("约1小时", "approximately 1 hour"),
    ("约14小时", "approximately 14 hours"),
    ("约30分钟", "approximately 30 minutes"),
    ("约2-3小时", "approximately 2-3 hours"),
    ("约4-6小时", "approximately 4-6 hours"),
    ("3-4周", "3-4 weeks"),
    ("2-4周", "2-4 weeks"),
    ("1-2周", "1-2 weeks"),
    ("3-4天", "3-4 days"),
    ("1-2天", "1-2 days"),
    ("10-20分钟", "10-20 minutes"),
    ("15-30分钟", "15-30 minutes"),

    # ===== SPECIFIC MEDICAL PHRASES =====
    ("阵发性室上性心动过速", "paroxysmal supraventricular tachycardia"),
    ("尖端扭转型室性心动过速", "torsades de pointes"),
    ("心房肌不应期", "atrial refractory period"),
    ("心室肌不应期", "ventricular refractory period"),
    ("不应期延长", "refractory period prolongation"),
    ("动作电位延长", "action potential prolongation"),
    ("冠状动脉扩张", "coronary artery dilation"),
    ("冠状动脉痉挛", "coronary artery spasm"),
    ("侧支循环开放", "collateral circulation opening"),
    ("心肌收缩力增强", "increased myocardial contractility"),
    ("心肌收缩力减弱", "decreased myocardial contractility"),
    ("心肌耗氧量增加", "increased myocardial oxygen consumption"),
    ("心肌耗氧量降低", "decreased myocardial oxygen consumption"),
    ("心室壁张力降低", "decreased ventricular wall tension"),
    ("外周血管阻力", "peripheral vascular resistance"),
    ("外周阻力降低", "decreased peripheral resistance"),
    ("回心血量减少", "decreased venous return"),
    ("射血时间缩短", "shortened ejection time"),
    ("心室容积缩小", "reduced ventricular volume"),
    ("前负荷降低", "decreased preload"),
    ("后负荷降低", "decreased afterload"),
    ("代谢性碱中毒", "metabolic alkalosis"),
    ("肾小管上皮细胞", "renal tubular epithelial cell"),
    ("肾小管", "renal tubule"),
    ("肾小球", "glomerulus"),
    ("组织纤溶酶原激活物", "tissue plasminogen activator"),
    ("抗血小板聚集", "antiplatelet aggregation"),
    ("血小板聚集", "platelet aggregation"),
    ("小肠黏膜细胞", "small intestinal mucosal cell"),
    ("泡沫细胞形成", "foam cell formation"),
    ("血管内皮功能", "vascular endothelial function"),
    ("血管内皮", "vascular endothelium"),
    ("内皮依赖性", "endothelium-dependent"),
    ("非内皮依赖性", "endothelium-independent"),
    ("一氧化氮", "nitric oxide"),
    ("鸟苷酸", "guanylic acid"),
    ("前列环素", "prostacyclin"),
    ("心肌缺血再灌注", "myocardial ischemia-reperfusion"),
    ("缺血再灌注", "ischemia-reperfusion"),
    ("预适应", "preconditioning"),
    ("后适应", "postconditioning"),
    ("心律失常", "arrhythmia"),
    ("抗心律失常", "antiarrhythmic"),
    ("心肌缺血", "myocardial ischemia"),
    ("心绞痛发作", "angina attack"),
    ("变异型心绞痛", "variant angina"),
    ("劳力性心绞痛", "effort angina"),
    ("不稳定型心绞痛", "unstable angina"),
    ("稳定型心绞痛", "stable angina"),
    ("心肌梗死", "myocardial infarction"),
    ("心电图改变", "ECG changes"),
    ("心电图正常", "normal ECG"),
    ("心电图异常", "abnormal ECG"),
    ("硝苯地平", "nifedipine"),
    ("心脏功能", "cardiac function"),
    ("心脏骤停", "cardiac arrest"),
    ("窦性", "sinus"),
    ("室性", "ventricular"),
    ("房性", "atrial"),
    ("房室", "atrioventricular"),
    ("心房", "atrial"),
    ("心室", "ventricular"),
    ("心肌", "myocardium"),
    ("心衰", "heart failure"),
    ("冠脉", "coronary"),

    # ===== DOSAGE-RELATED =====
    ("剂量依赖性", "dose-dependent"),
    ("频率依赖性", "use-dependent"),
    ("剂量依赖", "dose-dependent"),
    ("频率依赖", "use-dependent"),
    ("高剂量", "high dose"),
    ("低剂量", "low dose"),
    ("大剂量", "large dose"),
    ("小剂量", "small dose"),
    ("治疗剂量", "therapeutic dose"),
    ("中毒剂量", "toxic dose"),
    ("致死剂量", "lethal dose"),
    ("负荷量", "loading dose"),
    ("维持量", "maintenance dose"),
    ("初始量", "initial dose"),
    ("首剂", "first dose"),
    ("减量", "dose reduction"),
    ("增量", "dose increase"),

    # ===== SIDE EFFECT / TOXICITY TERMS =====
    ("金鸡纳反应", "cinchonism"),
    ("奎尼丁晕厥", "quinidine syncope"),
    ("角膜褐色微粒沉着", "corneal brown microdeposits"),
    ("甲状腺功能紊乱", "thyroid dysfunction"),
    ("粒细胞缺乏症", "agranulocytosis"),
    ("粒细胞减少症", "neutropenia"),
    ("白细胞减少症", "leukopenia"),
    ("肝毒性", "hepatotoxicity"),
    ("肾毒性", "nephrotoxicity"),
    ("神经毒性", "neurotoxicity"),
    ("耳毒性", "ototoxicity"),
    ("心脏毒性", "cardiotoxicity"),
    ("光敏反应", "photosensitivity"),
    ("过敏反应", "allergic reaction"),
    ("荨麻疹", "urticaria"),
    ("血管神经性水肿", "angioneurotic edema"),
    ("剥脱性皮炎", "exfoliative dermatitis"),
    ("红斑狼疮样综合征", "lupus-like syndrome"),
    ("系统性红斑狼疮", "systemic lupus erythematosus"),
    ("耐受性", "tolerance"),
    ("耐药性", "drug resistance"),
    ("依赖性", "dependence"),
    ("成瘾性", "addiction"),
    ("滥用", "abuse"),
    ("误用", "misuse"),
    ("过量", "overdose"),
    ("中毒", "toxicity"),
    ("解毒", "detoxification"),

    # ===== CANCER TYPES =====
    ("非小细胞肺癌", "non-small cell lung cancer"),
    ("小细胞肺癌", "small cell lung cancer"),
    ("霍奇金淋巴瘤", "Hodgkin lymphoma"),
    ("非霍奇金淋巴瘤", "non-Hodgkin lymphoma"),
    ("肾细胞癌", "renal cell carcinoma"),
    ("肝细胞癌", "hepatocellular carcinoma"),
    ("尿路上皮癌", "urothelial carcinoma"),
    ("梅克尔细胞癌", "Merkel cell carcinoma"),
    ("头颈部鳞状细胞癌", "head and neck squamous cell carcinoma"),
    ("恶性黑色素瘤", "malignant melanoma"),
    ("前列腺癌", "prostate cancer"),
    ("乳腺癌", "breast cancer"),
    ("卵巢癌", "ovarian cancer"),
    ("胰腺癌", "pancreatic cancer"),
    ("膀胱癌", "bladder cancer"),
    ("结直肠癌", "colorectal cancer"),
    ("胃癌", "gastric cancer"),
    ("黑色素瘤", "melanoma"),
    ("淋巴瘤", "lymphoma"),
    ("白血病", "leukemia"),
    ("实体瘤", "solid tumor"),
    ("肿瘤", "tumor"),
    ("癌症", "cancer"),
    ("肉瘤", "sarcoma"),
    ("癌", "carcinoma"),

    # ===== DRUG CATEGORIES (detailed) =====
    ("广谱抗心律失常药", "broad-spectrum antiarrhythmic"),
    ("窄谱抗心律失常药", "narrow-spectrum antiarrhythmic"),
    ("生物制剂", "biologic agent"),
    ("小分子药", "small molecule drug"),
    ("大分子药", "large molecule drug"),
    ("化学药", "chemical drug"),
    ("原研药", "brand-name drug"),
    ("仿制药", "generic drug"),

    # ===== SPECIFIC PHRASES =====
    ("取决于", "depends on"),
    ("有待于", "remains to be"),
    ("有助于", "contributes to"),
    ("有利于", "is beneficial for"),
    ("不利于", "is detrimental to"),
    ("有益于", "benefits"),
    ("相当于", "equivalent to"),
    ("适用于", "is suitable for"),
    ("局限", "limited to"),
    ("限于", "is limited to"),
    ("定量", "quantitative"),
    ("定性", "qualitative"),
    ("安全性", "safety"),
    ("有效性", "efficacy"),
    ("实用性", "practicality"),
    ("可行性", "feasibility"),
    ("必要性", "necessity"),
    ("重要性", "importance"),
    ("依从性", "compliance"),
    ("预后", "prognosis"),
    ("指标", "indicator"),
    ("参数", "parameter"),
    ("比值", "ratio"),

    # ===== METHODS / APPROACHES =====
    ("对症治疗", "symptomatic treatment"),
    ("对因治疗", "causal treatment"),
    ("根治性", "curative"),
    ("姑息性", "palliative"),
    ("对症", "symptomatic"),
    ("对因", "causal"),
    ("根治", "curative"),

    # ===== SPECIFIC PHYSIOLOGY =====
    ("超极化", "hyperpolarization"),
    ("去极化", "depolarization"),
    ("复极", "repolarization"),
    ("自律性", "automaticity"),
    ("传导性", "conductivity"),
    ("兴奋性", "excitability"),
    ("不应性", "refractoriness"),
    ("异位节律点", "ectopic pacemaker"),
    ("自律细胞", "automatic cell"),
    ("工作细胞", "working cell"),
    ("起搏细胞", "pacemaker cell"),
    ("快反应细胞", "fast response cell"),
    ("慢反应细胞", "slow response cell"),
    ("相对不应期", "relative refractory period"),
    ("绝对不应期", "absolute refractory period"),
    ("超常期", "supernormal period"),
    ("低常期", "subnormal period"),
    ("恢复期", "recovery phase"),
    ("不应期", "refractory period"),
    ("平台期", "plateau phase"),
    ("快速复极期", "rapid repolarization phase"),
    ("动作电位0期", "phase 0 of action potential"),
    ("动作电位1期", "phase 1 of action potential"),
    ("动作电位2期", "phase 2 of action potential"),
    ("动作电位3期", "phase 3 of action potential"),
    ("动作电位4期", "phase 4 of action potential"),
    ("0期去极", "phase 0 depolarization"),
    ("4期自动去极", "phase 4 automatic depolarization"),
    ("膜电位", "membrane potential"),
    ("静息电位", "resting potential"),
    ("阈电位", "threshold potential"),
    ("兴奋收缩", "excitation-contraction"),
    ("舒张功能", "diastolic function"),
    ("收缩功能", "systolic function"),
    ("舒张期", "diastole"),
    ("收缩期", "systole"),
    ("排钠", "natriuretic"),
    ("排钾", "kaliuretic"),
    ("保钾", "potassium-sparing"),
    ("排钠保钾", "natriuretic and potassium-sparing"),
    ("排钠利尿", "natriuretic"),
    ("肾单位", "nephron"),
    ("肾小管", "renal tubule"),
    ("髓质", "medulla"),
    ("皮质", "cortex"),
    ("渗透压", "osmotic pressure"),
    ("胶体渗透压", "oncotic pressure"),
    ("晶体渗透压", "crystalloid osmotic pressure"),
    ("血浆渗透压", "plasma osmotic pressure"),
    ("等渗", "isotonic"),
    ("高渗", "hypertonic"),
    ("低渗", "hypotonic"),
    ("磷酸化", "phosphorylation"),
    ("去磷酸化", "dephosphorylation"),
    ("乙酰化", "acetylation"),
    ("甲基化", "methylation"),
    ("氧化修饰", "oxidative modification"),
    ("活性氧", "reactive oxygen species"),
    ("氧化应激", "oxidative stress"),
    ("细胞凋亡", "apoptosis"),
    ("细胞坏死", "necrosis"),
    ("细胞增殖", "cell proliferation"),
    ("信号转导", "signal transduction"),
    ("转录因子", "transcription factor"),
    ("基因表达", "gene expression"),
    ("蛋白表达", "protein expression"),
    ("负反馈", "negative feedback"),
    ("正反馈", "positive feedback"),
    ("反馈抑制", "feedback inhibition"),
    ("反馈调节", "feedback regulation"),

    # ===== COMMON PARTICLES / CONNECTORS =====
    ("根据...的分类", "according to the classification of"),
    ("较...为...", "is more ... than ..."),
    ("不如", "is not as good as"),
    ("比...强", "is stronger than"),
    ("比...弱", "is weaker than"),
    ("比...更", "is more ... than"),
    ("最...之一", "one of the most"),
    ("不仅...而且", "not only ... but also"),
    ("虽然...但", "although ... though"),
    ("因为...所以", "because ... therefore"),
    ("如果...就", "if ... then"),
    ("除...外", "except for"),

    # ===== SHORT PARTICLES / PRONOUNS (single meaning) =====
    # These are applied LAST (after all compound terms) due to length sorting
    ("因此", "therefore"),
    ("所以", "therefore"),
    ("因为", "because"),
    ("然而", "however"),
    ("但是", "however"),
    ("虽然", "although"),
    ("如果", "if"),
    ("即使", "even if"),
    ("除非", "unless"),
    ("只要", "as long as"),
    ("只有", "only if"),
    ("无论", "regardless of"),
    ("不管", "regardless of"),
    ("尽管", "despite"),
    ("自从", "since"),
    ("任何", "any"),
    ("所有", "all"),
    ("有些", "some"),
    ("许多", "many"),
    ("大量", "a large amount of"),
    ("少量", "a small amount of"),
    ("称之为", "termed"),
    ("所谓", "so-called"),
    ("例如", "for example"),
    ("比如", "such as"),
    ("等等", "etc."),
    ("一类", "a class of"),
    ("这类", "this class of"),
    ("两类", "two classes of"),
    ("三大类", "three major classes"),
    ("四大类", "four major classes"),
    ("五大类", "five major classes"),
    ("六大类", "six major classes"),
    ("最为", "the most"),
    ("极为", "extremely"),
    ("颇为", "quite"),
    ("更加", "more"),
    ("越来越", "increasingly"),
    ("远高于", "much higher than"),
    ("远低于", "much lower than"),
    ("容易", "easily"),
    ("不易", "not easily"),
    ("很明显", "it is obvious that"),
    ("数据显示", "data show that"),
    ("研究表明", "studies indicate that"),
    ("结果提示", "results suggest that"),
    ("以上", "above"),
    ("以下", "below"),
    ("以内", "within"),
    ("以外", "outside of"),
    ("之前", "before this"),
    ("之后", "after this"),
    ("之中", "among"),

    # ===== SURVIVAL / EPIDEMIOLOGY =====
    ("生存质量", "quality of survival"),
    ("生活质量", "quality of life"),
    ("成本效益", "cost-effectiveness"),
    ("风险效益比", "risk-benefit ratio"),
    ("获益大于风险", "benefits outweigh risks"),
    ("风险大于获益", "risks outweigh benefits"),
    ("获益", "benefit"),
    ("风险", "risk"),
    ("个体差异", "individual variation"),
    ("种族差异", "ethnic difference"),
    ("性别差异", "sex difference"),
    ("年龄差异", "age-related difference"),
    ("遗传多态性", "genetic polymorphism"),
    ("生存率", "survival rate"),
    ("死亡率", "mortality rate"),
    ("病死率", "case fatality rate"),
    ("发病率", "incidence rate"),
    ("患病率", "prevalence rate"),
    ("致残率", "disability rate"),
    ("检出率", "detection rate"),
    ("阳性率", "positivity rate"),
    ("有效率", "response rate"),
    ("控制率", "control rate"),
    ("缓解率", "remission rate"),
    ("应答率", "response rate"),
    ("治愈率", "cure rate"),

    # ===== DISEASE COURSE =====
    ("首发", "first episode"),
    ("复发", "relapse"),
    ("难治性", "refractory"),
    ("顽固性", "refractory"),
    ("致死性", "fatal"),
    ("非致死性", "nonfatal"),
    ("急性", "acute"),
    ("慢性", "chronic"),
    ("亚急性", "subacute"),
    ("暴发性", "fulminant"),
    ("渐进性", "progressive"),
    ("可逆性", "reversible"),
    ("不可逆", "irreversible"),
    ("自限性", "self-limited"),
    ("潜在性", "latent"),
    ("静止性", "quiescent"),
    ("活动性", "active"),

    # ===== SAFETY / REGULATORY =====
    ("警告", "warning"),
    ("注意事项", "precautions"),
    ("禁忌症", "contraindication"),
    ("适应症", "indication"),
    ("解决方案", "solution"),
    ("实施", "implementation"),
    ("措施", "measure"),
    ("策略", "strategy"),
    ("原则", "principle"),
    ("方案", "regimen"),
    ("方法", "method"),
    ("手段", "means"),

    # ===== OTHER MEDICAL TERMS =====
    ("化学结构", "chemical structure"),
    ("不良反应", "adverse effect"),
    ("副作用", "side effect"),
    ("毒性反应", "toxic reaction"),
    ("过敏反应", "allergic reaction"),
    ("变态反应", "allergic reaction"),
    ("撤药综合征", "withdrawal syndrome"),
    ("戒断症状", "withdrawal symptoms"),
    ("反跳现象", "rebound phenomenon"),
    ("撤药反应", "withdrawal reaction"),
    ("过度反应", "excessive reaction"),
    ("特异质反应", "idiosyncratic reaction"),
    ("后遗效应", "residual effect"),
    ("增效作用", "synergistic effect"),
    ("协同作用", "synergistic effect"),
    ("相加作用", "additive effect"),
    ("拮抗作用", "antagonistic effect"),
    ("药物-药物相互作用", "drug-drug interaction"),
    ("药物-食物相互作用", "drug-food interaction"),
    ("治疗指数", "therapeutic index"),
    ("安全范围", "safety margin"),
    ("治疗窗", "therapeutic window"),
    ("峰谷浓度差", "peak-trough difference"),

    # ===== SPECIFIC DISEASE ENTITIES =====
    ("家族性高胆固醇血症", "familial hypercholesterolemia"),
    ("纯合子家族性高胆固醇血症", "homozygous familial hypercholesterolemia"),
    ("杂合子家族性高胆固醇血症", "heterozygous familial hypercholesterolemia"),
    ("原发性高胆固醇血症", "primary hypercholesterolemia"),
    ("继发性高胆固醇血症", "secondary hypercholesterolemia"),
    ("高脂蛋白血症", "hyperlipoproteinemia"),
    ("混合型高脂血症", "mixed hyperlipidemia"),
    ("高甘油三酯血症", "hypertriglyceridemia"),
    ("高胆固醇血症", "hypercholesterolemia"),
    ("甲状腺功能减退", "hypothyroidism"),
    ("甲状腺功能亢进", "hyperthyroidism"),
    ("肾功能衰竭", "renal failure"),
    ("肝功能衰竭", "hepatic failure"),
    ("心力衰竭", "heart failure"),
    ("呼吸衰竭", "respiratory failure"),
    ("多器官功能衰竭", "multiple organ failure"),
    ("休克", "shock"),
    ("过敏性休克", "anaphylactic shock"),
    ("感染性休克", "septic shock"),
    ("心源性休克", "cardiogenic shock"),
    ("低血容量性休克", "hypovolemic shock"),
    ("肾功能不全", "renal insufficiency"),
    ("肝功能不全", "hepatic insufficiency"),
    ("心功能不全", "cardiac insufficiency"),
    ("肾上腺皮质功能不全", "adrenal insufficiency"),
    ("性功能障碍", "sexual dysfunction"),
    ("勃起功能障碍", "erectile dysfunction"),
    ("肺动脉高压", "pulmonary arterial hypertension"),
    ("门静脉高压", "portal hypertension"),
    ("颅内高压", "intracranial hypertension"),
    ("眼内高压", "intraocular hypertension"),
    ("高血压危象", "hypertensive crisis"),
    ("冠心病", "coronary heart disease"),
    ("缺血性心脏病", "ischemic heart disease"),
    ("风湿性心脏病", "rheumatic heart disease"),
    ("先天性心脏病", "congenital heart disease"),
    ("肺源性心脏病", "cor pulmonale"),
    ("扩张型心肌病", "dilated cardiomyopathy"),
    ("肥厚型心肌病", "hypertrophic cardiomyopathy"),
    ("限制型心肌病", "restrictive cardiomyopathy"),

    # ===== DRUG SAFETY / TOXICITY =====
    ("产生耐受性", "develops tolerance"),
    ("产生耐药性", "develops resistance"),
    ("药物蓄积", "drug accumulation"),
    ("药物沉积", "drug deposition"),
    ("药物相互作用", "drug interaction"),
    ("配伍禁忌", "incompatibility"),
    ("药物过量", "drug overdose"),
    ("药物滥用", "drug abuse"),
    ("药物依赖", "drug dependence"),

    # ===== ROUTES / PHYSICAL =====
    ("经皮给药", "transdermal administration"),
    ("经黏膜给药", "transmucosal administration"),
    ("经呼吸道给药", "inhalation administration"),
    ("缓慢推注", "slow bolus injection"),
    ("快速推注", "rapid bolus injection"),
    ("持续输注", "continuous infusion"),
    ("持续滴注", "continuous drip infusion"),
    ("间歇给药", "intermittent dosing"),
    ("连续给药", "continuous administration"),
    ("单次给药", "single-dose administration"),
    ("多次给药", "multiple-dose administration"),
    ("空腹给药", "fasting administration"),
    ("餐后给药", "postprandial administration"),
    ("睡前给药", "bedtime administration"),
    ("早晚给药", "morning and evening dosing"),
    ("局部外敷", "topical application"),

    # ===== SUPPLEMENTS / GENERAL =====
    ("鱼油", "fish oil"),
    ("维生素", "vitamin"),
    ("矿物质", "mineral"),
    ("微量元素", "trace element"),
    ("抗氧化剂", "antioxidant"),
    ("不饱和脂肪酸", "unsaturated fatty acid"),
    ("饱和脂肪酸", "saturated fatty acid"),
    ("反式脂肪酸", "trans fatty acid"),
    ("欧米伽-3脂肪酸", "omega-3 fatty acid"),
    ("二十碳五烯酸", "eicosapentaenoic acid"),
    ("二十二碳六烯酸", "docosahexaenoic acid"),
    ("亚油酸", "linoleic acid"),
    ("亚麻酸", "linolenic acid"),
    ("花生四烯酸", "arachidonic acid"),
    ("油酸", "oleic acid"),
    ("棕榈酸", "palmitic acid"),
    ("硬脂酸", "stearic acid"),

    # ===== GENERAL TERMS =====
    ("口服生物利用度", "oral bioavailability"),
    ("绝对生物利用度", "absolute bioavailability"),
    ("相对生物利用度", "relative bioavailability"),
    ("肝功能损害", "hepatic impairment"),
    ("肾功能损害", "renal impairment"),
    ("肝功能异常", "abnormal liver function"),
    ("肾功能异常", "abnormal renal function"),
    ("肝功能下降", "decreased liver function"),
    ("肾功能下降", "decreased renal function"),
    ("心排血量", "cardiac output"),
    ("心排出量", "cardiac output"),
    ("心输出量", "cardiac output"),
    ("每搏输出量", "stroke volume"),
    ("射血分数", "ejection fraction"),
    ("缩短分数", "fractional shortening"),
    ("心室舒张末压", "left ventricular end-diastolic pressure"),
    ("心室舒张末容积", "left ventricular end-diastolic volume"),
    ("心室收缩末容积", "left ventricular end-systolic volume"),
    ("肺毛细血管楔压", "pulmonary capillary wedge pressure"),
    ("中心静脉压", "central venous pressure"),
    ("动脉血压", "arterial blood pressure"),
    ("动脉压", "arterial pressure"),
    ("静脉压", "venous pressure"),
    ("脉压", "pulse pressure"),
    ("平均动脉压", "mean arterial pressure"),

    # ===== KEY DESCRIPTIVE =====
    ("口服吸收迅速", "is rapidly absorbed orally"),
    ("口服吸收良好", "is well absorbed orally"),
    ("口服吸收较差", "is poorly absorbed orally"),
    ("口服吸收完全", "is completely absorbed orally"),
    ("口服吸收不完全", "is incompletely absorbed orally"),
    ("生物利用度高", "has high bioavailability"),
    ("生物利用度低", "has low bioavailability"),
    ("半衰期长", "has a long half-life"),
    ("半衰期短", "has a short half-life"),
    ("蛋白结合率高", "has high protein binding"),
    ("蛋白结合率低", "has low protein binding"),
    ("经肝脏代谢", "is metabolized in the liver"),
    ("经肾脏排泄", "is excreted by the kidney"),
    ("经胆汁排泄", "is excreted in bile"),
    ("经乳汁排泄", "is excreted in breast milk"),
    ("经胎盘转运", "crosses the placenta"),

    # ===== DRUG-SPECIFIC DESCRIPTORS =====
    ("长效制剂", "long-acting formulation"),
    ("短效制剂", "short-acting formulation"),
    ("中效制剂", "intermediate-acting formulation"),
    ("速效制剂", "rapid-acting formulation"),
    ("缓释制剂", "sustained-release formulation"),
    ("控释制剂", "controlled-release formulation"),
    ("迟释制剂", "delayed-release formulation"),
    ("速释制剂", "immediate-release formulation"),
    ("脂质体制剂", "liposomal formulation"),
    ("纳米制剂", "nano-formulation"),
    ("靶向制剂", "targeted formulation"),
    ("前药", "prodrug"),
    ("活性代谢物", "active metabolite"),
    ("无活性代谢物", "inactive metabolite"),
    ("毒性代谢物", "toxic metabolite"),
    ("原型药物", "parent drug"),
    ("原形", "unchanged form"),
    ("原形排出", "excreted unchanged"),
    ("代谢产物", "metabolite"),
    ("首关效应", "first-pass effect"),
    ("首关代谢", "first-pass metabolism"),
    ("首过效应", "first-pass effect"),
    ("首过代谢", "first-pass metabolism"),
    ("肠肝循环", "enterohepatic circulation"),
    ("肾小管重吸收", "renal tubular reabsorption"),
    ("肾小管分泌", "renal tubular secretion"),
    ("肾小球滤过", "glomerular filtration"),
    ("胆汁排泄", "biliary excretion"),
    ("粪便排泄", "fecal excretion"),
    ("尿排泄", "urinary excretion"),

    # ===== ADDITIONAL PHRASES =====
    ("下列描述错误的是", "Which of the following descriptions is INCORRECT?"),
    ("下列描述正确的是", "Which of the following descriptions is CORRECT?"),
    ("以下描述错误的是", "Which of the following descriptions is INCORRECT?"),
    ("以下描述正确的是", "Which of the following descriptions is CORRECT?"),
    ("不属于适应证的是", "is NOT an indication"),
    ("不属于禁忌证的是", "is NOT a contraindication"),
    ("不包括下列哪项", "does NOT include which of the following"),
    ("包括下列哪项", "includes which of the following"),
    ("首选药物是", "the drug of choice is"),
    ("首选治疗药物是", "the first-line treatment drug is"),
    ("不宜应用的是", "should NOT be used"),
    ("不能应用的是", "cannot be used"),
    ("常用的药物是", "the commonly used drug is"),
    ("最常用的药物是", "the most commonly used drug is"),
    ("监测指标是", "the monitoring parameter is"),
    ("治疗目标是", "the treatment goal is"),
    ("作用特点是", "is characterized by"),
    ("药理学特点", "pharmacological characteristics"),
    ("药物特点", "drug characteristics"),
    ("共同特点", "common characteristics"),
    ("基本特点", "basic characteristics"),
    ("不良反应包括", "adverse effects include"),
    ("不良反应有", "adverse effects include"),
    ("主要不良反应", "the main adverse effect"),
    ("常见不良反应", "common adverse effects"),
    ("罕见不良反应", "rare adverse effects"),
    ("严重不良反应", "serious adverse effects"),
    ("致死性不良反应", "fatal adverse effects"),
    ("引起的", "is caused by"),
    ("导致的", "is caused by"),
    ("造成的", "is caused by"),
    ("诱发的", "is induced by"),
    ("所致的", "is due to"),
    ("相关的", "is associated with"),
    ("有关的", "is related to"),
    ("相比较", "compared with"),
    ("相比较而言", "by comparison"),
    ("相比之下", "in comparison"),
    ("相对于", "relative to"),
    ("较", "more"),
    ("中", "in"),
    ("最", "most"),

    # ===== CRITICAL MISSING COMMON PARTICLES & CHARACTERS =====
    # These must come BEFORE 正确/错误 so sorting places them correctly

    # ===== ADDITIONAL COMPOUNDS THAT WERE MISSING =====
    ("反射", "reflex"),
    ("中枢", "CNS"),
    ("疾病", "disease"),
    ("镇静", "sedation"),
    ("非镇静性", "non-sedating"),
    ("通透性", "permeability"),
    ("通透", "permeability"),
    ("手术", "surgery"),
    ("化疗", "chemotherapy"),
    ("放疗", "radiotherapy"),
    ("患者", "patients"),
    ("禁用", "is contraindicated"),
    ("慎用", "use with caution"),
    ("禁用证", "contraindication"),
    ("适应证", "indication"),
    ("禁忌证", "contraindication"),
    ("痛觉", "pain sensation"),
    ("感觉", "sensation"),
    ("病理", "pathological"),
    ("生理", "physiological"),
    ("药理", "pharmacological"),
    ("毒理", "toxicological"),
    ("生化", "biochemical"),
    ("临床", "clinical"),
    ("治疗", "treatment"),
    ("诊断", "diagnosis"),
    ("预防", "prevention"),
    ("预后", "prognosis"),
    ("症状", "symptom"),
    ("体征", "sign"),
    ("综合征", "syndrome"),
    ("并发症", "complication"),
    ("合并症", "comorbidity"),
    ("适应证", "indication"),
    ("不良反应", "adverse effect"),
    ("副作用", "side effect"),
    ("毒性", "toxicity"),
    ("过敏", "allergy"),
    ("变态反应", "allergic reaction"),
    ("过敏性休克", "anaphylactic shock"),
    ("荨麻疹", "urticaria"),
    ("皮疹", "rash"),
    ("紫癜", "purpura"),
    ("出血", "bleeding"),
    ("凝血", "coagulation"),
    ("血栓形成", "thrombosis"),
    ("栓塞", "embolism"),
    ("梗死", "infarction"),
    ("缺血", "ischemia"),
    ("坏死", "necrosis"),
    ("凋亡", "apoptosis"),
    ("增殖", "proliferation"),
    ("分化", "differentiation"),
    ("再生", "regeneration"),
    ("修复", "repair"),
    ("重建", "remodeling"),
    ("收缩", "contraction"),
    ("舒张", "relaxation"),
    ("扩张", "dilation"),
    ("狭窄", "stenosis"),
    ("痉挛", "spasm"),
    ("麻痹", "paralysis"),
    ("昏迷", "coma"),
    ("休克", "shock"),
    ("衰竭", "failure"),
    ("功能障碍", "dysfunction"),
    ("损伤", "injury"),
    ("创伤", "trauma"),
    ("感染", "infection"),
    ("炎症", "inflammation"),
    ("水肿", "edema"),
    ("渗出", "exudation"),
    ("浸润", "infiltration"),
    ("纤维化", "fibrosis"),
    ("硬化", "sclerosis"),
    ("钙化", "calcification"),
    ("坏死", "necrosis"),
    ("增生", "hyperplasia"),
    ("肥大", "hypertrophy"),
    ("萎缩", "atrophy"),
    ("化生", "metaplasia"),
    ("异型增生", "dysplasia"),
    ("癌变", "malignant transformation"),
    ("转移", "metastasis"),
    ("复发", "recurrence"),
    ("缓解", "remission"),
    ("痊愈", "recovery"),
    ("恶化", "deterioration"),
    ("进展", "progression"),
    ("稳定", "stabilization"),
    ("改善", "improvement"),
    ("治愈", "cure"),
    ("死亡", "death"),
    ("存活", "survival"),
    ("生存", "survival"),
    ("发病率", "incidence"),
    ("患病率", "prevalence"),
    ("死亡率", "mortality"),
    ("治愈率", "cure rate"),
    ("有效率", "efficacy rate"),
    ("生存率", "survival rate"),
    ("依从性", "compliance"),
    ("安全性", "safety profile"),
    ("有效性", "efficacy"),
    ("可行性", "feasibility"),
    ("重要性", "importance"),
    ("必要性", "necessity"),
    ("可能性", "possibility"),
    ("相关性", "correlation"),
    ("特异性", "specificity"),
    ("敏感性", "sensitivity"),
    ("准确性", "accuracy"),
    ("精确性", "precision"),
    ("可靠性", "reliability"),
    ("安全性", "safety"),
    ("有效性", "effectiveness"),
    ("质量", "quality"),
    ("数量", "quantity"),
    ("剂量", "dosage"),
    ("浓度", "concentration"),
    ("含量", "content"),
    ("水平", "level"),
    ("阈值", "threshold"),
    ("范围", "range"),
    ("限度", "limit"),
    ("标准", "standard"),
    ("正常值", "normal value"),
    ("参考值", "reference value"),
    ("临界值", "critical value"),
    ("半衰期", "half-life"),
    ("生物利用度", "bioavailability"),
    ("分布容积", "volume of distribution"),
    ("清除率", "clearance"),
    ("血药浓度", "plasma concentration"),
    ("峰浓度", "peak concentration"),
    ("谷浓度", "trough concentration"),
    ("稳态浓度", "steady-state concentration"),
    ("负荷剂量", "loading dose"),
    ("维持剂量", "maintenance dose"),
    ("治疗指数", "therapeutic index"),
    ("安全范围", "safety margin"),
    ("治疗窗", "therapeutic window"),
    ("给药间隔", "dosing interval"),
    ("给药途径", "route of administration"),
    ("口服生物利用度", "oral bioavailability"),
    ("绝对生物利用度", "absolute bioavailability"),
    ("相对生物利用度", "relative bioavailability"),
    ("首过效应", "first-pass effect"),
    ("首过代谢", "first-pass metabolism"),
    ("肝肠循环", "enterohepatic circulation"),
    ("胎盘屏障", "placental barrier"),
    ("血脑屏障", "blood-brain barrier"),
    ("乳汁排泄", "excretion in milk"),
    ("药物相互作用", "drug interaction"),
    ("配伍禁忌", "incompatibility"),
    ("协同作用", "synergistic effect"),
    ("相加作用", "additive effect"),
    ("拮抗作用", "antagonistic effect"),
    ("增效作用", "potentiating effect"),
    ("减效作用", "attenuating effect"),
    ("耐药性", "drug resistance"),
    ("耐受性", "tolerance"),
    ("依赖性", "dependence"),
    ("成瘾性", "addiction"),
    ("戒断症状", "withdrawal symptom"),
    ("撤药反应", "withdrawal reaction"),
    ("反跳现象", "rebound phenomenon"),
    ("个体差异", "individual variation"),
    ("遗传多态性", "genetic polymorphism"),
    ("药物基因组学", "pharmacogenomics"),
    ("个体化治疗", "personalized therapy"),
    ("精准医疗", "precision medicine"),
    ("循证医学", "evidence-based medicine"),
    ("临床试验", "clinical trial"),
    ("随机对照试验", "randomized controlled trial"),
    ("多中心研究", "multicenter study"),
    ("荟萃分析", "meta-analysis"),
    ("系统评价", "systematic review"),

    # ===== CRITICAL GRAMMAR PARTICLES =====
    # Most critical: grammar particles that have no direct English equivalent -> space
    ("的", " "),  # Chinese possessive/attributive particle, mostly structural
    ("是", "is"),   # MOST CRITICAL - "to be"
    ("之", " of "),
    ("与", "and"),
    ("等", "etc."),
    ("并", "and"),
    ("且", "also"),
    # Common particles
    ("有", "has"),
    ("为", "is"),
    ("和", "and"),
    ("如", "such as"),
    ("对", "to"),
    ("在", "in"),
    ("其", "its"),
    ("时", "when"),
    ("可", "can"),
    ("会", "can"),
    ("也", "also"),
    ("否", "whether"),
    ("将", "will"),
    ("则", "then"),
    ("若", "if"),
    ("当", "when"),
    ("因", "due to"),
    ("做", "do"),
    ("由", "by"),
    ("经", "via"),
    ("于", "for"),
    ("已", "already"),
    ("未", "not yet"),
    ("再", "again"),
    ("每", "per"),
    ("此", "this"),
    ("及", "and"),
    ("却", "yet"),
    ("被", "is"),
    ("或", "or"),
    ("但", "but"),
    ("而", "while"),
    ("使", "causes"),
    ("需", "requires"),
    ("应", "should"),
    ("所", "that is"),
    ("更", "more"),
    ("最", "most"),
    ("极", "extremely"),
    ("很", "very"),
    ("较", "more"),
    ("越", "more"),
    ("即", "namely"),
    ("仅", "only"),
    ("又", "also"),
    ("还", "also"),
    ("仍", "still"),
    ("具", "has"),
    ("以", "by"),
    ("均", "all"),
    ("皆", "all"),
    ("各", "each"),
    ("某", "certain"),
    ("本", "this"),
    ("必", "must"),
    ("常", "often"),
    ("先", "first"),
    ("后", "after"),
    ("前", "before"),
    ("选", "select"),
    ("择", "choose"),
    ("择性", "selectivity"),
    ("通", "through"),
    ("断", "blocking"),
    ("非", "non"),
    ("无", "no"),
    ("没", "not"),
    ("不", "not"),
    ("太", "too"),
    ("过", "excessively"),
    ("多", "many"),
    ("少", "few"),
    ("高", "high"),
    ("低", "low"),
    ("大", "large"),
    ("小", "small"),
    ("强", "strong"),
    ("弱", "weak"),
    ("快", "rapid"),
    ("慢", "slow"),
    ("好", "good"),
    ("坏", "bad"),
    ("新", "new"),
    ("老", "old"),
    ("长", "long"),
    ("短", "short"),
    ("厚", "thick"),
    ("薄", "thin"),
    ("硬", "hard"),
    ("软", "soft"),
    ("宽", "wide"),
    ("窄", "narrow"),
    ("轻", "mild"),
    ("重", "severe"),
    ("深", "deep"),
    ("浅", "shallow"),
    ("纯", "pure"),
    ("杂", "mixed"),
    ("单", "single"),
    ("双", "dual"),
    ("总", "total"),
    ("全", "all"),
    ("整", "entire"),
    ("半", "semi"),
    ("干", "dry"),
    ("热", "hot"),
    ("冷", "cold"),
    ("温", "temperature"),
    ("血", "blood"),
    ("水", "water"),
    ("液", "fluid"),
    ("气", "gas"),
    ("毛", "capillary"),
    ("电", "electrical"),
    ("药", "drug"),
    ("物", "agent"),
    ("性", " "),   # Suffix particle, mostly structural like "的"

    # More missing short chars and compounds
    ("活动", "activity"),
    ("睡眠", "sleep"),
    ("昼夜", "circadian"),
    ("节律", "rhythm"),
    ("食欲", "appetite"),
    ("行为", "behavior"),
    ("方式", "manner"),
    ("起效", "takes effect"),
    ("生效", "takes effect"),
    ("失效", "loses effect"),
    ("入眠", "sleep onset"),
    ("觉醒", "wakefulness"),
    ("生理功能", "physiological function"),
    ("生理活动", "physiological activity"),
    ("储备能力", "reserve capacity"),
    ("供需平衡", "supply-demand balance"),
    ("传导速度", "conduction velocity"),
    ("心肌细胞", "cardiomyocyte"),
    ("心房肌", "atrial myocardium"),
    ("心室肌", "ventricular myocardium"),
    ("消遣", "recreational"),
    ("违法", "illegal"),
    ("种", " types of "),
    ("个", " "),
    ("项", " "),
    ("防", "prophylaxis"),
    ("治", "therapy"),
    ("动", "activity"),
    ("睡", "sleep"),
    ("眠", "sleep"),
    ("昼", "day"),
    ("夜", "night"),
    ("欲", "appetite"),
    ("律", "rhythm"),
    ("节", "rhythm"),
    ("醒", "awake"),
    ("备", "reserve"),
    ("储", "store"),
    ("需", "demand"),
    ("供", "supply"),
    ("衡", "balance"),
    ("解", "relieve"),
    ("除", "remove"),
    ("线", "line"),
    ("占", "occupy"),
    ("优", "dominant"),
    ("势", "position"),
    ("孕", "pregnancy"),
    ("妊娠", "pregnancy"),
    ("乳头", "nipple"),
    ("纵", "longitudinal"),
    ("延髓", "medulla oblongata"),
    ("呕吐中枢", "vomiting center"),
    ("性行为", "sexual behavior"),
    ("伴有", "associated with"),
    ("伴发", "associated with"),
    ("局部", "local"),
    ("全身", "systemic"),
    ("颅内", "intracranial"),
    ("人", "human"),
    ("镇吐", "antiemetic"),
    ("后除极", "afterdepolarization"),
    ("触发活动", "triggered activity"),
    ("折返激动", "reentry excitation"),
    ("折返", "reentry"),
    ("经典", "classic"),
    ("代表", "representative"),
    ("频率", "frequency"),
    ("张力", "tension"),
    ("自分泌", "autocrine"),
    ("旁分泌", "paracrine"),
    ("细胞内", "intracellular"),
    ("细胞外", "extracellular"),
    ("细胞内液", "intracellular fluid"),
    ("细胞外液", "extracellular fluid"),
    ("组织胺", "histamine"),
    ("抗组胺", "antihistamine"),
    ("组胺受体", "histamine receptor"),
    ("前列腺素", "prostaglandin"),
    ("白三烯", "leukotriene"),
    ("内皮", "endothelium"),
    ("内皮素", "endothelin"),
    ("内源性", "endogenous"),
    ("外源性", "exogenous"),
    ("原发", "primary"),
    ("继发", "secondary"),
    ("诱发", "induce"),
    ("自发", "spontaneous"),
    ("效果", "effect"),
    ("疗效", "therapeutic effect"),
    ("良好", "good"),
    ("较差", "poor"),
    ("较好", "better"),
    ("最佳", "optimal"),
    ("维持", "maintain"),
    ("巩固", "consolidate"),
    ("加强", "enhance"),
    ("逐步", "gradually"),
    ("立即", "immediately"),
    ("迅速", "rapidly"),
    ("内流", "influx"),
    ("外流", "efflux"),
    ("内向电流", "inward current"),
    ("外向电流", "outward current"),
    ("跨膜", "transmembrane"),
    ("除极", "depolarization"),
    ("复极", "repolarization"),
    ("超速", "ultra-rapid"),
    ("泵出", "pumps out"),
    ("泵入", "pumps in"),
    ("交换体", "exchanger"),
    ("电活动", "electrical activity"),
    ("电生理", "electrophysiological"),
    ("特性", "characteristics"),
    ("特点", "characteristics"),
    ("特征", "features"),
    ("差异", "difference"),
    ("相似", "similarity"),
    ("细胞膜", "cell membrane"),
    ("细胞核", "nucleus"),
    ("细胞质", "cytoplasm"),
    ("线粒体", "mitochondria"),
    ("内质网", "endoplasmic reticulum"),
    ("高尔基体", "Golgi apparatus"),
    ("溶酶体", "lysosome"),
    ("核糖体", "ribosome"),
    ("染色质", "chromatin"),
    ("染色体", "chromosome"),
    ("浆", "plasma"),
    ("血清", "serum"),
    ("血浆", "plasma"),
    ("血细胞", "blood cell"),
    ("淋巴细胞", "lymphocyte"),
    ("粒细胞", "granulocyte"),
    ("单核细胞", "monocyte"),
    ("血小板", "platelet"),
    ("红细胞", "red blood cell"),
    ("白细胞", "white blood cell"),
    ("肥大细胞", "mast cell"),
    ("上皮细胞", "epithelial cell"),
    ("内皮细胞", "endothelial cell"),
    ("平滑肌细胞", "smooth muscle cell"),
    ("成纤维细胞", "fibroblast"),
    ("干细胞", "stem cell"),
    ("祖细胞", "progenitor cell"),
    ("肌细胞", "myocyte"),
    ("神经元", "neuron"),
    ("胶质细胞", "glial cell"),
    ("症", "disease"),
    ("型", "type"),
    ("量", "dose"),
    ("数", "number"),
    ("度", "degree"),
    ("率", "rate"),
    ("比", "ratio"),
    ("值", "value"),
    ("压", "pressure"),
    ("力", "force"),
    ("素", "factor"),
    ("体", "body"),
    ("管", "vessel"),
    ("效", "effect"),
    ("治", "treatment"),
    ("病", "disease"),
    ("变", "change"),
    ("失", "loss"),
    ("活", "active"),
    ("死", "death"),
    ("增", "increase"),
    ("减", "decrease"),
    ("升", "elevate"),
    ("降", "reduce"),
    ("流", "flow"),
    ("排", "excrete"),
    ("供", "supply"),
    ("耗", "consumption"),
    ("吸", "absorption"),
    ("储", "storage"),
    ("存", "store"),
    ("放", "release"),
    ("释", "release"),
    ("带", "carry"),
    ("转", "convert"),
    ("递", "transmit"),
    ("传", "transmit"),
    ("控", "control"),
    ("调", "regulate"),
    ("激", "stimulate"),
    ("散", "disperse"),
    ("隔", "separate"),
    ("离", "separate"),
    ("合", "combine"),
    ("连", "connect"),
    ("接", "connect"),
    ("联", "combine"),
    ("交", "exchange"),
    ("互", "mutual"),
    ("换", "exchange"),
    ("改", "modify"),
    ("移", "shift"),
    ("导", "conduction"),
    ("稳", "stable"),
    ("乱", "disorder"),
    ("异", "abnormal"),
    ("衰", "failure"),
    ("竭", "exhaustion"),
    ("缺", "deficient"),
    ("损", "damage"),
    ("痛", "pain"),
    ("炎", "inflammation"),
    ("肿", "swelling"),
    ("瘤", "tumor"),
    ("毒", "toxic"),
    ("素", "factor"),
    ("酶", "enzyme"),
    ("蛋", "protein"),
    ("糖", "sugar"),
    ("盐", "salt"),
    ("酸", "acid"),
    ("碱", "base"),
    ("脂", "lipid"),
    ("油", "oil"),
    ("膜", "membrane"),
    ("壁", "wall"),
    ("腔", "cavity"),
    ("孔", "pore"),
    ("能", "can"),
    ("够", "able to"),
    ("久", "long"),
    ("必", "must"),
    ("须", "must"),
    ("都", "all"),
    ("另", "other"),
    ("正", "normal"),
    ("反", "reverse"),
    ("共", "co"),
    ("同", "same"),
    ("似", "similar"),
    ("继", "secondary"),
    ("续", "continue"),
    ("持", "maintain"),
    ("限", "limit"),
    ("周", "week"),
    ("年", "year"),
    ("月", "month"),
    ("日", "day"),
    ("晚", "late"),
    ("早", "early"),
    ("午", "noon"),
    ("夜", "night"),
    ("心", "heart"),
    ("肝", "liver"),
    ("肾", "kidney"),
    ("肺", "lung"),
    ("胃", "stomach"),
    ("肠", "intestine"),
    ("脑", "brain"),
    ("眼", "eye"),
    ("耳", "ear"),
    ("鼻", "nose"),
    ("口", "oral"),
    ("皮", "skin"),
    ("肉", "muscle"),
    ("骨", "bone"),
    ("血", "blood"),
    ("尿", "urine"),
    ("便", "stool"),
    ("汗", "sweat"),

    # Additional common 2-char words that weren't matching
    ("体内", "in the body"),
    ("体外", "in vitro"),
    ("其余", "the remaining"),
    ("任何", "any"),
    ("每次", "each time"),
    ("每天", "daily"),
    ("选择", "select"),
    ("选择性", "selectivity"),
    ("有效性", "effectiveness"),
    ("安全性", "safety"),
    ("依赖性", "dependence"),
    ("耐受性", "tolerability"),
    ("耐药性", "drug resistance"),
    ("特异性", "specificity"),
    ("敏感性", "sensitivity"),
    ("致死性", "lethality"),
    ("可逆性", "reversibility"),
    ("不可逆性", "irreversibility"),
    ("效价", "potency"),
    ("效力", "efficacy"),
    ("效能", "efficacy"),
    ("具有", "has"),
    ("没有", "does not have"),
    ("用于", "used for"),
    ("来自", "derived from"),
    ("发生", "occurs"),
    ("出现", "appears"),
    ("消失", "disappears"),
    ("含有", "contains"),
    ("缺乏", "lacks"),
    ("属于", "belongs to"),
    ("有关", "is related to"),
    ("无关", "is unrelated to"),
    ("相关", "is associated"),
    ("显著", "significantly"),
    ("明显", "markedly"),
    ("结果", "result"),
    ("原因", "cause"),
    ("因素", "factor"),
    ("方法", "method"),
    ("原则", "principle"),
    ("目的", "purpose"),
    ("意义", "significance"),
    ("功能", "function"),
    ("结构", "structure"),
    ("作用", "action"),
    ("效应", "effect"),
    ("反应", "reaction"),
    ("过程", "process"),
    ("机制", "mechanism"),
    ("途径", "pathway"),
    ("水平", "level"),
    ("浓度", "concentration"),
    ("活性", "activity"),
    ("时间", "time"),
    ("范围", "range"),
    ("状态", "status"),
    ("情况", "condition"),
    ("条件", "condition"),
    ("差异", "difference"),
    ("变化", "change"),
    ("影响", "influence"),
    ("关系", "relationship"),
    ("对比", "compared with"),
    ("比较", "comparison"),
    ("达到", "achieves"),
    ("超过", "exceeds"),
    ("低于", "below"),
    ("高于", "above"),
    ("开始", "begin"),
    ("结束", "end"),
    ("完成", "complete"),
    ("维持", "maintain"),
    ("停止", "stop"),
    ("继续", "continue"),
    ("恢复", "recover"),
    ("改善", "improve"),
    ("恶化", "worsen"),
    ("加强", "strengthen"),
    ("削弱", "weaken"),
    ("接受", "accept"),
    ("拒绝", "reject"),
    ("决定", "determine"),
    ("解决", "resolve"),
    ("需要", "require"),
    ("使用", "use"),
    ("利用", "utilize"),
    ("进行", "undergo"),
    ("形成", "form"),
    ("建立", "establish"),
    ("证明", "prove"),
    ("表明", "indicate"),
    ("显示", "show"),
    ("提示", "suggest"),
    ("说明", "indicate"),
    ("描述", "describe"),
    ("解释", "explain"),
    ("分类", "classification"),
    ("分别", "respectively"),
    ("区分", "differentiate"),
    ("总结", "summarize"),
    ("主要", "mainly"),
    ("重要", "important"),
    ("关键", "key"),
    ("基本", "basic"),
    ("根本", "fundamental"),
    ("尤其", "especially"),
    ("特别", "particularly"),
    ("广泛", "widely"),
    ("全面", "comprehensively"),
    ("首先", "first"),
    ("然后", "then"),
    ("最后", "finally"),
    ("目前", "currently"),
    ("同时", "simultaneously"),
    ("早期", "early"),
    ("中期", "intermediate"),
    ("晚期", "late"),
    ("最终", "ultimately"),
    ("短期", "short-term"),
    ("长期", "long-term"),
    ("持久", "sustained"),
    ("瞬间", "instant"),
    ("快速", "rapid"),
    ("缓慢", "slow"),
    ("逐渐", "gradually"),
    ("突然", "suddenly"),
    ("立即", "immediately"),
    ("及时", "timely"),
    ("暂时", "temporarily"),
    ("永久", "permanently"),
    ("经常", "frequently"),
    ("偶尔", "occasionally"),
    ("从未", "never"),
    ("大体", "generally"),
    ("总是", "always"),
    ("可能", "possible"),
    ("确实", "indeed"),
    ("当然", "of course"),
    ("必须", "must"),
    ("应该", "should"),
    ("能够", "able to"),
    ("可以", "can"),
    ("不能", "cannot"),
    ("不可", "must not"),
    ("不宜", "should not"),
    ("不应", "should not"),
    ("不得", "must not"),
    ("禁止", "is prohibited"),
    ("严禁", "is strictly prohibited"),
    ("所有", "all"),
    ("一些", "some"),
    ("各种", "various"),
    ("很少", "rarely"),
    ("许多", "many"),
    ("大量", "large amount"),
    ("少量", "small amount"),
    ("多数", "majority"),
    ("少数", "minority"),
    ("依次", "sequentially"),
    ("相互", "mutually"),
    ("一起", "together"),
    ("共同", "jointly"),
    ("单独", "alone"),
    ("联合", "combined"),
    ("直接", "directly"),
    ("间接", "indirectly"),
    ("首先", "first"),
    ("相反", "conversely"),
    ("一致", "consistent"),
    ("矛盾", "contradictory"),
    ("典型", "typical"),
    ("特殊", "special"),
    ("普遍", "general"),
    ("一般", "generally"),
    ("相同", "same"),
    ("不同", "different"),
    ("中等", "moderate"),
    ("常用", "commonly used"),
    ("首选", "preferred"),
    ("耐药", "resistant"),
    ("敏感", "sensitive"),
    ("特异", "specific"),
    ("有效", "effective"),
    ("无效", "ineffective"),
    ("安全", "safety"),
    ("危险", "risk"),
    ("严重", "serious"),
    ("轻微", "minor"),
    ("中等", "moderate"),
    ("过度", "excessive"),
    ("不足", "insufficient"),
    ("例如", "for example"),
    ("包括", "includes"),
    ("除了", "except"),
    ("按照", "according to"),
    ("相对", "relatively"),
    ("绝对", "absolutely"),
    ("十分", "very"),
    ("非常", "extremely"),
    ("几乎", "almost"),
    ("完全", "completely"),
    ("部分", "partially"),
    ("曾经", "previously"),
    ("至今", "to date"),
    ("今后", "henceforth"),
    ("目前", "currently"),
    ("当时", "at that time"),
    ("现将", "now"),
    ("即将", "about to"),
    ("进一步", "further"),
    ("正是", "is precisely"),
    ("恰好", "exactly"),
    ("因此", "therefore"),
    ("所以", "therefore"),
    ("因为", "because"),
    ("然而", "however"),
    ("但是", "but"),
    ("虽然", "although"),
    ("即使", "even if"),
    ("除非", "unless"),
    ("只要", "as long as"),
    ("不仅", "not only"),
    ("而且", "but also"),
    ("此外", "furthermore"),
    ("另外", "additionally"),
    ("况且", "moreover"),
    ("总之", "in summary"),
    ("同样", "similarly"),
    ("反而", "instead"),
    ("否则", "otherwise"),
    ("无论", "regardless of"),
    ("尽管", "despite"),
    ("不管", "no matter"),
    # Numbers
    ("零", "zero"), ("一", "one"), ("二", "two"), ("三", "three"),
    ("四", "four"), ("五", "five"), ("六", "six"), ("七", "seven"),
    ("八", "eight"), ("九", "nine"), ("十", "ten"),
    ("百", "hundred"), ("千", "thousand"), ("万", "ten thousand"),
    # Question types for final matching
    ("正确", "True"),
    ("错误", "False"),
]

# ============================================================
# Post-processing: fix concatenated English words
# ============================================================
def apply_post_processing(result):
    """Clean up spacing and formatting after translation."""
    # Insert space between lowercase-then-uppercase (WordWord -> Word Word)
    result = re.sub(r'([a-z])([A-Z])', r'\1 \2', result)
    # Insert space between letter-digit
    result = re.sub(r'([a-zA-Z])(\d)', r'\1 \2', result)
    result = re.sub(r'(\d)([a-zA-Z])', r'\1 \2', result)
    # Fix parenthetical spacing
    result = re.sub(r'\)([a-zA-Z])', r') \1', result)
    result = re.sub(r'([a-zA-Z])\(', r'\1 (', result)
    result = re.sub(r'\)([a-z])', r') \1', result)
    # Collapse multiple spaces
    result = re.sub(r' +', ' ', result)
    # Fix space-before-comma/period/semicolon/colon
    result = re.sub(r' ,', ',', result)
    result = re.sub(r' \.', '.', result)
    result = re.sub(r' ;', ';', result)
    result = re.sub(r' :', ':', result)
    # Fix space inside parentheses
    result = re.sub(r'\( ', '(', result)
    result = re.sub(r' \)', ')', result)
    # Fix doubled periods
    result = re.sub(r'\.\s*\.', '.', result)
    # Clean leading/trailing whitespace
    result = result.strip()
    # Capitalize first letter if alphabetic
    if result and result[0].isalpha():
        result = result[0].upper() + result[1:]
    return result


# Build sorted TRANS list: sort by decreasing length of Chinese source
TRANS = sorted(TRANS_RAW, key=lambda x: len(x[0]), reverse=True)


def translate_text(text):
    """Translate Chinese pharmacological text to English."""
    if not text or not text.strip():
        return text

    result = text
    for cn, en in TRANS:
        result = result.replace(cn, en)

    return apply_post_processing(result)


def translate_type(cn_type):
    return TYPE_MAP.get(cn_type, cn_type)


def translate_category(cn_cat):
    return CAT_MAP.get(cn_cat, cn_cat)


def translate_option(opt):
    if not opt or not opt.strip():
        return opt
    return translate_text(opt)


def translate_row(row):
    new_row = list(row)
    new_row[1] = translate_type(row[1])
    new_row[2] = translate_text(row[2])
    for j in range(3, min(13, len(row))):
        new_row[j] = translate_option(row[j])
    new_row[13] = row[13] if len(row) > 13 else ""
    if len(row) > 14:
        new_row[14] = translate_text(row[14])
    if len(row) > 15:
        new_row[15] = translate_category(row[15])
    return new_row


def process_chapter(ch_num):
    in_file = f"/Users/weixu/Downloads/pnas/pharma_cn_ch{ch_num:02d}.csv"
    out_file = f"/Users/weixu/Downloads/pnas/pharma_en_ch{ch_num:02d}.csv"

    print(f"  Processing Chapter {ch_num:02d} ... ", end="", flush=True)

    with open(in_file, 'r', encoding='utf-8-sig') as inf:
        reader = csv.reader(inf)
        headers = next(reader)
        rows = []
        for row in reader:
            if len(row) < 16:
                row = list(row) + [''] * (16 - len(row))
            rows.append(translate_row(row))

    with open(out_file, 'w', encoding='utf-8-sig', newline='') as outf:
        writer = csv.writer(outf)
        writer.writerow(headers)
        writer.writerows(rows)

    print(f"OK ({len(rows)} rows)")
    return len(rows)


def main():
    chapters = [19, 20, 21, 22, 23, 24]
    print("=" * 60)
    print("Pharmacology Quiz Translation: Chapters 19-24")
    print("=" * 60)

    total = 0
    for ch in chapters:
        try:
            n = process_chapter(ch)
            total += n
        except Exception as e:
            print(f"ERROR in Chapter {ch}: {e}")
            import traceback
            traceback.print_exc()
            sys.exit(1)

    print("-" * 60)
    print(f"All 6 chapters translated. Total: {total} questions.")
    print("=" * 60)


if __name__ == "__main__":
    main()
